# Translations template for paxes_cinder.
# Copyright (C) 2014 NCO Corp.
# This file is distributed under the same license as the paxes_cinder
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: paxes_cinder 1.2.1.0\n"
"Report-Msgid-Bugs-To: nguyen1d@us.ibm.com\n"
"POT-Creation-Date: 2014-04-24 16:04-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: paxes_cinder/k2aclient/openstack/common/gettextutils.py:255
msgid "Message objects do not support addition."
msgstr "NV-C33F89C Les objets message ne prennent pas en charge l'ajout."

#: paxes_cinder/k2aclient/openstack/common/gettextutils.py:264
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""
"NV-64408AE Les objets message ne prennent pas en charge str() car ce "
"dernier peut comporter des caractères non ascii. Utilisez à la place "
"unicode() ou translate()."

#: paxes_cinder/k2aclient/openstack/common/procutils.py:129
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr "NV-36AD129 Arguments de mot clé inconnu sur utils.execute : %r"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:144
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "NV-9F83237 Exécution commande (sous-processus) : %s"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:169
#: paxes_cinder/k2aclient/openstack/common/procutils.py:241
#, python-format
msgid "Result was %s"
msgstr "NV-E91D667 Résultat : %s"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:181
#, python-format
msgid "%r failed. Retrying."
msgstr "NV-E62FA94 %r en échec. Nouvelle tentative."

#: paxes_cinder/k2aclient/openstack/common/procutils.py:220
#, python-format
msgid "Running cmd (SSH): %s"
msgstr "NV-F226973 Exécution commande (SSH) : %s"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:222
msgid "Environment not supported over SSH"
msgstr "NV-5D0CD8B Environnement non pris en charge via SSH"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:226
msgid "process_input not supported over SSH"
msgstr "NV-E78B011 process_input non pris en charge via SSH"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:512
#, python-format
msgid "DB error: %s"
msgstr "NV-B907287 Erreur BD : %s"

#: paxes_cinder/k2aclient/shell.py:100
msgid "Print debugging output"
msgstr "Imprimer la sortie de débogage"

#: paxes_cinder/api/plugins/__init__.py:31
#, python-format
msgid "Failed to load extension %(name)s: %(ex)s"
msgstr "NV-E1E174C Echec du chargement de l'extension %(name)s : %(ex)s"

#: paxes_cinder/volume/manager.py:1275
#, python-format
msgid "Driver %s does not implement Discover Driver"
msgstr "NV-DA200A2 Le pilote %s n'implémente pas le pilote Discover"

#: paxes_cinder/exception.py:16
#, python-format
msgid "Connection control failure: %(reason)s"
msgstr "NV-BFC4353 Echec du contrôle de connexion : %(reason)s"

#: paxes_cinder/exception.py:20
#, python-format
msgid "Zone operation failed: %(reason)s"
msgstr "NV-A619680 Echec de l'opération de zone : %(reason)s"

#: paxes_cinder/exception.py:24
#, python-format
msgid "FC SAN Lookup failure: %(reason)s"
msgstr "NV-1316051 Echec de la recherche SAN FC : %(reason)s"

#: paxes_cinder/exception.py:32
#, python-format
msgid "Internal Misconfiguration detected: %(reason)s"
msgstr "NV-C9F5A2A Problème de configuration interne détecté : %(reason)s"

#: paxes_cinder/exception.py:58
#, python-format
msgid "Fabric '%(display_name)s' (%(username)s@%(ip)s:%(port)s)"
msgstr "NV-097D384 Fabrique '%(display_name)s' (%(username)s@%(ip)s:%(port)s)"

#: paxes_cinder/exception.py:93
#, python-format
msgid "%(descriptor)s: %(message)s"
msgstr "NV-12DC37C %(descriptor)s : %(message)s"

#: paxes_cinder/exception.py:142
#, python-format
msgid "%(problem)s: %(err)s"
msgstr "NV-7FA8022 %(problem)s : %(err)s"

#: paxes_cinder/exception.py:164
msgid "Could not authenticate with the specified credentials"
msgstr ""
"NV-BB4FAEC Authentification impossible avec les données d'identification "
"spécifiées"

#: paxes_cinder/exception.py:174
#, python-format
msgid "Timeout (%(timeout)s seconds) when attempting to connect"
msgstr ""
"NV-3AB9750 Délai d'attente (%(timeout)s secondes) lors de la tentative de"
" connexion"

#: paxes_cinder/exception.py:184
#, python-format
msgid "Timeout (%(timeout)s seconds) when executing command %(cmd)s"
msgstr ""
"NV-17277CD Délai d'attente (%(timeout)s secondes) lors de l'exécution de "
"la commande %(cmd)s"

#: paxes_cinder/exception.py:193
#, python-format
msgid "Could not connect: %(error)s %(detail)s"
msgstr "NV-2251927 Connexion impossible : %(error)s %(detail)s"

#: paxes_cinder/exception.py:201
#, python-format
msgid ""
"Another transaction was already in progress when attempting to execute "
"command '%(cmd)s'"
msgstr ""
"NV-B3EE2A1 Une autre transaction était déjà en cours lors de la tentative"
" d'exécution de la commande '%(cmd)s'"

#: paxes_cinder/exception.py:209
#, python-format
msgid ""
"Zone DB exceeded size limits when executing command '%(cmd)s', which "
"returned '%(res)s'"
msgstr ""
"NV-3D73335 La BD de zone a dépassé les limites de taille lors de "
"l'exécution de la commande '%(cmd)s', ce qui a renvoyé '%(res)s'"

#: paxes_cinder/exception.py:218
#, python-format
msgid "The CLI command '%(cmd)s' returned an unexpected response '%(res)s'"
msgstr ""
"NV-6BC3B8F La commande d'interface CLI '%(cmd)s' a renvoyé une réponse "
"inattendue '%(res)s'"

#: paxes_cinder/exception.py:240
#, python-format
msgid "Storage %(display_name)s (%(username)s@%(ip)s:%(port)s)"
msgstr "NV-FD8FAF8 Stockage %(display_name)s (%(username)s@%(ip)s:%(port)s)"

#: paxes_cinder/exception.py:272
msgid "No more host definitions can be created"
msgstr "NV-FAE0982 Aucune autre définition d'hôte ne peut être créée"

#: paxes_cinder/exception.py:281
msgid "No more flashcopy mappings can be created"
msgstr "NV-5071C44 Aucun autre mappage flashcopy ne peut être créé"

#: paxes_cinder/exception.py:289
msgid "Could not connect, possibly due to too many connections."
msgstr ""
"NV-16C6099 Connexion impossible probablement en raison du nombre excessif"
" de connexions."

#: paxes_cinder/exception.py:297
#, python-format
msgid ""
"Could not map vdisk %(vdisk_id)s to host %(host)s because it is already "
"mapped to another host"
msgstr ""
"NV-4B128AE Impossible de mapper le disque virtuel %(vdisk_id)s à l'hôte "
"%(host)s car il est déjà mappé à un autre hôte"

#: paxes_cinder/exception.py:312
#, python-format
msgid "vdisk %(vdisk_id)s does not exist"
msgstr "NV-8AE54C7 Le disque virtuel %(vdisk_id)s n'existe pas"

#: paxes_cinder/exception.py:322
msgid "No common fabrics between virtual machine and storage"
msgstr ""
"NV-E5685D0 Aucun ensemble de noeuds commun entre la machine virtuelle et "
"le stockage"

#: paxes_cinder/exception.py:339
#, python-format
msgid ""
"vdisk %(vdisk_id)s has been deleted and recreated. Expected UID is "
"%(expected_uid)s, current UID is %(current_uid)s"
msgstr ""
"NV-78057E1 le disque virtuel %(vdisk_id)s a été supprimé et recréé. L'UID"
" attendu est %(expected_uid)s, l'UID actuel est %(current_uid)s"

#: paxes_cinder/exception.py:350
#, python-format
msgid ""
"Not enough space left on storage host %(host)s to extend the volume "
"%(volume_id)s"
msgstr ""
"NV-EA431AC Espace insuffisant sur l'hôte de stockage %(host)s pour "
"l'extension du volume %(volume_id)s"

#: paxes_cinder/exception.py:360
msgid ""
"Flashcopy is in progress for boot volume, volume size didn't change. "
"Please try again later."
msgstr ""
"NV-461A839 Flashcopy est en cours pour le volume d'amorçage, la taille du"
" volume n'a pas changé. Réessayez ultérieurement."

#: paxes_cinder/exception.py:367
#, python-format
msgid ""
"vdisk %(vdisk_id)s is source of snapshot flashcopy and fcmap %(fcmapid)s "
"cannot be removed."
msgstr ""
"NV-CB3AB35 Le vdisk %(vdisk_id)s est la source du flashcopy d'instantané "
"et fcmap %(fcmapid)s ne peut pas être supprimé."

#: paxes_cinder/db/sqlalchemy/migrate_repo/versions/001_ibm_paxes_v1r2.py:35
#, python-format
msgid "Exception creating table %(table)s: %(ex_str)s"
msgstr "Exception lors de la création de la table %(table)s : %(ex_str)s"

#: paxes_cinder/db/sqlalchemy/migrate_repo/versions/001_ibm_paxes_v1r2.py:55
#, python-format
msgid "Exception dropping table %(table)s: %(ex_str)s"
msgstr "Exception lors de la suppression de la table %(table)s : %(ex_str)s"

#: paxes_cinder/fabric/map_initiators.py:70
msgid ""
"Could not obtain a fabric manager client. Fibre Channel switch fabrics "
"may not be registered."
msgstr ""
"NV-6EF68AC Impossible d'obtenir un client de gestionnaire d'ensemble de "
"noeuds.  Il se peut que le commutateur à fibre optique ne soit pas "
"enregistré."

#: paxes_cinder/fabric/map_initiators.py:85
#, python-format
msgid ""
"Unable to retrieve WWPN initiator information from one or more fabric "
"switches. Error: %(ex_str)s"
msgstr ""
"Impossible d'extraire les informations de demandeur WWPN d'un ou "
"plusieurs commutateurs d'ensemble de noeuds. Erreur : %(ex_str)s"

#: paxes_cinder/fabric/map_initiators.py:119
msgid "No fabrics registered."
msgstr "NV-0AA1511 Aucun ensemble de noeuds n'est enregistré."

#: paxes_cinder/fabric/map_initiators.py:124
msgid "No fabric names registered."
msgstr "NV-A4978F0 Aucun nom d'ensemble de noeuds n'est enregistré."

#: paxes_cinder/k2aclient/client.py:104
msgid ", during get"
msgstr "NV-C758794 , au cours de l'obtention (get)"

#: paxes_cinder/k2aclient/client.py:127
msgid ", during refresh"
msgstr "NV-A09A06D , au cours de la régénération (refresh)"

#: paxes_cinder/k2aclient/client.py:148
#: paxes_cinder/k2aclient/client.py:172
msgid ", during create"
msgstr "NV-16332E7 , au cours de la création (create)"

#: paxes_cinder/k2aclient/client.py:193
msgid ", during delete"
msgstr "NV-B5BE602 , au cours de la suppression (delete)"

#: paxes_cinder/k2aclient/client.py:207
msgid ", during runJob"
msgstr "NV-9A12874 , au cours de runJob"

#: paxes_cinder/k2aclient/client.py:219
msgid ", during readJob"
msgstr "NV-EA9B845 , au cours de readJob"

#: paxes_cinder/k2aclient/client.py:234
msgid ", during authenticate"
msgstr "NV-DD96084 , au cours de l'authentification (authenticate)"

#: paxes_cinder/k2aclient/client.py:247
#, python-format
msgid ""
"k2aclient: while obtaining client, invalid client version >%(version)s<. "
"must be one of: >%(versions)s<"
msgstr ""
"k2aclient : lors de l'obtention du client, version de client non valide "
">%(version)s<. doit être l'unee des versions suivantes : >%(versions)s<"

#: paxes_cinder/k2aclient/exceptions.py:46
#: paxes_cinder/k2aclient/exceptions.py:307
#, python-format
msgid ", exception diagnostics have been written to: >%s<"
msgstr ", les diagnostics d'exception ont été écrits dans : >%s<"

#: paxes_cinder/k2aclient/exceptions.py:56
#, python-format
msgid "Other Exception off of K2: >%s<"
msgstr "NV-92A2EB5 Autre exception indépendante de K2 : >%s<"

#: paxes_cinder/k2aclient/exceptions.py:58
#: paxes_cinder/k2aclient/exceptions.py:78
#: paxes_cinder/k2aclient/exceptions.py:88
#: paxes_cinder/k2aclient/exceptions.py:105
#, python-format
msgid ", during: >%s<"
msgstr ", au cours de : >%s<"

#: paxes_cinder/k2aclient/exceptions.py:66
#, python-format
msgid "SSL exception off of K2: >%s<"
msgstr "NV-852F651 Exception SSL indépendante de K2 : >%s<"

#: paxes_cinder/k2aclient/exceptions.py:76
#, python-format
msgid "Connection exception off of K2: >%s<"
msgstr "NV-DE65980 Exception de connexion indépendante de K2 : >%s<"

#: paxes_cinder/k2aclient/exceptions.py:86
#, python-format
msgid "Timeout exception off of K2: >%s<"
msgstr "NV-DC27602 Exception de délai d'attente indépendante de K2 : >%s<"

#: paxes_cinder/k2aclient/exceptions.py:100
#, python-format
msgid "K2Error off of K2: >%(msg)s<, Status: >%(status)d<, k2Error: >%(k2error)s<"
msgstr ""
"Erreur K2 indépendante de K2 : >%(msg)s<, Statut : >%(status)d<, Erreur "
"K2 : >%(k2error)s<"

#: paxes_cinder/k2aclient/exceptions.py:122
msgid "Bad Request"
msgstr "Requête incorrecte"

#: paxes_cinder/k2aclient/exceptions.py:130
msgid "Unauthorized"
msgstr "Non autorisé"

#: paxes_cinder/k2aclient/exceptions.py:144
msgid "Forbidden"
msgstr "Interdit"

#: paxes_cinder/k2aclient/exceptions.py:158
msgid "Not Found"
msgstr "Introuvable"

#: paxes_cinder/k2aclient/exceptions.py:167
msgid "Method Not Allowed"
msgstr "Méthode non autorisée"

#: paxes_cinder/k2aclient/exceptions.py:177
msgid "Not Acceptable"
msgstr "Non acceptable"

#: paxes_cinder/k2aclient/exceptions.py:189
msgid "Conflict"
msgstr "Conflit"

#: paxes_cinder/k2aclient/exceptions.py:197
msgid "PreCondition failed"
msgstr "Echec de précondition"

#: paxes_cinder/k2aclient/exceptions.py:206
msgid "Request Body Too Large"
msgstr "Corps de la demande trop grand"

#: paxes_cinder/k2aclient/exceptions.py:216
msgid "Unsupported Media Type"
msgstr "Type de support non pris en charge"

#: paxes_cinder/k2aclient/exceptions.py:225
msgid "Internal Server Error"
msgstr "Erreur de serveur interne"

#: paxes_cinder/k2aclient/exceptions.py:235
msgid "Not Implemented"
msgstr "Non implémenté"

#: paxes_cinder/k2aclient/exceptions.py:245
msgid "Service Unavailable"
msgstr "Service non disponible"

#: paxes_cinder/k2aclient/exceptions.py:255
msgid "HTTP Version Not Supported"
msgstr "Version HTTP non prise en charge"

#: paxes_cinder/k2aclient/exceptions.py:263
msgid "Not Classified"
msgstr "Non classifié"

#: paxes_cinder/k2aclient/k2exclogger.py:114
#, python-format
msgid ""
"k2aclient: during FFDC, cant create k2 exception log directory: >%s<, "
"will disable k2 exception logging .."
msgstr ""
"NV-ED6E0F0 k2aclient : pendant FFDC, impossible de créer le répertoire de"
" journal des exceptions k2 : >%s<, la journalisation des exceptions k2 va"
" être désactivée .."

#: paxes_cinder/k2aclient/k2exclogger.py:123
#, python-format
msgid ""
"k2aclient: during FFDC, cant write to k2 exception log directory: >%s<, "
"will disable k2 exception logging .."
msgstr ""
"NV-6373107 k2aclient : pendant FFDC, impossible d'écrire dans le "
"répertoire de journal des exceptions k2 : >%s<, la journalisation des "
"exceptions k2 va être désactivée .."

#: paxes_cinder/k2aclient/k2exclogger.py:146
#, python-format
msgid ""
"k2aclient: during FFDC,  caught an exception while writing to log "
"directory: >%s<, will disable k2 exception logging .."
msgstr ""
"NV-3376E54 k2aclient : pendant FFDC,  interception d'une exception lors "
"de l'écriture dans le répertoire de journal : >%s<, la journalisation des"
" exceptions k2 va être désactivée .."

#: paxes_cinder/k2aclient/shell.py:59
#, python-format
msgid ""
"k2aclient: error: %(errmsg)s\n"
"Try '%(mainp)s help %(subp)s' for more information.\n"
msgstr ""
"k2aclient : erreur : %(errmsg)s\n"
"Pour plus d'informations, entrez '%(mainp)s help %(subp)s'.\n"

#: paxes_cinder/k2aclient/shell.py:80
msgid "See \"k2a help COMMAND\" for help on a specific command."
msgstr ""
"Pour accéder à l'aide sur une commande spécifique, voir \"Commande de "
"l'aide k2a\"."

#: paxes_cinder/k2aclient/shell.py:106
msgid "Accepts 1,defaults to env[K2A_API_VERSION]."
msgstr "Valeur admise : 1, valeur par défaut : env[K2A_API_VERSION]."

#: paxes_cinder/k2aclient/shell.py:109
msgid "Number of retries when attempting k2 operations."
msgstr "Nombre de tentatives lors du lancement des opérations k2."

#: paxes_cinder/k2aclient/shell.py:119
msgid "url for k2 hmc, defaults to env[K2_URL]."
msgstr "url de k2 hmc, par défaut : env[K2_URL]."

#: paxes_cinder/k2aclient/shell.py:125
msgid "k2 username, defaults to env[K2_USERNAME]."
msgstr "nom d'utilisateur k2, par défaut : env[K2_USERNAME]."

#: paxes_cinder/k2aclient/shell.py:131
msgid "k2 password, defaults to env[K2_PASSWORD]."
msgstr "mot de passe k2, par défaut : env[K2_PASSWORD]."

#: paxes_cinder/k2aclient/shell.py:138
msgid ""
"k2 auditmemento, defaults to, if set, env[K2_AUDITMEMENTO], otherwise to "
"\"k2a\"."
msgstr ""
"k2 auditmemento, par défaut (si défini) : env[K2_AUDITMEMENTO], sinon : "
"\"k2a\"."

#: paxes_cinder/k2aclient/shell.py:145
msgid "k2 certpath, defaults to, if set, env[K2_CERTPATH], otherwise to None."
msgstr "k2 certpath, par défaut (si défini) : env[K2_CERTPATH], sinon : None."

#: paxes_cinder/k2aclient/shell.py:152
msgid ""
"log directory, defaults to, if set, env[K2A_LOGDIR], otherwise to None. "
"None turnsoff file logging"
msgstr ""
"répertoire de journal, par défaut (si défini) : env[K2A_LOGDIR], sinon : "
"None. None désactive la consignation"

#: paxes_cinder/k2aclient/shell.py:171
msgid ""
"directory where k2aexc subdirectorywill be placedie \"<excdir>/k2aexc\", "
"defaults to, if set, env[K2A_EXCDIR], otherwise to /tmp"
msgstr ""
"répertoire où sera placé le sous-répertoire k2aexc. ex : "
"\"<excdir>/k2aexc\", par défaut (si défini) env[K2A_EXCDIR], sinon /tmp"

#: paxes_cinder/k2aclient/shell.py:309
msgid ""
"k2aclient: you must provide a url for a k2 hmc via either --k2-url or "
"env[K2_URL]"
msgstr ""
"NV-D20F7FC k2aclient : vous devez fournir une URL pour k2 hmc via "
"--k2-url ou env[K2_URL]"

#: paxes_cinder/k2aclient/shell.py:315
msgid ""
"k2aclient: you must provide a k2 username via either --k2-username or "
"env[K2_USERNAME]"
msgstr ""
"NV-996BCEC k2aclient : vous devez fournir un nom d'utilisateur k2 via "
"--k2-username ou env[K2_USERNAME]"

#: paxes_cinder/k2aclient/shell.py:321
msgid ""
"k2aclient: you must provide a k2 password via either --k2-password or via"
" env[K2_PASSWORD]"
msgstr ""
"NV-EB948AA k2aclient : vous devez fournir un mot de passe k2 via "
"--k2-password ou env[K2_PASSWORD]"

#: paxes_cinder/k2aclient/shell.py:355
#, python-format
msgid "Display help for %s"
msgstr "Afficher l'aide sur %s"

#: paxes_cinder/k2aclient/shell.py:364
#, python-format
msgid "k2aclient:>%s< is not a valid subcommand"
msgstr "NV-DAC982A k2aclient :>%s< n'est pas une sous-commande valide"

#: paxes_cinder/k2aclient/shell.py:384
msgid "... terminating k2a client"
msgstr "NV-56344DF ... arrêt du client k2a"

#: paxes_cinder/k2aclient/shell.py:389
#, python-format
msgid "ERROR: type: >%(type)s<, msg: >%(e)s<"
msgstr "NV-9BF8F90 ERREUR : type : >%(type)s<, msg : >%(e)s<"

#: paxes_cinder/k2aclient/utils.py:101
#, python-format
msgid "k2aclient: no %(res)s with a name or ID of '%(name_or_id)s' exists."
msgstr ""
"NV-63A28A2 k2aclient : il n'existe pas de %(res)s avec le nom ou l'ID "
"'%(name_or_id)s'."

#: paxes_cinder/k2aclient/utils.py:108
#, python-format
msgid ""
"k2aclient: multiple %(res)s matches found for '%(name_or_id)s', use an ID"
" to be more specific."
msgstr ""
"NV-9ACDF38 k2aclient : plusieurs correspondances %(res)s trouvées pour "
"'%(name_or_id)s', utilisez un ID pour plus de précision."

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:144
#: paxes_cinder/k2aclient/v1/virtualioserver_manager.py:138
#, python-format
msgid "during directory preparation, cant create directory:  >%s<"
msgstr ""
"NV-64A449C lors de la péparation des répertoires, impossible de créer le "
"répertoire :  >%s<"

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:150
#: paxes_cinder/k2aclient/v1/virtualioserver_manager.py:144
#, python-format
msgid "during directory preparation, cant write to directory:  >%s<"
msgstr ""
"NV-C96CB61 lors de la péparation des répertoires, impossible d'écrire "
"dans le répertoire :  >%s<"

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:181
#: paxes_cinder/k2aclient/k2asample/k2_ssp_etag_test.py:44
#: paxes_cinder/k2aclient/k2asample/tool_ssp_simulation.py:228
#, python-format
msgid "Node: >%s<, has no virtual_io_server, continuing ..."
msgstr "NV-60D657D Noeud : >%s<, n'a pas de virtual_io_server, poursuivre..."

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:192
#: paxes_cinder/k2aclient/k2asample/k2_ssp_etag_test.py:55
#: paxes_cinder/k2aclient/k2asample/tool_ssp_simulation.py:239
#, python-format
msgid "Failed to retrieve node: >%s<, msg: >%s<, continuing ..."
msgstr "NV-0B99A4D Echec d'extraction du noeud : >%s<, msg : >%s<, poursuite..."

#: paxes_cinder/k2aclient/openstack/common/lockutils.py:276
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s for method \"%(method)s\"..."
msgstr ""
"NV-F6B31F1 Verrou de fichier \"%(lock)s\" libéré au niveau de %(path)s "
"pour la méthode \"%(method)s\"..."

#: paxes_cinder/k2aclient/v1/cluster_manager.py:98
#, python-format
msgid ""
"k2aclient: during lu_linked_clone_of_lu, source_lu_udid: "
">%(source_lu_udid)s<, not in sharedstoragepool: >%(ssp.id)s<"
msgstr ""
"NV-69F0ACE k2aclient : pendant lu_linked_clone_of_lu, source_lu_udid : "
">%(source_lu_udid)s<, pas dans sharedstoragepool : >%(ssp.id)s<"

#: paxes_cinder/k2aclient/v1/cluster_manager.py:221
#, python-format
msgid ""
"k2aclient: for cluster id : >%(cluster.id)s<,  during lu_linked_clone, "
"for SourceUDID: >%(sourceUDID)s<, and DestinationUDID: "
">%(destinationUDID)s<, experienced job failure, job_id: "
">%(jresponse.job_id)s<, status: >%(jresponse.status)s<, input K2 job "
"diagnostics have been written to: >%(diagfspeci)s<, response k2 job "
"diagnostics have been written to: >%(diagfspec)s<"
msgstr ""
"k2aclient : pour l'id de grappe : >%(cluster.id)s<,  pendant "
"lu_linked_clone, pour SourceUDID : >%(sourceUDID)s<, et DestinationUDID :"
" >%(destinationUDID)s<, échec du travail, job_id : "
">%(jresponse.job_id)s<, statut : >%(jresponse.status)s<, des diagnostics "
"de travail K2 en entrée ont été écrits dans : >%(diagfspeci)s<, des "
"diagnostics de travail k2 de réponse ont été écrits dans : "
">%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/cluster_manager.py:335
#, python-format
msgid ""
"k2aclient: for cluster id : >%(cluster.id)s<,  during lu_create, for "
"lu_unit_name: >%(lu_unit_name)s<, with lu_unit_capacity: "
">%(lu_unit_capacity)s<, experienced job failure, job_id: "
">%(jresponse.job_id)s<, status: >%(jresponse.status)s<, input K2 job "
"diagnostics have been written to: >%(diagfspeci)s<, response k2 job "
"diagnostics have been written to: >%(diagfspec)s<"
msgstr ""
"k2aclient : pour l'id de grappe : >%(cluster.id)s<,  pendant lu_create, "
"pour lu_unit_name : >%(lu_unit_name)s<, avec lu_unit_capacity : "
">%(lu_unit_capacity)s<, échec du travail, job_id : "
">%(jresponse.job_id)s<, statut : >%(jresponse.status)s<, des diagnostic "
"de travail K2 en entrée ont été écrits dans : >%(diagfspeci)s<, des "
"diagnostics de travail k2 de réponse ont été écrits dans : "
">%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/logicalpartition_manager.py:126
#: paxes_cinder/k2aclient/v1/logicalpartition_manager.py:191
#, python-format
msgid ""
"k2aclient: during power_on, for LogicalPartition: "
">%(logicalpartition.id)s<, failed to power on due to job failure, job_id:"
" >%(jresponse.job_id)s<, status: >%(jresponse.status)s<, input K2 job "
"diagnostics have been written to: >%(diagfspeci)s<, response k2 job "
"diagnostics have been written to: >%(diagfspec)s<"
msgstr ""
"k2aclient : pendant power_on, pour LogicalPartition : "
">%(logicalpartition.id)s<, échec de la mise sous tension en raison de "
"l'échec du travail, job_id : >%(jresponse.job_id)s<, statut : "
">%(jresponse.status)s<, des diagnostics de travail K2 en entrée ont été "
"écrits dans : >%(diagfspeci)s<, des diagnostics de travail k2 de réponse "
"ont été écrits dans : >%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/managementconsole_manager.py:77
#, python-format
msgid ""
"CLIRunner: ManagementConsole: >%(mc.id)s<, failed to run cmd: >%(cmd)s< "
"due to job failure, job_id: >%(jresponse.job_id)s<, status: "
">%(jresponse.status)s<, input K2 job diagnostics have been written to: "
">%(diagfspeci)s<,  response k2 job diagnostics have been written to: "
">%(diagfspec)s<"
msgstr ""
"CLIRunner : ManagementConsole : >%(mc.id)s<, échec d'exécution de "
"commande : >%(cmd)s< en raison de l'échec d'un travail, job_id : "
">%(jresponse.job_id)s<, statut : >%(jresponse.status)s<, les entrées de "
"diagnostic de travail K2 ont été écrits dans : >%(diagfspeci)s<,  le "
"diagnostic de travail k2 réponse a été écrit dans : >%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:108
#, python-format
msgid ""
"SharedStoragePool: While attempting to access Cluster: >%s<, unable to "
"connect to HMC: >%s<"
msgstr ""
"SharedStoragePool : Lors de la tentative d'accès à la grappe : >%s<, "
"impossible de se connecter à HMC : >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:110
msgid "Check the HMC and its configuration."
msgstr "Vérifiez la console HMC et sa configuration."

#: paxes_cinder/k2aclient/v1/paxes_manager.py:111
#, python-format
msgid "SharedStoragePool: Able to connect to HMC: >%s< for Cluster: >%s<"
msgstr "SharedStoragePool : Connexion possible à HMC : >%s< pour la grappe : >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:113
#, python-format
msgid "SharedStoragePool: Couldn't access Cluster: >%s<"
msgstr "SharedStoragePool : Impossible d'accéder à la grappe : >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:114
msgid "Check the PowerVC SharedStoragePool configuration"
msgstr "Vérifiez la configuration de SharedStoragePool PowerVC"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:115
#, python-format
msgid "SharedStoragePool: Couldn't access SharedStoragePool in Cluster: >%s<"
msgstr ""
"SharedStoragePool : Impossible d'accéder à SharedStoragePool dans la "
"grappe : >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:117
#: paxes_cinder/k2aclient/v1/paxes_manager.py:122
#: paxes_cinder/k2aclient/v1/paxes_manager.py:127
#: paxes_cinder/k2aclient/v1/paxes_manager.py:133
msgid "Diagnose and repair Cluster"
msgstr "Diagnostiquer et réparer la grappe"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:118
#, python-format
msgid ""
"SharedStoragePool: Successfully accessed SharedStoragePool in Cluster: "
">%s<"
msgstr "SharedStoragePool : Accès réussi à SharedStoragePool dans la grappe : >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:120
#, python-format
msgid "SharedStoragePool: Unable to create LogicalUnits in Cluster: >%s<"
msgstr "SharedStoragePool : Impossible de créer LogicalUnits dans la grappe : >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:123
#, python-format
msgid "SharedStoragePool: LogicalUnit creation functional in Cluster: >%s<"
msgstr ""
"SharedStoragePool : La création de LogicalUnit est fonctionnelle dans la "
"grappe : >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:125
#, python-format
msgid "SharedStoragePool: Unable to clone LogicalUnits in Cluster: >%s<"
msgstr ""
"SharedStoragePool : Impossible de cloner LogicalUnits dans la grappe : "
">%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:128
#, python-format
msgid ""
"SharedStoragePool: Unable to clone LogicalUnits in Cluster: >%s<, status:"
" >%s<"
msgstr ""
"SharedStoragePool : Impossible de cloner LogicalUnits dans la grappe : "
">%s<, statut : >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:130
#, python-format
msgid "Clone functional in Cluster: >%s<"
msgstr "Clone fonctionnel dans la grappe : >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:131
#, python-format
msgid "SharedStoragePool: Unable to delete LogicalUnits in Cluster: >%s<"
msgstr ""
"SharedStoragePool : Impossible de supprimer LogicalUnits dans la grappe :"
" >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:134
#, python-format
msgid "SharedStoragePool: LogicalUnit deletion functional in Cluster: >%s<"
msgstr ""
"Pool de stockage partagé : La suppression d'unité logique est "
"fonctionnelle dans la grappe : >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:136
msgid "SharedStoragePool: Not Attempted"
msgstr "Pool de stockage partagé : Non tenté"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:143
msgid "HMC connectivity"
msgstr "Connectivité HMC"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:144
msgid "Test connection to an HMC managing the SharedStoragePool"
msgstr "Testez la connexion à une console HMC qui gère le pool de stockage partagé"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:147
msgid "Cluster and SharedStoragePool accessibility"
msgstr "Accessibilité de la grappe et du groupe de stockage partagé"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:148
msgid "Test the accessibility of a SharedStoragePool"
msgstr "Testez l'accessibilité d'un pool de stockage partagé"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:151
msgid "Create SharedStoragePool LogicalUnits"
msgstr "Créez les unités logiques du pool de stockage partagé"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:152
msgid "Test the capability to create SharedStoragePool LogicalUnits"
msgstr ""
"Testez la capacité de création des unités logiques du pool de stockage "
"partagé"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:155
msgid "Clone LogicalUnits"
msgstr "Clonez les unités logiques"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:156
msgid "Test the capability to perform a clone"
msgstr "Testez la capacité de clonage"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:159
msgid "Delete SharedStoragePool LogicalUnits"
msgstr "Supprimez les unités logiques du pool de stockage partagé"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:160
msgid "Test the capability to delete SharedStoragePool LogicalUnits"
msgstr ""
"Testez la capacité de suppression des unités logiques du pool de stockage"
" partagé"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:112
#, python-format
msgid ""
"k2aclient: during updated_append_lus, cannot update K2 object(s) obtained"
" from a list operation, for ssp: >%s<"
msgstr ""
"NV-CEE080E k2aclient : au cours de updated_append_lus, impossible de "
"mettre à jour les objets K2 obtenus dans une opération de liste, pour ssp"
" : >%s<"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:158
#, python-format
msgid "k2aclient: during updated_append_lus, wrong length of lu input tuple: >%d<"
msgstr ""
"NV-B8F5AF7 k2aclient : au cours de updated_append_lus, longueur "
"incorrecte du bloc de données d'entrée d'unité logique : >%d<"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:192
#, python-format
msgid ""
"k2aclient:  during updated_append_lus, request to add LU unit_name: >%s< "
"failed, name must be unique"
msgstr ""
"NV-F6B87FC k2aclient :  au cours de updated_append_lus, la demande "
"d'ajout de l'unité logique nom_unité : >%s< a échoué, le nom doit être "
"unique"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:224
#, python-format
msgid ""
"k2aclient: during updated_append_lus, while adding LUs named: "
">%(lunames)s<,  # attempts due to HTTP 412 exceeded: "
">%(self.api.retries)d<"
msgstr ""
"NV-01A9381 k2aclient : au cours de updated_append_lus, lors de l'ajout "
"des unités logiques nommées : >%(lunames)s<,  dépassement du nb de "
"tentatives en raison de HTTP 412 : >%(self.api.retries)d<"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:260
#, python-format
msgid ""
"k2aclient: during updated_append_lus, cant handle K2 response, K2 "
"reported successful creation of >%(lenlus)d<  lus named: >%(lunames)s<,  "
"attempts: >%(attempts)d<  but only >%(lustoadd)d< LUs were found."
msgstr ""
"k2aclient : au cours de updated_append_lus, impossible de traiter la "
"réponse K2, K2 a signalé la création réussie de >%(lenlus)d< unités "
"logiques nommées : >%(lunames)s<,  tentatives : >%(attempts)d<  mais "
"seulement >%(lustoadd)d< unités logiques ont été trouvées."

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:276
#, python-format
msgid ""
"k2aclient: during updated_append_lus, cant handle K2 response, K2 "
"reported successful creation of >%(lenlus)d< lus named: >%(lunames)s<, "
"attempts: >%(attempts)d< but >%(lustoadd)d< extra LUs were returned."
msgstr ""
"k2aclient : au cours de updated_append_lus, impossible de traiter la "
"réponse K2, K2 a signalé la création réussie de >%(lenlus)d< unités "
"logiques nommées : >%(lunames)s<,  tentatives : >%(attempts)d< mais "
">%(lustoadd)d< unités logiques supplémentaires ont été renvoyées."

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:369
#, python-format
msgid ""
"k2aclient: during update_append_lu, programming error, could not find "
"lu_udid: >%(lu_udid)s<, in input ssp for: >%(pool)s<"
msgstr ""
"k2aclient : au cours de update_append_lu, erreur de programmation, "
"impossible de trouver lu_udid : >%(lu_udid)s<, dans le ssp d'entrée pour "
": >%(pool)s<"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:390
#, python-format
msgid ""
"k2aclient: during update_append_lu, while deleting LUs w/ udids: "
">%(lu_udids)s<, # attempts due to HTTP 412 exceeded: >%(retries)d<"
msgstr ""
"NV-A3B2A22 k2aclient : au cours de update_append_lu, lors de la "
"suppression des unités logiques avec udids : >%(lu_udids)s<, dépassement "
"du nb de tentatives en raison de HTTP 412 : >%(retries)d<"

#: paxes_cinder/k2aclient/v1/shell.py:55
#, python-format
msgid "k2aclient: during encoding unexpected type: >%s<"
msgstr "NV-AA592CA k2aclient : au cours du codage de type inattendu : >%s<"

#: paxes_cinder/k2aclient/v1/shell.py:205
#: paxes_cinder/k2aclient/v1/shell.py:801
#: paxes_cinder/k2aclient/v1/shell.py:812
msgid "Id of the cluster."
msgstr "Id de la grappe."

#: paxes_cinder/k2aclient/v1/shell.py:215
msgid "UUID of the cluster containing the LUs."
msgstr "UUID de la grappe contient les unités logiques."

#: paxes_cinder/k2aclient/v1/shell.py:218
msgid "UDID of the source logicalunit."
msgstr "UDID de l'unité logique source."

#: paxes_cinder/k2aclient/v1/shell.py:221
msgid "UDID of the destination logicalunit."
msgstr "UDID de l'unité logique de destination."

#: paxes_cinder/k2aclient/v1/shell.py:231
msgid "Id of the managedsystem to list logicalpartitions"
msgstr "ID du système géré pour répertorier les partitions logiques"

#: paxes_cinder/k2aclient/v1/shell.py:246
#: paxes_cinder/k2aclient/v1/shell.py:273
#: paxes_cinder/k2aclient/v1/shell.py:295
#: paxes_cinder/k2aclient/v1/shell.py:350
#: paxes_cinder/k2aclient/v1/shell.py:486
#: paxes_cinder/k2aclient/v1/shell.py:658
#: paxes_cinder/k2aclient/v1/shell.py:674
#: paxes_cinder/k2aclient/v1/shell.py:698
#: paxes_cinder/k2aclient/v1/shell.py:714
msgid "Id of the managedsystem."
msgstr "ID du système géré."

#: paxes_cinder/k2aclient/v1/shell.py:249
#: paxes_cinder/k2aclient/v1/shell.py:262
#: paxes_cinder/k2aclient/v1/shell.py:617
#: paxes_cinder/k2aclient/v1/shell.py:634
msgid "Id of the logicalpartition."
msgstr "ID de la partition logique."

#: paxes_cinder/k2aclient/v1/shell.py:276
msgid "UDIDs of the logicalpartition."
msgstr "UDID de la partition logique."

#: paxes_cinder/k2aclient/v1/shell.py:313
#: paxes_cinder/k2aclient/v1/shell.py:324
#: paxes_cinder/k2aclient/v1/shell.py:347
msgid "Id of the managementconsole."
msgstr "ID de la console de gestion."

#: paxes_cinder/k2aclient/v1/shell.py:327
#: paxes_cinder/k2aclient/v1/shell.py:356
msgid "Command to run."
msgstr "Commande à exécuter."

#: paxes_cinder/k2aclient/v1/shell.py:353
msgid "UUID of the virtualioserver."
msgstr "UUID de virtualioserver."

#: paxes_cinder/k2aclient/v1/shell.py:394
msgid "Id of the sharedstoragepool."
msgstr "ID du pool de stockage partagé."

#: paxes_cinder/k2aclient/v1/shell.py:405
#: paxes_cinder/k2aclient/v1/shell.py:443
#: paxes_cinder/k2aclient/v1/shell.py:456
msgid "UUID of the sharedstoragepool."
msgstr "UUID du pool de stockage partagé."

#: paxes_cinder/k2aclient/v1/shell.py:408
msgid "Name of the new logicalunit."
msgstr "Nom de la nouvelle unité logique."

#: paxes_cinder/k2aclient/v1/shell.py:411
msgid "Capacity of the new logicalunit."
msgstr "Capacité de la nouvelle unité logique."

#: paxes_cinder/k2aclient/v1/shell.py:414
msgid "Optional flag to control whether the new logicalunit will be thick or thin"
msgstr ""
"Indicateur facultatif contrôlant si la nouvelle unité logique sera à "
"allocation standard ou dynamique"

#: paxes_cinder/k2aclient/v1/shell.py:419
msgid "LogicalUnitType: VirtualIO_Disk | VirtualIO_Image"
msgstr "Type d'unité logique : VirtualIO_Disk | VirtualIO_Image"

#: paxes_cinder/k2aclient/v1/shell.py:423
msgid "Optional udid of LU to clone from, new if omitted"
msgstr ""
"udid facultatif de l'unité logique à partir de laquelle cloner, nouvelle "
"en cas d'omission"

#: paxes_cinder/k2aclient/v1/shell.py:446
msgid "UDIDs of the logicalunit."
msgstr "UDID de l'unité logique."

#: paxes_cinder/k2aclient/v1/shell.py:459
msgid "Optional flag to control whether full details should be output"
msgstr ""
"Indicateur facultatif contrôlant si des détails complets doivent être "
"fournis en sortie"

#: paxes_cinder/k2aclient/v1/shell.py:471
msgid "Id of the managedsystem to list virtualioservers"
msgstr "ID du système géré pour répertorier les virtualioservers"

#: paxes_cinder/k2aclient/v1/shell.py:489
#: paxes_cinder/k2aclient/v1/shell.py:513
msgid "Id of the virtualioserver."
msgstr "ID du virtualioserver."

#: paxes_cinder/k2aclient/v1/shell.py:493
msgid ""
"Optional extended attributes Valid values include: All, Advanced, "
"Hypervisor, SystemNetwork, ViosStorage, ViosNetwork, ViosFCMapping, "
"ViosSCSIMapping, and None May be used multiple times. \"All\" if omitted"
msgstr ""
"Attributs étendus facultatifs Valeurs valides : All, Advanced, "
"Hypervisor, SystemNetwork, ViosStorage, ViosNetwork, ViosFCMapping, "
"ViosSCSIMapping et None Peuvent être utilisés plusieurs fois. \"All\" en "
"cas d'omission"

#: paxes_cinder/k2aclient/v1/shell.py:608
msgid "Id of the logicalpartition to list clientnetworkadapters"
msgstr ""
"ID de la partition logique pour répertorier les adaptateurs de réseau "
"client"

#: paxes_cinder/k2aclient/v1/shell.py:620
msgid "Id of the clientnetworkadapter."
msgstr "ID de l'adaptateur de réseau client."

#: paxes_cinder/k2aclient/v1/shell.py:637
msgid "UDIDs of the clientnetworkadapter."
msgstr "UDID de l'adaptateur de réseau client."

#: paxes_cinder/k2aclient/v1/shell.py:649
msgid "Id of the managedsystem to list virtualnetworks"
msgstr "ID du système géré pour répertorier les réseaux virtuels"

#: paxes_cinder/k2aclient/v1/shell.py:661
msgid "Id of the virtualnetwork."
msgstr "ID du réseau virtuel."

#: paxes_cinder/k2aclient/v1/shell.py:677
msgid "UDIDs of the virtualnetwork."
msgstr "UDID du réseau virtuel."

#: paxes_cinder/k2aclient/v1/shell.py:689
msgid "Id of the managedsystem to list virtualswitchs"
msgstr "ID du système géré pour répertorier les commutateurs virtuels"

#: paxes_cinder/k2aclient/v1/shell.py:701
msgid "Id of the virtualswitch."
msgstr "ID du commutateur virtuel."

#: paxes_cinder/k2aclient/v1/shell.py:717
msgid "UDIDs of the virtualswitch."
msgstr "UDID du commutateur virtuel."

#: paxes_cinder/k2aclient/v1/shell.py:740
msgid "Id of the file."
msgstr "ID du fichier."

#: paxes_cinder/k2aclient/v1/shell.py:750
msgid "Ids of the files."
msgstr "ID des fichiers."

#: paxes_cinder/k2aclient/v1/shell.py:761
msgid "/rest/api/uom<uomresource>."
msgstr "/rest/api/uom<uomresource>."

#: paxes_cinder/k2aclient/v1/shell.py:766
msgid "Send output to file"
msgstr "Envoyer la sortie vers un fichier"

#: paxes_cinder/k2aclient/v1/shell.py:782
msgid "Read cinder ssp conf files and report on health"
msgstr ""
"Lecture des fichiers de configuration ssp cinder et rapport sur l'état de"
" santé"

#: paxes_cinder/k2aclient/v1/shell.py:815
#: paxes_cinder/k2aclient/v1/shell.py:843
msgid "VIOS password for all VIOS defaults to \"padmin\""
msgstr "Mot de passe VIOS pour tous les VIOS par défaut sur \"padmin\""

#: paxes_cinder/k2aclient/v1/shell.py:820
#: paxes_cinder/k2aclient/v1/shell.py:848
msgid "Target directory for snapsdefaults to \"/tmp/vios-snap\""
msgstr "Répertoire cible pour snapsdefaults sur \"/tmp/vios-snap\""

#: paxes_cinder/k2aclient/v1/shell.py:839
msgid "list of vios ips expressed as jsoneg '[\"9.47.161.157\"]'"
msgstr "liste des IP vios exprimées comme jsoneg '[\"9.47.161.157\"]'"

#: paxes_cinder/k2aclient/v1/v1k2creater.py:170
#, python-format
msgid "k2aclient: during process_root, unrecognized service: >%s<"
msgstr ""
"NV-1FC12D8 k2aclient : au cours de process_root, service non reconnu : "
">%s<"

#: paxes_cinder/k2aclient/v1/v1k2loader.py:61
#, python-format
msgid ""
"k2aclient: during k2 deserialization, for type: >%(pcname)s<, k2 gave "
"unknown attr: >%(us_tag)s<, is there a schema mismatch?, will skip ..."
msgstr ""
"NV-A18BFC5 k2aclient : au cours de la désérialisation k2, pour le type : "
">%(pcname)s<, k2 a fourni un attr inconnu : >%(us_tag)s<, existe-t-il une"
" non concordance de schéma ?, sera ignoré ..."

#: paxes_cinder/k2aclient/v1/v1k2loader.py:77
#, python-format
msgid ""
"k2aclient: during k2 deserialization, for type: >%(pcname)s<, k2 attr: "
">%(us_tag)s<: is listed as scalar, but maybe its not?, is there a schema "
"mismatch?, will replace existing scalar w/ next value ..."
msgstr ""
"k2aclient : au cours de la désérialisation de k2, pour le type : "
">%(pcname)s<, attr k2 : >%(us_tag)s<: est répertorié comme étant "
"scalaire, mais ce n'est peut-être pas le cas ?, existe-t-il une non "
"concordance de schéma ?, remplacera la valeur scalaire par la valeur "
"suivante ..."

#: paxes_cinder/k2aclient/v1/v1k2loader.py:131
#, python-format
msgid ""
"k2aclient: during k2 deserialization, while processing: k2 type: "
">%(parent_tag)s<, there is no definition for k2 type: >%(k2type)s<, is "
"there a schema mismatch?, will skip ..."
msgstr ""
"k2aclient : au cours de la désérialisation k2, lors du traitement : type "
"k2 : >%(parent_tag)s<, il n'existe pas de définition pour le type k2 : "
">%(k2type)s<, existe-t-il une non concordance de schéma ?, sera ignoré "
"..."

#: paxes_cinder/k2aclient/v1/v1k2loader.py:190
#: paxes_cinder/k2aclient/v1/v1k2loader.py:199
msgid "k2aclient:"
msgstr "NV-E561712 k2aclient :"

#: paxes_cinder/k2aclient/v1/virtualioserver_manager.py:280
#, python-format
msgid ""
"k2aclient: during lua_recovery, for device_id: >%(device_id)s<, "
"experienced job failure, job_id: >%(jresponse.job_id)s<, status: "
">%(jresponse.status)s<, input K2 job diagnostics have been written to: "
">%(diagfspeci)s<, response k2 job diagnostics have been written to: "
">%(diagfspec)s<"
msgstr ""
"k2aclient : au cours de lua_recovery, pour device_id : >%(device_id)s<, "
"échec du travail, job_id : >%(jresponse.job_id)s<, statut : "
">%(jresponse.status)s<, les diagnostics de travail K2 en entrée ont été "
"écrits dans : >%(diagfspeci)s<, les diagnostics de travail k2 de réponse "
"ont été écrits dans : >%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/web_file_manager.py:83
msgid ""
"k2aclient: during file upload, filename: >%(wf.filename)s<, id: "
">%(wf.id)s<, file_uuid: >%(wf.file_uuid)s<, file_enum_type: "
">%(wf.file_enum_type)s<"
msgstr ""
"k2aclient : au cours du téléchargement de fichier, nom de fichier : "
">%(wf.filename)s<, id : >%(wf.id)s<, file_uuid : >%(wf.file_uuid)s<, "
"file_enum_type : >%(wf.file_enum_type)s<"

#: paxes_cinder/k2aclient/v1/web_job_manager.py:65
#, python-format
msgid ""
"k2aclient: during %(jobtype)s, retry job, job_id: >%(job_id)s<, status: "
">%(status)s<,"
msgstr ""
"NV-FBECCFD k2aclient : durant %(jobtype)s, relancer travail, job_id : "
">%(job_id)s<, statut : >%(status)s<,"

#: paxes_cinder/k2aclient/v1/web_job_manager.py:77
#, python-format
msgid ""
"k2aclient: during %(jobtype)s, too many retries, maximum number of "
"retries: >%(maxretries)d<, job_id: >%(job_id)s<, status: >%(status)s<,"
msgstr ""
"k2aclient : durant %(jobtype)s, trop de relances, nombre maximal de "
"relances : >%(maxretries)d<, job_id : >%(job_id)s<, statut : "
">%(status)s<,"

#: paxes_cinder/scheduler/host_manager.py:59
#, python-format
msgid "clean up host_state_map: %(host)shost"
msgstr "NV-F9D1534 Nettoyage de host_state_map : %(host)shost"

#: paxes_cinder/scheduler/sched_drv.py:56
#, python-format
msgid "volume request: requested size: %(size)s. "
msgstr "demande de volume : taille demandée : %(size)s. "

#: paxes_cinder/scheduler/sched_drv.py:62
#, python-format
msgid ""
"{host: %(hostname)s, free_capacity: %(free_cap)s, total_capacity: "
"%(total)s, reserved_percentage: %(reserved)s, last update: "
"%(time_updated)s}"
msgstr ""
"{hôte : %(hostname)s, free_capacity: %(free_cap)s, total_capacity: "
"%(total)s, reserved_percentage: %(reserved)s, dernière mise à jour : "
"%(time_updated)s}"

#: paxes_cinder/scheduler/sched_drv.py:72
msgid "request exceeds capacity: info"
msgstr "NV-DBCC600 la demande dépasse la capacité : info"

#: paxes_cinder/scheduler/sched_drv.py:75
msgid "No storage has been registered. "
msgstr "NV-96E101B Aucun stockage n'a été enregistré. "

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:67
msgid ""
"Free capacity not set: Volume node is either still under initialization "
"or the node info collection is broken."
msgstr ""
"NV-872554F Capacité disponible non définie : le noeud de volume est "
"encore en cours d'initialisation ou la collecte des informations de noeud"
" est interrompue."

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:99
msgid "missing default_volume_type"
msgstr "NV-404930C default_volume_type manquant"

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:106
#, python-format
msgid ""
"missing valid rsize on                                 "
"%(default)svolume_type: %(vol_type)s"
msgstr ""
"NV-B717E15 rsize valide manquante dans                                "
"%(default)svolume_type : %(vol_type)s"

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:117
#, python-format
msgid ""
"Insufficient free space for volume creation (requested / avail / rsize): "
"%(requested)s/%(available)s/%(rsize)s"
msgstr ""
"NV-5CC98A1 Espace disque insuffisant pour la création du volume "
"(requested / avail / rsize) : %(requested)s/%(available)s/%(rsize)s"

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:124
#, python-format
msgid ""
"Sufficient free space for volume creation (requested / avail / rsize): "
"%(requested)s/%(available)s/%(rsize)s"
msgstr ""
"NV-D0E32D8 Espace disque suffisant pour la création du volume (requested "
"/ avail / rsize) : %(requested)s/%(available)s/%(rsize)s"

#: paxes_cinder/scohack/scohack_http.py:150
#, python-format
msgid "BadStoreUri: credentials '%(creds)s' not well-formatted."
msgstr ""
"NV-5991AD7 BadStoreUri : données d'identification utilisateur '%(creds)s'"
" qui ne sont pas formatées correctement."

#: paxes_cinder/scohack/scohack_http.py:160
msgid "BadStoreUri: no address specified in HTTP URL"
msgstr "NV-2A5D3E2 BadStoreUri : pas d'adresse spécifiée dans l'URL HTTP"

#: paxes_cinder/scohack/scohack_http.py:295
#, python-format
msgid "MaxRedirectsExceeded: redirects: >%(max)d<"
msgstr "NV-30617DF MaxRedirectsExceeded : redirections : >%(max)d<"

#: paxes_cinder/scohack/scohack_http.py:308
#, python-format
msgid "HTTP URL returned a %(status)s status code."
msgstr "L'URL HTTP a renvoyé un code d'état %(status)s."

#: paxes_cinder/scohack/scohack_http.py:310
#: paxes_cinder/scohack/scohack_http.py:322
#, python-format
msgid "BadStoreUri: loc.path: >%(path)s<, reason: >%(reason)s<"
msgstr "NV-0E3AB46 BadStoreUri : loc.path : >%(path)s<, raison : >%(reason)s<"

#: paxes_cinder/scohack/scohack_location.py:50
#, python-format
msgid "exception.UnknownScheme: scheme: >%(scheme)s<"
msgstr "NV-B8DA628 exception.UnknownScheme : schéma : >%(scheme)s<"

#: paxes_cinder/scohack/scohack_scohack.py:77
msgid "URI must start with scohack://"
msgstr "NV-DF4522D L'URI doit commencer par scohack://"

#: paxes_cinder/scohack/scohack_scohack.py:79
#, python-format
msgid "BadStore: uri: >%(uri)s<, reason: >%(reason)s<"
msgstr "NV-7D2A4E2 BadStore : uri : >%(uri)s<, raison : >%(reason)s<"

#: paxes_cinder/scohack/scohack_scohack.py:93
#, python-format
msgid "x-scg-vios-id: >%(id)s< not of form 'ttttmmm_sssssssnnn'"
msgstr ""
"NV-9CCE26B x-scg-vios-id : >%(id)s< n'est pas au format "
"'ttttmmm_sssssssnnn'"

#: paxes_cinder/scohack/scohack_scohack.py:106
#, python-format
msgid "scohack: x-scg-vios-id: cant list ManagedSystem: >%(ex)s<"
msgstr ""
"NV-405AA27 scohack : x-scg-vios-id : impossible de répertorier le système"
" géré : >%(ex)s<"

#: paxes_cinder/scohack/scohack_scohack.py:121
#, python-format
msgid "scohack: x-scg-vios-id: cant find ManagedSystem for: >%(id)s<"
msgstr ""
"NV-708F8BE scohack : x-scg-vios-id : impossible de trouver le système "
"géré pour : >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:129
#, python-format
msgid "scohack: x-scg-vios-id: cant list VirtualIoServer: >%(ex)s<"
msgstr ""
"NV-2D6AE0A scohack : x-scg-vios-id : impossible de répertorier "
"VirtualIoServer : >%(ex)s<"

#: paxes_cinder/scohack/scohack_scohack.py:139
#, python-format
msgid "scohack: x-scg-vios-id: cant find VirtualIOServer for: >%(id)s<"
msgstr ""
"NV-081426D scohack : x-scg-vios-id : impossible de trouver find "
"VirtualIOServer pour : >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:162
msgid "scohack: cant list vios"
msgstr "NV-D40CA86 scohack : impossible de répertorier vios"

#: paxes_cinder/scohack/scohack_scohack.py:168
msgid "scohack: no vios found"
msgstr "NV-ABFCCCD scohack : aucun vios trouvé"

#: paxes_cinder/scohack/scohack_scohack.py:177
#, python-format
msgid "scohack: cant list vios for ms: >%(id)s<"
msgstr "NV-D6ED6BF scohack : impossible de répertorier vios pour ms : >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:184
#, python-format
msgid "scohack: no vios found for ms: >%(id)s<"
msgstr "NV-0FD0B8A scohack : aucun vios trouvé pour ms : >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:195
#, python-format
msgid "scohack: for ms: >%(mid)s<, cant find vios: >%(vid)s<"
msgstr ""
"NV-AD83B35 scohack : pour ms : >%(mid)s<, impossible de trouver vios : "
">%(vid)s<"

#: paxes_cinder/scohack/scohack_scohack.py:204
#, python-format
msgid "scohack: cant find vios: >%(vid)s<"
msgstr "NV-3704F44 scohack : impossible de trouver vios : >%(vid)s<"

#: paxes_cinder/scohack/scohack_scohack.py:328
#, python-format
msgid ""
"scohack: only single hmc is supported: prev: >%(prev_id)s<, new: "
">%(new_id)s<"
msgstr ""
"NV-185C13E scohack : une seule console hmc est prise en charge : préc : "
">%(prev_id)s<, nouveau : >%(new_id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:339
#, python-format
msgid "scohack: no HMC for id: >%(id)s<"
msgstr "NV-628D2F6 scohack : aucune console HMC pour l'id : >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:352
#, python-format
msgid ""
"scohack: managemenconsole: >%(mc)s< could not be retrieved, hdisks will "
"not be cleaned up, msg: >%(msg)s<"
msgstr ""
"scohack : console de gestion : >%(mc)s< n'a pas pu être extrait, hdisks "
"ne sera pas nettoyé, msg : >%(msg)s<"

#: paxes_cinder/scohack/scohack_scohack.py:383
#, python-format
msgid "scohack: vios: >%(vios)s<, volume: >%(vol)s<"
msgstr "NV-22A4C11 scohack : vios : >%(vios)s<, volume : >%(vol)s<"

#: paxes_cinder/scohack/scohack_scohack.py:400
#, python-format
msgid "scohack: image upload: hdisk: >%(hdisk)s<, vios: >%(vios)s<"
msgstr ""
"NV-B86BF01 scohack : téléchargement d'image : hdisk : >%(hdisk)s<, vios :"
" >%(vios)s<"

#: paxes_cinder/scohack/scohack_scohack.py:417
#, python-format
msgid "scohack: volume not found: >%(volume)s<"
msgstr "NV-CDC6DBB scohack : volume introuvable : >%(volume)s<"

#: paxes_cinder/scohack/scohack_scohack.py:428
#, python-format
msgid "scohack: volume: invalid status: >%(status)s<"
msgstr "NV-D365509 scohack : volume : statut non valide : >%(status)s<"

#: paxes_cinder/scohack/scohack_scohack.py:445
#, python-format
msgid "scohack: no ports for vios: >%(vios)s<"
msgstr "NV-230F42F scohack : pas de port pour vios : >%(vios)s<"

#: paxes_cinder/scohack/scohack_scohack.py:461
#, python-format
msgid "scohack: failed to connect to volume >%(volume_id)s< "
msgstr "NV-E7095A2 scohack : impossible de se connecter au volume >%(volume_id)s< "

#: paxes_cinder/scohack/scohack_scohack.py:471
#, python-format
msgid ""
"scohack: for target volume: >%(volume)s<, bad connection: >%(info)s<, no "
"target_lun"
msgstr ""
"NV-79C5617 scohack : pour le volume cible : >%(volume)s<, connexion "
"incorrecte : >%(info)s<, pas de target_lun"

#: paxes_cinder/scohack/scohack_scohack.py:487
#, python-format
msgid ""
"scohack: for target volume: >%(volume)s<, no target wwpn found in "
"connection: >%(info)s< "
msgstr ""
"NV-5C2B384 scohack : pour le volume cible : >%(volume)s<, pas de wwpn "
"cible trouvé dans la connexion : >%(info)s< "

#: paxes_cinder/scohack/scohack_scohack.py:506
#, python-format
msgid "scohack: target volume: >%(volume)s<, does not have page83 data"
msgstr ""
"NV-33E8084 scohack : volume cible : >%(volume)s<, n'a pas de données "
"page83"

#: paxes_cinder/scohack/scohack_scohack.py:514
#, python-format
msgid "scohack: start luarecovery: deviceid: >%(id)s< , itls: >%(itls)s<"
msgstr ""
"NV-0A59DDD scohack : lancer luarecovery : deviceid : >%(id)s< , itls: "
">%(itls)s<"

#: paxes_cinder/scohack/scohack_scohack.py:525
#, python-format
msgid "scohack: lua_recovery job failed for target volume: >%(volume)s<"
msgstr ""
"NV-D94C9A2 scohack : échec du travail lua_recovery pour le volume cible :"
" >%(volume)s<"

#: paxes_cinder/scohack/scohack_scohack.py:538
#, python-format
msgid "scohack: luarcovery job status: >%(status)s<, result: >%(res)s<"
msgstr ""
"NV-FC7E239 scohack : statut luarcovery job : >%(status)s<, résultat : "
">%(res)s<"

#: paxes_cinder/scohack/scohack_scohack.py:544
#, python-format
msgid ""
"scohack: lua_recovery job internal error, device_list is invalid device "
"list: >%(lua_list)s<"
msgstr ""
"NV-610160F scohack : erreur interne du travail lua_recovery, device_list "
"n'est pas une liste d'unités valide : >%(lua_list)s<"

#: paxes_cinder/scohack/scohack_scohack.py:552
#, python-format
msgid ""
"scohack: lua_recovery job returned multiple devices device list: "
">%(lua_list)s<, will select first ..."
msgstr ""
"NV-3A4481D scohack : le travail lua_recovery a renvoyé plusieurs unités, "
"liste d'unités : >%(lua_list)s<, sélection de la première de la liste ..."

#: paxes_cinder/scohack/scohack_scohack.py:562
#, python-format
msgid ""
"This means that a device was found from an ITL nexus and it was "
"determined to be in use by the VIOS. The most likely cause is that a "
"virtual device was not removed from a previous deploy. The VIOS took no "
"action in this case. device: >%(dev)s<"
msgstr ""
"Cela signifie qu'une unité a été trouvée à partir d'un ITL nexus et il "
"s'avère qu'elle est utilisée par le VIOS. Cela est vraisemblablement dû "
"au fait qu'une unité virtuelle n'a pas été supprimée d'un déploiement "
"précédent. Dans ce cas, le VIOS n'a exécuté aucune action. unité : "
">%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:572
#, python-format
msgid ""
"This means that the ITL nexus is not consider reliable and some error "
"occurred that prevents the VIOS from determining making a decision on "
"safely removing a device. The VIOS took no action in this case. Perhaps "
"try to remove the offending hdisk from the VIOS, with rmdev -d -l hdiskx."
" device: >%(dev)s<"
msgstr ""
"NV-DC7D321 Cela signifie que l'ITL nexus n'est pas considéré comme fiable"
" et une erreur empêchant le VIOS de prendre la décision de supprimer une "
"unité en toute sécurité s'est produite. Dans ce cas, le VIOS n'a exécuté "
"aucune action. Essayez peut-être de supprimer le disque dur à l'origine "
"du problème du VIOS avec rmdev -d -l hdiskx. unité : >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:585
#, python-format
msgid ""
"This means the information provided and action taken by the VIOS was "
"sufficient to find the storage. pvName, and uniqueID elements will follow"
" in the data stream. device: >%(dev)s<"
msgstr ""
"NV-8DB8D33 Cela signifie que les informations fournies et l'action "
"effectuée par le VIOS n'était pas suffisante pour trouver le stockage. "
"Les éléments pvName et uniqueID suivront dans le flux de données. unité :"
" >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:593
#, python-format
msgid ""
"This means some new storage element was found at the ITL nexus but VIOS "
"could not determine if it is the storage of interest to the management "
"tool. device: >%(dev)s<"
msgstr ""
"NV-36ADD00 Cela signifie qu'un nouvel élément de stockage a été trouvé "
"dans l'ITL nexus, mais le VIOS n'a pas pu déterminer s'il s'agit d'un "
"stockage présentant de l'intérêt pour l'outil de gestion. unité : "
">%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:602
#, python-format
msgid ""
"The VIOS could not determine if this is logical unit of interest to the "
"management tool however did find a device from the ITL nexus list. "
"device: >%(dev)s<"
msgstr ""
"NV-6761BFF Le VIOS n'a pas pu déterminer s'il s'agit de l'unité logique "
"qui présente de l'intérêt pour l'outil de gestion. Cependant, l'unité a "
"été trouvée dans la liste d'ITL nexus. unité : >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:611
#, python-format
msgid ""
"The VIOS could not find a device from the itl nexus list. It could be "
"some SCSI or transport error occurred during configuration or the ITL "
"nexus list was incorrect. device: >%(dev)s<"
msgstr ""
"NV-2479600 Le VIOS n'a pas trouvé une unité dans la liste d'ITL nexus. Il"
" se peut qu'une erreur SCSI ou de transport se soit produire au cours de "
"la configuration ou que la liste d'ITL nexus soit incorrecte. unité : "
">%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:622
#, python-format
msgid ""
"Unknown device status. Severe internal error contact NCO. device: "
">%(dev)s<"
msgstr ""
"NV-2EF1D11 Statut d'unité inconnu. Erreur interne grave. Contactez NCO. "
"unité : >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:638
#, python-format
msgid "scohack: failed to find device name: >%(dev)s<"
msgstr "NV-B6E8402 scohack : impossible de trouver nom_unité : >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:643
#, python-format
msgid "scohack: found device name: >%(dev)s<"
msgstr "NV-32CF4C2 scohack : nom_unité trouvé : >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:665
#, python-format
msgid "scohack: hdisk_uuid: >%(hdisk)s<, checksum not specified"
msgstr ""
"NV-D85ABDC scohack : uuid_hdisk : >%(hdisk)s<, total de contrôle non "
"spécifié"

#: paxes_cinder/scohack/scohack_scohack.py:672
#, python-format
msgid "scohack: hdisk_uuid: >%(hdisk)s<, size not specified"
msgstr "NV-9783CB3 scohack : uuid_hdisk : >%(hdisk)s<, taille non spécifiée"

#: paxes_cinder/scohack/scohack_scohack.py:694
#, python-format
msgid ""
"scohack: image upload complete for hdisk_uuid: >%(hdisk)s<, webfile id: "
">%(wid)s<, actual size: >%(size)s< bytes, elapsed time: >%(time)d< "
"seconds, rate: >%(rate)f< minutes/GB"
msgstr ""
"scohack : téléchargement d'image terminé pour uuid_hdisk : >%(hdisk)s<, "
"id fichier web : >%(wid)s<, actual size: >%(size)s< octets, temps écoulé "
": >%(time)d< secondes, taux : >%(rate)f< minutes/Go"

#: paxes_cinder/scohack/scohack_scohack.py:709
#, python-format
msgid ""
"scohack:  mismatch: expected_file_size_in_bytes: >%e_size)d<, "
"current_file_size_in_bytes: >%(c_size)d<"
msgstr ""
"NV-E2ACA08 scohack :  non concordance : taille_fichier_attendue_en_octets"
" : >%e_size)d<, taille_fichier_actuelle_en_octets : >%(c_size)d<"

#: paxes_cinder/scohack/scohack_scohack.py:740
#, python-format
msgid ""
"scohack: cleanup failure for: >%(hdisk)s<, job status: >%(status)s<, "
"response: >%(res)s< continuing ..."
msgstr ""
"NV-C9A426B scohack : échec de nettoyage pour : >%(hdisk)s<, statut du "
"travail : >%(status)s<, réponse : >%(res)s< poursuite..."

#: paxes_cinder/scohack/scohack_scohack.py:752
#, python-format
msgid ""
"scohack: for hdisk_uuid: >%(hdisk)s<  no managementconsole, hisks will "
"not be cleaned up"
msgstr ""
"NV-508BE83 scohack : pour uuid_hdisk : >%(hdisk)s<  pas de console de "
"gestion, hisks ne seront pas nettoyés"

#: paxes_cinder/scohack/scohack_scohack.py:758
#: paxes_cinder/scohack/scohack_scohack.py:768
#, python-format
msgid "scohack: for hdisk_uuid: >%(hdisk)s< cleanup failed, msg: >%(ex)s<"
msgstr ""
"NV-B37BCB5 scohack : pour uuid_hdisk : >%(hdisk)s< échec du nettoyage, "
"msg : >%(ex)s<"

#: paxes_cinder/scohack/scohack_scohack.py:772
#, python-format
msgid "scohack: upload failed for hdisk_uuid: >%(dsk)s<"
msgstr "NV-D7A600C scohack : échec du téléchargement pour uuid_hdisk : >%(dsk)s<"

#: paxes_cinder/scohack/scohack_utils.py:47
#, python-format
msgid "Error: cooperative_iter exception %(error)s"
msgstr "NV-23E8986 Erreur : exception cooperative_iter %(error)s"

#: paxes_cinder/volume/__init__.py:46
#, python-format
msgid ""
"cinder volume_create interface has been changed. PowerVC monkey patch for"
" volume clone won't work. function: %(fx)s, arguments: %(args)s"
msgstr ""
"NV-7A6F9A4 L'interface cinder volume_create a été modifiée. Le correctif "
"PowerVC monkey patch pour le clonage de volume va échouer. fonction : "
"%(fx)s, arguments : %(args)s"

#: paxes_cinder/volume/__init__.py:61
#, python-format
msgid ""
"Monkey patched volume clone by paxes volume_create_decorator(). Source "
"Volume ID: %(svol)s, volume type name: %(voltpnm)s, volume type ID: "
"%(voltpid)s"
msgstr ""
"NV-D17192A Clonage du volume avec correctif Monkey par paxes "
"volume_create_decorator(). ID volume source : %(svol)s, nom de type de "
"volume : %(voltpnm)s, ID type de volume : %(voltpid)s"

#: paxes_cinder/volume/__init__.py:94
#, python-format
msgid ""
"Failed to get the parameters from function "
"cinder.volume.volume_types.create(). Default quota didn't set for the "
"storage template. Error: %(err)s"
msgstr ""
"NV-A4934EA Impossible d'obtenir les paramètres de la fonction "
"cinder.volume.volume_types.create(). Le quota par défaut n'a pas été "
"défini pour le modèle de stockage. Erreur : %(err)s"

#: paxes_cinder/volume/__init__.py:114
#, python-format
msgid "Successfully set default quota for storage template %(vol_type)s"
msgstr ""
"NV-71868FF Le quota par défaut a été défini avec succès pour le modèle de"
" stockage %(vol_type)s"

#: paxes_cinder/volume/__init__.py:118
#, python-format
msgid ""
"Failed to set default quota for storage template %(vol_type)s, error: "
"%(err)s"
msgstr ""
"NV-D86E5F7 Echec de la définition du quota par défaut pour le modèle de "
"stockage %(vol_type)s, erreur : %(err)s"

#: paxes_cinder/volume/__init__.py:122
#, python-format
msgid ""
"Cannot set default quota for storage template %(vol_type) due to invalid "
"Parameters from volume type create."
msgstr ""
"NV-D9BA448 Impossible de définir le quota par défaut pour le modèle de "
"stockage %(vol_type) en raison de paramètres non valides de la création "
"de type de volume."

#: paxes_cinder/volume/__init__.py:175
#, python-format
msgid "Error getting data volumes: %s "
msgstr "NV-7627301 Erreur lors de l'obtention des volumes de données : %s "

#: paxes_cinder/volume/manager.py:89
#, python-format
msgid "Cannot perform direct SAN operation on disk with prefix %(prefix)s"
msgstr ""
"NV-1701BDD Impossible d'exécuter l'opération SAN directe sur le disque "
"avec le préfixe %(prefix)s"

#: paxes_cinder/volume/manager.py:100
msgid "Driver still initializing, wait..."
msgstr ""
"NV-C6CA9E0 Le pilote est encore en cours d'initialisation, veuillez "
"patienter..."

#: paxes_cinder/volume/manager.py:102
#, python-format
msgid "Try again: %s"
msgstr "NV-FEE7BD0 Réessayez : %s"

#: paxes_cinder/volume/manager.py:172
#, python-format
msgid "Fabric {fabric_name} ({user}@{ip}:{port}): %(message)s"
msgstr ""
"NV-0A01336 Ensemble de noeuds {nom_ensembles_noeuds} "
"({utilisateur}@{ip}:{port}) : %(message)s"

#: paxes_cinder/volume/manager.py:188
#, python-format
msgid ""
"Storage Provider {storage_provider_hostname} ({user}@{ip}:{port}) "
"{volume_id}: %(message)s"
msgstr ""
"NV-E1A972C Fournisseur de stockage {nomhôte_fournisseur_stockage} "
"({utilisateur}@{ip}:{port}) {id_volume} : %(message)s"

#: paxes_cinder/volume/manager.py:223
msgid ""
"The volume is already attached to another virtual server, possibly one "
"that is not managed by PowerVC."
msgstr ""
"Le volume est déjà connecté à un autre serveur virtuel ; il se peut qu'il"
" s'agisse d'un volume qui n'est pas géré par PowerVC."

#: paxes_cinder/volume/manager.py:227
msgid ""
"The volume cannot be deleted because it is either mapped to a host or "
"part of a flashcopy or remote copy operation."
msgstr ""
"Le volume ne peut pas être supprimé car il mappé à un hôte ou fait partie"
" d'une opération Flashcopy ou de copie à distance."

#: paxes_cinder/volume/manager.py:239
#, python-format
msgid "%(error_prefix)s failure for volume {volume_id}: %(error)s"
msgstr "Echec %(error_prefix)s pour le volume {id_volume} : %(error)s"

#: paxes_cinder/volume/manager.py:244
#, python-format
msgid ""
"%(error_prefix)s failure for volume {volume_id}.Command %(cmd)s, error "
"%(error)s"
msgstr ""
"Echec %(error_prefix)s pour le volume {id_volume}. Commande %(cmd)s, "
"erreur %(error)s"

#: paxes_cinder/volume/manager.py:393
#, python-format
msgid "Resuming deletion of volume %s"
msgstr "NV-E253654 Reprise de la suppression du volume %s"

#: paxes_cinder/volume/manager.py:396
#, python-format
msgid ""
"Failed to delete volume %(volid)s during volume service startup. Error: "
"%(error)s"
msgstr ""
"NV-CCA27AC Echec de la suppression du volume %(volid)s au cours du "
"démarrage du service de volume. Erreur : %(error)s"

#: paxes_cinder/volume/manager.py:410
#, python-format
msgid "Processing volume that was left in the attaching state. Volume id: %(id)s"
msgstr ""
"NV-89FC9B0 Traitement du volume qui est resté à l'état Connecté. ID "
"volume : %(id)s"

#: paxes_cinder/volume/manager.py:483
#, python-format
msgid ""
"_volume_attach_rollback: Volume %(id)s is missing restricted metadata to "
"recover the attaching state."
msgstr ""
"NV-C8F1D06 _volume_attach_rollback : Le volume %(id)s ne contient pas les"
" données restreintes pour récupérer l'état Connexion."

#: paxes_cinder/volume/manager.py:487
#, python-format
msgid ""
"_volume_attach_rollback: No attach operation  to rollback for volume "
"%(id)s"
msgstr ""
"NV-77AEEA1 _volume_attach_rollback : Pas d'opération de connexion à "
"annuler pour le volume %(id)s"

#: paxes_cinder/volume/manager.py:493
#, python-format
msgid ""
"_volume_attach_rollback: Invalid connector %(conn)s in volume %(id)s "
"restrict metadata. Rollback without termination"
msgstr ""
"NV-4096184 _volume_attach_rollback : Connecteur non valide %(conn)s dans "
"le volume %(id)s - restriction des métadonnées. Annulation sans arrêt"

#: paxes_cinder/volume/manager.py:498
#, python-format
msgid "_volume_attach_rollback: Roll back attaching state for volume %(id)s."
msgstr ""
"NV-1EB0444 _volume_attach_rollback : Annulation de l'état de connexion "
"pour le volume %(id)s."

#: paxes_cinder/volume/manager.py:518
#, python-format
msgid ""
"_volume_attach_rollback: Finished. Volume %(id)s has rolled back to "
"available state."
msgstr ""
"NV-1E08B26 _volume_attach_rollback : Terminé. Le volume %(id)s a été "
"annulé à l'état Disponible."

#: paxes_cinder/volume/manager.py:600
#, python-format
msgid ""
"The volume detach didn't finish successfully before cinder service was "
"restarted. volume id: %(id)s"
msgstr ""
"NV-333B81A La déconnexion du volume n'a pas abouti avant que l'unité de "
"service cinder ait redémarré. id volume : %(id)s"

#: paxes_cinder/volume/manager.py:633
msgid "Unable to initialize host, driver is uninitialized"
msgstr "NV-7F33CBC Impossible d'initialiser l'hôte, le pilote n'est pas initialisé"

#: paxes_cinder/volume/manager.py:650
msgid "update default quota class..."
msgstr "NV-392B903 mise à jour de la classe de quota par défaut..."

#: paxes_cinder/volume/manager.py:652
msgid "Post init_host processing and update volume status."
msgstr ""
"NV-6EC3032 Post traitement de init_host et mise à jour du statut du "
"volume."

#: paxes_cinder/volume/manager.py:656
#, python-format
msgid "Error happened during post init_host volume processing. Error: %s"
msgstr ""
"NV-B263BC8 Une erreur s'est produite au cours de l'opération init_host "
"suivante de traitement du volume. Erreur : %s"

#: paxes_cinder/volume/manager.py:660
#, python-format
msgid "Rollback volume still attaching during init_host: %d volumes"
msgstr ""
"NV-BDEAFA8 Annulation du volume en cours de connexion au cours de "
"init_host : %d volumes"

#: paxes_cinder/volume/manager.py:665
#, python-format
msgid "Resume volume deletion during init_host: %d volumes"
msgstr ""
"NV-6BC64FF Reprise de la suppression du volume au cours de init_host : %d"
" volumes"

#: paxes_cinder/volume/manager.py:719
msgid "Caught Exception Refreshing Driver Status "
msgstr "Exception interceptée lors de l'actualisation du statut du pilote "

#: paxes_cinder/volume/manager.py:755
msgid "Caught Exception trying to update Storage Node in DB"
msgstr ""
"NV-36093B5 Exception interceptée lors de la tentative de mise à jour du "
"noeud de stockage dans la BD"

#: paxes_cinder/volume/manager.py:793
msgid "Unable to retrieve Default Volume Type"
msgstr "NV-544BC4C Impossible d'extraire le type de volume par défaut"

#: paxes_cinder/volume/manager.py:850
#, python-format
msgid "volume %s: removing export"
msgstr "NV-BAF02FC volume %s : suppression de l'exportation"

#: paxes_cinder/volume/manager.py:852
#, python-format
msgid "volume %s: deleting"
msgstr "NV-4F406DE volume %s : suppression en cours"

#: paxes_cinder/volume/manager.py:855
#, python-format
msgid "volume %s: volume is busy"
msgstr "NV-3431BA6 volume %s : le volume est occupé"

#: paxes_cinder/volume/manager.py:858
#, python-format
msgid "Fail to remove_export or delete_volume: %sname"
msgstr ""
"NV-E98201D Impossible d'effectuer l'opération remove_export ou "
"delete_volume : %sname"

#: paxes_cinder/volume/manager.py:862
#, python-format
msgid "Volume %s: deletion failed with exception "
msgstr "NV-137591B Volume %s : échec de la suppression avec l'exception "

#: paxes_cinder/volume/manager.py:954
#, python-format
msgid ""
"failed checking whether                              volume %(vol_id)s "
"backs an image, metadata=%(mdata)s"
msgstr ""
"NV-BE4D3EE échec de la vérification si le volume %(vol_id)s supporte une "
"image, métadonnées=%(mdata)s"

#: paxes_cinder/volume/manager.py:991
#, python-format
msgid ""
"volume %(volid)s has unfinished attach transaction. Rolling back before "
"deleting the volume."
msgstr ""
"NV-331CBBA le volume %(volid)s a terminé la transaction de connexion. "
"Annulation avant la suppression du volume."

#: paxes_cinder/volume/manager.py:1035
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to extend volume by %(s_size)sG, "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""
"NV-521C07E Dépassement du quota pour %(s_pid)s, tentative d'extension du "
"volume de %(s_size)sGo, (%(d_consumed)dGo de %(d_quota)dGo déjà "
"consommés)"

#: paxes_cinder/volume/manager.py:1091
#, python-format
msgid ""
"The host %(hostid)s for boot volume %(volid)s  does not support extend "
"volume."
msgstr ""
"NV-37CDE0F L'hôte %(hostid)s pour le volume d'amorçage %(volid)s ne prend"
" pas en charge l'extension de volume."

#: paxes_cinder/volume/manager.py:1145
#, python-format
msgid "Start attach transaction for volume %(id)s."
msgstr ""
"NV-1CBB13C Démarrage de la connexion de la transaction pour le volume "
"%(id)s."

#: paxes_cinder/volume/manager.py:1175
#, python-format
msgid "Driver returned %s"
msgstr "NV-B695526 Le pilote a renvoyé %s"

#: paxes_cinder/volume/manager.py:1208
#, python-format
msgid "Successfully attached the volume %(id)s. Clean up transaction."
msgstr ""
"NV-F606087 La connexion du volume %(id)s a abouti. Nettoyage de la "
"transaction."

#: paxes_cinder/volume/drivers/paxes_san.py:162
#, python-format
msgid "Waiting %(seconds)d seconds before next attempt..."
msgstr ""
"NV-0553DA5 Délai d'attente de %(seconds)d secondes avant la tentative "
"suivante..."

#: paxes_cinder/volume/drivers/paxes_san.py:182
#, python-format
msgid "Error running SSH command: %s"
msgstr "NV-052C0AB Erreur lors de l'exécution de la commande SSH : %s"

#: paxes_cinder/volume/drivers/emc/emc_common_product.py:35
msgid "Updating volume status"
msgstr "NV-A56DF8D Mise à jour de l'état du volume"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:89
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1374
msgid "protocol must be specified as '<in> iSCSI' or '<in> FC'"
msgstr "le protocole doit être spécifié comme '<in> iSCSI' ou '<in> FC'"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:123
msgid "Entering create_volume."
msgstr "NV-4C5AEEB Saisie de create_volume."

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:127
#, python-format
msgid "Create Volume: %(volume)s  Size: %(size)lu"
msgstr "NV-403E8FC Création du volume : %(volume)s  Taille : %(size)lu"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:157
#, python-format
msgid ""
"Unsupported element_type value %(element_type)s.  Specify a supported "
"element_type value and resubmit the request."
msgstr ""
"NV-AC11F99 Valeur element_type %(element_type)s non prise en charge.  "
"Spécifiez une valeur element_type prise en charge et soumettez à nouveau "
"la demande."

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:164
#, python-format
msgid "Create Volume: %(volume)s  Storage type: %(storage_type)s"
msgstr ""
"NV-4E4E2BB Création du volume : %(volume)s Type de stockage : "
"%(storage_type)s"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:171
#, python-format
msgid ""
"Create Volume: %(volume)s  Pool: %(pool)s,  Element Type: "
"%(element_type)s, Storage System: %(storage_system)s"
msgstr ""
"NV-723484A Création du volume : %(volume)s  Pool : %(pool)s,  Type "
"d'élément : %(element_type)s, Système de stockage : %(storage_system)s"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:182
#, python-format
msgid ""
"Error Create Volume: %(volumename)s. Storage Configuration Service not "
"found for pool %(storage_type)s."
msgstr ""
"NV-0EFA73A Erreur de création du volume : %(volumename)s. Service de "
"configuration du stockage introuvable pour le pool %(storage_type)s."

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:190
#, python-format
msgid ""
"Create Volume: %(name)s  Method: CreateOrModifyElementFromStoragePool  "
"ConfigServicie: %(service)s  ElementName: %(name)s  InPool: %(pool)s  "
"ElementType: %(element_type)s  Size: %(size)lu"
msgstr ""
"NV-6E312B4 Création du volume : %(name)s  Méthode : "
"CreateOrModifyElementFromStoragePool  ConfigServicie : %(service)s  "
"ElementName : %(name)s  InPool : %(pool)s  ElementType : %(element_type)s"
"  Taille : %(size)lu"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:206
#, python-format
msgid "Create Volume: %(volumename)s  Return code: %(rc)lu"
msgstr "NV-0214C49 Création du volume : %(volumename)s Code retour : %(rc)lu"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:213
#, python-format
msgid ""
"Error Create Volume: %(volumename)s.  Return code: %(rc)lu.  Error: "
"%(error)s"
msgstr ""
"NV-227D3AC Erreur de création du volume : %(volumename)s.  Code retour : "
"%(rc)lu.  Erreur : %(error)s"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:220
#, python-format
msgid "Leaving create_volume: %(volumename)s  Return code: %(rc)lu"
msgstr ""
"NV-C5C5CCC Conservation de create_volume : %(volumename)s Code retour : "
"%(rc)lu"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:235
#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:259
msgid "Could not establish ecom connection"
msgstr "NV-930992B Impossible d'établir la connexion ecom"

#: paxes_cinder/volume/drivers/ssp/ssp.py:177
#, python-format
msgid "ssp:  no matching HMC was found in the DB for host: >%s<"
msgstr ""
"NV-BFBE123 ssp : aucune console HMC correspondante détectée dans la base "
"de données pour l'hôte : >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:248
#, python-format
msgid "ssp: during create default volume type, DB error: >%s<"
msgstr ""
"NV-FA1BBE8 ssp : lors de la création du type de volume par défaut, erreur"
" de base de données : >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:279
#, python-format
msgid ""
"ssp: during _create_lu for LU: (name: >%(name)s<, size: >%(size)s<, thin:"
" >%(thin)s<), ssp_udid: >%(ssp_udid)s< is not same as extra_spec "
"shared_storage_pool: >%(extra_spec_ssp_id)s<"
msgstr ""
"ssp : au cours du travail _create_lu pour l'unité logique : (nom : "
">%(name)s<, taille : >%(size)s<, thin : >%(thin)s<), ssp_udid : "
">%(ssp_udid)s< différent de extra_spec shared_storage_pool : "
">%(extra_spec_ssp_id)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:299
#, python-format
msgid ""
"ssp: failed during _create_lu for LU: (name: >%(name)s<, size: "
">%(size)s<, thin: >%(thin)s<), message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : échec during _create_lu pour unité logique : (nom : >%(name)s<, "
"taille : >%(size)s<, fin : >%(thin)s<), message : >%(e)s<, k2xa : "
">%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:329
#, python-format
msgid ""
"ssp: during _create_lu job for LU: (name: >%(name)s<, size: >%(size)s<, "
"thin: >%(thin)s<), ssp_udid: >%(ssp_udid)s< is not same as extra_spec "
"shared_storage_pool: >%(extra_spec_ssp_id)s<"
msgstr ""
"ssp : au cours du travail _create_lu pour l'unité logique : (nom : "
">%(name)s<, taille : >%(size)s<, thin : >%(thin)s<), ssp_udid : "
">%(ssp_udid)s< est défini de extra_spec shared_storage_pool : "
">%(extra_spec_ssp_id)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:351
#, python-format
msgid ""
"ssp: failure during _create_lu, create parameters: name: >%(name)s<, "
"size: >%(size)s<, thin: >%(thin)s<, logicalunittype: "
">%(logicalunittype)s<, message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : échec au cours de _create_lu, paramètres de création : nom : "
">%(name)s<, taille : >%(size)s<, thin : >%(thin)s<, logicalunittype : "
">%(logicalunittype)s<, message: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:366
#, python-format
msgid ""
"ssp: failure during _create_lu job, expecting COMPLETED_OK, but for "
"job_id: >%(job_id)s< got status: >%(status)s< create parameters: name: "
">%(name)s<, size: >%(size)s<, thin: >%(thin)s<, logicalunittype: "
">%(logicalunittype)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-76A9409 ssp : échec au cours du travail _create_lu, COMPLETED_OK "
"attendu, mais pour job_id : >%(job_id)s< obtention du statut : "
">%(status)s< paramètres de création : nom : >%(name)s<, taille : "
">%(size)s<, thin : >%(thin)s<, logicalunittype : >%(logicalunittype)s<, "
"k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:382
#, python-format
msgid ""
"ssp: create complete, job_id: >%(job_id)s<, name: >%(name)s<, size: "
">%(size)s<, thin: >%(thin)s<, logicalunittype: >%(logicalunittype)s<, "
"k2xa: >%(k2xa)s<"
msgstr ""
"NV-9FEEE64 ssp : création terminée, job_id : >%(job_id)s<, nom : "
">%(name)s<, taille : >%(size)s<, fin : >%(thin)s<, typeLU : "
">%(logicalunittype)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:416
#, python-format
msgid ""
"ssp: failed during _delete_lu of LU w/ with unique_device_id: "
">%(lu_udid)s<,  message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : échec au cours de _delete_lu de l'unité logique avec "
"unique_device_id : >%(lu_udid)s<,  message : >%(e)s<, >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:431
#, python-format
msgid ""
"ssp: during _clone_lu_by_name, couldnt find lu with src_lu_name: "
">%(src_lu_name)s<, tgt_lu_name: >%(tgt_lu_name)s<"
msgstr ""
"ssp : au cours de _clone_lu_by_name, impossible de trouver l'unité "
"logique avec src_lu_name : >%(src_lu_name)s<, tgt_lu_name : "
">%(tgt_lu_name)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:439
#, python-format
msgid ""
"ssp: during _clone_lu_by_name, found too many lus with src_lu_name: "
">%(src_lu_name)s<, tgt_lu_name: >%(tgt_lu_name)s<"
msgstr ""
"NV-8FDE368 ssp : au cours de _clone_lu_by_name, un trop grand nombre "
"d'unités logiques ont été trouvées avec src_lu_name : >%(src_lu_name)s<, "
"tgt_lu_name : >%(tgt_lu_name)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:469
#, python-format
msgid ""
"ssp: failure during _clone_lu_bj, clone parameters: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s< msg: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : échec au cours de _clone_lu_bj, paramètres de clonage : src_lu_udid"
" : >%(src_lu_udid)s<, tgt_lu_name : >%(tgt_lu_name)s< tgt_lu_size : "
">%(tgt_lu_size)s< msg : >%(e)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:485
#: paxes_cinder/volume/drivers/ssp/ssp.py:547
#, python-format
msgid ""
"ssp: apparent failure during _clone_lu_bj, expecting COMPLETED_OK, but "
"for job_id: >%(job_id)s< got status: >%(status)s< clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-64234D9 ssp : échec apparent au cours de _clone_lu_bj, COMPLETED_OK "
"attendu, mais pour job_id : >%(job_id)s< statut obtenu : >%(status)s< "
"paramètres de clonage : src_lu_udid : >%(src_lu_udid)s<, tgt_lu_name : "
">%(tgt_lu_name)s< tgt_lu_size : >%(tgt_lu_size)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:509
#, python-format
msgid ""
"ssp: failure during _clone_lu_bj, during create, clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s< message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : échec au cours de _clone_lu_bj, lors de la création, paramètres de "
"clonage : src_lu_udid : >%(src_lu_udid)s<, tgt_lu_name : "
">%(tgt_lu_name)s< tgt_lu_size : >%(tgt_lu_size)s< message : >%(e)s<, k2xa"
" : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:530
#, python-format
msgid ""
"ssp: failure during _clone_lu_bj, during clone, clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s< message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : échec au cours de _clone_lu_bj, lors du clonage, paramètres de "
"clonage : src_lu_udid : >%(src_lu_udid)s<, tgt_lu_name : "
">%(tgt_lu_name)s< tgt_lu_size : >%(tgt_lu_size)s< message : >%(e)s<, k2xa"
" : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:576
#, python-format
msgid ""
"ssp: failure during _clone_lu_bp, clone parameters: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s< message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : échec au cours de _clone_lu_bp, paramètres de clonage : src_lu_udid"
" : >%(src_lu_udid)s<, tgt_lu_name : >%(tgt_lu_name)s< tgt_lu_size : "
">%(tgt_lu_size)s< message : >%(e)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:591
#, python-format
msgid ""
"ssp: apparent failure during _clone_lu_bp, expecting COMPLETED_OK, but "
"for job_id: >%(job_id)s< got status: >%(status)s< clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-21DAFDD ssp : échec apparent au cours de _clone_lu_bp, COMPLETED_OK "
"attendu, mais pour job_id : >%(job_id)s< statut obtenu : >%(status)s< "
"paramètres de clonage : src_lu_udid : >%(src_lu_udid)s<, tgt_lu_name : "
">%(tgt_lu_name)s< tgt_lu_size : >%(tgt_lu_size)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:606
#, python-format
msgid ""
"ssp: clone complete, job_id: >%(job_id)s<, src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-330DF39 ssp : clonage terminé, job_id : >%(job_id)s<, src_lu_udid : "
">%(src_lu_udid)s<, tgt_lu_name : >%(tgt_lu_name)s< tgt_lu_size : "
">%(tgt_lu_size)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:625
msgid "ssp: driver not yet initialized"
msgstr "NV-767C35B ssp : pilote pas encore initialisé"

#: paxes_cinder/volume/drivers/ssp/ssp.py:634
#, python-format
msgid ""
"K2 GET SharedStoragePool time: >%(delta)f< is bigger or equal to "
"update_stats periodic interval: >%(periodic_interval)d<"
msgstr ""
"NV-BB646A1 La durée d'obtention par K2 du pool de stockage partagé : "
">%(delta)f< est supérieur ou égal à l'intervalle périodique update_stats "
": >%(periodic_interval)d<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:641
#, python-format
msgid ""
"ssp: during get_volume_stats, failed to refresh shared storage pool with "
"ssp_id: >%(self._ssp.id)s<, message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : au cours de get_volume_stats, echec de régénération du pool de "
"stockage partagé avec ssp_id : >%(self._ssp.id)s<, message : >%(e)s<, "
"k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:680
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, while performing vios cluster check, "
"failed to refresh cluster id: >%(self._cluster.id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-AC40CF2 ssp : au cours de %(duringwhatstage)s, lors de l'exécution de "
"la vérification de cluster vios, echec de régénération ID cluster : "
">%(self._cluster.id)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:707
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, for vios id: >%(vios.id)s<, "
"OperatingSystemVersion: >%(os_version)s<"
msgstr ""
"ssp : au cours de %(duringwhatstage)s, pour ID vios : >%(vios.id)s<, "
"OperatingSystemVersion : >%(os_version)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:719
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, vios id: >%(vios.id)s<, running and "
"active"
msgstr ""
"ssp : au cours de %(duringwhatstage)s, id vios : >%(vios.id)s<, exécution"
" et actif"

#: paxes_cinder/volume/drivers/ssp/ssp.py:727
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, for cluster id: >%(self._cluster.id)s<, "
"vios state issue, vios id: >%(vios.id)s<: PartitionState: "
">%(vios.partition_state)s< ResourceMonitoringControlState: "
">%(vios.rmc_state)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : au cours de %(duringwhatstage)s, pour ID cluster : "
">%(self._cluster.id)s<, problème d'état vios, id vios : >%(vios.id)s<: "
"PartitionState : >%(vios.partition_state)s< "
"ResourceMonitoringControlState : >%(vios.rmc_state)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:751
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, could not find restricted metadata for "
"volume id: >%(volume_id)s<"
msgstr ""
"ssp : au cours de %(duringwhatstage)s, impossible de trouver les "
"métadonnées restreintes pour id volume : >%(volume_id)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:767
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, failed to refresh shared storage pool "
"with ssp_id: >%(self._ssp.id)s<, message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : au cours de %(duringwhatstage)s, echec de régénération du pool de "
"stockage partagé avec ssp_id : >%(self._ssp.id)s<, message : >%(e)s<, "
"k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:780
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, couldnt find lu for volume_id: "
">%(volume_id)s< with: unique_device_id: >%(lu_udid)s< and unit_name: "
">%(lu_name)s<"
msgstr ""
"ssp : au cours de %(duringwhatstage)s, impossible de trouver l'unité "
"logique pour volume_id : >%(volume_id)s< avec : unique_device_id : "
">%(lu_udid)s< et unit_name : >%(lu_name)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:791
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, found too many lus for volume_id: "
">%(volume_id)s< with: unique_device_id: >%(lu_udid)s< and unit_name: "
">%(lu_name)s<"
msgstr ""
"NV-338EFD0 ssp : au cours de %(duringwhatstage)s, trop d'unités logiques "
"détectées pour volume_id : >%(volume_id)s< avec : unique_device_id : "
">%(lu_udid)s< et unit_name : >%(lu_name)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:805
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:342
msgid "enter: do_setup"
msgstr "NV-9097266 entrer : do_setup"

#: paxes_cinder/volume/drivers/ssp/ssp.py:825
msgid "ssp: failure during do_setup, cant find hmc."
msgstr "NV-AE8B2E2 ssp : échec au cours de do_setup, hmc introuvable."

#: paxes_cinder/volume/drivers/ssp/ssp.py:853
#, python-format
msgid ""
"ssp: during do_setup, failed to obtain k2client, k2_url: >%(k2_url)s<, "
"k2_username: >%(k2_username)s<"
msgstr ""
"ssp : au cours de do_setup, échec de l'obtention de k2client, k2_url : "
">%(k2_url)s<, k2_username : >%(k2_username)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:866
#, python-format
msgid ""
"ssp: during do_setup, using hmc_uuid: >%(hmc_uuid)s<, failed to retrieve "
"managementconsole, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : au cours de do_setup, utilisation de hmc_uuid : >%(hmc_uuid)s<, "
"échec d'extraction de managementconsole, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:875
#, python-format
msgid "ssp: during do_setup, hmc version: >%s<"
msgstr "NV-3F31730 ssp : au cours de do_setup, version hmc : >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:885
#, python-format
msgid ""
"ssp: during do_setup, using k2_url: >%(k2_url)s<, failed to retrieve "
"cluster, cluster_id: >%(cluster_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : au cours de do_setup, utilisation de k2_url : >%(k2_url)s<, échec "
"de l'extension de la grappe, cluster_id :>%(cluster_id)s<, k2xa : "
">%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:904
#, python-format
msgid ""
"ssp: during do_setup, using k2_url: >%(k2_url)s< and cluster_id: "
">%(cluster_id)s< failed to retrieve shared storage pool with ssp_ip: "
">%(ssp_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : au cours de do_setup, utilisation de k2_url : >%(k2_url)s< et "
"cluster_id : >%(cluster_id)s< échec de l'extraction du pool de stockage "
"partagé avec ssp_ip : >%(ssp_id)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:923
#, python-format
msgid "ssp: during do_setup, creating default volume type: >%s<"
msgstr ""
"NV-379E7B0 ssp : au cours de do_setup, création du type de volume par "
"défaut : >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:928
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:487
msgid "leave: do_setup"
msgstr "NV-F492AE8 conserver : do_setup"

#: paxes_cinder/volume/drivers/ssp/ssp.py:931
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:580
msgid "leave: check_for_setup_error"
msgstr "NV-1C79D46 conserver : check_for_setup_error"

#: paxes_cinder/volume/drivers/ssp/ssp.py:981
#: paxes_cinder/volume/drivers/ssp/ssp.py:1009
#: paxes_cinder/volume/drivers/ssp/ssp.py:1050
#: paxes_cinder/volume/drivers/ssp/ssp.py:1149
#: paxes_cinder/volume/drivers/ssp/ssp_product.py:48
#: paxes_cinder/volume/drivers/ssp/ssp_product.py:73
#: paxes_cinder/volume/drivers/ssp/ssp_product.py:145
#, python-format
msgid "ssp: exception: >%s<"
msgstr "NV-31FED69 ssp : exception : >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:982
msgid "ssp: failed during create_volume"
msgstr "NV-E4EE3DB ssp : échec au cours de create_volume"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1010
#, python-format
msgid ""
"ssp: failed during delete_volume, lu_udid: >%(lu_udid)s< lu_name: "
">%(lu_name)s< volume id: >%(volume_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-41060EC ssp : échec au cours de delete_volume, lu_udid : >%(lu_udid)s<"
" lu_name : >%(lu_name)s< volume id : >%(volume_id)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1029
#, python-format
msgid "ssp: during create_snapshot, cant find volume_id: >%s<"
msgstr "NV-FDA9D85 ssp : au cours de create_snapshot, volume_id introuvable : >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1051
#, python-format
msgid ""
"ssp: failure during create_snapshot: lu_udid: >%(src_lu_udid)s< lu_name: "
">%(src_lu_name)s< volume id: >%(source_vol_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-ACF24A1 ssp : échec au cours de create_snapshot : lu_udid : "
">%(src_lu_udid)s< lu_name : >%(src_lu_name)s< volume id : "
">%(source_vol_id)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1070
#, python-format
msgid "ssp: during delete_snapshot, couldnt find lu with unit_name: >%s<"
msgstr ""
"NV-FCB5EA8 ssp : au cours de delete_snapshot, impossible de trouver "
"l'unité logique avec unit_name : >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1077
#, python-format
msgid "ssp: during delete_snapshot, found too many lus with unit_name: >%s<"
msgstr ""
"NV-66B083E ssp : au cours de delete_snapshot, trop d'unités logiques "
"détectées avec unit_name : >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1105
#, python-format
msgid ""
"ssp: error during create_volume_from_snapshot: snapshot with name: "
">%(snapshot_name)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-F6CFF00 ssp : erreur au cours de create_volume_from_snapshot : "
"instantané avec le nom : >%(snapshot_name)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1150
#, python-format
msgid ""
"ssp:  error during create_cloned_volume: src_lu_udid: >%(src_lu_udid)s< "
"src_lu_name: >%(src_lu_name)s< volume id: >%(src_volume_id)s<, k2xa: "
">%(k2xa)s<"
msgstr ""
"NV-24854A9 ssp :  erreur au cours de create_cloned_volume : src_lu_udid :"
" >%(src_lu_udid)s< src_lu_name : >%(src_lu_name)s< id volume : "
">%(src_volume_id)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1211
#, python-format
msgid "stats = %(stats)s"
msgstr "NV-898A2AA stats = %(stats)s"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:49
#, python-format
msgid ""
"ssp: while discovering mapped LUs, failed to refresh cluster with "
"cluster_id: >%(self._cluster.id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-347194B ssp : lors de la reconnaissance des unités logiques mappées, "
"echec de régénération du cluster avec cluster_id : "
">%(self._cluster.id)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:59
#, python-format
msgid "Node >%s< has no virtual_io_server. Skipping."
msgstr ""
"NV-C3FDDFD Le noeud >%s< ne comporte aucun virtual_io_server. Il est "
"ignoré."

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:74
#, python-format
msgid ""
"ssp: while discovering mapped LUs, in cluster with cluster_id: "
">%(self._cluster.id)s< failed to retrieve vios with managedsystem_id: "
">%(ms_id)s< and virtualioserver_id: >%(vios_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-F12DD40 ssp : lors de la reconnaissance des unités logiques mappées, "
"dans le cluster avec cluster_id : >%(self._cluster.id)s< impossible "
"d'extraire les vios avec managedsystem_id : >%(ms_id)s< et "
"virtualioserver_id : >%(vios_id)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:115
msgid ""
"No volume statistics available, either driver has not been initialized or"
" there is a problem w/ the driver, check cinder logs."
msgstr ""
"NV-A8A5D70 Aucune statistiques sur les volumes disponible, le pilote n'a "
"pas été initialisé ou il y a un problème avec le pilote, consultez les "
"journaux cinder."

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:146
#, python-format
msgid ""
"ssp: while discovering volumes, failed to refresh shared storage pool "
"with ssp_id: >%(self._ssp.id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-7BF09DB ssp : lors de la reconnaissance des volumes, échec de "
"régénération du pool de stockage partagé avec ssp_id : "
">%(self._ssp.id)s<, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:173
msgid ""
"This volume is not a candidate for management because it is already "
"attached to a virtual machine.  To manage this volume with PowerVC, you "
"must bring the virtual machine under management.  Select to manage the "
"virtual machine that has the volume attached.  The attached volume will "
"be automatically included for management."
msgstr ""
"Ce volume n'est pas un candidat pour la gestion car il est déjà connecté "
"à une machine virtuelle. Pour gérer ce volume avec PowerVC, vous devez "
"mettre la machine virtuelle sous gestion. Sélectionnez pour gestion la "
"machine virtuelle à laquelle est connectée le volume. Celui-ci sera "
"automatiquement inclus pour la gestion."

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:184
#, python-format
msgid ""
"ssp: during Logical Unit discovery, ssp_id: >%(ssp_id)s<, "
"lu_unique_device_id: >%(lu_unique_device_id)s<, lu_unit_name: "
">%(lu_unit_name)s<, volume is in use and not available for management, "
"k2xa: >%(k2xa)s<"
msgstr ""
"ssp : au cours de la reconnaissance d'unité logique, ssp_id : "
">%(ssp_id)s<, lu_unique_device_id : >%(lu_unique_device_id)s<, "
"lu_unit_name : >%(lu_unit_name)s<, le volume est utilisé et n'est pas "
"disponible pour la gestion, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:200
msgid ""
"Because it is of type VirtualIO_Image, this volume is not a candidate for"
" management. Perhaps, while deleting a PowerVC image, someone chose not "
"to delete the backing storage? If you wish to work with the underlying "
"Shared Storage Pool Logical Unit please use the HMC or VIOS commands."
msgstr ""
"En raison de son type VirtualIO_Image, ce volume n'est pas candidat pour "
"la gestion. Il est possible que, lors de la suppression d'une image "
"PowerVC, une personne ait décidé de ne pas supprimer le stockage de "
"support. si vous souhaitez utiliser l'unité logique de pool de stockage "
"partagé sous-jacente, utilisez les commandes HMC ou VIOS."

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:210
#, python-format
msgid ""
"ssp: during Logical Unit discovery, ssp_id: >%(ssp_id)s<, "
"lu_unique_device_id: >%(lu_unique_device_id)s<, lu_unit_name: "
">%(lu_unit_name)s<, volume is of type VirtualIO_Image and not available  "
"for management, k2xa: >%(k2xa)s<"
msgstr ""
"ssp : au cours de la reconnaissance d'unité logique, ssp_id : "
">%(ssp_id)s<, lu_unique_device_id : >%(lu_unique_device_id)s<, "
"lu_unit_name : >%(lu_unit_name)s<, le volume est de type VirtualIO_Image "
"et n'est pas disponible pour la gestion, k2xa : >%(k2xa)s<"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:240
#, python-format
msgid "WWPN on node %(node)s: %(wwpn)s"
msgstr "NV-D154765 WWPN sur le noeud %(node)s : %(wwpn)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:299
#, python-format
msgid "Required keys %(required)s not found in vdisk dictionary %(dictionary)r"
msgstr ""
"Les clés requises %(required)s sont introuvables dans le dictionnaire "
"vdisk %(dictionary)r"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:349
msgid "do_setup: Could not get system name"
msgstr "NV-5732B20 do_setup : Impossible d'obtenir le nom du système"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:361
#, python-format
msgid "do_setup: Pool %s does not exist"
msgstr "NV-1B3A18D do_setup : le pool %s n'existe pas"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:412
#, python-format
msgid ""
"Expected integers for node_count and vdisk_count, svcinfo lsiogrp "
"returned: %(node)s and %(vdisk)s"
msgstr ""
"NV-D7E5D72 Entiers attendus pour node_count et vdisk_count, svcinfo "
"lsiogrp a renvoyé : %(node)s et %(vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:475
msgid "do_setup: No configured nodes"
msgstr "do_setup : aucun noeud configuré"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:484
#, python-format
msgid "Creating default volume type '%s'"
msgstr "NV-5FF13AA Création du type de volume par défaut '%s'"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:541
msgid "enter: check_for_setup_error"
msgstr "entrer : check_for_setup_error"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:545
msgid "Unable to determine system name"
msgstr "NV-82D9304 Impossible de déterminer le nom système"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:548
msgid "Unable to determine system id"
msgstr "NV-3C12EE7 Impossible de déterminer l'identificateur système"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:551
msgid "Unable to determine pool extent size"
msgstr "NV-D455E3E Impossible de déterminer la taille d'extension de pool"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:558
#, python-format
msgid "%s is not set"
msgstr "NV-6919A40 %s n'est pas défini"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:564
msgid ""
"Password or SSH private key is required for authentication: set either "
"san_password or san_private_key option"
msgstr ""
"NV-6FE00A0 Le mot de passe ou la clé privée SSH est requis(e) pour "
"l'authentification : définissez l'option san_password ou san_private_key"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:572
#, python-format
msgid ""
"Illegal value %d specified for storwize_svc_flashcopy_timeout: valid "
"values are between 0 and 600"
msgstr ""
"NV-F2E38D9 Valeur non admise %d spécifiée pour l'option "
"storwize_svc_flashcopy_timeout : les valeurs valides sont comprises entre"
" 0 et 600"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:594
#, python-format
msgid "ensure_export: Volume %(volume_id)s does not reference a vdisk"
msgstr ""
"NV-EF2904A ensure_export : Le volume %(volume_id)s ne fait pas référence "
"à un vdisk"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:601
#, python-format
msgid ""
"ensure_export: Volume %(volume_id)s references vdisk %(vdisk)s, which was"
" not found on storage"
msgstr ""
"NV-C3410C4 ensure_export : Le volume %(volume_id)s fait référence à vdisk"
" %(vdisk)s, qui n'a pas été trouvé dans le stockage"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:627
#, python-format
msgid "enter: _get_chap_secret_for_host: host name %s"
msgstr "entrer : _get_chap_secret_for_host : nom d'hôte %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:663
#, python-format
msgid ""
"leave: _get_chap_secret_for_host: host name %(host_name)s with secret "
"%(chap_secret)s"
msgstr ""
"conserver : _get_chap_secret_for_host : nom d'hôte %(host_name)s avec "
"valeur confidentielle %(chap_secret)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:686
msgid "_create_host: Cannot clean host name. Host name is not unicode or string"
msgstr ""
"NV-ED84213 _create_host : Impossible de nettoyer le nom d'hôte. Le nom "
"d'hôte n'est pas en Unicode ou n'est pas une chaîne"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:837
#, python-format
msgid "enter: _get_host_from_connector: prefix %s"
msgstr "entrer : _get_host_from_connector : préfixe %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:865
#, python-format
msgid ""
"Continue to fall back processing after initial failure to make a host on "
"the SAN controller: %s"
msgstr ""
"NV-41DBBAB Poursuivre le traitement après l'échec initial de création "
"d'un hôte sur le contrôleur SAN : %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:909
#, python-format
msgid "leave: _get_host_from_connector: host %s"
msgstr "conserver : _get_host_from_connector : hôte %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:921
#, python-format
msgid "enter: _create_host: host %s"
msgstr "entrer : _create_host : hôte %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:936
msgid "_create_host: No connector ports"
msgstr "_create_host : aucun port de connecteur"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:969
#, python-format
msgid "leave: _create_host: host %(host)s - %(host_name)s"
msgstr "conserver : _create_host : hôte %(host)s - %(host_name)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:992
#, python-format
msgid "enter: _map_vol_to_host: vdisk %(vdisk_id)s to host %(host_name)s"
msgstr "entrer : _map_vol_to_host : vdisk %(vdisk_id)s vers l'hôte %(host_name)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1022
msgid ""
"storwize_svc_multihostmap_enabled is set to False, Not allow multi host "
"mapping"
msgstr ""
"NV-ABB7D85 storwize_svc_multihostmap_enabled est défini sur False, Ne pas"
" autoriser le mappage multi-hôte"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1034
#, python-format
msgid "vdisk %s mapping to multi host"
msgstr "NV-45393AC mappage de vdisk %s vers multi-hôte"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1040
#, python-format
msgid ""
"leave: _map_vol_to_host: LUN %(result_lun)s, vdisk %(vdisk_id)s, host "
"%(host_name)s"
msgstr ""
"conserver : _map_vol_to_host : Numéro d'unité logique %(result_lun)s, "
"vdisk %(vdisk_id)s, hôte %(host_name)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1050
#, python-format
msgid "enter: _delete_host: host %s "
msgstr "entrer : _delete_host : hôte %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1058
#, python-format
msgid "leave: _delete_host: host %s "
msgstr "conserver : _delete_host : hôte %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1084
#, python-format
msgid ""
"The connector does not contain the required information: %(connector)s, "
"protocols %(protos)s"
msgstr ""
"NV-6A00D73 Le connecteur ne contient pas les informations requises : "
"%(connector)s, protocoles %(protos)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1105
#, python-format
msgid "Enter: initialize_connection: %s"
msgstr "NV-4DB79BA Entrer : initialize_connection : %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1128
#, python-format
msgid "Did not find expected column name in lsvdisk: %s"
msgstr "NV-5EFF8EA Nom de colonne attendu non trouvé dans lsvdisk : %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1130
#, python-format
msgid "initialize_connection: Missing volume attribute for vdisk %s"
msgstr ""
"NV-4FE8A8D initialize_connection : Attribut de volume manquant pour vdisk"
" %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1142
msgid "_create_host failed to return the host name."
msgstr "Echec de _create_host pour renvoyer le nom d'hôte."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1164
#, python-format
msgid ""
"initialize_connection: No node found in I/O group %(gid)s for vdisk "
"%(vdisk_id)s"
msgstr ""
"NV-8182517 initialize_connection : Aucun noeud trouvé dans le groupe "
"d'E-S %(gid)s pour vdisk %(vdisk_id)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1173
#, python-format
msgid "initialize_connection: Did not find a preferred node for vdisk %s"
msgstr ""
"NV-1DB16EC initialize_connection : Aucun noeud préféré n'a été trouvé "
"pour vdisk %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1195
msgid ""
"Could not get FC connection information for the host-volume connection. "
"Is the host configured properly for FC connections?"
msgstr ""
"NV-D8556EE Impossible d'obtenir les informations de connexion FC pour la "
"connexion multi-hôte. L'hôte est-il configuré correctement pour les "
"connexions FC ?"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1210
#, python-format
msgid ""
"initialize_connection: Failed to collect return properties for volume "
"%(vol)s and connector %(conn)s.\n"
msgstr ""
"NV-0A9D0F9 initialize_connection : Echec de collecte des propriétés de "
"renvoi pour le volume %(vol)s et le connecteur %(conn)s.\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1215
#, python-format
msgid ""
"leave: initialize_connection:\n"
" volume: %(vol)s\n"
" connector %(conn)s\n"
" properties: %(prop)s"
msgstr ""
"conserver : initialize_connection:\n"
" volume : %(vol)s\n"
" connecteur : %(conn)s\n"
" propriétés : %(prop)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1233
#, python-format
msgid "enter: terminate_connection: volume %(vol)s with connector %(conn)s"
msgstr "entrer : terminate_connection: volume %(vol)s avec connecteur %(conn)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1246
#, python-format
msgid ""
"terminate_connection: vdisk mismatch: %(err)s. Performing no operation on"
" the storage controller"
msgstr ""
"NV-78DEE4C terminate_connection : non concordance vdisk : %(err)s. "
"Exécution d'aucune opération sur le contrôleur de stockage"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1252
#, python-format
msgid ""
"terminate_connection: vdisk deleted: %(err)s. Performing no operation on "
"the storage controller"
msgstr ""
"NV-0E7CDF3 terminate_connection : vdisk supprimé : %(err)s. Aucune "
"opération n'est exécutée sur le contrôleur de stockage"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1265
#, python-format
msgid "Detach volume: failed to lookup host name for vdisk ID: %(vdisk)s"
msgstr ""
"NV-5D2DC5C Détacher le volume : échec de recherche de nom d'hôte pour "
"l'ID vdisk : %(vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1291
#, python-format
msgid ""
"There was an error when attempting to remove the host disk mappings for "
"volume ID %(vol)s and vdsik ID %(vdisk)s: %(err)s"
msgstr ""
"NV-07BAF93 Une erreur s'est produite lors de la tentative de retrait des "
"mappages de disque hôte pour l'ID volume %(vol)s et l'OD vdsik %(vdisk)s "
": %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1303
#, python-format
msgid ""
"terminate_connection: No mapping of vdisk %(vdisk_id)s to host "
"%(host_name)s found"
msgstr ""
"NV-0CD2F25 terminate_connection : Aucun mappage de vdisk %(vdisk_id)s à "
"l'hôte %(host_name)s n'a été trouvé"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1314
#, python-format
msgid "leave: terminate_connection: volume %(vol)s with connector %(conn)s"
msgstr "conserver : terminate_connection : volume %(vol)s avec connecteur %(conn)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1414
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:118
#, python-format
msgid "enter: _create_vdisk: candidate names %s "
msgstr "NV-2D6FE98 entrer : _create_vdisk : noms candidats %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1470
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:218
#, python-format
msgid ""
"_create_vdisk %(name)s - did not find success message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"_create_vdisk %(name)s - aucun message de réussite trouvé dans la sortie "
"CLI.\n"
" stdout : %(out)s\n"
" stderr : %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1477
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:225
#, python-format
msgid "leave: _create_vdisk: volume %(name)s ID %(id)s "
msgstr "NV-3A4E903 conserver : _create_vdisk : volume %(name)s ID %(id)s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1499
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1513
#, python-format
msgid ""
"create FC mapping from %(source)s to %(target)s - did not find success "
"message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"
msgstr ""
"créer mappage FC depuis %(source)s vers %(target)s - aucun message de "
"réussite trouvé dans la sortie CLI.\n"
" stdout : %(out)s\n"
" stderr : %(err)s\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1525
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1535
#, python-format
msgid ""
"create FC mapping from %(source)s to %(target)s - did not find mapping id"
" in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"
msgstr ""
"créer mappage FC depuis %(source)s vers %(target)s - aucun id de mappage "
"trouvé dans la sortie CLI.\n"
" stdout : %(out)s\n"
" stderr : %(err)s\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1550
#, python-format
msgid ""
"_prepare_fc_map: Failed to prepare FlashCopy from %(source)s to "
"%(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"NV-AD077CD _prepare_fc_map : Echec de préparation de FlashCopy depuis "
"%(source)s vers %(target)s.\n"
"stdout : %(out)s\n"
" stderr : %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1578
#, python-format
msgid ""
"Unexecpted mapping status %(status)s for mapping %(id)s. Attributes: "
"%(attr)s"
msgstr ""
"Statut de mappage %(status)s inattendu pour le mappage %(id)s. Attributs "
": %(attr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1590
#, python-format
msgid ""
"Mapping %(id)s prepare failed to complete within the allotted %(to)d "
"seconds timeout. Terminating."
msgstr ""
"NV-46B21B5 Echec d'achèvement de la préparation du mappage %(id)s dans le"
" délai alloué de %(to)d secondes. En cours de fermeture."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1595
#, python-format
msgid ""
"_prepare_fc_map: Failed to start FlashCopy from %(source)s to %(target)s "
"with exception %(ex)s"
msgstr ""
"NV-B48FD34 _prepare_fc_map : Echec de démarrage de FlashCopy depuis "
"%(source)s vers %(target)s avec l'exception %(ex)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1602
#, python-format
msgid "_prepare_fc_map: %s"
msgstr "NV-956CB6C _prepare_fc_map : %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1609
#, python-format
msgid ""
"_start_fc_map: Failed to start FlashCopy from %(source)s to %(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"NV-FCBE987 _start_fc_map : Echec de démarrage de FlashCopy depuis "
"%(source)s vers %(target)s.\n"
"stdout : %(out)s\n"
" stderr : %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1620
#, python-format
msgid ""
"enter: _run_flashcopy: execute FlashCopy from source %(source)s to target"
" %(target)s"
msgstr ""
"entrer : _run_flashcopy : exécution de FlashCopy depuis la source "
"%(source)s vers la cible %(target)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1633
#, python-format
msgid "leave: _run_flashcopy: FlashCopy started from %(source)s to %(target)s"
msgstr ""
"conserver : _run_flashcopy : FlashCopy démarré depuis %(source)s vers "
"%(target)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1642
#, python-format
msgid ""
"enter: _create_copy: snapshot with possible names %(names)s from vdisk "
"%(src_vdisk)s"
msgstr ""
"entrer : _create_copy : instantané avec noms possibles %(names)s à partir"
" de vdisk %(src_vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1650
#, python-format
msgid "_create_copy: Source vdisk %s does not exist"
msgstr "NV-8A48F71 _create_copy : Le vdisk source %s n'existe pas"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1662
#, python-format
msgid ""
"_create_copy: cannot get source vdisk %(src)s capacity from vdisk "
"attributes %(attr)s"
msgstr ""
"_create_copy : Impossible d'obtenir la capacité du Vdisk source %(src)s "
"depuis les attributs de Vdisk %(attr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1681
#, python-format
msgid "leave: _create_copy: snapshot vdisk %(tgt_vdisk)s from vdisk %(src_vdisk)s"
msgstr ""
"conserver : _create_copy : instantanée vdisk %(tgt_vdisk)s à partir de "
"vdisk %(src_vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1688
#, python-format
msgid "enter: _get_flashcopy_mapping_attributes: mapping %s"
msgstr "entrer : _get_flashcopy_mapping_attributes : mappage %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1711
#, python-format
msgid ""
"leave: _get_flashcopy_mapping_attributes: mapping %(fc_map_id)s, "
"attributes %(attributes)s"
msgstr ""
"conserver : _get_flashcopy_mapping_attributes : mappage %(fc_map_id)s, "
"attributs %(attributes)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1719
#, python-format
msgid "enter: _is_vdisk_defined: vdisk %s "
msgstr "entrer : _is_vdisk_defined : vdisk %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1721
#, python-format
msgid "leave: _is_vdisk_defined: vdisk %(vdisk)s with %(str)s "
msgstr "conserver : _is_vdisk_defined : vdisk %(vdisk)s avec %(str)s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1764
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1228
#, python-format
msgid "%(map_id)s [vdisk %(src)s to vdisk %(tgt)s]"
msgstr "%(map_id)s [vdisk %(src)s à vdisk %(tgt)s]"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1777
#, python-format
msgid ""
"To delete vdisk %(vdisk_id)s, increasing copyrate of flashcopy mapping "
"%(map)s from 0 to %(copyrate)s and waiting for completion."
msgstr ""
"NV-0B06E40 Pour supprimer vdisk %(vdisk_id)s, augmentation du débit de "
"copie du mappage flashcopy %(map)s à partir de 0 à %(copyrate)s et "
"attente de son achèvement."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1791
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1261
#, python-format
msgid "Vdisk %(id)s not involved in mapping %(src)s -> %(tgt)s"
msgstr "Le Vdisk %(id)s n'est pas impliqué dans le mappage %(src)s -> %(tgt)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1798
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1268
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, flashcopy mapping %(map)s with "
"status '%(status)s' was removed."
msgstr ""
"NV-4CA8ED6 Pour autoriser la suppression du vdisk %(vdisk_id)s, le "
"mappage flashcopy %(map)s avec le statut '%(status)s' a été supprimé."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1806
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1276
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, waiting for flashcopy mapping "
"%(map)s with status '%(status)s' to complete."
msgstr ""
"NV-E66FA4E Pour autoriser la suppression du vdisk %(vdisk_id)s, attente "
"que le mappage flashcopy %(map)s avec le statut '%(status)s' s'achève."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1816
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1286
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, forcing removal of flashcopy "
"mapping %(map)s with status '%(status)s'"
msgstr ""
"NV-824284E Pour autoriser la suppression du vdisk %(vdisk_id)s, "
"suppression forcée du mappage flashcopy %(map)s avec le statut "
"'%(status)s'"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1827
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1300
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, prepared flashcopy mapping "
"%(map)s was removed."
msgstr ""
"NV-211FA49 Pour autoriser la suppression du vdisk %(vdisk_id)s, le "
"mappage flashcopy préparé %(map)s a été supprimé."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1835
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1310
#, python-format
msgid ""
"To delete vdisk %(vdisk_id)s, flashcopy mapping %(map)s with status "
"'idle_or_copied' was removed."
msgstr ""
"NV-DA08F03 Pour supprimer le vdisk %(vdisk_id)s, le mappage flashcopy "
"%(map)s avec le statut 'idle_or_copied' a été supprimé."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1841
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1318
#, python-format
msgid ""
"To delete vdisk %(vdisk_id)s, waiting for completion of flashcopy mapping"
" %(map)s, which is currently %(progress)s%% complete and has status "
"'%(status)s'."
msgstr ""
"NV-CE3069A Pour supprimer le vdisk %(vdisk_id)s, attente de l'achèvement "
"du mappage flashcopy %(map)s, qui est actuellement terminé à "
"%(progress)s%% et est à l'état '%(status)s'."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1881
msgid ""
"Flashcopy mapping copy rate is 0. Copy is not in progress. Return to "
"caller."
msgstr ""
"NV-45B5480 Le débit de copie du mappage Flashcopy est 0. La copie n'est "
"pas en cours. Retour à l'appelant."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1944
#, python-format
msgid "enter: _delete_vdisk: vdisk %s"
msgstr "entrer : _delete_vdisk : vdisk %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1949
#, python-format
msgid "warning: Tried to delete vdisk %s but it does not exist."
msgstr ""
"NV-E47B663 avertissement : Tentative de suppression de vdisk %s mais il "
"n'existe pas."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1955
#, python-format
msgid "Removing vdisk %(vdisk_id)s"
msgstr "NV-E18AA05 Suppression de vdisk %(vdisk_id)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1968
#, python-format
msgid ""
"Hosts mapped to vdisk %(vdisk)s:\n"
"%(out)s"
msgstr ""
"NV-4159ED7 Hôtes mappés à vdisk %(vdisk)s:\n"
"%(out)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1974
#, python-format
msgid ""
"Existing FlashCopy mappings:\n"
"%(out)s"
msgstr ""
"NV-A345C87 Mappages FlashCopy existants :\n"
"%(out)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1982
#, python-format
msgid "leave: _delete_vdisk: vdisk %s"
msgstr "conserver : _delete_vdisk : vdisk %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1992
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2086
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2135
#, python-format
msgid "adding volume_type_id to volume=%s"
msgstr "NV-86F0410 ajout de volume_type_id à volume=%s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2014
#, python-format
msgid ""
"Starting deletion of volume %(volume_id)s.  There is no associated vdisk,"
" so no operation will be performed on the storage controller."
msgstr ""
"NV-04391FA Début de la suppression du volume %(volume_id)s.  Comme il "
"n'existe pas de vdisk associé, l'opération ne sera pas exécutée sur le "
"contrôleur de stockage."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2020
#, python-format
msgid "Starting deletion of volume %(volume_id)s, backed by vdisk %(vdisk_id)s"
msgstr ""
"NV-0C0C004 Début de la suppression du volume %(volume_id)s, supporté par "
"vdisk %(vdisk_id)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2032
#, python-format
msgid ""
"delete_volume: vdisk mismatch: %(err)s. Performing no operation on the "
"storage controller"
msgstr ""
"NV-D258084 delete_volume : non concordance de vdisk : %(err)s. Aucune "
"opération n'est exécutée sur le contrôleur de stockage"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2038
#, python-format
msgid ""
"delete_volume: vdisk deleted: %(err)s. Performing no operation on the "
"storage controller"
msgstr ""
"NV-FC2A0B0 delete_volume : vdisk supprimé : %(err)s. Aucune opération "
"n'est exécutée sur le contrôleur de stockage"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2075
msgid "create_volume_from_snapshot: Source and destination size differ."
msgstr ""
"NV-5A82296 create_volume_from_snapshot : La taille de la source et de la "
"destination diffère."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2096
#, python-format
msgid "create_volume_from_snapshot:  Source vdisk %s does not exist"
msgstr "NV-4729BC4 create_volume_from_snapshot :  Le vdisk source %s n'existe pas"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2123
msgid "create_cloned_volume: Source and destination size differ."
msgstr ""
"NV-4DD8AF7 create_cloned_volume : La taille de la source et de la "
"destination diffère."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2164
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1025
#, python-format
msgid "enter: extend_volume: volume %s"
msgstr "NV-826757D entrer : extend_volume : volume %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2174
msgid "extend_volume: Extending a volume with snapshots is not supported."
msgstr ""
"NV-E7C02C3 extend_volume : l'extension d'un volume avec des instantanés "
"n'est pas prise en charge."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2186
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1051
#, python-format
msgid "leave: extend_volume: volume %s"
msgstr "NV-0CDE488 quitter : extend_volume : volume %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2202
#, python-format
msgid "enter: migrate_volume: id=%(id)s, host=%(host)s"
msgstr "entrer : migrate_volume : id=%(id)s, hôte=%(host)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2234
msgid "migrate_volume started with more than one vdisk copy"
msgstr "migrate_volume démarré avec plusieurs copies vdisk"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2252
#, python-format
msgid ""
"migrate_volume %(name)s - did not find success message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"migrate_volume %(name)s - aucun message de réussite trouvé dans la sortie"
" CLI.\n"
" stdout : %(out)s\n"
" stderr : %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2264
msgid "migrate_volume: Could not get vdisk copy data"
msgstr ""
"NV-E8B0820 migrate_volume : impossible de récupérer les données de copie "
"vdisk"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2279
#, python-format
msgid "leave: migrate_volume: id=%(id)s, host=%(host)s"
msgstr "conserver : migrate_volume : id=%(id)s, host=%(host)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2301
msgid "Updating volume stats"
msgstr "Mise à jour des stats de volume"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2324
msgid "Could not get pool data from the storage"
msgstr "NV-675559D Impossible d'obtenir les données du pool depuis le stockage"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2325
msgid "_update_volume_stats: Could not get storage pool data"
msgstr ""
"NV-F6BB258 _update_volume_stats : Impossible d'obtenir les données du "
"pool de stockage"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2412
msgid ""
"Illegal value specified for storwize_svc_vol_rsize: set to either a "
"percentage (0-100) or -1"
msgstr ""
"NV-8977C50 Valeur non admise spécifiée pour storwize_svc_vol_rsize : "
"définir sur un pourcentage (0-100) ou sur -1"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2418
msgid ""
"Illegal value specified for storwize_svc_vol_warning: set to a percentage"
" (0-100)"
msgstr ""
"NV-80C1898 Valeur non admise spécifiée pour storwize_svc_vol_warning : "
"définir sur un pourcentage (0-100)"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2425
msgid ""
"Illegal value specified for storwize_svc_vol_grainsize: set to either 32,"
" 64, 128, or 256"
msgstr ""
"NV-8A90F92 Valeur non admise spécifiée pour storwize_svc_vol_grainsize : "
"définir sur 32, 64, 128 ou 256"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2432
msgid "System does not support compression"
msgstr "NV-90F35C9 Le système ne prend pas en charge la compression"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2437
msgid "If compression is set to True, rsize must also be set (not equal to -1)"
msgstr ""
"NV-102C98D Si la compression est définie sur True, rsize doit aussi être "
"défini sur (différent de -1)"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2443
#, python-format
msgid ""
"Illegal value %(prot)s specified for storwize_svc_connection_protocol: "
"valid values are %(enabled)s"
msgstr ""
"NV-5EBEB51 Valeur non admise %(prot)s spécifiée pour "
"storwize_svc_connection_protocol : les valeurs valides sont %(enabled)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2451
#, python-format
msgid "I/O group %(iogrp)d is not valid; available I/O groups are %(avail)s"
msgstr ""
"NV-9E31DDB Groupe d'E-S %(iogrp)d non valide ; les groupes d'E-S "
"disponibles sont %(avail)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2465
#, python-format
msgid "enter: _execute_command_and_parse_attributes:  command %s"
msgstr "entrer : _execute_command_and_parse_attributes : commande %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2477
#, python-format
msgid ""
"CLI Exception output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"NV-A3B1CA4 Sortie exception CLI :\n"
" commande : %(cmd)s\n"
" stdout : %(out)s\n"
" stderr : %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2494
#, python-format
msgid ""
"leave: _execute_command_and_parse_attributes:\n"
"command: %(cmd)s\n"
"attributes: %(attr)s"
msgstr ""
"conserver : _execute_command_and_parse_attributes :\n"
"commande : %(cmd)s\n"
"attributs : %(attr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2513
#, python-format
msgid ""
"_get_hdr_dic: attribute headers and values do not match.\n"
" Headers: %(header)s\n"
" Values: %(row)s"
msgstr ""
"_get_hdr_dic : les en-têtes et les valeurs d'attribut ne correspondent "
"pas.\n"
" En-têtes : %(header)s\n"
" Valeurs : %(row)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2521
#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
"stdout: %(out)s\n"
"stderr: %(err)s\n"
msgstr ""
"NV-39015B6 %(fun)s : Echec avec une sortie CLI inattendue.\n"
" Command : %(cmd)s\n"
"stdout : %(out)s\n"
"stderr : %(err)s\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2535
#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"%(fun)s : Echec avec une sortie CLI inattendue.\n"
" Command : %(cmd)s\n"
" stdout : %(out)s\n"
" stderr : %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2543
#, python-format
msgid "Did not find expected column in %(fun)s: %(hdr)s"
msgstr "NV-BEC3CF8 Colonne attendue non trouvée dans %(fun)s : %(hdr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:103
#, python-format
msgid ""
"StorwizeSVCProductDriver: start flashcopy mapping polling timer, polling "
"interval: %(intval)s seconds"
msgstr ""
"NV-796256C StorwizeSVCProductDriver : démarrage du temporisateur "
"d'interrogation du mappage flashcopy, intervalle d'interrogation : "
"%(intval)s secondes"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:328
#, python-format
msgid ""
"The volume %(name)s is in the error state and not a candidate for "
"management.  vdisk status: %(status)s  vdisk id: %(vdisk_id)s  vdisk uid:"
" %(vdisk_uid)s  "
msgstr ""
"Le volume %(name)s est à l'état d'erreur et n'est pas candidat pour la "
"gestion.  statut vdisk : %(status)s  id vdisk : %(vdisk_id)s  uid vdisk :"
" %(vdisk_uid)s  "

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:592
#, python-format
msgid ""
"The connector %(connector)s does not contain the required keys, which are"
" %(expected_fc_keys)s.or %(expected_iscsi_keys)s"
msgstr ""
"Le connecteur %(connector)s ne contient pas les clés requises qui sont "
"%(expected_fc_keys)s.ou %(expected_iscsi_keys)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:647
#, python-format
msgid "Incorporating WWPNS for Node %(node_id)s: %(wwpns)s"
msgstr "NV-365ED6F Incorporation des WWPNS du noeud %(node_id)s : %(wwpns)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:659
#, python-format
msgid ""
"Attachment for host '%(host)s' to %(storage)s for volume %(volume)s "
"expects zoning between initiator WWPNs %(initiators)s and target WWPNs "
"%(targets)s"
msgstr ""
"NV-0F22247 La connexion pour l'hôte '%(host)s' à %(storage)s pour le "
"volume %(volume)s attend la segmentation entre les WWPN du demandeur "
"%(initiators)s et les WWPN cible %(targets)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:721
#, python-format
msgid "Mapping initiator %(phy)s to node %(node)s"
msgstr "NV-5DC7B55 Mappage du demandeur %(phy)s au noeud %(node)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:766
#, python-format
msgid ""
"Fabric %(fabric)s does not have visibility to any WWPNs in node %(node)s,"
" part of iogrp %(iogrp)s of storage controller %(name)s. WWPNs visible on"
" the fabric are %(visible)s. WWPNs on the controller are %(available)s."
msgstr ""
"Le sous-ensemble de noeuds %(fabric)s n'a pas de visibilité sur les WWPN "
"du noeud %(node)s, qui font partie du iogrp %(iogrp)s du contrôleur de "
"stockage %(name)s. Les WWPN visibles dans l'ensemble de noeuds sont "
"%(visible)s. Les WWPN sur le contrôleur sont %(available)s."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:811
msgid "Zoning for single fabric, one initiator."
msgstr "NV-6E5D37F Segmentation pour un ensemble de noeuds unique, un demandeur."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:821
msgid "Zoning for single fabric, two initiators."
msgstr ""
"NV-2E0EF21 Segmentation pour un ensemble de noeuds unique, deux "
"demandeurs."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:835
#, python-format
msgid ""
"Zoning for single fabric, general case due to %(count)s initiators on "
"fabric."
msgstr ""
"NV-D9A5CD2 Segmentation pour un ensemble de noeuds unique, cas général dû"
" à %(count)s demandeurs dans l'ensemble de noeuds."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:845
msgid "Zoning for dual fabric, one initiator per fabric."
msgstr ""
"NV-EE35C79 Segmentation pour des ensembles de noeuds doubles, un "
"demandeur par ensemble de noeuds."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:864
msgid "Zoning for dual fabric, two initiators per fabric."
msgstr ""
"NV-C638EFA Segmentation pour des ensembles de noeuds doubles, deux "
"demandeurs par ensemble de noeuds."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:884
#, python-format
msgid ""
"Zoning for dual fabric, general case due to %(count1)s initiators on "
"first fabric and %(count2)s initiators on second fabric."
msgstr ""
"NV-4351BA7 Segmentation pour des ensembles de noeuds doubles, cas général"
" dû à %(count1)s demandeurs dans le premier ensemble de noeuds et "
"%(count2)s demandeurs dans le second."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:894
#, python-format
msgid "Zoning for general case due to %(count)s fabrics."
msgstr ""
"NV-0733A1E Segmentation pour le cas général dû à %(count)s ensembles de "
"noeuds."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:911
#, python-format
msgid "Creating zones: %r"
msgstr "NV-70BDC4D Création de zones : %r"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:923
#, python-format
msgid "Requested mapping for initiators  %(initiators)s and targets %(targets)s"
msgstr ""
"NV-35F3CC8 Mappage demandé pour les demandeurs  %(initiators)s et les "
"cibles %(targets)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:941
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:950
#, python-format
msgid "Returned mapping is %(mapping)s"
msgstr "NV-10E28B0 Le mappage renvoyé est %(mapping)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:976
#, python-format
msgid "Terminating connection with parameters %(connector)sconnector"
msgstr ""
"NV-4EFE246 Fermeture de la connexion avec les paramètres "
"%(connector)sconnector"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:986
#, python-format
msgid "Removing zones for initiators: %(initiator_list)s"
msgstr "NV-CC588B5 Suppression des zones pour les demandeurs : %(initiator_list)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:996
#, python-format
msgid ""
"There was a failure when the zone manager attempted to remove zones "
"created for WWPNs %(wwpns)s during detach of volume %(vol)s."
msgstr ""
"NV-AA064A4 Incident lorsque le gestionnaire de zones a tenté de supprimer"
" des zones créées pour les WWPN %(wwpns)s lors du détachement du volume "
"%(vol)s."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1083
#, python-format
msgid "SSH Pool: %d free, %d waiting, in-flight commands:"
msgstr ""
"NV-F9DD698 Pool SSH : %d disponibles, %d en attente, commandes à la volée"
" :"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1087
#, python-format
msgid " %(duration).2f %(commands)s"
msgstr "NV-98D8DC3  %(duration).2f %(commands)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1141
#, python-format
msgid ""
"vdisk %(vdsk)s has been added to the flashcopy mapping delete queue with "
"priority %(pri)s."
msgstr ""
"NV-38E83B6 Le vdisk %(vdsk)s a été ajouté à la file d'attente de "
"suppression du mappage flashcopy avec la priorité %(pri)s."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1149
#, python-format
msgid ""
"Successfully returned from flashcopy mapping waiter for vdisk %(vdsk)s, "
"returned value: %(ret)s, total wait time: %(wt)s seconds."
msgstr ""
"NV-62F28E6 Retour réussi de l'unité en attente du mappage flashcopy pour "
"le vdisk %(vdsk)s, valeur renvoyée : %(ret)s, temps d'attente total : "
"%(wt)s secondes."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1166
#, python-format
msgid ""
"Exception happened when waiting for flashcopy mapping handling for vdisk "
"%(vdsk)s, total wait time: %(wt)s seconds."
msgstr ""
"NV-71EC636 Exception générée lors de l'attente du traitement du mappage "
"flashcopy pour le vdisk %(vdsk)s, durée d'attente totale : %(wt)s "
"secondes."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1172
#, python-format
msgid ""
"Removed flashcopy mappings waiter from waiting queue for vdisk %(vdsk)s "
"deletion."
msgstr ""
"NV-46703B0 Suppression de l'unité en attente des mappages flashcopy de la"
" file d'attente pour la suppression de vdisk %(vdsk)s."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1183
#, python-format
msgid "Flashcopy mapping delete queue: %(vdsks)s"
msgstr "NV-CA4A211 File d'attente de suppression du mappage Flashcopy : %(vdsks)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1193
#, python-format
msgid ""
"Flashcopy mapping delete queue: %(cnt)s vdisks pending delete, average "
"wait time: %(avg)s seconds"
msgstr ""
"NV-91BB641 File d'attente de suppression du mappage Flashcopy : %(cnt)s "
"vdisks en attente de suppression, temps d'attente moyen : %(avg)s "
"secondes"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1242
#, python-format
msgid "fcmapping_handler: %(err)s"
msgstr "fcmapping_handler : %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1245
#, python-format
msgid ""
"fcmapping_handler: to delete vdisk %(vdisk_id)s, increasing copyrate of "
"flashcopy mapping %(map)s from 0 to %(copyrate)s and waiting for "
"completion."
msgstr ""
"NV-EE5BEB1 fcmapping_handler : pour supprimer le vdisk %(vdisk_id)s, "
"augmentation du débit de copie du mappage flashcopy %(map)s de 0 à "
"%(copyrate)s et attente de son achèvement."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1357
#, python-format
msgid ""
"Exception happened during processing flashcopy mapping per vdisk %(vdsk)s"
" deletion: %(err)s"
msgstr ""
"NV-71C30D1 Une exception s'est produite lors du traitement du mappage "
"flashcopy par suppression de vdisk %(vdsk)s : %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1387
#, python-format
msgid ""
"Duration of fcmapping_handler timer: %(runtime)s seconds, %(pct)s%% of "
"fixed polling interval."
msgstr ""
"NV-80870AC Durée du temporisateur fcmapping_handler : %(runtime)s "
"secondes, %(pct)s%% d'intervalle d'interrogation fixe."

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:93
#, python-format
msgid "Fabric names are not unique: %(fabric_names)s"
msgstr ""
"NV-2ED2D0B Les noms des ensembles de noeuds ne sont pas uniques : "
"%(fabric_names)s"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:261
#, python-format
msgid "Connection established to fabric %(f_name)s"
msgstr "NV-41B567C Connexion établie à l'ensemble de noeuds %(f_name)s"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:376
#, python-format
msgid "Zones to be created for %(fabric)s are %(zones)r"
msgstr "NV-2E6EE4A Les zones à créer pour %(fabric)s sont %(zones)r"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:410
#, python-format
msgid "%(fabric_descriptor)s: deleting zones %(zone_list)s"
msgstr "NV-C3FDFEA %(fabric_descriptor)s : suppression des zones %(zone_list)s"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:449
#, python-format
msgid "Returned data from get_nameserver_info() is %(info)r"
msgstr ""
"NV-7863F08 Les données renvoyées depuis get_nameserver_info() sont "
"%(info)r"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:122
msgid "Could not connect"
msgstr "NV-07C9AAF Connexion impossible"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:124
#, python-format
msgid "SSH Client created for %s"
msgstr "NV-08C2923 Client SSH créé pour %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:187
#, python-format
msgid "Failed getting active zone set from %s"
msgstr "NV-373682A Echec de l'obtention du jeu de zones actif depuis %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:218
msgid "Malformed zone configuration"
msgstr "NV-9BF2FBF Configuration de zone syntaxiquement incorrecte"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:220
#, python-format
msgid "Failed getting active zone set from fabric %s"
msgstr ""
"NV-A5B77A2 Echec de l'obtention du jeu de zones actif depuis l'ensemble "
"de noeuds %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:259
#, python-format
msgid "Add Zones - Zones passed: %s"
msgstr "NV-8A18A84 Ajout de zones - Zones transmises : %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:267
#, python-format
msgid "Adding zone failed. Error in getting active zone set from fabric %s"
msgstr ""
"NV-C692314 L'ajout de zone a échoué. Erreur lors de l'obtention du jeu de"
" zones actif depuis l'ensemble de noeuds %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:276
#, python-format
msgid "Zone %(zoneName)s already contains required members"
msgstr "NV-EADDEDC La zone %(zoneName)s contient déjà les membres requis"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:282
#, python-format
msgid "Deleted Zone before insert : %s"
msgstr "NV-4C9797D Suppression de la zone avant l'insertion : %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:286
#, python-format
msgid "Deleting zone failed %s"
msgstr "NV-C1A773E La suppression de la zone a échoué %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:294
#, python-format
msgid "Adding zone, cmd to run %s"
msgstr "NV-D2B3DDC Ajout de la zone, cmd à exécuter %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:301
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:304
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:338
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:341
#, python-format
msgid "Adding zone failed, cmd %s"
msgstr "NV-3F8FCCF L'ajout de zone a échoué, cmd %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:312
msgid "No new zones created"
msgstr "NV-145C307 Aucune zone créée"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:322
#, python-format
msgid "Zoneset create operation failed with output %s"
msgstr ""
"NV-0645570 L'opération de création du jeu de zones a échoué avec la "
"sortie %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:330
#, python-format
msgid "cfgAdd operation failed : %s"
msgstr "NV-C8F3EB6 L'opération cfgAdd a échoué : %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:343
msgid "Zoning completed"
msgstr "NV-BC5301E Segmentation terminée"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:373
#, python-format
msgid "Failed getting active zones from fabric %s"
msgstr ""
"NV-21CE132 Echec de l'obtention des zones actives depuis l'ensemble de "
"noeuds %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:395
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:398
#, python-format
msgid "Deleting zones failed, cmd %s"
msgstr "NV-AFACFBC La suppression des zones a échoué, cmd %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:414
#, python-format
msgid "Failed collecting nsshow info for fabric %s"
msgstr ""
"NV-6039569 Echec de la collecte des infos nsshow pour l'ensemble de "
"noeuds %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:421
#, python-format
msgid "Failed collecting nscamshow info for fabric %s"
msgstr ""
"NV-A1992B9 Echec de la collecte des infos nscamshow pour l'ensemble de "
"noeuds %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:453
#, python-format
msgid "Problem: %(problem)s"
msgstr "NV-D20CB78 Problème : %(problem)s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:471
#, python-format
msgid "Will retry after %(seconds)s seconds..."
msgstr "NV-A7C85C7 Nouvelle tentative après un délai de %(seconds)s secondes..."

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:490
#, python-format
msgid "Failed closing SSH connection %s"
msgstr "NV-3EA57B2 Echec de la fermeture de la connexion SSH %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:512
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:561
#, python-format
msgid "running: '%s'"
msgstr "NV-081F69F en cours d'exécution : '%s'"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:521
#, python-format
msgid "Returned data was %r"
msgstr "NV-93F16B7 Données renvoyées : %r"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:535
#, python-format
msgid "Error running command via ssh: %s"
msgstr "NV-20D0255 Erreur lors de l'exécution de la commande via ssh : %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:587
#, python-format
msgid "Error while checking zoning txn status: %s"
msgstr ""
"NV-2D4C6DF Erreur lors de la vérification du statut txn de segmentation :"
" %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:599
#, python-format
msgid "Executing: %s"
msgstr "NV-4EBB354 En cours d'exécution : %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:609
#, python-format
msgid "CLI execution returned: %s"
msgstr "NV-538FB7E Retour de l'exécution CLI : %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:633
#, python-format
msgid "Error executing command %(cmd)s: %s"
msgstr "Erreur lors de l'exécution de la commande %(cmd)s : %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:648
#, python-format
msgid "Failed when executing command '%(cmd)s': %(err)s"
msgstr "NV-B5BA5A5 Echec lors de l'exécution de la commande '%(cmd)s' : %(err)s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:670
#, python-format
msgid "Malformed nameserver output is: %s"
msgstr "NV-07E23F0 Sortie de serveur de noms syntaxiquement incorrecte : %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:672
msgid "Malformed nameserver info"
msgstr "NV-4331BBF Infos de serveurs de noms syntaxiquement incorrectes"

