# Translations template for paxes_cinder.
# Copyright (C) 2014 NCO Corp.
# This file is distributed under the same license as the paxes_cinder
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: paxes_cinder 1.2.1.0\n"
"Report-Msgid-Bugs-To: nguyen1d@us.ibm.com\n"
"POT-Creation-Date: 2014-04-24 16:04-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: paxes_cinder/k2aclient/openstack/common/gettextutils.py:255
msgid "Message objects do not support addition."
msgstr "NV-C33F89C Nachrichtenobjekte unterstützen das Hinzufügen nicht."

#: paxes_cinder/k2aclient/openstack/common/gettextutils.py:264
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""
"NV-64408AE Nachrichtenobjekte unterstützen str() nicht, da sie auch "
"Zeichen, die keine ASCII-Zeichen sind, enthalten können. Verwenden Sie "
"stattdessen unicode() oder translate()."

#: paxes_cinder/k2aclient/openstack/common/procutils.py:129
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr "NV-36AD129 Unbekannte Schlüsselwortargumente für utils.execute: %r"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:144
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "NV-9F83237 Aktiver Befehl (Unterprozess): %s"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:169
#: paxes_cinder/k2aclient/openstack/common/procutils.py:241
#, python-format
msgid "Result was %s"
msgstr "NV-E91D667 Ergebnis war %s"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:181
#, python-format
msgid "%r failed. Retrying."
msgstr "NV-E62FA94 %r fehlgeschlagen. Wiederholung."

#: paxes_cinder/k2aclient/openstack/common/procutils.py:220
#, python-format
msgid "Running cmd (SSH): %s"
msgstr "NV-F226973 Aktiver Befehl (SSH): %s"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:222
msgid "Environment not supported over SSH"
msgstr "NV-5D0CD8B Umgebung über SSH nicht unterstützt"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:226
msgid "process_input not supported over SSH"
msgstr "NV-E78B011 process_input über SSH nicht unterstützt"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:512
#, python-format
msgid "DB error: %s"
msgstr "NV-B907287 Datenbankfehler: %s"

#: paxes_cinder/k2aclient/shell.py:100
msgid "Print debugging output"
msgstr "Debugausgabe drucken"

#: paxes_cinder/api/plugins/__init__.py:31
#, python-format
msgid "Failed to load extension %(name)s: %(ex)s"
msgstr "NV-E1E174C Fehler beim Laden der Erweiterung %(name)s: %(ex)s"

#: paxes_cinder/volume/manager.py:1275
#, python-format
msgid "Driver %s does not implement Discover Driver"
msgstr "NV-DA200A2 Treiber %s implementiert 'Treiber erkennen' nicht"

#: paxes_cinder/exception.py:16
#, python-format
msgid "Connection control failure: %(reason)s"
msgstr "NV-BFC4353 Fehler bei Verbindungssteuerung: %(reason)s"

#: paxes_cinder/exception.py:20
#, python-format
msgid "Zone operation failed: %(reason)s"
msgstr "NV-A619680 Zonenoperation fehlgeschlagen: %(reason)s"

#: paxes_cinder/exception.py:24
#, python-format
msgid "FC SAN Lookup failure: %(reason)s"
msgstr "NV-1316051 Fehler bei FC-SAN-Suche: %(reason)s"

#: paxes_cinder/exception.py:32
#, python-format
msgid "Internal Misconfiguration detected: %(reason)s"
msgstr "NV-C9F5A2A Fehlerhafte interne Konfiguration gefunden: %(reason)s"

#: paxes_cinder/exception.py:58
#, python-format
msgid "Fabric '%(display_name)s' (%(username)s@%(ip)s:%(port)s)"
msgstr "NV-097D384 Fabric '%(display_name)s' (%(username)s@%(ip)s:%(port)s)"

#: paxes_cinder/exception.py:93
#, python-format
msgid "%(descriptor)s: %(message)s"
msgstr "NV-12DC37C %(descriptor)s: %(message)s"

#: paxes_cinder/exception.py:142
#, python-format
msgid "%(problem)s: %(err)s"
msgstr "NV-7FA8022 %(problem)s: %(err)s"

#: paxes_cinder/exception.py:164
msgid "Could not authenticate with the specified credentials"
msgstr ""
"NV-BB4FAEC Konnte mit den angegebenen Berechtigungsnachweisen nicht "
"authentifiziert werden"

#: paxes_cinder/exception.py:174
#, python-format
msgid "Timeout (%(timeout)s seconds) when attempting to connect"
msgstr "NV-3AB9750 Zeitlimit (%(timeout)s Sekunden) beim Herstellen der Verbindung"

#: paxes_cinder/exception.py:184
#, python-format
msgid "Timeout (%(timeout)s seconds) when executing command %(cmd)s"
msgstr ""
"NV-17277CD Zeitlimit (%(timeout)s Sekunden) beim Ausführen des Befehls "
"%(cmd)s"

#: paxes_cinder/exception.py:193
#, python-format
msgid "Could not connect: %(error)s %(detail)s"
msgstr ""
"NV-2251927 Es konnte keine Verbindung hergestellt werden: %(error)s "
"%(detail)s"

#: paxes_cinder/exception.py:201
#, python-format
msgid ""
"Another transaction was already in progress when attempting to execute "
"command '%(cmd)s'"
msgstr ""
"NV-B3EE2A1 Beim Versuch, den Befehl '%(cmd)s' auszuführen, war bereits "
"eine andere Transaktion in Bearbeitung"

#: paxes_cinder/exception.py:209
#, python-format
msgid ""
"Zone DB exceeded size limits when executing command '%(cmd)s', which "
"returned '%(res)s'"
msgstr ""
"NV-3D73335 Zonen-DB hat beim Ausführen des Befehls '%(cmd)s', der "
"'%(res)s' zurückgegeben hat, die Größenbegrenzung überschritten"

#: paxes_cinder/exception.py:218
#, python-format
msgid "The CLI command '%(cmd)s' returned an unexpected response '%(res)s'"
msgstr ""
"NV-6BC3B8F Der CLI-Befehl '%(cmd)s' hat die nicht erwartete Antwort "
"'%(res)s' zurückgegeben"

#: paxes_cinder/exception.py:240
#, python-format
msgid "Storage %(display_name)s (%(username)s@%(ip)s:%(port)s)"
msgstr "NV-FD8FAF8 Speicher %(display_name)s (%(username)s@%(ip)s:%(port)s)"

#: paxes_cinder/exception.py:272
msgid "No more host definitions can be created"
msgstr "NV-FAE0982 Es können keine weiteren Hostdefinitionen erstellt werden"

#: paxes_cinder/exception.py:281
msgid "No more flashcopy mappings can be created"
msgstr "NV-5071C44 Es können keine weiteren FlashCopy-Zuordnungen erstellt werden"

#: paxes_cinder/exception.py:289
msgid "Could not connect, possibly due to too many connections."
msgstr ""
"NV-16C6099 Es konnte keine Verbindung hergestellt werden. Ein möglicher "
"Grund dafür sind zu viele Verbindungen."

#: paxes_cinder/exception.py:297
#, python-format
msgid ""
"Could not map vdisk %(vdisk_id)s to host %(host)s because it is already "
"mapped to another host"
msgstr ""
"NV-4B128AE Die virtuelle Platte %(vdisk_id)s konnte nicht zu Host "
"%(host)s zugeordnet werden, weil sie bereits einem anderen Host "
"zugeordnet ist"

#: paxes_cinder/exception.py:312
#, python-format
msgid "vdisk %(vdisk_id)s does not exist"
msgstr "NV-8AE54C7 Die virtuelle Platte %(vdisk_id)s ist nicht vorhanden"

#: paxes_cinder/exception.py:322
msgid "No common fabrics between virtual machine and storage"
msgstr ""
"NV-E5685D0 Keine gemeinsamen Fabrics zwischen virtueller Maschine und "
"Speicher"

#: paxes_cinder/exception.py:339
#, python-format
msgid ""
"vdisk %(vdisk_id)s has been deleted and recreated. Expected UID is "
"%(expected_uid)s, current UID is %(current_uid)s"
msgstr ""
"NV-78057E1 Die virtuelle Platte %(vdisk_id)s wurde gelöscht und neu "
"erstellt. Erwartet wurde die UID %(expected_uid)s, die aktuelle UID ist "
"%(current_uid)s"

#: paxes_cinder/exception.py:350
#, python-format
msgid ""
"Not enough space left on storage host %(host)s to extend the volume "
"%(volume_id)s"
msgstr ""
"NV-EA431AC Der Speicherplatz auf Speicherhost %(host)s reicht nicht aus, "
"um den Datenträger %(volume_id)s zu erweitern"

#: paxes_cinder/exception.py:360
msgid ""
"Flashcopy is in progress for boot volume, volume size didn't change. "
"Please try again later."
msgstr ""
"NV-461A839 FlashCopy ist für Bootdatenträger in Bearbeitung. Die "
"Datenträgergröße hat sich nicht geändert. Versuchen Sie es zu einem "
"späteren Zeitpunkt erneut."

#: paxes_cinder/exception.py:367
#, python-format
msgid ""
"vdisk %(vdisk_id)s is source of snapshot flashcopy and fcmap %(fcmapid)s "
"cannot be removed."
msgstr ""
"NV-CB3AB35 Die virtuelle Platte %(vdisk_id)s ist die Quelle für "
"Momentaufnahme-FlashCopy und FC-Zuordnung %(fcmapid)s kann nicht entfernt"
" werden."

#: paxes_cinder/db/sqlalchemy/migrate_repo/versions/001_ibm_paxes_v1r2.py:35
#, python-format
msgid "Exception creating table %(table)s: %(ex_str)s"
msgstr "Ausnahmebedingung beim Erstellen der Tabelle %(table)s: %(ex_str)s"

#: paxes_cinder/db/sqlalchemy/migrate_repo/versions/001_ibm_paxes_v1r2.py:55
#, python-format
msgid "Exception dropping table %(table)s: %(ex_str)s"
msgstr "Ausnahmebedingung beim Löschen der Tabelle %(table)s: %(ex_str)s"

#: paxes_cinder/fabric/map_initiators.py:70
msgid ""
"Could not obtain a fabric manager client. Fibre Channel switch fabrics "
"may not be registered."
msgstr ""
"NV-6EF68AC Es wurde kein Fabric Manager-Client gefunden. Möglicherweise "
"sind Fibre Channel-Switch-Fabrics nicht registriert."

#: paxes_cinder/fabric/map_initiators.py:85
#, python-format
msgid ""
"Unable to retrieve WWPN initiator information from one or more fabric "
"switches. Error: %(ex_str)s"
msgstr ""
"Fehler beim Abrufen der Informationen zum WWPN-Initiator von einem oder "
"mehreren Fabric-Switches. Fehler: %(ex_str)s"

#: paxes_cinder/fabric/map_initiators.py:119
msgid "No fabrics registered."
msgstr "NV-0AA1511 Keine Fabrics registriert."

#: paxes_cinder/fabric/map_initiators.py:124
msgid "No fabric names registered."
msgstr "NV-A4978F0 Keine Fabric-Namen registriert."

#: paxes_cinder/k2aclient/client.py:104
msgid ", during get"
msgstr "NV-C758794 , beim Abrufen"

#: paxes_cinder/k2aclient/client.py:127
msgid ", during refresh"
msgstr "NV-A09A06D , beim Aktualisieren"

#: paxes_cinder/k2aclient/client.py:148
#: paxes_cinder/k2aclient/client.py:172
msgid ", during create"
msgstr "NV-16332E7 , beim Erstellen"

#: paxes_cinder/k2aclient/client.py:193
msgid ", during delete"
msgstr "NV-B5BE602 , beim Löschen"

#: paxes_cinder/k2aclient/client.py:207
msgid ", during runJob"
msgstr "NV-9A12874 , beim Ausführungsjob"

#: paxes_cinder/k2aclient/client.py:219
msgid ", during readJob"
msgstr "NV-EA9B845 , beim Lesejob"

#: paxes_cinder/k2aclient/client.py:234
msgid ", during authenticate"
msgstr "NV-DD96084 , beim Authentifizieren"

#: paxes_cinder/k2aclient/client.py:247
#, python-format
msgid ""
"k2aclient: while obtaining client, invalid client version >%(version)s<. "
"must be one of: >%(versions)s<"
msgstr ""
"k2aclient: Beim Abrufen des Clients: Ungültige Clientversion "
">%(version)s<. Zulässige Werte: >%(versions)s<"

#: paxes_cinder/k2aclient/exceptions.py:46
#: paxes_cinder/k2aclient/exceptions.py:307
#, python-format
msgid ", exception diagnostics have been written to: >%s<"
msgstr ". Diagnosen für Ausnahmebedingungen wurden geschrieben in: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:56
#, python-format
msgid "Other Exception off of K2: >%s<"
msgstr "NV-92A2EB5 Sonstige Ausnahmebedingung aus K2 heraus: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:58
#: paxes_cinder/k2aclient/exceptions.py:78
#: paxes_cinder/k2aclient/exceptions.py:88
#: paxes_cinder/k2aclient/exceptions.py:105
#, python-format
msgid ", during: >%s<"
msgstr ", bei: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:66
#, python-format
msgid "SSL exception off of K2: >%s<"
msgstr "NV-852F651 SSL-Ausnahmebedingung aus K2 heraus: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:76
#, python-format
msgid "Connection exception off of K2: >%s<"
msgstr "NV-DE65980 Verbindungsausnahmebedingung aus K2 heraus: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:86
#, python-format
msgid "Timeout exception off of K2: >%s<"
msgstr "NV-DC27602 Zeitlimitausnahmebedingung aus K2 heraus: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:100
#, python-format
msgid "K2Error off of K2: >%(msg)s<, Status: >%(status)d<, k2Error: >%(k2error)s<"
msgstr ""
"K2-Fehler aus K2 heraus: >%(msg)s<, Status: >%(status)d<, k2-Fehler: "
">%(k2error)s<"

#: paxes_cinder/k2aclient/exceptions.py:122
msgid "Bad Request"
msgstr "Fehlerhafte Anforderung"

#: paxes_cinder/k2aclient/exceptions.py:130
msgid "Unauthorized"
msgstr "Nicht berechtigt"

#: paxes_cinder/k2aclient/exceptions.py:144
msgid "Forbidden"
msgstr "Untersagt"

#: paxes_cinder/k2aclient/exceptions.py:158
msgid "Not Found"
msgstr "Nicht gefunden"

#: paxes_cinder/k2aclient/exceptions.py:167
msgid "Method Not Allowed"
msgstr "Methode nicht zulässig"

#: paxes_cinder/k2aclient/exceptions.py:177
msgid "Not Acceptable"
msgstr "Nicht zulässig"

#: paxes_cinder/k2aclient/exceptions.py:189
msgid "Conflict"
msgstr "Konflikt"

#: paxes_cinder/k2aclient/exceptions.py:197
msgid "PreCondition failed"
msgstr "Vorbedingung fehlgeschlagen"

#: paxes_cinder/k2aclient/exceptions.py:206
msgid "Request Body Too Large"
msgstr "Anforderungshauptteil zu groß"

#: paxes_cinder/k2aclient/exceptions.py:216
msgid "Unsupported Media Type"
msgstr "Nicht unterstützter Medientyp"

#: paxes_cinder/k2aclient/exceptions.py:225
msgid "Internal Server Error"
msgstr "Interner Serverfehler"

#: paxes_cinder/k2aclient/exceptions.py:235
msgid "Not Implemented"
msgstr "Nicht implementiert"

#: paxes_cinder/k2aclient/exceptions.py:245
msgid "Service Unavailable"
msgstr "Service nicht verfügbar"

#: paxes_cinder/k2aclient/exceptions.py:255
msgid "HTTP Version Not Supported"
msgstr "HTTP-Version nicht unterstützt"

#: paxes_cinder/k2aclient/exceptions.py:263
msgid "Not Classified"
msgstr "Nicht klassifiziert"

#: paxes_cinder/k2aclient/k2exclogger.py:114
#, python-format
msgid ""
"k2aclient: during FFDC, cant create k2 exception log directory: >%s<, "
"will disable k2 exception logging .."
msgstr ""
"NV-ED6E0F0 k2aclient: Bei FFDC: k2-Ausnahmeprotokollverzeichnis >%s< "
"konnte nicht erstellt werden. Deshalb wird die k2-Ausnahmeprotokollierung"
" inaktiviert .."

#: paxes_cinder/k2aclient/k2exclogger.py:123
#, python-format
msgid ""
"k2aclient: during FFDC, cant write to k2 exception log directory: >%s<, "
"will disable k2 exception logging .."
msgstr ""
"NV-6373107 k2aclient: Bei FFDC: In k2-Ausnahmeprotokollverzeichnis >%s< "
"konnte nicht geschrieben werden. Deshalb wird die "
"k2-Ausnahmeprotokollierung inaktiviert .."

#: paxes_cinder/k2aclient/k2exclogger.py:146
#, python-format
msgid ""
"k2aclient: during FFDC,  caught an exception while writing to log "
"directory: >%s<, will disable k2 exception logging .."
msgstr ""
"NV-3376E54 k2aclient: Bei FFDC: Beim Schreiben in Protokollverzeichnis "
">%s< wurde eine Ausnahmebedingung abgefangen. Deshalb wird die "
"k2-Ausnahmeprotokollierung inaktiviert .."

#: paxes_cinder/k2aclient/shell.py:59
#, python-format
msgid ""
"k2aclient: error: %(errmsg)s\n"
"Try '%(mainp)s help %(subp)s' for more information.\n"
msgstr ""
"k2aclient: Fehler: %(errmsg)s\n"
"Weitere Informationen finden Sie unter '%(mainp)s Hilfe %(subp)s'.\n"

#: paxes_cinder/k2aclient/shell.py:80
msgid "See \"k2a help COMMAND\" for help on a specific command."
msgstr "Hilfe zu einem bestimmten Befehl finden Sie unter \"k2a-Hilfe BEFEHL\"."

#: paxes_cinder/k2aclient/shell.py:106
msgid "Accepts 1,defaults to env[K2A_API_VERSION]."
msgstr "Akzeptiert 1. Hat standardmäßig den Wert env[K2A_API_VERSION]."

#: paxes_cinder/k2aclient/shell.py:109
msgid "Number of retries when attempting k2 operations."
msgstr "Anzahl der Wiederholungsversuche für k2-Operationen."

#: paxes_cinder/k2aclient/shell.py:119
msgid "url for k2 hmc, defaults to env[K2_URL]."
msgstr "URL für k2-HMC. Hat standardmäßig den Wert env[K2_URL]."

#: paxes_cinder/k2aclient/shell.py:125
msgid "k2 username, defaults to env[K2_USERNAME]."
msgstr "k2-Benutzername. Hat standardmäßig den Wert env[K2_USERNAME]."

#: paxes_cinder/k2aclient/shell.py:131
msgid "k2 password, defaults to env[K2_PASSWORD]."
msgstr "k2-Kennwort. Hat standardmäßig den Wert env[K2_PASSWORD]."

#: paxes_cinder/k2aclient/shell.py:138
msgid ""
"k2 auditmemento, defaults to, if set, env[K2_AUDITMEMENTO], otherwise to "
"\"k2a\"."
msgstr ""
"k2-Prüferinnerungselement. Hat, wenn festgelegt, standardmäßig den Wert "
"env[K2_AUDITMEMENTO], andernfalls den Wert \"k2a\"."

#: paxes_cinder/k2aclient/shell.py:145
msgid "k2 certpath, defaults to, if set, env[K2_CERTPATH], otherwise to None."
msgstr ""
"k2-Zertifikatspfad. Hat, wenn festgelegt, standardmäßig den Wert "
"env[K2_CERTPATH], andernfalls den Wert 'None'."

#: paxes_cinder/k2aclient/shell.py:152
msgid ""
"log directory, defaults to, if set, env[K2A_LOGDIR], otherwise to None. "
"None turnsoff file logging"
msgstr ""
"Protokollverzeichnis. Hat, wenn festgelegt, standardmäßig den Wert "
"env[K2A_LOGDIR], andernfalls den Wert 'None'. Bei 'None' wird die "
"Dateiprotokollierung ausgeschaltet"

#: paxes_cinder/k2aclient/shell.py:171
msgid ""
"directory where k2aexc subdirectorywill be placedie \"<excdir>/k2aexc\", "
"defaults to, if set, env[K2A_EXCDIR], otherwise to /tmp"
msgstr ""
"Verzeichnis, in dem das Unterverzeichnis k2aexc angelegt wird, d. h. "
"\"<excdir>/k2aexc\". Hat, wenn festgelegt, standardmäßig den Wert "
"env[K2A_EXCDIR], andernfalls den Wert /tmp"

#: paxes_cinder/k2aclient/shell.py:309
msgid ""
"k2aclient: you must provide a url for a k2 hmc via either --k2-url or "
"env[K2_URL]"
msgstr ""
"NV-D20F7FC k2aclient: Sie müssen eine URL für eine k2-HMC über --k2-url "
"oder über env[K2_URL] angeben"

#: paxes_cinder/k2aclient/shell.py:315
msgid ""
"k2aclient: you must provide a k2 username via either --k2-username or "
"env[K2_USERNAME]"
msgstr ""
"NV-996BCEC k2aclient: Sie müssen einen k2-Benutzernamen über "
"--k2-username oder über env[K2_USERNAME] angeben"

#: paxes_cinder/k2aclient/shell.py:321
msgid ""
"k2aclient: you must provide a k2 password via either --k2-password or via"
" env[K2_PASSWORD]"
msgstr ""
"NV-EB948AA k2aclient: Sie müssen ein k2-Kennwort über --k2-password oder "
"über env[K2_PASSWORD] angeben"

#: paxes_cinder/k2aclient/shell.py:355
#, python-format
msgid "Display help for %s"
msgstr "Hilfe für %s anzeigen"

#: paxes_cinder/k2aclient/shell.py:364
#, python-format
msgid "k2aclient:>%s< is not a valid subcommand"
msgstr "NV-DAC982A k2aclient: >%s< ist kein gültiger Unterbefehl"

#: paxes_cinder/k2aclient/shell.py:384
msgid "... terminating k2a client"
msgstr "NV-56344DF ... k2a-Client wird beendet"

#: paxes_cinder/k2aclient/shell.py:389
#, python-format
msgid "ERROR: type: >%(type)s<, msg: >%(e)s<"
msgstr "NV-9BF8F90 FEHLER: Typ: >%(type)s<, Nachricht: >%(e)s<"

#: paxes_cinder/k2aclient/utils.py:101
#, python-format
msgid "k2aclient: no %(res)s with a name or ID of '%(name_or_id)s' exists."
msgstr ""
"NV-63A28A2 k2aclient: %(res)s mit dem Namen oder der ID '%(name_or_id)s' "
"nicht vorhanden."

#: paxes_cinder/k2aclient/utils.py:108
#, python-format
msgid ""
"k2aclient: multiple %(res)s matches found for '%(name_or_id)s', use an ID"
" to be more specific."
msgstr ""
"NV-9ACDF38 k2aclient: Mehrere Übereinstimmungen mit %(res)s für "
"'%(name_or_id)s' gefunden. Verwenden Sie eine ID, um weiter einzugrenzen."

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:144
#: paxes_cinder/k2aclient/v1/virtualioserver_manager.py:138
#, python-format
msgid "during directory preparation, cant create directory:  >%s<"
msgstr ""
"NV-64A449C Bei Verzeichnisvorbereitung: Folgendes Verzeichnis kann nicht "
"erstellt werden: >%s<"

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:150
#: paxes_cinder/k2aclient/v1/virtualioserver_manager.py:144
#, python-format
msgid "during directory preparation, cant write to directory:  >%s<"
msgstr ""
"NV-C96CB61 Bei Verzeichnisvorbereitung: In folgendes Verzeichnis kann "
"nicht geschrieben werden: >%s<"

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:181
#: paxes_cinder/k2aclient/k2asample/k2_ssp_etag_test.py:44
#: paxes_cinder/k2aclient/k2asample/tool_ssp_simulation.py:228
#, python-format
msgid "Node: >%s<, has no virtual_io_server, continuing ..."
msgstr ""
"NV-60D657D Knoten: >%s< ohne virtual_io_server. Vorgang wird fortgesetzt "
"..."

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:192
#: paxes_cinder/k2aclient/k2asample/k2_ssp_etag_test.py:55
#: paxes_cinder/k2aclient/k2asample/tool_ssp_simulation.py:239
#, python-format
msgid "Failed to retrieve node: >%s<, msg: >%s<, continuing ..."
msgstr ""
"NV-0B99A4D Fehler beim Abrufen von Knoten: >%s<, Nachricht: >%s<, Vorgang"
" wird fortgesetzt ..."

#: paxes_cinder/k2aclient/openstack/common/lockutils.py:276
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s for method \"%(method)s\"..."
msgstr ""
"NV-F6B31F1 Freigegeben wurde Dateisperre \"%(lock)s\" bei %(path)s für "
"Methode \"%(method)s\"..."

#: paxes_cinder/k2aclient/v1/cluster_manager.py:98
#, python-format
msgid ""
"k2aclient: during lu_linked_clone_of_lu, source_lu_udid: "
">%(source_lu_udid)s<, not in sharedstoragepool: >%(ssp.id)s<"
msgstr ""
"NV-69F0ACE k2aclient: Bei lu_linked_clone_of_lu: source_lu_udid "
">%(source_lu_udid)s< ist nicht in gemeinsam genutztem Speicherpool "
">%(ssp.id)s<"

#: paxes_cinder/k2aclient/v1/cluster_manager.py:221
#, python-format
msgid ""
"k2aclient: for cluster id : >%(cluster.id)s<,  during lu_linked_clone, "
"for SourceUDID: >%(sourceUDID)s<, and DestinationUDID: "
">%(destinationUDID)s<, experienced job failure, job_id: "
">%(jresponse.job_id)s<, status: >%(jresponse.status)s<, input K2 job "
"diagnostics have been written to: >%(diagfspeci)s<, response k2 job "
"diagnostics have been written to: >%(diagfspec)s<"
msgstr ""
"k2aclient: Für Cluster-ID >%(cluster.id)s< bei lu_linked_clone: Für "
"Quellen-UDID >%(sourceUDID)s< und Ziel-UDID >%(destinationUDID)s< ist ein"
" Jobfehler aufgetreten. job_id: >%(jresponse.job_id)s<, Status: "
">%(jresponse.status)s<. Diagnosen für K2-Eingabejobs wurden geschrieben "
"in: >%(diagfspeci)s<. Diagnosen für K2-Antwortjobs wurden geschrieben in:"
" >%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/cluster_manager.py:335
#, python-format
msgid ""
"k2aclient: for cluster id : >%(cluster.id)s<,  during lu_create, for "
"lu_unit_name: >%(lu_unit_name)s<, with lu_unit_capacity: "
">%(lu_unit_capacity)s<, experienced job failure, job_id: "
">%(jresponse.job_id)s<, status: >%(jresponse.status)s<, input K2 job "
"diagnostics have been written to: >%(diagfspeci)s<, response k2 job "
"diagnostics have been written to: >%(diagfspec)s<"
msgstr ""
"k2aclient: Für Cluster-ID >%(cluster.id)s< bei lu_create: Für "
"lu_unit_name >%(lu_unit_name)s< mit lu_unit_capacity "
">%(lu_unit_capacity)s< ist ein Jobfehler aufgetreten. job_id: "
">%(jresponse.job_id)s<, Status: >%(jresponse.status)s<. Diagnosen für "
"K2-Eingabejobs wurden geschrieben in: >%(diagfspeci)s<. Diagnosen für "
"K2-Antwortjobs wurden geschrieben in: >%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/logicalpartition_manager.py:126
#: paxes_cinder/k2aclient/v1/logicalpartition_manager.py:191
#, python-format
msgid ""
"k2aclient: during power_on, for LogicalPartition: "
">%(logicalpartition.id)s<, failed to power on due to job failure, job_id:"
" >%(jresponse.job_id)s<, status: >%(jresponse.status)s<, input K2 job "
"diagnostics have been written to: >%(diagfspeci)s<, response k2 job "
"diagnostics have been written to: >%(diagfspec)s<"
msgstr ""
"k2aclient: Bei power_on für logische Partition >%(logicalpartition.id)s<:"
" Einschalten ist wegen eines Jobfehlers fehlgeschlagen. job_id: "
">%(jresponse.job_id)s<, Status: >%(jresponse.status)s<. Diagnosen für "
"K2-Eingabejobs wurden geschrieben in: >%(diagfspeci)s<. Diagnosen für "
"K2-Antwortjobs wurden geschrieben in: >%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/managementconsole_manager.py:77
#, python-format
msgid ""
"CLIRunner: ManagementConsole: >%(mc.id)s<, failed to run cmd: >%(cmd)s< "
"due to job failure, job_id: >%(jresponse.job_id)s<, status: "
">%(jresponse.status)s<, input K2 job diagnostics have been written to: "
">%(diagfspeci)s<,  response k2 job diagnostics have been written to: "
">%(diagfspec)s<"
msgstr ""
"CLIRunner: Managementkonsole: >%(mc.id)s<, Ausführen von Befehl >%(cmd)s<"
" wegen eines Jobfehlers fehlgeschlagen. job_id: >%(jresponse.job_id)s<, "
"Status: >%(jresponse.status)s<. Diagnosen für K2-Eingabejobs wurden "
"geschrieben in: >%(diagfspeci)s<. Diagnosen für K2-Antwortjobs wurden "
"geschrieben in: >%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:108
#, python-format
msgid ""
"SharedStoragePool: While attempting to access Cluster: >%s<, unable to "
"connect to HMC: >%s<"
msgstr ""
"Gemeinsam genutzter Speicherpool: Beim Zugriff auf den Cluster >%s< "
"konnte keine Verbindung mit der HMC >%s< hergestellt werden"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:110
msgid "Check the HMC and its configuration."
msgstr "Überprüfen Sie die HMC und deren Konfiguration."

#: paxes_cinder/k2aclient/v1/paxes_manager.py:111
#, python-format
msgid "SharedStoragePool: Able to connect to HMC: >%s< for Cluster: >%s<"
msgstr ""
"Gemeinsam genutzter Speicherpool: Verbindung zur HMC >%s< für Cluster "
">%s< konnte hergestellt werden"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:113
#, python-format
msgid "SharedStoragePool: Couldn't access Cluster: >%s<"
msgstr "Gemeinsam genutzter Speicherpool: Kein Zugriff auf Cluster: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:114
msgid "Check the PowerVC SharedStoragePool configuration"
msgstr ""
"Überprüfen Sie die PowerVC-SSP-Konfiguration (SSP = gemeinsam genutzter "
"Speicherpool)"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:115
#, python-format
msgid "SharedStoragePool: Couldn't access SharedStoragePool in Cluster: >%s<"
msgstr ""
"Gemeinsam genutzter Speicherpool: Kein Zugriff auf gemeinsam genutzten "
"Speicherpool in Cluster: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:117
#: paxes_cinder/k2aclient/v1/paxes_manager.py:122
#: paxes_cinder/k2aclient/v1/paxes_manager.py:127
#: paxes_cinder/k2aclient/v1/paxes_manager.py:133
msgid "Diagnose and repair Cluster"
msgstr "Cluster diagnostizieren und reparieren"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:118
#, python-format
msgid ""
"SharedStoragePool: Successfully accessed SharedStoragePool in Cluster: "
">%s<"
msgstr ""
"Gemeinsam genutzter Speicherpool: Der Zugriff auf den gemeinsam genutzten"
" Speicherpool in Cluster >%s< war erfolgreich"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:120
#, python-format
msgid "SharedStoragePool: Unable to create LogicalUnits in Cluster: >%s<"
msgstr ""
"Gemeinsam genutzter Speicherpool: Die logischen Einheiten konnten in "
"Cluster >%s< nicht erstellt werden"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:123
#, python-format
msgid "SharedStoragePool: LogicalUnit creation functional in Cluster: >%s<"
msgstr ""
"Gemeinsam genutzter Speicherpool: Erstellung von logischen Einheiten in "
"Cluster >%s< funktionsfähig"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:125
#, python-format
msgid "SharedStoragePool: Unable to clone LogicalUnits in Cluster: >%s<"
msgstr ""
"Gemeinsam genutzter Speicherpool: Die logischen Einheiten konnten in "
"Cluster >%s< nicht geklont werden"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:128
#, python-format
msgid ""
"SharedStoragePool: Unable to clone LogicalUnits in Cluster: >%s<, status:"
" >%s<"
msgstr ""
"Gemeinsam genutzter Speicherpool: Die logischen Einheiten konnten in "
"Cluster >%s< nicht geklont werden. Status: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:130
#, python-format
msgid "Clone functional in Cluster: >%s<"
msgstr "Klonen in Cluster >%s< funktionsfähig"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:131
#, python-format
msgid "SharedStoragePool: Unable to delete LogicalUnits in Cluster: >%s<"
msgstr ""
"Gemeinsam genutzter Speicherpool: Die logischen Einheiten konnten in "
"Cluster >%s< nicht gelöscht werden"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:134
#, python-format
msgid "SharedStoragePool: LogicalUnit deletion functional in Cluster: >%s<"
msgstr ""
"Gemeinsam genutzter Speicherpool: Löschung von logischen Einheiten in "
"Cluster >%s< funktionsfähig"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:136
msgid "SharedStoragePool: Not Attempted"
msgstr "Gemeinsam genutzter Speicherpool: Kein Versuch"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:143
msgid "HMC connectivity"
msgstr "HMC-Konnektivität"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:144
msgid "Test connection to an HMC managing the SharedStoragePool"
msgstr ""
"Testverbindung zu einer HMC, die den gemeinsam genutzten Speicherpool "
"verwaltet"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:147
msgid "Cluster and SharedStoragePool accessibility"
msgstr "Möglichkeit des Zugriffs auf Cluster und gemeinsam genutzten Speicherpool"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:148
msgid "Test the accessibility of a SharedStoragePool"
msgstr "Zugänglichkeit eines gemeinsam genutzten Speicherpools testen"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:151
msgid "Create SharedStoragePool LogicalUnits"
msgstr "Logische Einheiten im gemeinsam genutzten Speicherpool erstellen"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:152
msgid "Test the capability to create SharedStoragePool LogicalUnits"
msgstr ""
"Möglichkeit zum Erstellen von logischen Einheiten im gemeinsam genutzten "
"Speicherpool testen"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:155
msgid "Clone LogicalUnits"
msgstr "Logische Einheiten klonen"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:156
msgid "Test the capability to perform a clone"
msgstr "Möglichkeit zum Erstellen eines Klons testen"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:159
msgid "Delete SharedStoragePool LogicalUnits"
msgstr "Logische Einheiten im gemeinsam genutzten Speicherpool löschen"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:160
msgid "Test the capability to delete SharedStoragePool LogicalUnits"
msgstr ""
"Möglichkeit zum Löschen von logischen Einheiten im gemeinsam genutzten "
"Speicherpool testen"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:112
#, python-format
msgid ""
"k2aclient: during updated_append_lus, cannot update K2 object(s) obtained"
" from a list operation, for ssp: >%s<"
msgstr ""
"NV-CEE080E k2aclient: Bei updated_append_lus: K2-Objekte, die aus einer "
"Listenoperation abgerufen wurden, konnten für SSP >%s< nicht aktualisiert"
" werden"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:158
#, python-format
msgid "k2aclient: during updated_append_lus, wrong length of lu input tuple: >%d<"
msgstr ""
"NV-B8F5AF7 k2aclient: Bei updated_append_lus: Falsche Länge des LU-"
"Eingabetupels: >%d<"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:192
#, python-format
msgid ""
"k2aclient:  during updated_append_lus, request to add LU unit_name: >%s< "
"failed, name must be unique"
msgstr ""
"NV-F6B87FC k2aclient: Bei updated_append_lus: Anforderung zum Hinzufügen "
"der LU mit dem unit_name >%s< ist fehlgeschlagen. Der Name muss eindeutig"
" sein"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:224
#, python-format
msgid ""
"k2aclient: during updated_append_lus, while adding LUs named: "
">%(lunames)s<,  # attempts due to HTTP 412 exceeded: "
">%(self.api.retries)d<"
msgstr ""
"NV-01A9381 k2aclient: Bei updated_append_lus: Beim Hinzufügen der LUs mit"
" den Namen >%(lunames)s< wurde die Anzahl der Versuche wegen HTTP 412 "
"überschritten: >%(self.api.retries)d<"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:260
#, python-format
msgid ""
"k2aclient: during updated_append_lus, cant handle K2 response, K2 "
"reported successful creation of >%(lenlus)d<  lus named: >%(lunames)s<,  "
"attempts: >%(attempts)d<  but only >%(lustoadd)d< LUs were found."
msgstr ""
"k2aclient: Bei updated_append_lus: K2-Antwort kann nicht verarbeitet "
"werden. K2 meldete erfolgreiche Erstellung von >%(lenlus)d< LUs mit den "
"Namen: >%(lunames)s<, Versuche: >%(attempts)d<. Es wurden aber nur "
">%(lustoadd)d< LUs gefunden."

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:276
#, python-format
msgid ""
"k2aclient: during updated_append_lus, cant handle K2 response, K2 "
"reported successful creation of >%(lenlus)d< lus named: >%(lunames)s<, "
"attempts: >%(attempts)d< but >%(lustoadd)d< extra LUs were returned."
msgstr ""
"k2aclient: Bei updated_append_lus: K2-Antwort kann nicht verarbeitet "
"werden. K2 meldete erfolgreiche Erstellung von >%(lenlus)d< LUs mit den "
"Namen: >%(lunames)s<, Versuche: >%(attempts)d<. Es wurden aber "
">%(lustoadd)d< zusätzliche LUs zurückgegeben."

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:369
#, python-format
msgid ""
"k2aclient: during update_append_lu, programming error, could not find "
"lu_udid: >%(lu_udid)s<, in input ssp for: >%(pool)s<"
msgstr ""
"k2aclient: Bei update_append_lu: Programmierfehler. lu_udid >%(lu_udid)s<"
" in Eingabe-SSP für >%(pool)s< nicht gefunden"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:390
#, python-format
msgid ""
"k2aclient: during update_append_lu, while deleting LUs w/ udids: "
">%(lu_udids)s<, # attempts due to HTTP 412 exceeded: >%(retries)d<"
msgstr ""
"NV-A3B2A22 k2aclient: Bei update_append_lu: Beim Löschen der LUs mit den "
"UDIDs >%(lu_udids)s< wurde die Anzahl der Versuche wegen HTTP 412 "
"überschritten: >%(retries)d<"

#: paxes_cinder/k2aclient/v1/shell.py:55
#, python-format
msgid "k2aclient: during encoding unexpected type: >%s<"
msgstr "NV-AA592CA k2aclient: Bei Codierung nicht erwarteter Typ: >%s<"

#: paxes_cinder/k2aclient/v1/shell.py:205
#: paxes_cinder/k2aclient/v1/shell.py:801
#: paxes_cinder/k2aclient/v1/shell.py:812
msgid "Id of the cluster."
msgstr "ID des Clusters."

#: paxes_cinder/k2aclient/v1/shell.py:215
msgid "UUID of the cluster containing the LUs."
msgstr "UUID des Clusters, der die LUs enthält."

#: paxes_cinder/k2aclient/v1/shell.py:218
msgid "UDID of the source logicalunit."
msgstr "UDID der als Quelle angegebenen logischen Einheit."

#: paxes_cinder/k2aclient/v1/shell.py:221
msgid "UDID of the destination logicalunit."
msgstr "UDID der als Ziel angegebenen logischen Einheit."

#: paxes_cinder/k2aclient/v1/shell.py:231
msgid "Id of the managedsystem to list logicalpartitions"
msgstr "ID des verwalteten Systems zum Auflisten der logischen Partitionen"

#: paxes_cinder/k2aclient/v1/shell.py:246
#: paxes_cinder/k2aclient/v1/shell.py:273
#: paxes_cinder/k2aclient/v1/shell.py:295
#: paxes_cinder/k2aclient/v1/shell.py:350
#: paxes_cinder/k2aclient/v1/shell.py:486
#: paxes_cinder/k2aclient/v1/shell.py:658
#: paxes_cinder/k2aclient/v1/shell.py:674
#: paxes_cinder/k2aclient/v1/shell.py:698
#: paxes_cinder/k2aclient/v1/shell.py:714
msgid "Id of the managedsystem."
msgstr "ID des verwalteten Systems."

#: paxes_cinder/k2aclient/v1/shell.py:249
#: paxes_cinder/k2aclient/v1/shell.py:262
#: paxes_cinder/k2aclient/v1/shell.py:617
#: paxes_cinder/k2aclient/v1/shell.py:634
msgid "Id of the logicalpartition."
msgstr "ID der logischen Partition."

#: paxes_cinder/k2aclient/v1/shell.py:276
msgid "UDIDs of the logicalpartition."
msgstr "UDIDs der logischen Partition."

#: paxes_cinder/k2aclient/v1/shell.py:313
#: paxes_cinder/k2aclient/v1/shell.py:324
#: paxes_cinder/k2aclient/v1/shell.py:347
msgid "Id of the managementconsole."
msgstr "ID der Managementkonsole."

#: paxes_cinder/k2aclient/v1/shell.py:327
#: paxes_cinder/k2aclient/v1/shell.py:356
msgid "Command to run."
msgstr "Der auszuführende Befehl."

#: paxes_cinder/k2aclient/v1/shell.py:353
msgid "UUID of the virtualioserver."
msgstr "UUID des virtuellen E/A-Servers."

#: paxes_cinder/k2aclient/v1/shell.py:394
msgid "Id of the sharedstoragepool."
msgstr "ID des gemeinsam genutzten Speicherpools."

#: paxes_cinder/k2aclient/v1/shell.py:405
#: paxes_cinder/k2aclient/v1/shell.py:443
#: paxes_cinder/k2aclient/v1/shell.py:456
msgid "UUID of the sharedstoragepool."
msgstr "UUID des gemeinsam genutzten Speicherpools."

#: paxes_cinder/k2aclient/v1/shell.py:408
msgid "Name of the new logicalunit."
msgstr "Name der neuen logischen Einheit."

#: paxes_cinder/k2aclient/v1/shell.py:411
msgid "Capacity of the new logicalunit."
msgstr "Kapazität der neuen logischen Einheit."

#: paxes_cinder/k2aclient/v1/shell.py:414
msgid "Optional flag to control whether the new logicalunit will be thick or thin"
msgstr ""
"Optionales Flag zum Steuern, ob die neue logische Einheit eine Einheit "
"mit Thick Provisioning oder eine Einheit mit Thin Provisioning sein soll"

#: paxes_cinder/k2aclient/v1/shell.py:419
msgid "LogicalUnitType: VirtualIO_Disk | VirtualIO_Image"
msgstr "Typ der logischen Einheit: VirtualIO_Disk | VirtualIO_Image"

#: paxes_cinder/k2aclient/v1/shell.py:423
msgid "Optional udid of LU to clone from, new if omitted"
msgstr "Optionale UDID der LU, die geklont werden soll. Neu, wenn nicht angegeben"

#: paxes_cinder/k2aclient/v1/shell.py:446
msgid "UDIDs of the logicalunit."
msgstr "UDIDs der logischen Einheit."

#: paxes_cinder/k2aclient/v1/shell.py:459
msgid "Optional flag to control whether full details should be output"
msgstr "Optionales Flag zum Steuern, ob alle Details ausgegeben werden sollen"

#: paxes_cinder/k2aclient/v1/shell.py:471
msgid "Id of the managedsystem to list virtualioservers"
msgstr "ID des verwalteten Systems zum Auflisten der virtuellen E/A-Server"

#: paxes_cinder/k2aclient/v1/shell.py:489
#: paxes_cinder/k2aclient/v1/shell.py:513
msgid "Id of the virtualioserver."
msgstr "ID des virtuellen E/A-Servers."

#: paxes_cinder/k2aclient/v1/shell.py:493
msgid ""
"Optional extended attributes Valid values include: All, Advanced, "
"Hypervisor, SystemNetwork, ViosStorage, ViosNetwork, ViosFCMapping, "
"ViosSCSIMapping, and None May be used multiple times. \"All\" if omitted"
msgstr ""
"Optionale erweiterte Attribute. Gültige Werte: All, Advanced, Hypervisor,"
" SystemNetwork, ViosStorage, ViosNetwork, ViosFCMapping, ViosSCSIMapping "
"und None. Können mehrmals verwendet werden. \"All\", wenn nicht angegeben"

#: paxes_cinder/k2aclient/v1/shell.py:608
msgid "Id of the logicalpartition to list clientnetworkadapters"
msgstr "ID der logischen Partition zum Auflisten der Clientnetzadapter"

#: paxes_cinder/k2aclient/v1/shell.py:620
msgid "Id of the clientnetworkadapter."
msgstr "ID des Clientnetzadapters."

#: paxes_cinder/k2aclient/v1/shell.py:637
msgid "UDIDs of the clientnetworkadapter."
msgstr "UDIDs des Clientnetzadapters."

#: paxes_cinder/k2aclient/v1/shell.py:649
msgid "Id of the managedsystem to list virtualnetworks"
msgstr "ID des verwalteten Systems zum Auflisten der virtuellen Netze"

#: paxes_cinder/k2aclient/v1/shell.py:661
msgid "Id of the virtualnetwork."
msgstr "ID des virtuellen Netzes."

#: paxes_cinder/k2aclient/v1/shell.py:677
msgid "UDIDs of the virtualnetwork."
msgstr "UDIDs des virtuellen Netzes."

#: paxes_cinder/k2aclient/v1/shell.py:689
msgid "Id of the managedsystem to list virtualswitchs"
msgstr "ID des verwalteten Systems zum Auflisten der virtuellen Switches"

#: paxes_cinder/k2aclient/v1/shell.py:701
msgid "Id of the virtualswitch."
msgstr "ID des virtuellen Switch."

#: paxes_cinder/k2aclient/v1/shell.py:717
msgid "UDIDs of the virtualswitch."
msgstr "UDIDs des virtuellen Switch."

#: paxes_cinder/k2aclient/v1/shell.py:740
msgid "Id of the file."
msgstr "ID der Datei."

#: paxes_cinder/k2aclient/v1/shell.py:750
msgid "Ids of the files."
msgstr "IDs der Dateien."

#: paxes_cinder/k2aclient/v1/shell.py:761
msgid "/rest/api/uom<uomresource>."
msgstr "/rest/api/uom<UOM-Ressource>."

#: paxes_cinder/k2aclient/v1/shell.py:766
msgid "Send output to file"
msgstr "Ausgabe senden an Datei"

#: paxes_cinder/k2aclient/v1/shell.py:782
msgid "Read cinder ssp conf files and report on health"
msgstr "Cinder-SSP-Konfigurationsdateien lesen und an Health melden"

#: paxes_cinder/k2aclient/v1/shell.py:815
#: paxes_cinder/k2aclient/v1/shell.py:843
msgid "VIOS password for all VIOS defaults to \"padmin\""
msgstr "Standardkennwort für virtuelle E/A-Server ist \"padmin\"."

#: paxes_cinder/k2aclient/v1/shell.py:820
#: paxes_cinder/k2aclient/v1/shell.py:848
msgid "Target directory for snapsdefaults to \"/tmp/vios-snap\""
msgstr "Standardzielverzeichnis für Momentaufnahmen ist \"/tmp/vios-snap\"."

#: paxes_cinder/k2aclient/v1/shell.py:839
msgid "list of vios ips expressed as jsoneg '[\"9.47.161.157\"]'"
msgstr ""
"Liste der IPs der virtuellen E/A-Server, ausgedrückt als json, z. B. "
"'[\"9.47.161.157\"]'"

#: paxes_cinder/k2aclient/v1/v1k2creater.py:170
#, python-format
msgid "k2aclient: during process_root, unrecognized service: >%s<"
msgstr "NV-1FC12D8 k2aclient: Bei process_root: Nicht erkannter Service: >%s<"

#: paxes_cinder/k2aclient/v1/v1k2loader.py:61
#, python-format
msgid ""
"k2aclient: during k2 deserialization, for type: >%(pcname)s<, k2 gave "
"unknown attr: >%(us_tag)s<, is there a schema mismatch?, will skip ..."
msgstr ""
"NV-A18BFC5 k2aclient: Bei k2-Deserialisierung für Typ >%(pcname)s<: k2 "
"hat das unbekannte Attribut >%(us_tag)s< zurückgegeben. Abweichung im "
"Schema? Wird übersprungen ..."

#: paxes_cinder/k2aclient/v1/v1k2loader.py:77
#, python-format
msgid ""
"k2aclient: during k2 deserialization, for type: >%(pcname)s<, k2 attr: "
">%(us_tag)s<: is listed as scalar, but maybe its not?, is there a schema "
"mismatch?, will replace existing scalar w/ next value ..."
msgstr ""
"k2aclient: Bei k2-Deserialisierung für Typ >%(pcname)s<: k2-Attribut "
">%(us_tag)s< wurde als skalar aufgelistet. Ist es möglicherweise nicht "
"skalar? Abweichung im Schema? Das vorhandene skalare Attribut wird durch "
"den nächsten Wert ersetzt ..."

#: paxes_cinder/k2aclient/v1/v1k2loader.py:131
#, python-format
msgid ""
"k2aclient: during k2 deserialization, while processing: k2 type: "
">%(parent_tag)s<, there is no definition for k2 type: >%(k2type)s<, is "
"there a schema mismatch?, will skip ..."
msgstr ""
"k2aclient: Bei k2-Verarbeitung: Während der Verarbeitung: k2-Typ: "
">%(parent_tag)s<. Es gibt keine Definition für k2-Typ >%(k2type)s<. "
"Abweichung im Schema? Wird übersprungen ..."

#: paxes_cinder/k2aclient/v1/v1k2loader.py:190
#: paxes_cinder/k2aclient/v1/v1k2loader.py:199
msgid "k2aclient:"
msgstr "NV-E561712 k2aclient:"

#: paxes_cinder/k2aclient/v1/virtualioserver_manager.py:280
#, python-format
msgid ""
"k2aclient: during lua_recovery, for device_id: >%(device_id)s<, "
"experienced job failure, job_id: >%(jresponse.job_id)s<, status: "
">%(jresponse.status)s<, input K2 job diagnostics have been written to: "
">%(diagfspeci)s<, response k2 job diagnostics have been written to: "
">%(diagfspec)s<"
msgstr ""
"k2aclient: Bei lua_recovery für device_id >%(device_id)s<: Es ist ein "
"Jobfehler aufgetreten. job_id: >%(jresponse.job_id)s<, Status: "
">%(jresponse.status)s<. Diagnosen für K2-Eingabejobs wurden geschrieben "
"in: >%(diagfspeci)s<. Diagnosen für K2-Antwortjobs wurden geschrieben in:"
" >%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/web_file_manager.py:83
msgid ""
"k2aclient: during file upload, filename: >%(wf.filename)s<, id: "
">%(wf.id)s<, file_uuid: >%(wf.file_uuid)s<, file_enum_type: "
">%(wf.file_enum_type)s<"
msgstr ""
"k2aclient: Beim Hochladen der Datei: Dateiname: >%(wf.filename)s<, ID: "
">%(wf.id)s<, file_uuid: >%(wf.file_uuid)s<, file_enum_type: "
">%(wf.file_enum_type)s<"

#: paxes_cinder/k2aclient/v1/web_job_manager.py:65
#, python-format
msgid ""
"k2aclient: during %(jobtype)s, retry job, job_id: >%(job_id)s<, status: "
">%(status)s<,"
msgstr ""
"NV-FBECCFD k2aclient: Bei %(jobtype)s Job wiederholen, job_id: "
">%(job_id)s<, Status: >%(status)s<,"

#: paxes_cinder/k2aclient/v1/web_job_manager.py:77
#, python-format
msgid ""
"k2aclient: during %(jobtype)s, too many retries, maximum number of "
"retries: >%(maxretries)d<, job_id: >%(job_id)s<, status: >%(status)s<,"
msgstr ""
"k2aclient: Bei %(jobtype)s maximale Anzahl der Wiederholungen "
"überschritten, maximale Anzahl der Wiederholungen: >%(maxretries)d<, "
"job_id: >%(job_id)s<, Status: >%(status)s<,"

#: paxes_cinder/scheduler/host_manager.py:59
#, python-format
msgid "clean up host_state_map: %(host)shost"
msgstr "NV-F9D1534 host_state_map bereinigen: %(host)s-Host"

#: paxes_cinder/scheduler/sched_drv.py:56
#, python-format
msgid "volume request: requested size: %(size)s. "
msgstr "Datenträgeranforderung: Angeforderte Größe: %(size)s. "

#: paxes_cinder/scheduler/sched_drv.py:62
#, python-format
msgid ""
"{host: %(hostname)s, free_capacity: %(free_cap)s, total_capacity: "
"%(total)s, reserved_percentage: %(reserved)s, last update: "
"%(time_updated)s}"
msgstr ""
"{Host: %(hostname)s, free_capacity: %(free_cap)s, total_capacity: "
"%(total)s, reserved_percentage: %(reserved)s, letzte Aktualisierung: "
"%(time_updated)s}"

#: paxes_cinder/scheduler/sched_drv.py:72
msgid "request exceeds capacity: info"
msgstr "NV-DBCC600 Anforderung überschreitet Kapazität: Info"

#: paxes_cinder/scheduler/sched_drv.py:75
msgid "No storage has been registered. "
msgstr "NV-96E101B Es wurde kein Speicher registriert. "

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:67
msgid ""
"Free capacity not set: Volume node is either still under initialization "
"or the node info collection is broken."
msgstr ""
"NV-872554F Freie Kapazität nicht festgelegt: Datenträgerknoten ist "
"entweder noch in der Initialisierung oder die Erfassung der "
"Knoteninformationen ist unterbrochen."

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:99
msgid "missing default_volume_type"
msgstr "NV-404930C Fehlender default_volume_type"

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:106
#, python-format
msgid ""
"missing valid rsize on                                 "
"%(default)svolume_type: %(vol_type)s"
msgstr ""
"NV-B717E15 Fehlende gültige rsize für                                "
"%(default)svolume_type: %(vol_type)s"

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:117
#, python-format
msgid ""
"Insufficient free space for volume creation (requested / avail / rsize): "
"%(requested)s/%(available)s/%(rsize)s"
msgstr ""
"NV-5CC98A1 Nicht ausreichend freier Speicherplatz für "
"Datenträgererstellung (angefordert/verfügbar/rsize): "
"%(requested)s/%(available)s/%(rsize)s"

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:124
#, python-format
msgid ""
"Sufficient free space for volume creation (requested / avail / rsize): "
"%(requested)s/%(available)s/%(rsize)s"
msgstr ""
"NV-D0E32D8 Ausreichend freier Speicherplatz für Datenträgererstellung "
"(angefordert/verfügbar/rsize): %(requested)s/%(available)s/%(rsize)s"

#: paxes_cinder/scohack/scohack_http.py:150
#, python-format
msgid "BadStoreUri: credentials '%(creds)s' not well-formatted."
msgstr ""
"NV-5991AD7 BadStoreUri: Berechtigungsnachweise '%(creds)s' nicht korrekt "
"formatiert."

#: paxes_cinder/scohack/scohack_http.py:160
msgid "BadStoreUri: no address specified in HTTP URL"
msgstr "NV-2A5D3E2 BadStoreUri: Keine Adresse in HTTP-URL angegeben"

#: paxes_cinder/scohack/scohack_http.py:295
#, python-format
msgid "MaxRedirectsExceeded: redirects: >%(max)d<"
msgstr "NV-30617DF MaxRedirectsExceeded: Umleitungen: >%(max)d<"

#: paxes_cinder/scohack/scohack_http.py:308
#, python-format
msgid "HTTP URL returned a %(status)s status code."
msgstr "HTTP-URL hat den Statuscode %(status)s zurückgegeben."

#: paxes_cinder/scohack/scohack_http.py:310
#: paxes_cinder/scohack/scohack_http.py:322
#, python-format
msgid "BadStoreUri: loc.path: >%(path)s<, reason: >%(reason)s<"
msgstr "NV-0E3AB46 BadStoreUri: loc.path: >%(path)s<, Grund: >%(reason)s<"

#: paxes_cinder/scohack/scohack_location.py:50
#, python-format
msgid "exception.UnknownScheme: scheme: >%(scheme)s<"
msgstr "NV-B8DA628 exception.UnknownScheme: Schema: >%(scheme)s<"

#: paxes_cinder/scohack/scohack_scohack.py:77
msgid "URI must start with scohack://"
msgstr "NV-DF4522D URI muss mit scohack:// beginnen"

#: paxes_cinder/scohack/scohack_scohack.py:79
#, python-format
msgid "BadStore: uri: >%(uri)s<, reason: >%(reason)s<"
msgstr "NV-7D2A4E2 BadStore: URI: >%(uri)s<, Grund: >%(reason)s<"

#: paxes_cinder/scohack/scohack_scohack.py:93
#, python-format
msgid "x-scg-vios-id: >%(id)s< not of form 'ttttmmm_sssssssnnn'"
msgstr "NV-9CCE26B x-scg-vios-id: >%(id)s< nicht im Format 'ttttmmm_sssssssnnn'"

#: paxes_cinder/scohack/scohack_scohack.py:106
#, python-format
msgid "scohack: x-scg-vios-id: cant list ManagedSystem: >%(ex)s<"
msgstr ""
"NV-405AA27 scohack: x-scg-vios-id: Verwaltetes System kann nicht "
"aufgelistet werden: >%(ex)s<"

#: paxes_cinder/scohack/scohack_scohack.py:121
#, python-format
msgid "scohack: x-scg-vios-id: cant find ManagedSystem for: >%(id)s<"
msgstr ""
"NV-708F8BE scohack: x-scg-vios-id: Kein verwaltetes System gefunden für: "
">%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:129
#, python-format
msgid "scohack: x-scg-vios-id: cant list VirtualIoServer: >%(ex)s<"
msgstr ""
"NV-2D6AE0A scohack: x-scg-vios-id: Virtueller E/A-Server kann nicht "
"aufgelistet werden: >%(ex)s<"

#: paxes_cinder/scohack/scohack_scohack.py:139
#, python-format
msgid "scohack: x-scg-vios-id: cant find VirtualIOServer for: >%(id)s<"
msgstr ""
"NV-081426D scohack: x-scg-vios-id: Kein virtueller E/A-Server gefunden "
"für: >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:162
msgid "scohack: cant list vios"
msgstr "NV-D40CA86 scohack: VIOS kann nicht aufgelistet werden"

#: paxes_cinder/scohack/scohack_scohack.py:168
msgid "scohack: no vios found"
msgstr "NV-ABFCCCD scohack: Kein VIOS gefunden"

#: paxes_cinder/scohack/scohack_scohack.py:177
#, python-format
msgid "scohack: cant list vios for ms: >%(id)s<"
msgstr ""
"NV-D6ED6BF scohack: VIOS kann nicht aufgelistet werden für verwaltetes "
"System: >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:184
#, python-format
msgid "scohack: no vios found for ms: >%(id)s<"
msgstr "NV-0FD0B8A scohack: Kein VIOS gefunden für verwaltetes System: >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:195
#, python-format
msgid "scohack: for ms: >%(mid)s<, cant find vios: >%(vid)s<"
msgstr ""
"NV-AD83B35 scohack: Für verwaltetes System >%(mid)s< wurde der folgende "
"VIOS nicht gefunden: >%(vid)s<"

#: paxes_cinder/scohack/scohack_scohack.py:204
#, python-format
msgid "scohack: cant find vios: >%(vid)s<"
msgstr "NV-3704F44 scohack: Der folgende VIOS wurde nicht gefunden: >%(vid)s<"

#: paxes_cinder/scohack/scohack_scohack.py:328
#, python-format
msgid ""
"scohack: only single hmc is supported: prev: >%(prev_id)s<, new: "
">%(new_id)s<"
msgstr ""
"NV-185C13E scohack: Nur eine HMC wird unterstützt: bisher: >%(prev_id)s<,"
" neu: >%(new_id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:339
#, python-format
msgid "scohack: no HMC for id: >%(id)s<"
msgstr "NV-628D2F6 scohack: Keine HMC für ID: >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:352
#, python-format
msgid ""
"scohack: managemenconsole: >%(mc)s< could not be retrieved, hdisks will "
"not be cleaned up, msg: >%(msg)s<"
msgstr ""
"scohack: Managementkonsole >%(mc)s< konnte nicht abgerufen werden. "
"Festplatten werden nicht bereinigt. Nachricht: >%(msg)s<"

#: paxes_cinder/scohack/scohack_scohack.py:383
#, python-format
msgid "scohack: vios: >%(vios)s<, volume: >%(vol)s<"
msgstr "NV-22A4C11 scohack: VIOS: >%(vios)s<, Datenträger: >%(vol)s<"

#: paxes_cinder/scohack/scohack_scohack.py:400
#, python-format
msgid "scohack: image upload: hdisk: >%(hdisk)s<, vios: >%(vios)s<"
msgstr ""
"NV-B86BF01 scohack: Image-Upload: HMC-Festplatte: >%(hdisk)s<, VIOS: "
">%(vios)s<"

#: paxes_cinder/scohack/scohack_scohack.py:417
#, python-format
msgid "scohack: volume not found: >%(volume)s<"
msgstr "NV-CDC6DBB scohack: Datenträger nicht gefunden: >%(volume)s<"

#: paxes_cinder/scohack/scohack_scohack.py:428
#, python-format
msgid "scohack: volume: invalid status: >%(status)s<"
msgstr "NV-D365509 scohack: Datenträger: Ungültiger Status: >%(status)s<"

#: paxes_cinder/scohack/scohack_scohack.py:445
#, python-format
msgid "scohack: no ports for vios: >%(vios)s<"
msgstr "NV-230F42F scohack: Keine Ports für VIOS: >%(vios)s<"

#: paxes_cinder/scohack/scohack_scohack.py:461
#, python-format
msgid "scohack: failed to connect to volume >%(volume_id)s< "
msgstr ""
"NV-E7095A2 scohack: Verbindung zu Datenträger >%(volume_id)s< konnte "
"nicht hergestellt werden "

#: paxes_cinder/scohack/scohack_scohack.py:471
#, python-format
msgid ""
"scohack: for target volume: >%(volume)s<, bad connection: >%(info)s<, no "
"target_lun"
msgstr ""
"NV-79C5617 scohack: Für Zieldatenträger >%(volume)s<: Fehlerhafte "
"Verbindung: >%(info)s<, keine target_lun"

#: paxes_cinder/scohack/scohack_scohack.py:487
#, python-format
msgid ""
"scohack: for target volume: >%(volume)s<, no target wwpn found in "
"connection: >%(info)s< "
msgstr ""
"NV-5C2B384 scohack: Für Zieldatenträger >%(volume)s<: Kein Ziel-WWPN "
"gefunden in Verbindung: >%(info)s< "

#: paxes_cinder/scohack/scohack_scohack.py:506
#, python-format
msgid "scohack: target volume: >%(volume)s<, does not have page83 data"
msgstr ""
"NV-33E8084 scohack: Zieldatenträger >%(volume)s< enthält keine "
"page83-Daten"

#: paxes_cinder/scohack/scohack_scohack.py:514
#, python-format
msgid "scohack: start luarecovery: deviceid: >%(id)s< , itls: >%(itls)s<"
msgstr ""
"NV-0A59DDD scohack: Start lua_recovery: Einheiten-ID: >%(id)s<, ITLS: "
">%(itls)s<"

#: paxes_cinder/scohack/scohack_scohack.py:525
#, python-format
msgid "scohack: lua_recovery job failed for target volume: >%(volume)s<"
msgstr ""
"NV-D94C9A2 scohack: lua_recovery-Job fehlgeschlagen für Zieldatenträger: "
">%(volume)s<"

#: paxes_cinder/scohack/scohack_scohack.py:538
#, python-format
msgid "scohack: luarcovery job status: >%(status)s<, result: >%(res)s<"
msgstr ""
"NV-FC7E239 scohack: Status des lua_recovery-Jobs: >%(status)s<. Ergebnis:"
" >%(res)s<"

#: paxes_cinder/scohack/scohack_scohack.py:544
#, python-format
msgid ""
"scohack: lua_recovery job internal error, device_list is invalid device "
"list: >%(lua_list)s<"
msgstr ""
"NV-610160F scohack: Interner Fehler in lua_recovery-Job. Ungültige "
"Einheitenliste in device_list: >%(lua_list)s<"

#: paxes_cinder/scohack/scohack_scohack.py:552
#, python-format
msgid ""
"scohack: lua_recovery job returned multiple devices device list: "
">%(lua_list)s<, will select first ..."
msgstr ""
"NV-3A4481D scohack: lua_recovery-Job hat Einheitenliste mit mehreren "
"Einheiten zurückgegeben: >%(lua_list)s<. Ausgewählt wird die erste "
"Einheit ..."

#: paxes_cinder/scohack/scohack_scohack.py:562
#, python-format
msgid ""
"This means that a device was found from an ITL nexus and it was "
"determined to be in use by the VIOS. The most likely cause is that a "
"virtual device was not removed from a previous deploy. The VIOS took no "
"action in this case. device: >%(dev)s<"
msgstr ""
"Das bedeutet, dass eine Einheit aus einem ITL-Nexus gefunden wurde und "
"festgestellt wurde, das sie durch den VIOS verwendet wird. Die "
"wahrscheinlichste Ursache dafür ist, dass eine virtuelle Einheit nicht "
"aus einer vorherigen Implementierung entfernt wurde. In diesem Fall hat "
"der VIOS keine Aktion ausgeführt. Einheit: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:572
#, python-format
msgid ""
"This means that the ITL nexus is not consider reliable and some error "
"occurred that prevents the VIOS from determining making a decision on "
"safely removing a device. The VIOS took no action in this case. Perhaps "
"try to remove the offending hdisk from the VIOS, with rmdev -d -l hdiskx."
" device: >%(dev)s<"
msgstr ""
"NV-DC7D321 Das bedeutet, dass der ITL-Nexus nicht als zuverlässig "
"eingestuft wurde und ein Fehler aufgetreten ist, der verhindert, dass der"
" VIOS eine Entscheidung zum sicheren Entfernen einer Einheit treffen "
"kann. In diesem Fall hat der VIOS keine Aktion ausgeführt. Sie könnten "
"versuchen, mit 'rmdev -d -l hdiskx' die problematische Festplatte zu "
"entfernen. Einheit: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:585
#, python-format
msgid ""
"This means the information provided and action taken by the VIOS was "
"sufficient to find the storage. pvName, and uniqueID elements will follow"
" in the data stream. device: >%(dev)s<"
msgstr ""
"NV-8DB8D33 Das bedeutet, die angegebenen Informationen und die Aktion des"
" VIOS haben nicht ausgereicht, um den Speicher zu finden. Die Elemente "
"pvName und uniqueID werden dann im Datenstream mit angegeben. Einheit: "
">%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:593
#, python-format
msgid ""
"This means some new storage element was found at the ITL nexus but VIOS "
"could not determine if it is the storage of interest to the management "
"tool. device: >%(dev)s<"
msgstr ""
"NV-36ADD00 Das bedeutet, im ITL-Nexus wurde ein neues Speicherelement "
"gefunden, bei dem der VIOS nicht feststellen konnte, ob es der vom "
"Management-Tool gewünschte Speicher ist. Einheit: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:602
#, python-format
msgid ""
"The VIOS could not determine if this is logical unit of interest to the "
"management tool however did find a device from the ITL nexus list. "
"device: >%(dev)s<"
msgstr ""
"NV-6761BFF Der VIOS konnte nicht feststellen, ob dies die vom Management-"
"Tool gewünschte logische Einheit ist, und hat auch keine Einheit in der "
"ITL-Nexus-Liste gefunden. Einheit: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:611
#, python-format
msgid ""
"The VIOS could not find a device from the itl nexus list. It could be "
"some SCSI or transport error occurred during configuration or the ITL "
"nexus list was incorrect. device: >%(dev)s<"
msgstr ""
"NV-2479600 Der VIOS hat keine Einheit in der ITL-Nexus-Liste gefunden. "
"Möglicherweise ist ein SCSI- oder Transportfehler während der "
"Konfiguration aufgetreten oder die ITL-Nexus-Liste war falsch. Einheit: "
">%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:622
#, python-format
msgid ""
"Unknown device status. Severe internal error contact NCO. device: "
">%(dev)s<"
msgstr ""
"NV-2EF1D11 Unbekannter Einheitenstatus. Schwerwiegender interner Fehler. "
"Wenden Sie sich an NCO. Einheit: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:638
#, python-format
msgid "scohack: failed to find device name: >%(dev)s<"
msgstr ""
"NV-B6E8402 scohack: Der folgende Einheitenname wurde nicht gefunden: "
">%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:643
#, python-format
msgid "scohack: found device name: >%(dev)s<"
msgstr "NV-32CF4C2 scohack: Gefunden wurde der Einheitenname: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:665
#, python-format
msgid "scohack: hdisk_uuid: >%(hdisk)s<, checksum not specified"
msgstr "NV-D85ABDC scohack: hdisk_uuid: >%(hdisk)s<. Kontrollsumme nicht angegeben"

#: paxes_cinder/scohack/scohack_scohack.py:672
#, python-format
msgid "scohack: hdisk_uuid: >%(hdisk)s<, size not specified"
msgstr "NV-9783CB3 scohack: hdisk_uuid: >%(hdisk)s<. Größe nicht angegeben"

#: paxes_cinder/scohack/scohack_scohack.py:694
#, python-format
msgid ""
"scohack: image upload complete for hdisk_uuid: >%(hdisk)s<, webfile id: "
">%(wid)s<, actual size: >%(size)s< bytes, elapsed time: >%(time)d< "
"seconds, rate: >%(rate)f< minutes/GB"
msgstr ""
"scohack: Image-Upload abgeschlossen für hdisk_uuid: >%(hdisk)s<, "
"Webdatei-ID: >%(wid)s<, tatsächliche Größe: >%(size)s< Byte, abgelaufene "
"Zeit: >%(time)d< Sekunden, Rate: >%(rate)f< Minuten/GB"

#: paxes_cinder/scohack/scohack_scohack.py:709
#, python-format
msgid ""
"scohack:  mismatch: expected_file_size_in_bytes: >%e_size)d<, "
"current_file_size_in_bytes: >%(c_size)d<"
msgstr ""
"NV-E2ACA08 scohack: Keine Übereinstimmung: expected_file_size_in_bytes: "
">%e_size)d<, current_file_size_in_bytes: >%(c_size)d<"

#: paxes_cinder/scohack/scohack_scohack.py:740
#, python-format
msgid ""
"scohack: cleanup failure for: >%(hdisk)s<, job status: >%(status)s<, "
"response: >%(res)s< continuing ..."
msgstr ""
"NV-C9A426B scohack: Bereinigungsfehler für: >%(hdisk)s<, Jobstatus: "
">%(status)s<, Antwort: >%(res)s<. Vorgang wird fortgesetzt ..."

#: paxes_cinder/scohack/scohack_scohack.py:752
#, python-format
msgid ""
"scohack: for hdisk_uuid: >%(hdisk)s<  no managementconsole, hisks will "
"not be cleaned up"
msgstr ""
"NV-508BE83 scohack: Für hdisk_uuid: >%(hdisk)s<. Keine Managementkonsole."
" Festplatten werden nicht bereinigt"

#: paxes_cinder/scohack/scohack_scohack.py:758
#: paxes_cinder/scohack/scohack_scohack.py:768
#, python-format
msgid "scohack: for hdisk_uuid: >%(hdisk)s< cleanup failed, msg: >%(ex)s<"
msgstr ""
"NV-B37BCB5 scohack: Für hdisk_uuid: >%(hdisk)s<. Bereinigung "
"fehlgeschlagen. Nachricht: >%(ex)s<"

#: paxes_cinder/scohack/scohack_scohack.py:772
#, python-format
msgid "scohack: upload failed for hdisk_uuid: >%(dsk)s<"
msgstr "NV-D7A600C scohack: Upload fehlgeschlagen für hdisk_uuid: >%(dsk)s<"

#: paxes_cinder/scohack/scohack_utils.py:47
#, python-format
msgid "Error: cooperative_iter exception %(error)s"
msgstr "NV-23E8986 Fehler: cooperative_iter Ausnahmebedingung %(error)s"

#: paxes_cinder/volume/__init__.py:46
#, python-format
msgid ""
"cinder volume_create interface has been changed. PowerVC monkey patch for"
" volume clone won't work. function: %(fx)s, arguments: %(args)s"
msgstr ""
"NV-7A6F9A4 Cinder-Schnittstelle volume_create wurde geändert. PowerVC-"
"Monkey-Patch für Datenträgerklon funktioniert nicht. Funktion: %(fx)s, "
"Argumente: %(args)s"

#: paxes_cinder/volume/__init__.py:61
#, python-format
msgid ""
"Monkey patched volume clone by paxes volume_create_decorator(). Source "
"Volume ID: %(svol)s, volume type name: %(voltpnm)s, volume type ID: "
"%(voltpid)s"
msgstr ""
"NV-D17192A Datenträgerklon durch paxes volume_create_decorator() mit "
"Monkey-Patch erstellt. Quellendatenträger-ID: %(svol)s, "
"Datenträgertypname: %(voltpnm)s, Datenträgertyp-ID: %(voltpid)s"

#: paxes_cinder/volume/__init__.py:94
#, python-format
msgid ""
"Failed to get the parameters from function "
"cinder.volume.volume_types.create(). Default quota didn't set for the "
"storage template. Error: %(err)s"
msgstr ""
"NV-A4934EA Fehler beim Abrufen der Parameter von Funktion "
"cinder.volume.volume_types.create(). Standardquote für die "
"Speichervorlage wurde nicht festgelegt. Fehler: %(err)s"

#: paxes_cinder/volume/__init__.py:114
#, python-format
msgid "Successfully set default quota for storage template %(vol_type)s"
msgstr ""
"NV-71868FF Standardquote für Speichervorlage %(vol_type)s erfolgreich "
"festgelegt"

#: paxes_cinder/volume/__init__.py:118
#, python-format
msgid ""
"Failed to set default quota for storage template %(vol_type)s, error: "
"%(err)s"
msgstr ""
"NV-D86E5F7 Fehler beim Festlegen der Standardquote für Speichervorlage "
"%(vol_type)s. Fehler: %(err)s"

#: paxes_cinder/volume/__init__.py:122
#, python-format
msgid ""
"Cannot set default quota for storage template %(vol_type) due to invalid "
"Parameters from volume type create."
msgstr ""
"NV-D9BA448 Standardquote für Speichervorlage %(vol_type) kann wegen "
"ungültiger Parameter aus volume_types.create() nicht festgelegt werden."

#: paxes_cinder/volume/__init__.py:175
#, python-format
msgid "Error getting data volumes: %s "
msgstr "NV-7627301 Fehler beim Abrufen der Datenträger: %s "

#: paxes_cinder/volume/manager.py:89
#, python-format
msgid "Cannot perform direct SAN operation on disk with prefix %(prefix)s"
msgstr ""
"NV-1701BDD SAN-Umleitungsoperation kann für Platte mit Präfix %(prefix)s "
"nicht ausgeführt werden"

#: paxes_cinder/volume/manager.py:100
msgid "Driver still initializing, wait..."
msgstr "NV-C6CA9E0 Treiber wird noch initialisiert, bitte warten..."

#: paxes_cinder/volume/manager.py:102
#, python-format
msgid "Try again: %s"
msgstr "NV-FEE7BD0 Versuchen Sie es noch einmal: %s"

#: paxes_cinder/volume/manager.py:172
#, python-format
msgid "Fabric {fabric_name} ({user}@{ip}:{port}): %(message)s"
msgstr "NV-0A01336 Fabric {fabric_name} ({user}@{ip}:{port}): %(message)s"

#: paxes_cinder/volume/manager.py:188
#, python-format
msgid ""
"Storage Provider {storage_provider_hostname} ({user}@{ip}:{port}) "
"{volume_id}: %(message)s"
msgstr ""
"NV-E1A972C Speicheranbieter {storage_provider_hostname} "
"({Benutzer}@{IP}:{Port}) {volume_id}: %(message)s"

#: paxes_cinder/volume/manager.py:223
msgid ""
"The volume is already attached to another virtual server, possibly one "
"that is not managed by PowerVC."
msgstr ""
"Der Datenträger wurde bereits einem anderen virtuellen Server zugeordnet,"
" der möglicherweise nicht durch PowerVC verwaltet wird."

#: paxes_cinder/volume/manager.py:227
msgid ""
"The volume cannot be deleted because it is either mapped to a host or "
"part of a flashcopy or remote copy operation."
msgstr ""
"Der Datenträger kann nicht gelöscht werden, da er entweder einem Host "
"zugeordnet wurde oder Teil einer FlashCopy- oder Remote Copy-Operation "
"ist."

#: paxes_cinder/volume/manager.py:239
#, python-format
msgid "%(error_prefix)s failure for volume {volume_id}: %(error)s"
msgstr "%(error_prefix)s Fehler für Datenträger {volume_id}: %(error)s"

#: paxes_cinder/volume/manager.py:244
#, python-format
msgid ""
"%(error_prefix)s failure for volume {volume_id}.Command %(cmd)s, error "
"%(error)s"
msgstr ""
"%(error_prefix)s Fehler für Datenträger {volume_id}. Befehl %(cmd)s, "
"Fehler %(error)s"

#: paxes_cinder/volume/manager.py:393
#, python-format
msgid "Resuming deletion of volume %s"
msgstr "NV-E253654 Wiederaufnehmen der Löschung von Datenträger %s"

#: paxes_cinder/volume/manager.py:396
#, python-format
msgid ""
"Failed to delete volume %(volid)s during volume service startup. Error: "
"%(error)s"
msgstr ""
"NV-CCA27AC Datenträger %(volid)s konnte beim Start des Volume Service "
"nicht gelöscht werden. Fehler: %(error)s"

#: paxes_cinder/volume/manager.py:410
#, python-format
msgid "Processing volume that was left in the attaching state. Volume id: %(id)s"
msgstr ""
"NV-89FC9B0 Verarbeiten des noch zugeordneten Datenträgers. Datenträger-"
"ID: %(id)s"

#: paxes_cinder/volume/manager.py:483
#, python-format
msgid ""
"_volume_attach_rollback: Volume %(id)s is missing restricted metadata to "
"recover the attaching state."
msgstr ""
"NV-C8F1D06 _volume_attach_rollback: Datenträger %(id)s enthält nicht die "
"eingeschränkten Metadaten zum Wiederherstellen der Zuordnung."

#: paxes_cinder/volume/manager.py:487
#, python-format
msgid ""
"_volume_attach_rollback: No attach operation  to rollback for volume "
"%(id)s"
msgstr ""
"NV-77AEEA1 _volume_attach_rollback: Keine rückgängig zu machende "
"Zuordnungsoperation für Datenträger %(id)s"

#: paxes_cinder/volume/manager.py:493
#, python-format
msgid ""
"_volume_attach_rollback: Invalid connector %(conn)s in volume %(id)s "
"restrict metadata. Rollback without termination"
msgstr ""
"NV-4096184 _volume_attach_rollback: Ungültiger Connector %(conn)s in "
"Metadaten von Datenträger %(id)s. Rollback ohne Beendigung"

#: paxes_cinder/volume/manager.py:498
#, python-format
msgid "_volume_attach_rollback: Roll back attaching state for volume %(id)s."
msgstr ""
"NV-1EB0444 _volume_attach_rollback: Zuordnung rückgängig machen für "
"Datenträger %(id)s."

#: paxes_cinder/volume/manager.py:518
#, python-format
msgid ""
"_volume_attach_rollback: Finished. Volume %(id)s has rolled back to "
"available state."
msgstr ""
"NV-1E08B26 _volume_attach_rollback: Fertig. Datenträger %(id)s ist nach "
"Rollback wieder verfügbar."

#: paxes_cinder/volume/manager.py:600
#, python-format
msgid ""
"The volume detach didn't finish successfully before cinder service was "
"restarted. volume id: %(id)s"
msgstr ""
"NV-333B81A Das Aufheben der Zuordnung des Datenträgers konnte nicht "
"erfolgreich abgeschlossen werden, bevor der Cinder-Service erneut "
"gestartet wurde. Datenträger-ID: %(id)s"

#: paxes_cinder/volume/manager.py:633
msgid "Unable to initialize host, driver is uninitialized"
msgstr ""
"NV-7F33CBC Host konnte nicht initialisiert werden. Treiber wurde nicht "
"initialisiert"

#: paxes_cinder/volume/manager.py:650
msgid "update default quota class..."
msgstr "NV-392B903 Standardquotenklasse aktualisieren..."

#: paxes_cinder/volume/manager.py:652
msgid "Post init_host processing and update volume status."
msgstr ""
"NV-6EC3032 Verarbeitung nach init_host und Datenträgerstatus "
"aktualisieren."

#: paxes_cinder/volume/manager.py:656
#, python-format
msgid "Error happened during post init_host volume processing. Error: %s"
msgstr "NV-B263BC8 Fehler bei Datenträgerverarbeitung nach init_host. Fehler: %s"

#: paxes_cinder/volume/manager.py:660
#, python-format
msgid "Rollback volume still attaching during init_host: %d volumes"
msgstr ""
"NV-BDEAFA8 Datenträger für Rollback-Operation bei init_host noch "
"zugeordnet: %d Datenträger"

#: paxes_cinder/volume/manager.py:665
#, python-format
msgid "Resume volume deletion during init_host: %d volumes"
msgstr ""
"NV-6BC64FF Löschung des Datenträgers bei init_host wiederaufnehmen: %d "
"Datenträger"

#: paxes_cinder/volume/manager.py:719
msgid "Caught Exception Refreshing Driver Status "
msgstr "Abgefangene Ausnahmebedingung beim Aktualisieren des Treiberstatus "

#: paxes_cinder/volume/manager.py:755
msgid "Caught Exception trying to update Storage Node in DB"
msgstr ""
"NV-36093B5 Abgefangene Ausnahmebedingung beim Aktualisieren des "
"Speicherknotens in DB"

#: paxes_cinder/volume/manager.py:793
msgid "Unable to retrieve Default Volume Type"
msgstr "NV-544BC4C Fehler beim Abrufen des Standarddatenträgertyps"

#: paxes_cinder/volume/manager.py:850
#, python-format
msgid "volume %s: removing export"
msgstr "NV-BAF02FC Datenträger %s: Entfernen des Exports"

#: paxes_cinder/volume/manager.py:852
#, python-format
msgid "volume %s: deleting"
msgstr "NV-4F406DE Datenträger %s: Löschen"

#: paxes_cinder/volume/manager.py:855
#, python-format
msgid "volume %s: volume is busy"
msgstr "NV-3431BA6 Datenträger %s: Datenträger ist ausgelastet"

#: paxes_cinder/volume/manager.py:858
#, python-format
msgid "Fail to remove_export or delete_volume: %sname"
msgstr "NV-E98201D Fehler bei remove_export oder delete_volume: %sname"

#: paxes_cinder/volume/manager.py:862
#, python-format
msgid "Volume %s: deletion failed with exception "
msgstr "NV-137591B Datenträger %s: Löschung fehlgeschlagen mit Ausnahmebedingung "

#: paxes_cinder/volume/manager.py:954
#, python-format
msgid ""
"failed checking whether                              volume %(vol_id)s "
"backs an image, metadata=%(mdata)s"
msgstr ""
"NV-BE4D3EE Fehler beim Überprüfen, ob                              "
"Datenträger %(vol_id)s ein Image sichert. Metadaten=%(mdata)s"

#: paxes_cinder/volume/manager.py:991
#, python-format
msgid ""
"volume %(volid)s has unfinished attach transaction. Rolling back before "
"deleting the volume."
msgstr ""
"NV-331CBBA Für Datenträger %(volid)s gibt es eine nicht abgeschlossene "
"Zuordnungstransaktion. Vor dem Löschen des Datenträgers wird Rollback "
"durchgeführt."

#: paxes_cinder/volume/manager.py:1035
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to extend volume by %(s_size)sG, "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""
"NV-521C07E Quote für %(s_pid)s überschritten. Es wurde versucht, den "
"Datenträger um %(s_size)s G zu erweitern (%(d_consumed)d G von "
"%(d_quota)d G bereits verbraucht)"

#: paxes_cinder/volume/manager.py:1091
#, python-format
msgid ""
"The host %(hostid)s for boot volume %(volid)s  does not support extend "
"volume."
msgstr ""
"NV-37CDE0F Der Host %(hostid)s für Bootdatenträger %(volid)s unterstützt "
"das Erweitern von Datenträgern nicht."

#: paxes_cinder/volume/manager.py:1145
#, python-format
msgid "Start attach transaction for volume %(id)s."
msgstr "NV-1CBB13C Zuordnungstransaktion für Datenträger %(id)s starten."

#: paxes_cinder/volume/manager.py:1175
#, python-format
msgid "Driver returned %s"
msgstr "NV-B695526 Rückgabe Treiber: %s"

#: paxes_cinder/volume/manager.py:1208
#, python-format
msgid "Successfully attached the volume %(id)s. Clean up transaction."
msgstr ""
"NV-F606087 Der Datenträger %(id)s wurde erfolgreich zugeordnet. "
"Bereinigungstransaktion."

#: paxes_cinder/volume/drivers/paxes_san.py:162
#, python-format
msgid "Waiting %(seconds)d seconds before next attempt..."
msgstr "NV-0553DA5 Vor dem nächsten Versuch wird %(seconds)d Sekunden gewartet..."

#: paxes_cinder/volume/drivers/paxes_san.py:182
#, python-format
msgid "Error running SSH command: %s"
msgstr "NV-052C0AB Fehler beim Ausführen des SSH-Befehls: %s"

#: paxes_cinder/volume/drivers/emc/emc_common_product.py:35
msgid "Updating volume status"
msgstr "NV-A56DF8D Aktualisieren des Datenträgerstatus"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:89
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1374
msgid "protocol must be specified as '<in> iSCSI' or '<in> FC'"
msgstr "Protokoll muss angegeben werden als '<in> iSCSI' oder '<in> FC'"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:123
msgid "Entering create_volume."
msgstr "NV-4C5AEEB Eintreten: create_volume."

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:127
#, python-format
msgid "Create Volume: %(volume)s  Size: %(size)lu"
msgstr "NV-403E8FC Datenträger erstellen: %(volume)s, Größe: %(size)lu"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:157
#, python-format
msgid ""
"Unsupported element_type value %(element_type)s.  Specify a supported "
"element_type value and resubmit the request."
msgstr ""
"NV-AC11F99 Nicht unterstützter Wert %(element_type)s für element_type. "
"Geben Sie einen unterstützten Wert für element_type an und wiederholen "
"Sie die Anforderung."

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:164
#, python-format
msgid "Create Volume: %(volume)s  Storage type: %(storage_type)s"
msgstr ""
"NV-4E4E2BB Datenträger erstellen: %(volume)s, Speichertyp: "
"%(storage_type)s"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:171
#, python-format
msgid ""
"Create Volume: %(volume)s  Pool: %(pool)s,  Element Type: "
"%(element_type)s, Storage System: %(storage_system)s"
msgstr ""
"NV-723484A Datenträger erstellen: %(volume)s, Pool: %(pool)s, Elementtyp:"
" %(element_type)s, Speichersystem: %(storage_system)s"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:182
#, python-format
msgid ""
"Error Create Volume: %(volumename)s. Storage Configuration Service not "
"found for pool %(storage_type)s."
msgstr ""
"NV-0EFA73A Fehler beim Erstellen des Datenträgers %(volumename)s. "
"Speicherkonfigurationsservice für Pool %(storage_type)s nicht gefunden."

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:190
#, python-format
msgid ""
"Create Volume: %(name)s  Method: CreateOrModifyElementFromStoragePool  "
"ConfigServicie: %(service)s  ElementName: %(name)s  InPool: %(pool)s  "
"ElementType: %(element_type)s  Size: %(size)lu"
msgstr ""
"NV-6E312B4 Datenträger erstellen: %(name)s, Methode: "
"CreateOrModifyElementFromStoragePool, Konfigurationsservice: %(service)s,"
" Elementname: %(name)s, in Pool: %(pool)s, Elementtyp: %(element_type)s, "
"Größe: %(size)lu"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:206
#, python-format
msgid "Create Volume: %(volumename)s  Return code: %(rc)lu"
msgstr "NV-0214C49 Datenträger erstellen: %(volumename)s, Rückgabecode: %(rc)lu"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:213
#, python-format
msgid ""
"Error Create Volume: %(volumename)s.  Return code: %(rc)lu.  Error: "
"%(error)s"
msgstr ""
"NV-227D3AC Fehler beim Erstellen des Datenträgers %(volumename)s. "
"Rückgabecode: %(rc)lu. Fehler: %(error)s"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:220
#, python-format
msgid "Leaving create_volume: %(volumename)s  Return code: %(rc)lu"
msgstr "NV-C5C5CCC Verlassen: create_volume: %(volumename)s. Rückgabecode: %(rc)lu"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:235
#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:259
msgid "Could not establish ecom connection"
msgstr "NV-930992B ECOM-Verbindung konnte nicht hergestellt werden"

#: paxes_cinder/volume/drivers/ssp/ssp.py:177
#, python-format
msgid "ssp:  no matching HMC was found in the DB for host: >%s<"
msgstr ""
"NV-BFBE123 ssp: Keine übereinstimmende Hardware Management Console in der"
" Datenbank gefunden für Host: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:248
#, python-format
msgid "ssp: during create default volume type, DB error: >%s<"
msgstr ""
"NV-FA1BBE8 ssp: Beim Erstellen des Standarddatenträgertyps "
"Datenbankfehler: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:279
#, python-format
msgid ""
"ssp: during _create_lu for LU: (name: >%(name)s<, size: >%(size)s<, thin:"
" >%(thin)s<), ssp_udid: >%(ssp_udid)s< is not same as extra_spec "
"shared_storage_pool: >%(extra_spec_ssp_id)s<"
msgstr ""
"SSP: Bei _create_lu für LU: (Name: >%(name)s<, Größe: >%(size)s<, Thin: "
">%(thin)s<). ssp_udid: >%(ssp_udid)s< ist nicht identisch mit extra_spec "
"shared_storage_pool: >%(extra_spec_ssp_id)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:299
#, python-format
msgid ""
"ssp: failed during _create_lu for LU: (name: >%(name)s<, size: "
">%(size)s<, thin: >%(thin)s<), message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Fehler bei _create_lu für LU: (Name: >%(name)s<, Größe: >%(size)s<, "
"Thin: >%(thin)s<), Nachricht: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:329
#, python-format
msgid ""
"ssp: during _create_lu job for LU: (name: >%(name)s<, size: >%(size)s<, "
"thin: >%(thin)s<), ssp_udid: >%(ssp_udid)s< is not same as extra_spec "
"shared_storage_pool: >%(extra_spec_ssp_id)s<"
msgstr ""
"SSP: Bei _create_lu-Job für LU: (Name: >%(name)s<, Größe: >%(size)s<, "
"Thin: >%(thin)s<). ssp_udid: >%(ssp_udid)s< ist nicht identisch mit "
"extra_spec shared_storage_pool: >%(extra_spec_ssp_id)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:351
#, python-format
msgid ""
"ssp: failure during _create_lu, create parameters: name: >%(name)s<, "
"size: >%(size)s<, thin: >%(thin)s<, logicalunittype: "
">%(logicalunittype)s<, message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Fehler bei _create_lu. Erstellungsparameter: Name: >%(name)s<, "
"Größe: >%(size)s<, Thin: >%(thin)s<, Typ der logischen Einheit: "
">%(logicalunittype)s<. Nachricht: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:366
#, python-format
msgid ""
"ssp: failure during _create_lu job, expecting COMPLETED_OK, but for "
"job_id: >%(job_id)s< got status: >%(status)s< create parameters: name: "
">%(name)s<, size: >%(size)s<, thin: >%(thin)s<, logicalunittype: "
">%(logicalunittype)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-76A9409 SSP: Fehler bei _create_lu-Job. Erwartet wurde COMPLETED_OK, "
"aber für job_id >%(job_id)s< Status >%(status)s< erhalten. "
"Erstellungsparameter: Name: >%(name)s<, Größe: >%(size)s<, Thin: "
">%(thin)s<, Typ der logischen Einheit: >%(logicalunittype)s<, k2xa: "
">%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:382
#, python-format
msgid ""
"ssp: create complete, job_id: >%(job_id)s<, name: >%(name)s<, size: "
">%(size)s<, thin: >%(thin)s<, logicalunittype: >%(logicalunittype)s<, "
"k2xa: >%(k2xa)s<"
msgstr ""
"NV-9FEEE64 SSP: Erstellung beendet. job_id: >%(job_id)s<, Name: "
">%(name)s<, Größe: >%(size)s<, Thin: >%(thin)s<, Typ der logischen "
"Einheit: >%(logicalunittype)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:416
#, python-format
msgid ""
"ssp: failed during _delete_lu of LU w/ with unique_device_id: "
">%(lu_udid)s<,  message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Fehler bei _delete_lu von LU mit unique_device_id: >%(lu_udid)s<. "
"Nachricht: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:431
#, python-format
msgid ""
"ssp: during _clone_lu_by_name, couldnt find lu with src_lu_name: "
">%(src_lu_name)s<, tgt_lu_name: >%(tgt_lu_name)s<"
msgstr ""
"SSP: Bei _clone_lu_by_name: Keine LU gefunden mit src_lu_name: "
">%(src_lu_name)s<, tgt_lu_name: >%(tgt_lu_name)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:439
#, python-format
msgid ""
"ssp: during _clone_lu_by_name, found too many lus with src_lu_name: "
">%(src_lu_name)s<, tgt_lu_name: >%(tgt_lu_name)s<"
msgstr ""
"NV-8FDE368 SSP: Bei _clone_lu_by_name: Zu viele LUs gefunden mit "
"src_lu_name: >%(src_lu_name)s<, tgt_lu_name: >%(tgt_lu_name)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:469
#, python-format
msgid ""
"ssp: failure during _clone_lu_bj, clone parameters: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s< msg: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Fehler bei _clone_lu_bj. Klonparameter: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s<, tgt_lu_size: "
">%(tgt_lu_size)s< Nachricht: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:485
#: paxes_cinder/volume/drivers/ssp/ssp.py:547
#, python-format
msgid ""
"ssp: apparent failure during _clone_lu_bj, expecting COMPLETED_OK, but "
"for job_id: >%(job_id)s< got status: >%(status)s< clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-64234D9 SSP: Scheinbarer Fehler bei _clone_lu_bj. Erwartet wurde "
"COMPLETED_OK, aber für job_id >%(job_id)s< Status >%(status)s< erhalten. "
"Klonparameter: src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: "
">%(tgt_lu_name)s< tgt_lu_unit_size: >%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:509
#, python-format
msgid ""
"ssp: failure during _clone_lu_bj, during create, clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s< message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Fehler bei _clone_lu_bj beim Erstellen. Klonparameter: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s<, tgt_lu_size: "
">%(tgt_lu_size)s< Nachricht: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:530
#, python-format
msgid ""
"ssp: failure during _clone_lu_bj, during clone, clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s< message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Fehler bei _clone_lu_bj beim Klonen. Klonparameter: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s<, tgt_lu_size: "
">%(tgt_lu_size)s< Nachricht: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:576
#, python-format
msgid ""
"ssp: failure during _clone_lu_bp, clone parameters: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s< message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Fehler bei _clone_lu_bp. Klonparameter: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s<, tgt_lu_size: "
">%(tgt_lu_size)s< Nachricht: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:591
#, python-format
msgid ""
"ssp: apparent failure during _clone_lu_bp, expecting COMPLETED_OK, but "
"for job_id: >%(job_id)s< got status: >%(status)s< clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-21DAFDD SSP: Scheinbarer Fehler bei _clone_lu_bp. Erwartet wurde "
"COMPLETED_OK, aber für job_id >%(job_id)s< Status >%(status)s< erhalten. "
"Klonparameter: src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: "
">%(tgt_lu_name)s< tgt_lu_unit_size: >%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:606
#, python-format
msgid ""
"ssp: clone complete, job_id: >%(job_id)s<, src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-330DF39 SSP: Klonen beendet. job_id: >%(job_id)s<, src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s<, tgt_lu_size: "
">%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:625
msgid "ssp: driver not yet initialized"
msgstr "NV-767C35B SSP: Treiber noch nicht initialisiert"

#: paxes_cinder/volume/drivers/ssp/ssp.py:634
#, python-format
msgid ""
"K2 GET SharedStoragePool time: >%(delta)f< is bigger or equal to "
"update_stats periodic interval: >%(periodic_interval)d<"
msgstr ""
"NV-BB646A1 Zeit des gemeinsam genutzten K2-GET-Speicherpools: >%(delta)f<"
" ist größer oder gleich dem Intervall zur periodischen Aktualisierung der"
" Statistiken: >%(periodic_interval)d<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:641
#, python-format
msgid ""
"ssp: during get_volume_stats, failed to refresh shared storage pool with "
"ssp_id: >%(self._ssp.id)s<, message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Bei get_volume_stats: Fehler beim Aktualisieren des gemeinsam "
"genutzten Speicherpools mit ssp_id: >%(self._ssp.id)s<, Nachricht: "
">%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:680
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, while performing vios cluster check, "
"failed to refresh cluster id: >%(self._cluster.id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-AC40CF2 SSP: Bei %(duringwhatstage)s: Beim Durchführen der VIOS-"
"Clusterprüfung konnte folgende Cluster-ID nicht aktualisiert werden: "
">%(self._cluster.id)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:707
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, for vios id: >%(vios.id)s<, "
"OperatingSystemVersion: >%(os_version)s<"
msgstr ""
"SSP: Bei %(duringwhatstage)s für VIOS-ID: >%(vios.id)s<, "
"Betriebssystemversion: >%(os_version)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:719
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, vios id: >%(vios.id)s<, running and "
"active"
msgstr ""
"SSP: Bei %(duringwhatstage)s: VIOS-ID >%(vios.id)s< wird ausgeführt und "
"ist aktiv"

#: paxes_cinder/volume/drivers/ssp/ssp.py:727
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, for cluster id: >%(self._cluster.id)s<, "
"vios state issue, vios id: >%(vios.id)s<: PartitionState: "
">%(vios.partition_state)s< ResourceMonitoringControlState: "
">%(vios.rmc_state)s<, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Bei %(duringwhatstage)s für Cluster-ID >%(self._cluster.id)s<: "
"Problem bei VIOS-Status. VIOS-ID: >%(vios.id)s<, Partitionsstatus: "
">%(vios.partition_state)s<, Ressourcenüberwachungssteuerstatus: "
">%(vios.rmc_state)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:751
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, could not find restricted metadata for "
"volume id: >%(volume_id)s<"
msgstr ""
"SSP: Bei %(duringwhatstage)s: Eingeschränkte Metadaten für Datenträger-ID"
" >%(volume_id)s< nicht gefunden"

#: paxes_cinder/volume/drivers/ssp/ssp.py:767
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, failed to refresh shared storage pool "
"with ssp_id: >%(self._ssp.id)s<, message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Bei %(duringwhatstage)s: Fehler beim Aktualisieren des gemeinsam "
"genutzten Speicherpools mit ssp_id: >%(self._ssp.id)s<, Nachricht: "
">%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:780
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, couldnt find lu for volume_id: "
">%(volume_id)s< with: unique_device_id: >%(lu_udid)s< and unit_name: "
">%(lu_name)s<"
msgstr ""
"SSP: Bei %(duringwhatstage)s: LU für volume_id >%(volume_id)s< mit "
"unique_device_id >%(lu_udid)s< und unit_name >%(lu_name)s< nicht "
"gefunden."

#: paxes_cinder/volume/drivers/ssp/ssp.py:791
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, found too many lus for volume_id: "
">%(volume_id)s< with: unique_device_id: >%(lu_udid)s< and unit_name: "
">%(lu_name)s<"
msgstr ""
"NV-338EFD0 SSP: Bei %(duringwhatstage)s: Zu viele LUs für volume_id "
">%(volume_id)s< mit unique_device_id >%(lu_udid)s< und unit_name "
">%(lu_name)s< gefunden."

#: paxes_cinder/volume/drivers/ssp/ssp.py:805
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:342
msgid "enter: do_setup"
msgstr "NV-9097266 Eintreten: do_setup"

#: paxes_cinder/volume/drivers/ssp/ssp.py:825
msgid "ssp: failure during do_setup, cant find hmc."
msgstr "NV-AE8B2E2 SSP: Fehler bei do_setup. HMC nicht gefunden."

#: paxes_cinder/volume/drivers/ssp/ssp.py:853
#, python-format
msgid ""
"ssp: during do_setup, failed to obtain k2client, k2_url: >%(k2_url)s<, "
"k2_username: >%(k2_username)s<"
msgstr ""
"SSP: Bei do_setup: Fehler beim Abrufen des k2client mit k2_url: "
">%(k2_url)s<, k2_username: >%(k2_username)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:866
#, python-format
msgid ""
"ssp: during do_setup, using hmc_uuid: >%(hmc_uuid)s<, failed to retrieve "
"managementconsole, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Bei do_setup mit hmc_uuid >%(hmc_uuid)s<: Fehler beim Abrufen der "
"Managementkonsole, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:875
#, python-format
msgid "ssp: during do_setup, hmc version: >%s<"
msgstr "NV-3F31730 SSP: Bei do_setup: HMC-Version: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:885
#, python-format
msgid ""
"ssp: during do_setup, using k2_url: >%(k2_url)s<, failed to retrieve "
"cluster, cluster_id: >%(cluster_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Bei do_setup mit k2_url >%(k2_url)s<: Fehler beim Abrufen des "
"Clusters mit cluster_id: >%(cluster_id)s, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:904
#, python-format
msgid ""
"ssp: during do_setup, using k2_url: >%(k2_url)s< and cluster_id: "
">%(cluster_id)s< failed to retrieve shared storage pool with ssp_ip: "
">%(ssp_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Bei do_setup mit k2_url >%(k2_url)s< und cluster_id "
">%(cluster_id)s<: Fehler beim Abrufen des gemeinsam genutzten "
"Speicherpools mit ssp_ip: >%(ssp_id)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:923
#, python-format
msgid "ssp: during do_setup, creating default volume type: >%s<"
msgstr "NV-379E7B0 SSP: Bei do_setup: Erstellen des Standarddatenträgertyps: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:928
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:487
msgid "leave: do_setup"
msgstr "NV-F492AE8 Verlassen: do_setup"

#: paxes_cinder/volume/drivers/ssp/ssp.py:931
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:580
msgid "leave: check_for_setup_error"
msgstr "NV-1C79D46 Verlassen: check_for_setup_error"

#: paxes_cinder/volume/drivers/ssp/ssp.py:981
#: paxes_cinder/volume/drivers/ssp/ssp.py:1009
#: paxes_cinder/volume/drivers/ssp/ssp.py:1050
#: paxes_cinder/volume/drivers/ssp/ssp.py:1149
#: paxes_cinder/volume/drivers/ssp/ssp_product.py:48
#: paxes_cinder/volume/drivers/ssp/ssp_product.py:73
#: paxes_cinder/volume/drivers/ssp/ssp_product.py:145
#, python-format
msgid "ssp: exception: >%s<"
msgstr "NV-31FED69 SSP: Ausnahmebedingung: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:982
msgid "ssp: failed during create_volume"
msgstr "NV-E4EE3DB SSP: Fehlgeschlagen bei create_volume"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1010
#, python-format
msgid ""
"ssp: failed during delete_volume, lu_udid: >%(lu_udid)s< lu_name: "
">%(lu_name)s< volume id: >%(volume_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-41060EC SSP: Fehler bei delete_volume: lu_udid: >%(lu_udid)s<, "
"lu_name: >%(lu_name)s<, Datenträger-ID: >%(volume_id)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1029
#, python-format
msgid "ssp: during create_snapshot, cant find volume_id: >%s<"
msgstr ""
"NV-FDA9D85 SSP: Bei create_snapshot: Folgende volume_id nicht gefunden: "
">%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1051
#, python-format
msgid ""
"ssp: failure during create_snapshot: lu_udid: >%(src_lu_udid)s< lu_name: "
">%(src_lu_name)s< volume id: >%(source_vol_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-ACF24A1 SSP: Fehler bei create_snapshot: lu_udid: >%(src_lu_udid)s<, "
"lu_name: >%(src_lu_name)s<, Datenträger-ID: >%(source_vol_id)s<, k2xa: "
">%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1070
#, python-format
msgid "ssp: during delete_snapshot, couldnt find lu with unit_name: >%s<"
msgstr "NV-FCB5EA8 SSP: Bei delete_snapshot: LU mit unit_name >%s< nicht gefunden."

#: paxes_cinder/volume/drivers/ssp/ssp.py:1077
#, python-format
msgid "ssp: during delete_snapshot, found too many lus with unit_name: >%s<"
msgstr ""
"NV-66B083E SSP: Bei delete_snapshot: Zu viele LUs mit unit_name >%s< "
"gefunden."

#: paxes_cinder/volume/drivers/ssp/ssp.py:1105
#, python-format
msgid ""
"ssp: error during create_volume_from_snapshot: snapshot with name: "
">%(snapshot_name)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-F6CFF00 SSP: Fehler bei create_volume_from_snapshot: Momentaufnahme "
"mit Name: >%(snapshot_name)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1150
#, python-format
msgid ""
"ssp:  error during create_cloned_volume: src_lu_udid: >%(src_lu_udid)s< "
"src_lu_name: >%(src_lu_name)s< volume id: >%(src_volume_id)s<, k2xa: "
">%(k2xa)s<"
msgstr ""
"NV-24854A9 SSP: Fehler bei create_cloned_volume: src_lu_udid: "
">%(src_lu_udid)s<, src_lu_name: >%(src_lu_name)s<, Datenträger-ID: "
">%(src_volume_id)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1211
#, python-format
msgid "stats = %(stats)s"
msgstr "NV-898A2AA Statistiken = %(stats)s"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:49
#, python-format
msgid ""
"ssp: while discovering mapped LUs, failed to refresh cluster with "
"cluster_id: >%(self._cluster.id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-347194B SSP: Bei Erkennung zugeordneter LUs: Fehler beim Aktualisieren"
" von Cluster mit folgender cluster_id: >%(self._cluster.id)s<, k2xa: "
">%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:59
#, python-format
msgid "Node >%s< has no virtual_io_server. Skipping."
msgstr ""
"NV-C3FDDFD Knoten >%s< enthält keinen virtual_io_server. Wird "
"übersprungen."

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:74
#, python-format
msgid ""
"ssp: while discovering mapped LUs, in cluster with cluster_id: "
">%(self._cluster.id)s< failed to retrieve vios with managedsystem_id: "
">%(ms_id)s< and virtualioserver_id: >%(vios_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-F12DD40 SSP: Beim Erkennen zugeordneter LUs: In Cluster mit "
"cluster_id: >%(self._cluster.id)s< konnte VIOS mit managedsystem_id "
">%(ms_id)s< und virtualioserver_id >%(vios_id)s< nicht abgerufen werden, "
"k2xa >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:115
msgid ""
"No volume statistics available, either driver has not been initialized or"
" there is a problem w/ the driver, check cinder logs."
msgstr ""
"NV-A8A5D70 Keine Datenträgerstatistik verfügbar. Entweder wurde der "
"Treiber nicht initialisiert oder es besteht ein Problem mit dem Treiber. "
"Prüfen Sie die Cinder-Protokolle."

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:146
#, python-format
msgid ""
"ssp: while discovering volumes, failed to refresh shared storage pool "
"with ssp_id: >%(self._ssp.id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-7BF09DB SSP: Bei Erkennung von Datenträgern: Fehler beim Aktualisieren"
" des gemeinsam genutzten Speicherpools mit ssp_id: >%(self._ssp.id)s<, "
"k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:173
msgid ""
"This volume is not a candidate for management because it is already "
"attached to a virtual machine.  To manage this volume with PowerVC, you "
"must bring the virtual machine under management.  Select to manage the "
"virtual machine that has the volume attached.  The attached volume will "
"be automatically included for management."
msgstr ""
"Dieser Datenträger kommt nicht für die Verwaltung infrage, weil er "
"bereits einer virtuellen Maschine zugeordnet ist. Zum Verwalten dieses "
"Datenträgers mit PowerVC muss die virtuelle Maschine mit dem zugeordneten"
" Datenträger zur Verwaltung ausgewählt werden. Der zugeordnete "
"Datenträger wird dann automatisch in die Verwaltung einbezogen."

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:184
#, python-format
msgid ""
"ssp: during Logical Unit discovery, ssp_id: >%(ssp_id)s<, "
"lu_unique_device_id: >%(lu_unique_device_id)s<, lu_unit_name: "
">%(lu_unit_name)s<, volume is in use and not available for management, "
"k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Bei der LU-Erkennung: ssp_id: >%(ssp_id)s<, lu_unique_device_id: "
">%(lu_unique_device_id)s<, lu_unit_name: >%(lu_unit_name)s<: Datenträger "
"wird verwendet und ist nicht zur Verwaltung verfügbar. k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:200
msgid ""
"Because it is of type VirtualIO_Image, this volume is not a candidate for"
" management. Perhaps, while deleting a PowerVC image, someone chose not "
"to delete the backing storage? If you wish to work with the underlying "
"Shared Storage Pool Logical Unit please use the HMC or VIOS commands."
msgstr ""
"Da dieser Datenträger den Typ VirtualIO_Image hat, kommt er nicht zur "
"Verwaltung infrage. Vielleicht wurde beim Löschen eines PowerVC-Images "
"der Sicherungsspeicher nicht gelöscht? Wenn Sie mit der LU des gemeinsam "
"genutzten Speicherpools arbeiten wollen, verwenden Sie die HMC- oder "
"VIOS-Befehle."

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:210
#, python-format
msgid ""
"ssp: during Logical Unit discovery, ssp_id: >%(ssp_id)s<, "
"lu_unique_device_id: >%(lu_unique_device_id)s<, lu_unit_name: "
">%(lu_unit_name)s<, volume is of type VirtualIO_Image and not available  "
"for management, k2xa: >%(k2xa)s<"
msgstr ""
"SSP: Bei der LU-Erkennung: ssp_id: >%(ssp_id)s<, lu_unique_device_id: "
">%(lu_unique_device_id)s<, lu_unit_name: >%(lu_unit_name)s<: Datenträger "
"hat den Typ VirtualIO_Image und ist nicht zur Verwaltung verfügbar. k2xa:"
" >%(k2xa)s<"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:240
#, python-format
msgid "WWPN on node %(node)s: %(wwpn)s"
msgstr "NV-D154765 WWPN für Knoten %(node)s: %(wwpn)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:299
#, python-format
msgid "Required keys %(required)s not found in vdisk dictionary %(dictionary)r"
msgstr ""
"Erforderliche Schlüssel %(required)s in Festplattenverzeichnis "
"%(dictionary)r nicht gefunden"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:349
msgid "do_setup: Could not get system name"
msgstr "NV-5732B20 do_setup: Fehler beim Abrufen des Systemnamens"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:361
#, python-format
msgid "do_setup: Pool %s does not exist"
msgstr "NV-1B3A18D do_setup: Pool %s ist nicht vorhanden"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:412
#, python-format
msgid ""
"Expected integers for node_count and vdisk_count, svcinfo lsiogrp "
"returned: %(node)s and %(vdisk)s"
msgstr ""
"NV-D7E5D72 Erwartet wurden ganzzahlige Werte für node_count und "
"vdisk_count. Rückgabe von svcinfo lsiogrp: %(node)s und %(vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:475
msgid "do_setup: No configured nodes"
msgstr "do_setup: Keine konfigurierten Knoten"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:484
#, python-format
msgid "Creating default volume type '%s'"
msgstr "NV-5FF13AA Erstellen des Standarddatenträgertyps '%s'"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:541
msgid "enter: check_for_setup_error"
msgstr "Eintreten: check_for_setup_error"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:545
msgid "Unable to determine system name"
msgstr "NV-82D9304 Systemname konnte nicht bestimmt werden"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:548
msgid "Unable to determine system id"
msgstr "NV-3C12EE7 System-ID konnte nicht bestimmt werden"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:551
msgid "Unable to determine pool extent size"
msgstr "NV-D455E3E Poolspeicherbereichsgröße konnte nicht bestimmt werden"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:558
#, python-format
msgid "%s is not set"
msgstr "NV-6919A40 %s wurde nicht festgelegt"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:564
msgid ""
"Password or SSH private key is required for authentication: set either "
"san_password or san_private_key option"
msgstr ""
"NV-6FE00A0 Kennwort oder privater SSH-Schlüssel ist für Authentifizierung"
" erforderlich: Entweder Option san_password oder Option san_private_key "
"festlegen"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:572
#, python-format
msgid ""
"Illegal value %d specified for storwize_svc_flashcopy_timeout: valid "
"values are between 0 and 600"
msgstr ""
"NV-F2E38D9 Unzulässiger Wert %d für storwize_svc_flashcopy_timeout "
"angegeben: Gültige Werte liegen zwischen 0 und 600"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:594
#, python-format
msgid "ensure_export: Volume %(volume_id)s does not reference a vdisk"
msgstr ""
"NV-EF2904A ensure_export: Datenträger %(volume_id)s referenziert keine "
"virtuelle Platte"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:601
#, python-format
msgid ""
"ensure_export: Volume %(volume_id)s references vdisk %(vdisk)s, which was"
" not found on storage"
msgstr ""
"NV-C3410C4 ensure_export: Datenträger %(volume_id)s referenziert "
"virtuelle Platte %(vdisk)s, die im Speicher nicht gefunden wurde"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:627
#, python-format
msgid "enter: _get_chap_secret_for_host: host name %s"
msgstr "Eintreten: _get_chap_secret_for_host: Hostname %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:663
#, python-format
msgid ""
"leave: _get_chap_secret_for_host: host name %(host_name)s with secret "
"%(chap_secret)s"
msgstr ""
"Verlassen: _get_chap_secret_for_host: Hostname %(host_name)s mit geheimem"
" Schlüssel %(chap_secret)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:686
msgid "_create_host: Cannot clean host name. Host name is not unicode or string"
msgstr ""
"NV-ED84213 _create_host: Hostname kann nicht gelöscht werden. Hostname "
"ist weder Unicode noch Zeichenfolge"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:837
#, python-format
msgid "enter: _get_host_from_connector: prefix %s"
msgstr "Eintreten: _get_host_from_connector: Präfix %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:865
#, python-format
msgid ""
"Continue to fall back processing after initial failure to make a host on "
"the SAN controller: %s"
msgstr ""
"NV-41DBBAB Verarbeitung nach ursprünglichem Fehler weiter zurücksetzen, "
"um einen Host auf folgendem SAN-Controller zu erstellen: %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:909
#, python-format
msgid "leave: _get_host_from_connector: host %s"
msgstr "Verlassen: _get_host_from_connector: Host %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:921
#, python-format
msgid "enter: _create_host: host %s"
msgstr "Eintreten: _create_host: Host %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:936
msgid "_create_host: No connector ports"
msgstr "_create_host: Keine Connector-Ports"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:969
#, python-format
msgid "leave: _create_host: host %(host)s - %(host_name)s"
msgstr "Verlassen: _create_host: Host %(host)s - %(host_name)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:992
#, python-format
msgid "enter: _map_vol_to_host: vdisk %(vdisk_id)s to host %(host_name)s"
msgstr ""
"Eintreten: _map_vol_to_host: Virtuelle Platte %(vdisk_id)s zu Host "
"%(host_name)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1022
msgid ""
"storwize_svc_multihostmap_enabled is set to False, Not allow multi host "
"mapping"
msgstr ""
"NV-ABB7D85 storwize_svc_multihostmap_enabled wurde auf False festgelegt. "
"Zuordnung mehrerer Hosts nicht zulässig"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1034
#, python-format
msgid "vdisk %s mapping to multi host"
msgstr "NV-45393AC Zuordnung der virtuellen Platte %s zu mehreren Hosts"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1040
#, python-format
msgid ""
"leave: _map_vol_to_host: LUN %(result_lun)s, vdisk %(vdisk_id)s, host "
"%(host_name)s"
msgstr ""
"Verlassen: _map_vol_to_host: LUN %(result_lun)s, virtuelle Platte "
"%(vdisk_id)s, Host %(host_name)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1050
#, python-format
msgid "enter: _delete_host: host %s "
msgstr "Eintreten: _delete_host: Host %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1058
#, python-format
msgid "leave: _delete_host: host %s "
msgstr "Verlassen: _delete_host: Host %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1084
#, python-format
msgid ""
"The connector does not contain the required information: %(connector)s, "
"protocols %(protos)s"
msgstr ""
"NV-6A00D73 Der Connector enthält nicht die erforderlichen Informationen: "
"%(connector)s, Protokolle %(protos)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1105
#, python-format
msgid "Enter: initialize_connection: %s"
msgstr "NV-4DB79BA Eintreten: initialize_connection: %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1128
#, python-format
msgid "Did not find expected column name in lsvdisk: %s"
msgstr "NV-5EFF8EA Erwarteter Spaltenname in lsvdisk nicht gefunden: %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1130
#, python-format
msgid "initialize_connection: Missing volume attribute for vdisk %s"
msgstr ""
"NV-4FE8A8D initialize_connection: Fehlendes Datenträgerattribut für "
"virtuelle Platte %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1142
msgid "_create_host failed to return the host name."
msgstr "_create_host hat den Hostnamen nicht zurückgegeben."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1164
#, python-format
msgid ""
"initialize_connection: No node found in I/O group %(gid)s for vdisk "
"%(vdisk_id)s"
msgstr ""
"NV-8182517 initialize_connection: Kein Knoten in E/A-Gruppe %(gid)s für "
"virtuelle Platte %(vdisk_id)s gefunden"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1173
#, python-format
msgid "initialize_connection: Did not find a preferred node for vdisk %s"
msgstr ""
"NV-1DB16EC initialize_connection: Kein bevorzugter Knoten für virtuelle "
"Platte %s gefunden"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1195
msgid ""
"Could not get FC connection information for the host-volume connection. "
"Is the host configured properly for FC connections?"
msgstr ""
"NV-D8556EE Fehler beim Abrufen der FC-Verbindungsinformationen für die "
"Verbindung zwischen Host und Datenträger. Ist der Host ordnungsgemäß für "
"FC-Verbindungen konfiguriert?"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1210
#, python-format
msgid ""
"initialize_connection: Failed to collect return properties for volume "
"%(vol)s and connector %(conn)s.\n"
msgstr ""
"NV-0A9D0F9 initialize_connection: Fehler beim Erfassen der "
"Rückgabeeigenschaften für Datenträger %(vol)s und Connector %(conn)s.\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1215
#, python-format
msgid ""
"leave: initialize_connection:\n"
" volume: %(vol)s\n"
" connector %(conn)s\n"
" properties: %(prop)s"
msgstr ""
"Verlassen: initialize_connection:\n"
" Datenträger: %(vol)s\n"
" Connector %(conn)s\n"
" Eigenschaften: %(prop)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1233
#, python-format
msgid "enter: terminate_connection: volume %(vol)s with connector %(conn)s"
msgstr ""
"Eintreten: terminate_connection: Datenträger %(vol)s mit Connector "
"%(conn)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1246
#, python-format
msgid ""
"terminate_connection: vdisk mismatch: %(err)s. Performing no operation on"
" the storage controller"
msgstr ""
"NV-78DEE4C terminate_connection: Keine Übereinstimmung bei virtueller "
"Platte: %(err)s. Keine Operation auf Speichercontroller"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1252
#, python-format
msgid ""
"terminate_connection: vdisk deleted: %(err)s. Performing no operation on "
"the storage controller"
msgstr ""
"NV-0E7CDF3 terminate_connection: Virtuelle Platte gelöscht: %(err)s. "
"Keine Operation auf Speichercontroller"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1265
#, python-format
msgid "Detach volume: failed to lookup host name for vdisk ID: %(vdisk)s"
msgstr ""
"NV-5D2DC5C Aufheben der Zuordnung eines Datenträgers: Fehler beim Suchen "
"des Hostnamens für VDisk-ID: %(vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1291
#, python-format
msgid ""
"There was an error when attempting to remove the host disk mappings for "
"volume ID %(vol)s and vdsik ID %(vdisk)s: %(err)s"
msgstr ""
"NV-07BAF93 Beim Versuch, die Hostdatenträgerzuordnungen für Datenträger-"
"ID %(vol)s und VDisk-ID %(vdisk)s zu entfernen, ist ein Fehler "
"aufgetreten: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1303
#, python-format
msgid ""
"terminate_connection: No mapping of vdisk %(vdisk_id)s to host "
"%(host_name)s found"
msgstr ""
"NV-0CD2F25 terminate_connection: Keine Zuordnung der virtuellen Platte "
"%(vdisk_id)s zu Host %(host_name)s gefunden"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1314
#, python-format
msgid "leave: terminate_connection: volume %(vol)s with connector %(conn)s"
msgstr ""
"Verlassen: terminate_connection: Datenträger %(vol)s mit Connector "
"%(conn)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1414
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:118
#, python-format
msgid "enter: _create_vdisk: candidate names %s "
msgstr "NV-2D6FE98 Eintreten: _create_vdisk: Mögliche Namen %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1470
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:218
#, python-format
msgid ""
"_create_vdisk %(name)s - did not find success message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"_create_vdisk %(name)s - Nachricht über erfolgreiche Ausführung in CLI-"
"Ausgabe nicht gefunden.\n"
" Standardausgabe: %(out)s\n"
" Standard-Fehlerausgabe: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1477
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:225
#, python-format
msgid "leave: _create_vdisk: volume %(name)s ID %(id)s "
msgstr "NV-3A4E903 Verlassen: _create_vdisk: Datenträger %(name)s, ID %(id)s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1499
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1513
#, python-format
msgid ""
"create FC mapping from %(source)s to %(target)s - did not find success "
"message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"
msgstr ""
"FC-Zuordnung von %(source)s zu %(target)s erstellen - Nachricht über "
"erfolgreiche Ausführung in CLI-Ausgabe nicht gefunden.\n"
" Standardausgabe: %(out)s\n"
" Standard-Fehlerausgabe: %(err)s\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1525
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1535
#, python-format
msgid ""
"create FC mapping from %(source)s to %(target)s - did not find mapping id"
" in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"
msgstr ""
"FC-Zuordnung von %(source)s zu %(target)s erstellen - Zuordnungs-ID in "
"CLI-Ausgabe nicht gefunden.\n"
" Standardausgabe: %(out)s\n"
" Standard-Fehlerausgabe: %(err)s\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1550
#, python-format
msgid ""
"_prepare_fc_map: Failed to prepare FlashCopy from %(source)s to "
"%(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"NV-AD077CD _prepare_fc_map: Fehler beim Vorbereiten von FlashCopy von "
"%(source)s zu %(target)s.\n"
"Standardausgabe: %(out)s\n"
" Standard-Fehlerausgabe: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1578
#, python-format
msgid ""
"Unexecpted mapping status %(status)s for mapping %(id)s. Attributes: "
"%(attr)s"
msgstr ""
"Nicht erwarteter Zuordnungsstatus %(status)s für Zuordnung %(id)s. "
"Attribute: %(attr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1590
#, python-format
msgid ""
"Mapping %(id)s prepare failed to complete within the allotted %(to)d "
"seconds timeout. Terminating."
msgstr ""
"NV-46B21B5 Die Vorbereitung der Zuordnung %(id)s wurde nicht im "
"zugeteilten Zeitlimit von %(to)d Sekunden abgeschlossen. Der Vorgang wird"
" beendet."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1595
#, python-format
msgid ""
"_prepare_fc_map: Failed to start FlashCopy from %(source)s to %(target)s "
"with exception %(ex)s"
msgstr ""
"NV-B48FD34 _prepare_fc_map: Fehler beim Starten von FlashCopy von "
"%(source)s zu %(target)s mit Ausnahmebedingung %(ex)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1602
#, python-format
msgid "_prepare_fc_map: %s"
msgstr "NV-956CB6C _prepare_fc_map: %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1609
#, python-format
msgid ""
"_start_fc_map: Failed to start FlashCopy from %(source)s to %(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"NV-FCBE987 _start_fc_map: Fehler beim Starten von FlashCopy von "
"%(source)s zu %(target)s.\n"
"Standardausgabe: %(out)s\n"
" Standard-Fehlerausgabe: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1620
#, python-format
msgid ""
"enter: _run_flashcopy: execute FlashCopy from source %(source)s to target"
" %(target)s"
msgstr ""
"Eintreten: _run_flashcopy: Ausführen von FlashCopy von Quelle %(source)s "
"zu Ziel %(target)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1633
#, python-format
msgid "leave: _run_flashcopy: FlashCopy started from %(source)s to %(target)s"
msgstr ""
"Verlassen: _run_flashcopy: FlashCopy von %(source)s zu %(target)s "
"gestartet"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1642
#, python-format
msgid ""
"enter: _create_copy: snapshot with possible names %(names)s from vdisk "
"%(src_vdisk)s"
msgstr ""
"Eintreten: _create_copy: Momentaufnahme mit möglichen Namen %(names)s von"
" virtueller Platte %(src_vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1650
#, python-format
msgid "_create_copy: Source vdisk %s does not exist"
msgstr ""
"NV-8A48F71 _create_copy: Als Quelle angegebene virtuelle Platte %s ist "
"nicht vorhanden"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1662
#, python-format
msgid ""
"_create_copy: cannot get source vdisk %(src)s capacity from vdisk "
"attributes %(attr)s"
msgstr ""
"_create_copy: Kapazität der als Quelle angegebenen virtuellen Platte "
"%(src)s kann aus Attributen %(attr)s der virtuellen Platte nicht "
"abgerufen werden"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1681
#, python-format
msgid "leave: _create_copy: snapshot vdisk %(tgt_vdisk)s from vdisk %(src_vdisk)s"
msgstr ""
"Verlassen: _create_copy: Momentaufnahme auf virtueller Platte "
"%(tgt_vdisk)s von virtueller Platte %(src_vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1688
#, python-format
msgid "enter: _get_flashcopy_mapping_attributes: mapping %s"
msgstr "Eintreten: _get_flashcopy_mapping_attributes: Zuordnung %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1711
#, python-format
msgid ""
"leave: _get_flashcopy_mapping_attributes: mapping %(fc_map_id)s, "
"attributes %(attributes)s"
msgstr ""
"Verlassen: _get_flashcopy_mapping_attributes: Zuordnung %(fc_map_id)s, "
"Attribute %(attributes)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1719
#, python-format
msgid "enter: _is_vdisk_defined: vdisk %s "
msgstr "Eintreten: _is_vdisk_defined: Virtuelle Platte %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1721
#, python-format
msgid "leave: _is_vdisk_defined: vdisk %(vdisk)s with %(str)s "
msgstr "Verlassen: _is_vdisk_defined: Virtuelle Platte %(vdisk)s mit %(str)s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1764
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1228
#, python-format
msgid "%(map_id)s [vdisk %(src)s to vdisk %(tgt)s]"
msgstr "%(map_id)s [virtuelle Platte %(src)s zu virtueller Platte %(tgt)s]"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1777
#, python-format
msgid ""
"To delete vdisk %(vdisk_id)s, increasing copyrate of flashcopy mapping "
"%(map)s from 0 to %(copyrate)s and waiting for completion."
msgstr ""
"NV-0B06E40 Um die virtuelle Platte %(vdisk_id)s zu löschen, wird die "
"Kopiergeschwindigkeit der FlashCopy-Zuordnung %(map)s von 0 auf "
"%(copyrate)s erhöht und auf Fertigstellung gewartet."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1791
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1261
#, python-format
msgid "Vdisk %(id)s not involved in mapping %(src)s -> %(tgt)s"
msgstr "Virtuelle Platte %(id)s nicht in Zuordnung %(src)s -> %(tgt)s enthalten"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1798
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1268
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, flashcopy mapping %(map)s with "
"status '%(status)s' was removed."
msgstr ""
"NV-4CA8ED6 Um die Löschung der virtuellen Platte %(vdisk_id)s zu "
"ermöglichen, wurde die FlashCopy-Zuordnung %(map)s mit dem Status "
"'%(status)s' entfernt."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1806
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1276
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, waiting for flashcopy mapping "
"%(map)s with status '%(status)s' to complete."
msgstr ""
"NV-E66FA4E Um die Löschung der virtuellen Platte %(vdisk_id)s zu "
"ermöglichen, wird auf die Fertigstellung der FlashCopy-Zuordnung %(map)s "
"mit dem Status '%(status)s' gewartet."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1816
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1286
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, forcing removal of flashcopy "
"mapping %(map)s with status '%(status)s'"
msgstr ""
"NV-824284E Um die Löschung der virtuellen Platte %(vdisk_id)s zu "
"ermöglichen, wird die Entfernung der FlashCopy-Zuordnung %(map)s mit dem "
"Status '%(status)s' erzwungen."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1827
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1300
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, prepared flashcopy mapping "
"%(map)s was removed."
msgstr ""
"NV-211FA49 Um die Löschung der virtuellen Platte %(vdisk_id)s zu "
"ermöglichen, wurde die vorbereitete FlashCopy-Zuordnung %(map)s entfernt."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1835
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1310
#, python-format
msgid ""
"To delete vdisk %(vdisk_id)s, flashcopy mapping %(map)s with status "
"'idle_or_copied' was removed."
msgstr ""
"NV-DA08F03 Um die virtuelle Platte %(vdisk_id)s zu löschen, wurde die "
"FlashCopy-Zuordnung %(map)s mit dem Status 'idle_or_copied' entfernt."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1841
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1318
#, python-format
msgid ""
"To delete vdisk %(vdisk_id)s, waiting for completion of flashcopy mapping"
" %(map)s, which is currently %(progress)s%% complete and has status "
"'%(status)s'."
msgstr ""
"NV-CE3069A Um die virtuelle Platte %(vdisk_id)s zu löschen, wird auf die "
"Fertigstellung der FlashCopy-Zuordnung %(map)s, die aktuell zu "
"%(progress)s%% fertig gestellt ist und den Status '%(status)s' hat, "
"gewartet."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1881
msgid ""
"Flashcopy mapping copy rate is 0. Copy is not in progress. Return to "
"caller."
msgstr ""
"NV-45B5480 Die Kopiergeschwindigkeit der FlashCopy-Zuordnung ist 0. Der "
"Kopiervorgang ist nicht in Bearbeitung. Zurück zum aufrufenden Programm."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1944
#, python-format
msgid "enter: _delete_vdisk: vdisk %s"
msgstr "Eintreten: _delete_vdisk: Virtuelle Platte %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1949
#, python-format
msgid "warning: Tried to delete vdisk %s but it does not exist."
msgstr ""
"NV-E47B663 Warnung: Es wurde versucht, die nicht vorhandene virtuelle "
"Platte %s zu löschen."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1955
#, python-format
msgid "Removing vdisk %(vdisk_id)s"
msgstr "NV-E18AA05 Entfernen der virtuellen Platte %(vdisk_id)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1968
#, python-format
msgid ""
"Hosts mapped to vdisk %(vdisk)s:\n"
"%(out)s"
msgstr ""
"NV-4159ED7 Hosts zugeordnet zu virtueller Platte %(vdisk)s:\n"
"%(out)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1974
#, python-format
msgid ""
"Existing FlashCopy mappings:\n"
"%(out)s"
msgstr ""
"NV-A345C87 Vorhandene FlashCopy-Zuordnungen:\n"
"%(out)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1982
#, python-format
msgid "leave: _delete_vdisk: vdisk %s"
msgstr "Verlassen: _delete_vdisk: Virtuelle Platte %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1992
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2086
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2135
#, python-format
msgid "adding volume_type_id to volume=%s"
msgstr "NV-86F0410 Hinzufügen der volume_type_id zu Datenträger=%s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2014
#, python-format
msgid ""
"Starting deletion of volume %(volume_id)s.  There is no associated vdisk,"
" so no operation will be performed on the storage controller."
msgstr ""
"NV-04391FA Starten der Löschung des Datenträgers %(volume_id)s. Da keine "
"zugeordnete virtuelle Platte vorhanden ist, wird keine Operation auf dem "
"Speichercontroller ausgeführt."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2020
#, python-format
msgid "Starting deletion of volume %(volume_id)s, backed by vdisk %(vdisk_id)s"
msgstr ""
"NV-0C0C004 Starten der Löschung des Datenträgers %(volume_id)s, gesichert"
" durch virtuelle Platte %(vdisk_id)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2032
#, python-format
msgid ""
"delete_volume: vdisk mismatch: %(err)s. Performing no operation on the "
"storage controller"
msgstr ""
"NV-D258084 delete_volume: Keine Übereinstimmung bei virtueller Platte: "
"%(err)s. Keine Operation auf Speichercontroller"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2038
#, python-format
msgid ""
"delete_volume: vdisk deleted: %(err)s. Performing no operation on the "
"storage controller"
msgstr ""
"NV-FC2A0B0 delete_volume: Virtuelle Platte gelöscht: %(err)s. Keine "
"Operation auf Speichercontroller"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2075
msgid "create_volume_from_snapshot: Source and destination size differ."
msgstr ""
"NV-5A82296 create_volume_from_snapshot: Größe von Quelle und Größe von "
"Ziel unterscheiden sich."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2096
#, python-format
msgid "create_volume_from_snapshot:  Source vdisk %s does not exist"
msgstr ""
"NV-4729BC4 create_volume_from_snapshot: Als Quelle angegebene virtuelle "
"Platte %s ist nicht vorhanden"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2123
msgid "create_cloned_volume: Source and destination size differ."
msgstr ""
"NV-4DD8AF7 create_cloned_volume: Größe von Quelle und Größe von Ziel "
"unterscheiden sich."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2164
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1025
#, python-format
msgid "enter: extend_volume: volume %s"
msgstr "NV-826757D Eintreten: extend_volume: Datenträger %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2174
msgid "extend_volume: Extending a volume with snapshots is not supported."
msgstr ""
"NV-E7C02C3 extend_volume: Erweitern eines Datenträgers mit "
"Momentaufnahmen wird nicht unterstützt."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2186
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1051
#, python-format
msgid "leave: extend_volume: volume %s"
msgstr "NV-0CDE488 Verlassen: extend_volume: Datenträger %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2202
#, python-format
msgid "enter: migrate_volume: id=%(id)s, host=%(host)s"
msgstr "Eintreten: migrate_volume: ID=%(id)s, Host=%(host)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2234
msgid "migrate_volume started with more than one vdisk copy"
msgstr "migrate_volume mit mehr als einer Kopie einer virtuellen Platte gestartet"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2252
#, python-format
msgid ""
"migrate_volume %(name)s - did not find success message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"migrate_volume %(name)s - Nachricht über erfolgreiche Ausführung in CLI-"
"Ausgabe nicht gefunden.\n"
" Standardausgabe: %(out)s\n"
" Standard-Fehlerausgabe: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2264
msgid "migrate_volume: Could not get vdisk copy data"
msgstr ""
"NV-E8B0820 migrate_volume: Fehler beim Abrufen der Daten zur Kopie der "
"virtuellen Platte"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2279
#, python-format
msgid "leave: migrate_volume: id=%(id)s, host=%(host)s"
msgstr "Verlassen: migrate_volume: ID=%(id)s, Host=%(host)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2301
msgid "Updating volume stats"
msgstr "Aktualisieren der Datenträgerstatistiken"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2324
msgid "Could not get pool data from the storage"
msgstr "NV-675559D Fehler beim Abrufen der Daten zum Pool aus dem Speicher"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2325
msgid "_update_volume_stats: Could not get storage pool data"
msgstr "NV-F6BB258 _update_volume_stats: Fehler beim Abrufen der Speicherpooldaten"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2412
msgid ""
"Illegal value specified for storwize_svc_vol_rsize: set to either a "
"percentage (0-100) or -1"
msgstr ""
"NV-8977C50 Unzulässiger Wert für storwize_svc_vol_rsize angegeben: "
"Entweder auf einen Prozentsatz (0-100) oder auf -1 festlegen"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2418
msgid ""
"Illegal value specified for storwize_svc_vol_warning: set to a percentage"
" (0-100)"
msgstr ""
"NV-80C1898 Unzulässiger Wert für storwize_svc_vol_warning angegeben: Auf "
"einen Prozentsatz (0-100) festlegen"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2425
msgid ""
"Illegal value specified for storwize_svc_vol_grainsize: set to either 32,"
" 64, 128, or 256"
msgstr ""
"NV-8A90F92 Unzulässiger Wert für storwize_svc_vol_grainsize angegeben: "
"Auf 32, 64, 128 oder 256 festlegen"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2432
msgid "System does not support compression"
msgstr "NV-90F35C9 System unterstützt Komprimierung nicht"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2437
msgid "If compression is set to True, rsize must also be set (not equal to -1)"
msgstr ""
"NV-102C98D Wenn die Komprimierung auf True festgelegt wurde, muss auch "
"rsize festgelegt werden (auf einen Wert ungleich -1)"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2443
#, python-format
msgid ""
"Illegal value %(prot)s specified for storwize_svc_connection_protocol: "
"valid values are %(enabled)s"
msgstr ""
"NV-5EBEB51 Unzulässiger Wert %(prot)s für "
"storwize_svc_connection_protocol angegeben: Gültige Werte sind "
"%(enabled)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2451
#, python-format
msgid "I/O group %(iogrp)d is not valid; available I/O groups are %(avail)s"
msgstr ""
"NV-9E31DDB E/A-Gruppe %(iogrp)d ist ungültig. Verfügbare E/A-Gruppen sind"
" %(avail)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2465
#, python-format
msgid "enter: _execute_command_and_parse_attributes:  command %s"
msgstr "Eintreten: _execute_command_and_parse_attributes: Befehl %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2477
#, python-format
msgid ""
"CLI Exception output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"NV-A3B1CA4 Ausgabe der CLI-Ausnahmebedingung:\n"
" Befehl: %(cmd)s\n"
" Standardausgabe: %(out)s\n"
" Standard-Fehlerausgabe: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2494
#, python-format
msgid ""
"leave: _execute_command_and_parse_attributes:\n"
"command: %(cmd)s\n"
"attributes: %(attr)s"
msgstr ""
"Verlassen: _execute_command_and_parse_attributes:\n"
"Befehl: %(cmd)s\n"
"Attribute: %(attr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2513
#, python-format
msgid ""
"_get_hdr_dic: attribute headers and values do not match.\n"
" Headers: %(header)s\n"
" Values: %(row)s"
msgstr ""
"_get_hdr_dic: Attributheader und Werte stimmen nicht überein.\n"
" Header: %(header)s\n"
" Werte: %(row)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2521
#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
"stdout: %(out)s\n"
"stderr: %(err)s\n"
msgstr ""
"NV-39015B6 %(fun)s: Mit nicht erwarteter CLI-Ausgabe fehlgeschlagen.\n"
" Befehl: %(cmd)s\n"
"Standardausgabe: %(out)s\n"
"Standard-Fehlerausgabe: %(err)s\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2535
#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"%(fun)s: Mit nicht erwarteter CLI-Ausgabe fehlgeschlagen.\n"
" Befehl: %(cmd)s\n"
" Standardausgabe: %(out)s\n"
" Standard-Fehlerausgabe: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2543
#, python-format
msgid "Did not find expected column in %(fun)s: %(hdr)s"
msgstr "NV-BEC3CF8 Erwartete Spalte in %(fun)s nicht gefunden: %(hdr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:103
#, python-format
msgid ""
"StorwizeSVCProductDriver: start flashcopy mapping polling timer, polling "
"interval: %(intval)s seconds"
msgstr ""
"NV-796256C StorwizeSVCProductDriver: Teitgeber für Abfrage der FlashCopy-"
"Zuordnung starten. Abfrageintervall: %(intval)s Sekunden"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:328
#, python-format
msgid ""
"The volume %(name)s is in the error state and not a candidate for "
"management.  vdisk status: %(status)s  vdisk id: %(vdisk_id)s  vdisk uid:"
" %(vdisk_uid)s  "
msgstr ""
"Der Datenträger %(name)s befindet sich im Fehlerstatus und ist kein "
"Kandidat für das Management. Status der virtuellen Platte: %(status)s, ID"
" der virtuellen Platte: %(vdisk_id)s, UID der virtuellen Platte: "
"%(vdisk_uid)s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:592
#, python-format
msgid ""
"The connector %(connector)s does not contain the required keys, which are"
" %(expected_fc_keys)s.or %(expected_iscsi_keys)s"
msgstr ""
"Der Connector %(connector)s enthält nicht die folgenden erforderlichen "
"Schlüssel: %(expected_fc_keys)s oder %(expected_iscsi_keys)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:647
#, python-format
msgid "Incorporating WWPNS for Node %(node_id)s: %(wwpns)s"
msgstr "NV-365ED6F Übernehmen der WWPNs für Knoten %(node_id)s: %(wwpns)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:659
#, python-format
msgid ""
"Attachment for host '%(host)s' to %(storage)s for volume %(volume)s "
"expects zoning between initiator WWPNs %(initiators)s and target WWPNs "
"%(targets)s"
msgstr ""
"NV-0F22247 Die Zuordnung von Host '%(host)s' zu %(storage)s für "
"Datenträger %(volume)s erwartet das Zoning zwischen Initiator-WWPNs "
"%(initiators)s und Ziel-WWPNs %(targets)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:721
#, python-format
msgid "Mapping initiator %(phy)s to node %(node)s"
msgstr "NV-5DC7B55 Zuordnen von Initiator %(phy)s zu Knoten %(node)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:766
#, python-format
msgid ""
"Fabric %(fabric)s does not have visibility to any WWPNs in node %(node)s,"
" part of iogrp %(iogrp)s of storage controller %(name)s. WWPNs visible on"
" the fabric are %(visible)s. WWPNs on the controller are %(available)s."
msgstr ""
"Fabric %(fabric)s kann keinen WWPN in Knoten %(node)s als Teil der "
"E/A-Gruppe %(iogrp)s von Speichercontroller %(name)s erkennen. Auf dem "
"Fabric sichtbare WWPNs sind %(visible)s. WWPNs auf dem Controller sind "
"%(available)s."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:811
msgid "Zoning for single fabric, one initiator."
msgstr "NV-6E5D37F Zoning für Einzelfabric, ein Initiator."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:821
msgid "Zoning for single fabric, two initiators."
msgstr "NV-2E0EF21 Zoning für Einzelfabric, zwei Initiatoren."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:835
#, python-format
msgid ""
"Zoning for single fabric, general case due to %(count)s initiators on "
"fabric."
msgstr ""
"NV-D9A5CD2 Zoning für Einzelfabric, Normalfall bei %(count)s Initiatoren "
"pro Fabric."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:845
msgid "Zoning for dual fabric, one initiator per fabric."
msgstr "NV-EE35C79 Zoning für Doppelfabric, ein Initiator pro Fabric."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:864
msgid "Zoning for dual fabric, two initiators per fabric."
msgstr "NV-C638EFA Zoning für Doppelfabric, zwei Initiatoren pro Fabric."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:884
#, python-format
msgid ""
"Zoning for dual fabric, general case due to %(count1)s initiators on "
"first fabric and %(count2)s initiators on second fabric."
msgstr ""
"NV-4351BA7 Zoning für Doppelfabric, Normalfall bei %(count1)s Initiatoren"
" beim ersten Fabric und %(count2)s Initiatoren beim zweiten Fabric."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:894
#, python-format
msgid "Zoning for general case due to %(count)s fabrics."
msgstr "NV-0733A1E Zoning für Normalfall bei %(count)s Fabrics."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:911
#, python-format
msgid "Creating zones: %r"
msgstr "NV-70BDC4D Erstellen von Zonen: %r"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:923
#, python-format
msgid "Requested mapping for initiators  %(initiators)s and targets %(targets)s"
msgstr ""
"NV-35F3CC8 Angeforderte Zuordnung für Initiatoren %(initiators)s und "
"Ziele %(targets)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:941
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:950
#, python-format
msgid "Returned mapping is %(mapping)s"
msgstr "NV-10E28B0 Zurückgegebene Zuordnung ist %(mapping)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:976
#, python-format
msgid "Terminating connection with parameters %(connector)sconnector"
msgstr "NV-4EFE246 Beenden der Verbindung mit Parametern Connector %(connector)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:986
#, python-format
msgid "Removing zones for initiators: %(initiator_list)s"
msgstr "NV-CC588B5 Entfernen der Zonen für Initiatoren: %(initiator_list)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:996
#, python-format
msgid ""
"There was a failure when the zone manager attempted to remove zones "
"created for WWPNs %(wwpns)s during detach of volume %(vol)s."
msgstr ""
"NV-AA064A4 Es ist ein Fehler aufgetreten, als der Zonenmanager versucht "
"hat, für WWPNs %(wwpns)s erstellte Zonen beim Aufheben der Zuordnung von "
"Datenträger %(vol)s zu entfernen."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1083
#, python-format
msgid "SSH Pool: %d free, %d waiting, in-flight commands:"
msgstr ""
"NV-F9DD698 SSH-Pool: %d frei, %d im Wartezustand, momentan ausgeführte "
"Befehle:"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1087
#, python-format
msgid " %(duration).2f %(commands)s"
msgstr "NV-98D8DC3  %(duration).2f %(commands)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1141
#, python-format
msgid ""
"vdisk %(vdsk)s has been added to the flashcopy mapping delete queue with "
"priority %(pri)s."
msgstr ""
"NV-38E83B6 Virtuelle Platte %(vdsk)s wurde zur Warteschlange der zu "
"löschenden FlashCopy-Zuordnungen mit Priorität %(pri)s hinzugefügt."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1149
#, python-format
msgid ""
"Successfully returned from flashcopy mapping waiter for vdisk %(vdsk)s, "
"returned value: %(ret)s, total wait time: %(wt)s seconds."
msgstr ""
"NV-62F28E6 Erfolgreich aus Wartezyklus der FlashCopy-Zuordnung für "
"virtuelle Platte %(vdsk)s zurückgegeben. Zurückgegebener Wert: %(ret)s. "
"Gesamtwartezeit: %(wt)s Sekunden."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1166
#, python-format
msgid ""
"Exception happened when waiting for flashcopy mapping handling for vdisk "
"%(vdsk)s, total wait time: %(wt)s seconds."
msgstr ""
"NV-71EC636 Ausnahmebedingung beim Warten auf Behandlung der FlashCopy-"
"Zuordnung für virtuelle Platte %(vdsk)s. Gesamtwartezeit: %(wt)s "
"Sekunden."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1172
#, python-format
msgid ""
"Removed flashcopy mappings waiter from waiting queue for vdisk %(vdsk)s "
"deletion."
msgstr ""
"NV-46703B0 Wartezyklus von FlashCopy-Zuordnungen aus Warteschlange für "
"die Löschung der virtuellen Platte %(vdsk)s entfernt."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1183
#, python-format
msgid "Flashcopy mapping delete queue: %(vdsks)s"
msgstr ""
"NV-CA4A211 Warteschlange der zu löschenden FlashCopy-Zuordnungen: "
"%(vdsks)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1193
#, python-format
msgid ""
"Flashcopy mapping delete queue: %(cnt)s vdisks pending delete, average "
"wait time: %(avg)s seconds"
msgstr ""
"NV-91BB641 Warteschlange der zu löschenden FlashCopy-Zuordnungen: %(cnt)s"
" virtuelle Platten mit anstehender Löschung, durchschnittliche Wartezeit:"
" %(avg)s Sekunden"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1242
#, python-format
msgid "fcmapping_handler: %(err)s"
msgstr "fcmapping_handler: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1245
#, python-format
msgid ""
"fcmapping_handler: to delete vdisk %(vdisk_id)s, increasing copyrate of "
"flashcopy mapping %(map)s from 0 to %(copyrate)s and waiting for "
"completion."
msgstr ""
"NV-EE5BEB1 fcmapping_handler: Um die virtuelle Platte %(vdisk_id)s zu "
"löschen, wird die Kopiergeschwindigkeit der FlashCopy-Zuordnung %(map)s "
"von 0 auf %(copyrate)s erhöht und auf Fertigstellung gewartet."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1357
#, python-format
msgid ""
"Exception happened during processing flashcopy mapping per vdisk %(vdsk)s"
" deletion: %(err)s"
msgstr ""
"NV-71C30D1 Ausnahmebedingung beim Verarbeiten der FlashCopy-Zuordnung für"
" die Löschung der virtuelle Platte %(vdsk)s: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1387
#, python-format
msgid ""
"Duration of fcmapping_handler timer: %(runtime)s seconds, %(pct)s%% of "
"fixed polling interval."
msgstr ""
"NV-80870AC Dauer des Zeitgebers für fcmapping_handler: %(runtime)s "
"Sekunden, %(pct)s%% des festgelegten Abfrageintervalls."

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:93
#, python-format
msgid "Fabric names are not unique: %(fabric_names)s"
msgstr "NV-2ED2D0B Fabric-Namen sind nicht eindeutig: %(fabric_names)s"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:261
#, python-format
msgid "Connection established to fabric %(f_name)s"
msgstr "NV-41B567C Verbindung zu Fabric %(f_name)s hergestellt"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:376
#, python-format
msgid "Zones to be created for %(fabric)s are %(zones)r"
msgstr ""
"NV-2E6EE4A Für %(fabric)s müssen die folgenden Zonen erstellt werden: "
"%(zones)r"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:410
#, python-format
msgid "%(fabric_descriptor)s: deleting zones %(zone_list)s"
msgstr "NV-C3FDFEA %(fabric_descriptor)s: Löschen der Zonen %(zone_list)s"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:449
#, python-format
msgid "Returned data from get_nameserver_info() is %(info)r"
msgstr ""
"NV-7863F08 Von get_nameserver_info() wurden die folgenden Daten "
"zurückgegeben: %(info)r"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:122
msgid "Could not connect"
msgstr "NV-07C9AAF Es konnte keine Verbindung hergestellt werden"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:124
#, python-format
msgid "SSH Client created for %s"
msgstr "NV-08C2923 SSH-Client erstellt für %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:187
#, python-format
msgid "Failed getting active zone set from %s"
msgstr "NV-373682A Fehler beim Abrufen der aktiven Zonengruppe von %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:218
msgid "Malformed zone configuration"
msgstr "NV-9BF2FBF Fehlerhafte Zonenkonfiguration"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:220
#, python-format
msgid "Failed getting active zone set from fabric %s"
msgstr "NV-A5B77A2 Fehler beim Abrufen der aktiven Zonengruppe von Fabric %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:259
#, python-format
msgid "Add Zones - Zones passed: %s"
msgstr "NV-8A18A84 Zonen hinzufügen - Durchlaufene Zonen: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:267
#, python-format
msgid "Adding zone failed. Error in getting active zone set from fabric %s"
msgstr ""
"NV-C692314 Hinzufügen der Zone fehlgeschlagen. Fehler beim Abrufen der "
"aktiven Zonengruppe von Fabric %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:276
#, python-format
msgid "Zone %(zoneName)s already contains required members"
msgstr "NV-EADDEDC Zone %(zoneName)s enthält bereits die erforderlichen Mitglieder"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:282
#, python-format
msgid "Deleted Zone before insert : %s"
msgstr "NV-4C9797D Gelöschte Zone vor dem Einfügen: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:286
#, python-format
msgid "Deleting zone failed %s"
msgstr "NV-C1A773E Löschen der Zone fehlgeschlagen %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:294
#, python-format
msgid "Adding zone, cmd to run %s"
msgstr "NV-D2B3DDC Hinzufügen der Zone. Ausführender Befehl %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:301
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:304
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:338
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:341
#, python-format
msgid "Adding zone failed, cmd %s"
msgstr "NV-3F8FCCF Hinzufügen der Zone fehlgeschlagen. Befehl %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:312
msgid "No new zones created"
msgstr "NV-145C307 Keine neuen Zonen erstellt"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:322
#, python-format
msgid "Zoneset create operation failed with output %s"
msgstr ""
"NV-0645570 Operation zum Erstellen einer Zonengruppe fehlgeschlagen mit "
"Ausgabe %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:330
#, python-format
msgid "cfgAdd operation failed : %s"
msgstr "NV-C8F3EB6 Operation cfgAdd fehlgeschlagen: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:343
msgid "Zoning completed"
msgstr "NV-BC5301E Zoning abgeschlossen"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:373
#, python-format
msgid "Failed getting active zones from fabric %s"
msgstr "NV-21CE132 Fehler beim Abrufen der aktiven Zonen von Fabric %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:395
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:398
#, python-format
msgid "Deleting zones failed, cmd %s"
msgstr "NV-AFACFBC Löschen der Zonen fehlgeschlagen. Befehl %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:414
#, python-format
msgid "Failed collecting nsshow info for fabric %s"
msgstr "NV-6039569 Fehler beim Erfassen der nsshow-Informationen für Fabric %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:421
#, python-format
msgid "Failed collecting nscamshow info for fabric %s"
msgstr "NV-A1992B9 Fehler beim Erfassen der nscamshow-Informationen für Fabric %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:453
#, python-format
msgid "Problem: %(problem)s"
msgstr "NV-D20CB78 Problem: %(problem)s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:471
#, python-format
msgid "Will retry after %(seconds)s seconds..."
msgstr "NV-A7C85C7 Versuch wird nach %(seconds)s Sekunden wiederholt..."

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:490
#, python-format
msgid "Failed closing SSH connection %s"
msgstr "NV-3EA57B2 Fehler beim Schließen der SSH-Verbindung %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:512
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:561
#, python-format
msgid "running: '%s'"
msgstr "NV-081F69F wird ausgeführt: '%s'"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:521
#, python-format
msgid "Returned data was %r"
msgstr "NV-93F16B7 Die folgenden Daten wurden zurückgegeben: %r"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:535
#, python-format
msgid "Error running command via ssh: %s"
msgstr "NV-20D0255 Fehler beim Ausführen des Befehls über SSH: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:587
#, python-format
msgid "Error while checking zoning txn status: %s"
msgstr "NV-2D4C6DF Fehler beim Prüfen des Transaktionsstatus beim Zoning: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:599
#, python-format
msgid "Executing: %s"
msgstr "NV-4EBB354 Ausführen: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:609
#, python-format
msgid "CLI execution returned: %s"
msgstr "NV-538FB7E CLI-Ausführung zurückgegeben: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:633
#, python-format
msgid "Error executing command %(cmd)s: %s"
msgstr "Fehler beim Ausführen des Befehls %(cmd)s: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:648
#, python-format
msgid "Failed when executing command '%(cmd)s': %(err)s"
msgstr "NV-B5BA5A5 Fehler beim Ausführen des Befehls '%(cmd)s': %(err)s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:670
#, python-format
msgid "Malformed nameserver output is: %s"
msgstr "NV-07E23F0 Fehlerhafte Namensserver-Ausgabe: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:672
msgid "Malformed nameserver info"
msgstr "NV-4331BBF Fehlerhafte Namensserver-Informationen"

