# Translations template for paxes_cinder.
# Copyright (C) 2014 NCO Corp.
# This file is distributed under the same license as the paxes_cinder
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: paxes_cinder 1.2.1.0\n"
"Report-Msgid-Bugs-To: nguyen1d@us.ibm.com\n"
"POT-Creation-Date: 2014-04-24 16:04-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: paxes_cinder/k2aclient/openstack/common/gettextutils.py:255
msgid "Message objects do not support addition."
msgstr "NV-C33F89C Gli oggetti messaggio non supportano l'aggiunta."

#: paxes_cinder/k2aclient/openstack/common/gettextutils.py:264
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""
"NV-64408AE Gli oggetti messaggio non supportano str() perché possono "
"contenere caratteri non ascii. Utilizzare unicode() o translate()."

#: paxes_cinder/k2aclient/openstack/common/procutils.py:129
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr "NV-36AD129 Argomenti parola chiave sconosciuti per utils.execute: %r"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:144
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "NV-9F83237 Esecuzione comando (sottoprocesso): %s"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:169
#: paxes_cinder/k2aclient/openstack/common/procutils.py:241
#, python-format
msgid "Result was %s"
msgstr "NV-E91D667 Il risultato era %s"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:181
#, python-format
msgid "%r failed. Retrying."
msgstr "NV-E62FA94 %r non riuscito. Nuovo tentativo."

#: paxes_cinder/k2aclient/openstack/common/procutils.py:220
#, python-format
msgid "Running cmd (SSH): %s"
msgstr "NV-F226973 Esecuzione comando (SSH): %s"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:222
msgid "Environment not supported over SSH"
msgstr "NV-5D0CD8B Ambiente non supportato su SSH"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:226
msgid "process_input not supported over SSH"
msgstr "NV-E78B011 process_input non supportato su SSH"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:512
#, python-format
msgid "DB error: %s"
msgstr "NV-B907287 Errore DB: %s"

#: paxes_cinder/k2aclient/shell.py:100
msgid "Print debugging output"
msgstr "Stampa output di debug"

#: paxes_cinder/api/plugins/__init__.py:31
#, python-format
msgid "Failed to load extension %(name)s: %(ex)s"
msgstr "NV-E1E174C Impossibile caricare l'estensione %(name)s: %(ex)s"

#: paxes_cinder/volume/manager.py:1275
#, python-format
msgid "Driver %s does not implement Discover Driver"
msgstr "NV-DA200A2 Il driver %s non implementa il rilevamento driver"

#: paxes_cinder/exception.py:16
#, python-format
msgid "Connection control failure: %(reason)s"
msgstr "NV-BFC4353 Errore di controllo connessione: %(reason)s"

#: paxes_cinder/exception.py:20
#, python-format
msgid "Zone operation failed: %(reason)s"
msgstr "NV-A619680 Operazione zona non riuscita: %(reason)s"

#: paxes_cinder/exception.py:24
#, python-format
msgid "FC SAN Lookup failure: %(reason)s"
msgstr "NV-1316051 Errore di ricerca FC SAN: %(reason)s"

#: paxes_cinder/exception.py:32
#, python-format
msgid "Internal Misconfiguration detected: %(reason)s"
msgstr "NV-C9F5A2A Rilevato problema di configurazione interno: %(reason)s"

#: paxes_cinder/exception.py:58
#, python-format
msgid "Fabric '%(display_name)s' (%(username)s@%(ip)s:%(port)s)"
msgstr "NV-097D384 Fabric '%(display_name)s' (%(username)s@%(ip)s:%(port)s)"

#: paxes_cinder/exception.py:93
#, python-format
msgid "%(descriptor)s: %(message)s"
msgstr "NV-12DC37C %(descriptor)s: %(message)s"

#: paxes_cinder/exception.py:142
#, python-format
msgid "%(problem)s: %(err)s"
msgstr "NV-7FA8022 %(problem)s: %(err)s"

#: paxes_cinder/exception.py:164
msgid "Could not authenticate with the specified credentials"
msgstr "NV-BB4FAEC Impossibile autenticare con le credenziale specificate"

#: paxes_cinder/exception.py:174
#, python-format
msgid "Timeout (%(timeout)s seconds) when attempting to connect"
msgstr ""
"NV-3AB9750 Timeout (%(timeout)s secondi) durante il tentativo di "
"connessione"

#: paxes_cinder/exception.py:184
#, python-format
msgid "Timeout (%(timeout)s seconds) when executing command %(cmd)s"
msgstr ""
"NV-17277CD Timeout (%(timeout)s secondi) durante l'esecuzione del comando"
" %(cmd)s"

#: paxes_cinder/exception.py:193
#, python-format
msgid "Could not connect: %(error)s %(detail)s"
msgstr "NV-2251927 Impossibile connettersi: %(error)s %(detail)s"

#: paxes_cinder/exception.py:201
#, python-format
msgid ""
"Another transaction was already in progress when attempting to execute "
"command '%(cmd)s'"
msgstr ""
"NV-B3EE2A1 Un'altra transazione era già in corso quando è stata tentata "
"l'esecuzione del comando '%(cmd)s'"

#: paxes_cinder/exception.py:209
#, python-format
msgid ""
"Zone DB exceeded size limits when executing command '%(cmd)s', which "
"returned '%(res)s'"
msgstr ""
"NV-3D73335 Il DB di zona ha superato i limiti di dimensione durante "
"l'esecuzione del comando '%(cmd)s', che ha restituito '%(res)s'"

#: paxes_cinder/exception.py:218
#, python-format
msgid "The CLI command '%(cmd)s' returned an unexpected response '%(res)s'"
msgstr ""
"NV-6BC3B8F Il comando CLI '%(cmd)s' ha restituito una risposta imprevista"
" '%(res)s'"

#: paxes_cinder/exception.py:240
#, python-format
msgid "Storage %(display_name)s (%(username)s@%(ip)s:%(port)s)"
msgstr "NV-FD8FAF8 Memoria %(display_name)s (%(username)s@%(ip)s:%(port)s)"

#: paxes_cinder/exception.py:272
msgid "No more host definitions can be created"
msgstr "NV-FAE0982 Non è possibile creare altre definizioni host"

#: paxes_cinder/exception.py:281
msgid "No more flashcopy mappings can be created"
msgstr "NV-5071C44 Non è possibile creare altre associazioni flashcopy"

#: paxes_cinder/exception.py:289
msgid "Could not connect, possibly due to too many connections."
msgstr ""
"NV-16C6099 Impossibile connettersi, probabilmente a causa di troppe "
"connessioni."

#: paxes_cinder/exception.py:297
#, python-format
msgid ""
"Could not map vdisk %(vdisk_id)s to host %(host)s because it is already "
"mapped to another host"
msgstr ""
"NV-4B128AE Impossibile associare il disco virtuale %(vdisk_id)s all'host"
"  %(host)s poiché è già associato ad un altro host"

#: paxes_cinder/exception.py:312
#, python-format
msgid "vdisk %(vdisk_id)s does not exist"
msgstr "NV-8AE54C7 Il disco virtuale %(vdisk_id)s non esiste"

#: paxes_cinder/exception.py:322
msgid "No common fabrics between virtual machine and storage"
msgstr "NV-E5685D0 Nessun fabric comune tra macchina virtuale e memoria"

#: paxes_cinder/exception.py:339
#, python-format
msgid ""
"vdisk %(vdisk_id)s has been deleted and recreated. Expected UID is "
"%(expected_uid)s, current UID is %(current_uid)s"
msgstr ""
"NV-78057E1 Il disco virtuale %(vdisk_id)s è stato eliminato e ricreato. "
"L'UID previsto è %(expected_uid)s, l'UID corrente è %(current_uid)s"

#: paxes_cinder/exception.py:350
#, python-format
msgid ""
"Not enough space left on storage host %(host)s to extend the volume "
"%(volume_id)s"
msgstr ""
"NV-EA431AC Spazio insufficiente nell'host di memoria %(host)s per "
"estendere il volume %(volume_id)s"

#: paxes_cinder/exception.py:360
msgid ""
"Flashcopy is in progress for boot volume, volume size didn't change. "
"Please try again later."
msgstr ""
"NV-461A839 Flashcopy in corso per il volume di avvio, la dimensione del "
"volume non è cambiata. Riprovare in seguito."

#: paxes_cinder/exception.py:367
#, python-format
msgid ""
"vdisk %(vdisk_id)s is source of snapshot flashcopy and fcmap %(fcmapid)s "
"cannot be removed."
msgstr ""
"NV-CB3AB35 Il disco virtuale %(vdisk_id)s è l'origine della flashcopy "
"dell'istantanea e fcmap %(fcmapid)s non può essere rimosso."

#: paxes_cinder/db/sqlalchemy/migrate_repo/versions/001_ibm_paxes_v1r2.py:35
#, python-format
msgid "Exception creating table %(table)s: %(ex_str)s"
msgstr "Eccezione durante la creazione della tabella %(table)s: %(ex_str)s"

#: paxes_cinder/db/sqlalchemy/migrate_repo/versions/001_ibm_paxes_v1r2.py:55
#, python-format
msgid "Exception dropping table %(table)s: %(ex_str)s"
msgstr "Eccezione durante l'eliminazione della tabella %(table)s: %(ex_str)s"

#: paxes_cinder/fabric/map_initiators.py:70
msgid ""
"Could not obtain a fabric manager client. Fibre Channel switch fabrics "
"may not be registered."
msgstr ""
"NV-6EF68AC Impossibile ottenere un client gestore fabric. I fabric di "
"switch Fibre Channel potrebbero non essere registrati."

#: paxes_cinder/fabric/map_initiators.py:85
#, python-format
msgid ""
"Unable to retrieve WWPN initiator information from one or more fabric "
"switches. Error: %(ex_str)s"
msgstr ""
"Impossibile richiamare le informazioni iniziatore WWPN da uno o più "
"switch fabric. Errore: %(ex_str)s"

#: paxes_cinder/fabric/map_initiators.py:119
msgid "No fabrics registered."
msgstr "NV-0AA1511 Nessun fabric registrato."

#: paxes_cinder/fabric/map_initiators.py:124
msgid "No fabric names registered."
msgstr "NV-A4978F0 Nessun nome fabric registrato."

#: paxes_cinder/k2aclient/client.py:104
msgid ", during get"
msgstr "NV-C758794 , durante il richiamo"

#: paxes_cinder/k2aclient/client.py:127
msgid ", during refresh"
msgstr "NV-A09A06D , durante l'aggiornamento"

#: paxes_cinder/k2aclient/client.py:148
#: paxes_cinder/k2aclient/client.py:172
msgid ", during create"
msgstr "NV-16332E7 , durante la creazione"

#: paxes_cinder/k2aclient/client.py:193
msgid ", during delete"
msgstr "NV-B5BE602 , durante l'eliminazione"

#: paxes_cinder/k2aclient/client.py:207
msgid ", during runJob"
msgstr "NV-9A12874 , durante runJob"

#: paxes_cinder/k2aclient/client.py:219
msgid ", during readJob"
msgstr "NV-EA9B845 , durante readJob"

#: paxes_cinder/k2aclient/client.py:234
msgid ", during authenticate"
msgstr "NV-DD96084 , durante l'autenticazione"

#: paxes_cinder/k2aclient/client.py:247
#, python-format
msgid ""
"k2aclient: while obtaining client, invalid client version >%(version)s<. "
"must be one of: >%(versions)s<"
msgstr ""
"k2aclient: durante acquisizione client, versione client non valida "
">%(version)s<. Deve essere una delle seguenti: >%(versions)s<"

#: paxes_cinder/k2aclient/exceptions.py:46
#: paxes_cinder/k2aclient/exceptions.py:307
#, python-format
msgid ", exception diagnostics have been written to: >%s<"
msgstr ", diagnostica eccezione scritta in: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:56
#, python-format
msgid "Other Exception off of K2: >%s<"
msgstr "NV-92A2EB5 Altra eccezione al di fuori di K2: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:58
#: paxes_cinder/k2aclient/exceptions.py:78
#: paxes_cinder/k2aclient/exceptions.py:88
#: paxes_cinder/k2aclient/exceptions.py:105
#, python-format
msgid ", during: >%s<"
msgstr ", durante: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:66
#, python-format
msgid "SSL exception off of K2: >%s<"
msgstr "NV-852F651 Eccezione SSL al di fuori di K2: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:76
#, python-format
msgid "Connection exception off of K2: >%s<"
msgstr "NV-DE65980 Eccezione di connessione al di fuori di K2: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:86
#, python-format
msgid "Timeout exception off of K2: >%s<"
msgstr "NV-DC27602 Eccezione timeout al di fuori di K2: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:100
#, python-format
msgid "K2Error off of K2: >%(msg)s<, Status: >%(status)d<, k2Error: >%(k2error)s<"
msgstr ""
"K2Error al di fuori di K2: >%(msg)s<, Stato: >%(status)d<, k2Error: "
">%(k2error)s<"

#: paxes_cinder/k2aclient/exceptions.py:122
msgid "Bad Request"
msgstr "Richiesta errata"

#: paxes_cinder/k2aclient/exceptions.py:130
msgid "Unauthorized"
msgstr "Non autorizzato"

#: paxes_cinder/k2aclient/exceptions.py:144
msgid "Forbidden"
msgstr "Non consentito"

#: paxes_cinder/k2aclient/exceptions.py:158
msgid "Not Found"
msgstr "Non trovato"

#: paxes_cinder/k2aclient/exceptions.py:167
msgid "Method Not Allowed"
msgstr "Metodo non consentito"

#: paxes_cinder/k2aclient/exceptions.py:177
msgid "Not Acceptable"
msgstr "Non accettabile"

#: paxes_cinder/k2aclient/exceptions.py:189
msgid "Conflict"
msgstr "Conflitto"

#: paxes_cinder/k2aclient/exceptions.py:197
msgid "PreCondition failed"
msgstr "Precondizione non riuscita"

#: paxes_cinder/k2aclient/exceptions.py:206
msgid "Request Body Too Large"
msgstr "Corpo della richiesta troppo grande"

#: paxes_cinder/k2aclient/exceptions.py:216
msgid "Unsupported Media Type"
msgstr "Tipo di supporto non supportato"

#: paxes_cinder/k2aclient/exceptions.py:225
msgid "Internal Server Error"
msgstr "Errore server interno"

#: paxes_cinder/k2aclient/exceptions.py:235
msgid "Not Implemented"
msgstr "Non implementato"

#: paxes_cinder/k2aclient/exceptions.py:245
msgid "Service Unavailable"
msgstr "Servizio non disponibile"

#: paxes_cinder/k2aclient/exceptions.py:255
msgid "HTTP Version Not Supported"
msgstr "Versione HTTP non supportata"

#: paxes_cinder/k2aclient/exceptions.py:263
msgid "Not Classified"
msgstr "Non classificato"

#: paxes_cinder/k2aclient/k2exclogger.py:114
#, python-format
msgid ""
"k2aclient: during FFDC, cant create k2 exception log directory: >%s<, "
"will disable k2 exception logging .."
msgstr ""
"NV-ED6E0F0 k2aclient: durante FFDC, impossibile creare directory di log "
"eccezione k2: >%s<, verrà disabilitata la registrazione eccezioni k2 .."

#: paxes_cinder/k2aclient/k2exclogger.py:123
#, python-format
msgid ""
"k2aclient: during FFDC, cant write to k2 exception log directory: >%s<, "
"will disable k2 exception logging .."
msgstr ""
"NV-6373107 k2aclient: durante FFDC, impossibile scrivere directory di log"
" eccezione k2: >%s<, verrà disabilitata la registrazione eccezioni k2 .."

#: paxes_cinder/k2aclient/k2exclogger.py:146
#, python-format
msgid ""
"k2aclient: during FFDC,  caught an exception while writing to log "
"directory: >%s<, will disable k2 exception logging .."
msgstr ""
"NV-3376E54 k2aclient: durante FFDC, rilevata eccezione durante la "
"scrittura nella directory di log: >%s<, disabiliterà la registrazione "
"eccezioni k2 .."

#: paxes_cinder/k2aclient/shell.py:59
#, python-format
msgid ""
"k2aclient: error: %(errmsg)s\n"
"Try '%(mainp)s help %(subp)s' for more information.\n"
msgstr ""
"k2aclient: errore: %(errmsg)s\n"
"Tentare '%(mainp)s help %(subp)s' per ulteriori informazioni.\n"

#: paxes_cinder/k2aclient/shell.py:80
msgid "See \"k2a help COMMAND\" for help on a specific command."
msgstr ""
"Consultare \"k2a help COMANDO\" per l'aiuto relativo ad un comando "
"specifico."

#: paxes_cinder/k2aclient/shell.py:106
msgid "Accepts 1,defaults to env[K2A_API_VERSION]."
msgstr "Accetta 1, valore predefinito env[VERSIONE_API_K2A]."

#: paxes_cinder/k2aclient/shell.py:109
msgid "Number of retries when attempting k2 operations."
msgstr "Numero di nuovi tentativi quando si tentano operazioni k2."

#: paxes_cinder/k2aclient/shell.py:119
msgid "url for k2 hmc, defaults to env[K2_URL]."
msgstr "URL per hmc k2, valore predefinito env[K2_URL]."

#: paxes_cinder/k2aclient/shell.py:125
msgid "k2 username, defaults to env[K2_USERNAME]."
msgstr "Nome utente k2, valore predefinito env[NOMEUTENTE_K2]."

#: paxes_cinder/k2aclient/shell.py:131
msgid "k2 password, defaults to env[K2_PASSWORD]."
msgstr "Password k2, valore predefinito env[PASSWORD_k2]."

#: paxes_cinder/k2aclient/shell.py:138
msgid ""
"k2 auditmemento, defaults to, if set, env[K2_AUDITMEMENTO], otherwise to "
"\"k2a\"."
msgstr ""
"auditmemento k2, valore predefinito, se impostato, env[K2_AUDITMEMENTO], "
"altrimenti \"k2a\"."

#: paxes_cinder/k2aclient/shell.py:145
msgid "k2 certpath, defaults to, if set, env[K2_CERTPATH], otherwise to None."
msgstr ""
"certpath k2, valore predefinito, se impostato, env[K2_CERTPATH], "
"altrimenti Nessuno."

#: paxes_cinder/k2aclient/shell.py:152
msgid ""
"log directory, defaults to, if set, env[K2A_LOGDIR], otherwise to None. "
"None turnsoff file logging"
msgstr ""
"directory di log, valore predefinito, se impostato, env[K2A_LOGDIR], "
"altrimenti Nessuno. Nessuno disattiva la registrazione file"

#: paxes_cinder/k2aclient/shell.py:171
msgid ""
"directory where k2aexc subdirectorywill be placedie \"<excdir>/k2aexc\", "
"defaults to, if set, env[K2A_EXCDIR], otherwise to /tmp"
msgstr ""
"directory in cui verrà collocata la sottodirectory k2aexc cioè "
"\"<excdir>/k2aexc\", valore predefinito, se impostato, env[K2A_EXCDIR], "
"altrimenti /tmp"

#: paxes_cinder/k2aclient/shell.py:309
msgid ""
"k2aclient: you must provide a url for a k2 hmc via either --k2-url or "
"env[K2_URL]"
msgstr ""
"NV-D20F7FC k2aclient: è necessario fornire un url per una hmc k2 tramite "
"--k2-url o env[K2_URL]"

#: paxes_cinder/k2aclient/shell.py:315
msgid ""
"k2aclient: you must provide a k2 username via either --k2-username or "
"env[K2_USERNAME]"
msgstr ""
"NV-996BCEC k2aclient: è necessario fornire un nome utente k2 tramite "
"--k2-username o env[K2_USERNAME]"

#: paxes_cinder/k2aclient/shell.py:321
msgid ""
"k2aclient: you must provide a k2 password via either --k2-password or via"
" env[K2_PASSWORD]"
msgstr ""
"NV-EB948AA k2aclient: è necessario fornire una password k2 tramite "
"--k2-password o env[K2_PASSWORD]"

#: paxes_cinder/k2aclient/shell.py:355
#, python-format
msgid "Display help for %s"
msgstr "Visualizzare l'aiuto per %s"

#: paxes_cinder/k2aclient/shell.py:364
#, python-format
msgid "k2aclient:>%s< is not a valid subcommand"
msgstr "NV-DAC982A k2aclient:>%s< non è un sottocomando valido"

#: paxes_cinder/k2aclient/shell.py:384
msgid "... terminating k2a client"
msgstr "NV-56344DF ... chiusura client k2a"

#: paxes_cinder/k2aclient/shell.py:389
#, python-format
msgid "ERROR: type: >%(type)s<, msg: >%(e)s<"
msgstr "NV-9BF8F90 ERRORE: tipo: >%(type)s<, msg: >%(e)s<"

#: paxes_cinder/k2aclient/utils.py:101
#, python-format
msgid "k2aclient: no %(res)s with a name or ID of '%(name_or_id)s' exists."
msgstr ""
"NV-63A28A2 k2aclient: non esiste alcun %(res)s con nome o ID "
"'%(name_or_id)s'."

#: paxes_cinder/k2aclient/utils.py:108
#, python-format
msgid ""
"k2aclient: multiple %(res)s matches found for '%(name_or_id)s', use an ID"
" to be more specific."
msgstr ""
"NV-9ACDF38 k2aclient: trovate più corrispondenze %(res)s per "
"'%(name_or_id)s', utilizzare un ID per essere più precisi."

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:144
#: paxes_cinder/k2aclient/v1/virtualioserver_manager.py:138
#, python-format
msgid "during directory preparation, cant create directory:  >%s<"
msgstr ""
"NV-64A449C durante la preparazione della directory, impossibile creare la"
" directory:  >%s<"

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:150
#: paxes_cinder/k2aclient/v1/virtualioserver_manager.py:144
#, python-format
msgid "during directory preparation, cant write to directory:  >%s<"
msgstr ""
"NV-C96CB61 durante la preparazione della directory, impossibile scrivere "
"nella directory:  >%s<"

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:181
#: paxes_cinder/k2aclient/k2asample/k2_ssp_etag_test.py:44
#: paxes_cinder/k2aclient/k2asample/tool_ssp_simulation.py:228
#, python-format
msgid "Node: >%s<, has no virtual_io_server, continuing ..."
msgstr "NV-60D657D Nodo: >%s<, non ha virtual_io_server, si procede..."

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:192
#: paxes_cinder/k2aclient/k2asample/k2_ssp_etag_test.py:55
#: paxes_cinder/k2aclient/k2asample/tool_ssp_simulation.py:239
#, python-format
msgid "Failed to retrieve node: >%s<, msg: >%s<, continuing ..."
msgstr "NV-0B99A4D Richiamo nodo non riuscito: >%s<, msg: >%s<, si procede..."

#: paxes_cinder/k2aclient/openstack/common/lockutils.py:276
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s for method \"%(method)s\"..."
msgstr ""
"NV-F6B31F1 Rilasciato il blocco sul file \"%(lock)s\" in %(path)s per il "
"metodo \"%(method)s\"..."

#: paxes_cinder/k2aclient/v1/cluster_manager.py:98
#, python-format
msgid ""
"k2aclient: during lu_linked_clone_of_lu, source_lu_udid: "
">%(source_lu_udid)s<, not in sharedstoragepool: >%(ssp.id)s<"
msgstr ""
"NV-69F0ACE k2aclient: durante lu_linked_clone_of_lu, udid lu origine: "
">%(source_lu_udid)s<, non in pool di memoria condiviso: >%(ssp.id)s<"

#: paxes_cinder/k2aclient/v1/cluster_manager.py:221
#, python-format
msgid ""
"k2aclient: for cluster id : >%(cluster.id)s<,  during lu_linked_clone, "
"for SourceUDID: >%(sourceUDID)s<, and DestinationUDID: "
">%(destinationUDID)s<, experienced job failure, job_id: "
">%(jresponse.job_id)s<, status: >%(jresponse.status)s<, input K2 job "
"diagnostics have been written to: >%(diagfspeci)s<, response k2 job "
"diagnostics have been written to: >%(diagfspec)s<"
msgstr ""
"k2aclient: per id cluster: >%(cluster.id)s<,  durante lu_linked_clone, "
"per UDID origine: >%(sourceUDID)s<, e UDID destinazione: "
">%(destinationUDID)s<, verificatosi errore lavoro, id lavoro: "
">%(jresponse.job_id)s<, stato: >%(jresponse.status)s<, diagnostica lavoro"
" K2 input scritta in: >%(diagfspeci)s<, diagnostica lavoro K2 risposta "
"scritta in: >%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/cluster_manager.py:335
#, python-format
msgid ""
"k2aclient: for cluster id : >%(cluster.id)s<,  during lu_create, for "
"lu_unit_name: >%(lu_unit_name)s<, with lu_unit_capacity: "
">%(lu_unit_capacity)s<, experienced job failure, job_id: "
">%(jresponse.job_id)s<, status: >%(jresponse.status)s<, input K2 job "
"diagnostics have been written to: >%(diagfspeci)s<, response k2 job "
"diagnostics have been written to: >%(diagfspec)s<"
msgstr ""
"k2aclient: per id cluster: >%(cluster.id)s<,  durante lu_create, per nome"
" unità lu: >%(lu_unit_name)s<, con capacità unità lu: "
">%(lu_unit_capacity)s<, verificatosi errore lavoro, id lavoro: "
">%(jresponse.job_id)s<, stato: >%(jresponse.status)s<, diagnostica lavoro"
" K2 input scritta in: >%(diagfspeci)s<, diagnostica lavoro K2 risposta "
"scritta in: >%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/logicalpartition_manager.py:126
#: paxes_cinder/k2aclient/v1/logicalpartition_manager.py:191
#, python-format
msgid ""
"k2aclient: during power_on, for LogicalPartition: "
">%(logicalpartition.id)s<, failed to power on due to job failure, job_id:"
" >%(jresponse.job_id)s<, status: >%(jresponse.status)s<, input K2 job "
"diagnostics have been written to: >%(diagfspeci)s<, response k2 job "
"diagnostics have been written to: >%(diagfspec)s<"
msgstr ""
"k2aclient: durante power_on, per partizione logica: "
">%(logicalpartition.id)s<, accensione non riuscita a causa di errore "
"lavoro, id lavoro: >%(jresponse.job_id)s<, stato: >%(jresponse.status)s<,"
" diagnostica lavoro K2 input scritta in: >%(diagfspeci)s<, diagnostica "
"lavoro K2 risposta scritta in: >%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/managementconsole_manager.py:77
#, python-format
msgid ""
"CLIRunner: ManagementConsole: >%(mc.id)s<, failed to run cmd: >%(cmd)s< "
"due to job failure, job_id: >%(jresponse.job_id)s<, status: "
">%(jresponse.status)s<, input K2 job diagnostics have been written to: "
">%(diagfspeci)s<,  response k2 job diagnostics have been written to: "
">%(diagfspec)s<"
msgstr ""
"CLIRunner: la console di gestione: >%(mc.id)s<, non è riuscita ad "
"eseguire il comando: >%(cmd)s< a causa di un errore del lavoro, id "
"lavoro: >%(jresponse.job_id)s<, stato: >%(jresponse.status)s<, "
"diagnostica lavoro K2 input scritta in: >%(diagfspeci)s<, diagnostica "
"lavoro K2 risposta scritta in: >%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:108
#, python-format
msgid ""
"SharedStoragePool: While attempting to access Cluster: >%s<, unable to "
"connect to HMC: >%s<"
msgstr ""
"PoolMemoriaCondivisa: Durante il tentativo di accedere al cluster: >%s<, "
"impossibile connettersi all'HMC: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:110
msgid "Check the HMC and its configuration."
msgstr "Controllare l'HMC e la sua configurazione."

#: paxes_cinder/k2aclient/v1/paxes_manager.py:111
#, python-format
msgid "SharedStoragePool: Able to connect to HMC: >%s< for Cluster: >%s<"
msgstr ""
"PoolMemoriaCondivisa: È possibile connettersi all'HMC: >%s< per il "
"cluster: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:113
#, python-format
msgid "SharedStoragePool: Couldn't access Cluster: >%s<"
msgstr "PoolMemoriaCondivisa: Impossibile accedere al cluster: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:114
msgid "Check the PowerVC SharedStoragePool configuration"
msgstr "Controllare la configurazione del pool di memoria condiviso"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:115
#, python-format
msgid "SharedStoragePool: Couldn't access SharedStoragePool in Cluster: >%s<"
msgstr ""
"PoolMemoriaCondivisa: Impossibile accedere al pool di memoria condiviso "
"nel cluster: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:117
#: paxes_cinder/k2aclient/v1/paxes_manager.py:122
#: paxes_cinder/k2aclient/v1/paxes_manager.py:127
#: paxes_cinder/k2aclient/v1/paxes_manager.py:133
msgid "Diagnose and repair Cluster"
msgstr "Eseguire la diagnostica e la riparazione del Cluster."

#: paxes_cinder/k2aclient/v1/paxes_manager.py:118
#, python-format
msgid ""
"SharedStoragePool: Successfully accessed SharedStoragePool in Cluster: "
">%s<"
msgstr ""
"PoolMemoriaCondivisa: Accesso riuscito al pool di memoria condiviso nel "
"cluster: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:120
#, python-format
msgid "SharedStoragePool: Unable to create LogicalUnits in Cluster: >%s<"
msgstr ""
"PoolMemoriaCondivisa: Impossibile creare le unità logiche nel cluster: "
">%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:123
#, python-format
msgid "SharedStoragePool: LogicalUnit creation functional in Cluster: >%s<"
msgstr "PoolMemoriaCondivisa: Creazione unità logiche operativa nel cluster: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:125
#, python-format
msgid "SharedStoragePool: Unable to clone LogicalUnits in Cluster: >%s<"
msgstr ""
"PoolMemoriaCondivisa: Impossibile clonare le unità logiche nel cluster: "
">%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:128
#, python-format
msgid ""
"SharedStoragePool: Unable to clone LogicalUnits in Cluster: >%s<, status:"
" >%s<"
msgstr ""
"PoolMemoriaCondivisa: Impossibile clonare le unità logiche nel cluster: "
">%s<, stato: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:130
#, python-format
msgid "Clone functional in Cluster: >%s<"
msgstr "Clonazione operativa nel cluster: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:131
#, python-format
msgid "SharedStoragePool: Unable to delete LogicalUnits in Cluster: >%s<"
msgstr ""
"PoolMemoriaCondivisa: Impossibile eliminare le unità logiche nel cluster:"
" >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:134
#, python-format
msgid "SharedStoragePool: LogicalUnit deletion functional in Cluster: >%s<"
msgstr ""
"PoolMemoriaCondivisa: Eliminazione unità logiche operativa nel cluster: "
">%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:136
msgid "SharedStoragePool: Not Attempted"
msgstr "PoolMemoriaCondivisa: Non tentato"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:143
msgid "HMC connectivity"
msgstr "Connettività HMC"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:144
msgid "Test connection to an HMC managing the SharedStoragePool"
msgstr "Verifica connessione a un'HMC che gestisce il pool di memoria condiviso"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:147
msgid "Cluster and SharedStoragePool accessibility"
msgstr "Accessibilità cluster e pool di memoria condiviso"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:148
msgid "Test the accessibility of a SharedStoragePool"
msgstr "Verificare l'accessibilità di un pool di memoria condiviso"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:151
msgid "Create SharedStoragePool LogicalUnits"
msgstr "Creare unità logiche del pool di memoria condiviso"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:152
msgid "Test the capability to create SharedStoragePool LogicalUnits"
msgstr ""
"Verificare la capacità di creare unità logiche del pool di memoria "
"condiviso"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:155
msgid "Clone LogicalUnits"
msgstr "Clonare unità logiche"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:156
msgid "Test the capability to perform a clone"
msgstr "Verificare la capacità di eseguire un clone"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:159
msgid "Delete SharedStoragePool LogicalUnits"
msgstr "Eliminare unità logiche del pool di memoria condiviso"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:160
msgid "Test the capability to delete SharedStoragePool LogicalUnits"
msgstr ""
"Verificare la capacità di eliminare unità logiche del pool di memoria "
"condiviso"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:112
#, python-format
msgid ""
"k2aclient: during updated_append_lus, cannot update K2 object(s) obtained"
" from a list operation, for ssp: >%s<"
msgstr ""
"NV-CEE080E k2aclient: durante updated_append_lus, impossibile aggiornare "
"oggetti K2 ottenuti da un'operazione elenco, per ssp: >%s<"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:158
#, python-format
msgid "k2aclient: during updated_append_lus, wrong length of lu input tuple: >%d<"
msgstr ""
"NV-B8F5AF7 k2aclient: durante updated_append_lus, lunghezza non corretta "
"per tupla di input lu: >%d<"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:192
#, python-format
msgid ""
"k2aclient:  during updated_append_lus, request to add LU unit_name: >%s< "
"failed, name must be unique"
msgstr ""
"NV-F6B87FC k2aclient:  durante updated_append_lus, richiesta di aggiunta "
"LU nome_unità: >%s< non riuscita, il nome deve essere univoco"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:224
#, python-format
msgid ""
"k2aclient: during updated_append_lus, while adding LUs named: "
">%(lunames)s<,  # attempts due to HTTP 412 exceeded: "
">%(self.api.retries)d<"
msgstr ""
"NV-01A9381 k2aclient: durante updated_append_lus, durante l'aggiunta di "
"LU con nome: >%(lunames)s<,  numero di tentativi a causa di HTTP 412 "
"superato: >%(self.api.retries)d<"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:260
#, python-format
msgid ""
"k2aclient: during updated_append_lus, cant handle K2 response, K2 "
"reported successful creation of >%(lenlus)d<  lus named: >%(lunames)s<,  "
"attempts: >%(attempts)d<  but only >%(lustoadd)d< LUs were found."
msgstr ""
"k2aclient: durante updated_append_lus, impossibile gestire la risposta "
"K2, K2 ha notificato la corretta creazione di >%(lenlus)d<  lu con nome: "
">%(lunames)s<,  tentativi: >%(attempts)d<  ma solo >%(lustoadd)d< LU "
"trovate."

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:276
#, python-format
msgid ""
"k2aclient: during updated_append_lus, cant handle K2 response, K2 "
"reported successful creation of >%(lenlus)d< lus named: >%(lunames)s<, "
"attempts: >%(attempts)d< but >%(lustoadd)d< extra LUs were returned."
msgstr ""
"k2aclient: durante updated_append_lus, impossibile gestire la risposta "
"K2, K2 ha notificato la corretta creazione di >%(lenlus)d<  lu con nome: "
">%(lunames)s<,  tentativi: >%(attempts)d<  ma >%(lustoadd)d< extra LU "
"restituite."

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:369
#, python-format
msgid ""
"k2aclient: during update_append_lu, programming error, could not find "
"lu_udid: >%(lu_udid)s<, in input ssp for: >%(pool)s<"
msgstr ""
"k2aclient: durante update_append_lu, errore di programmazione, "
"impossibile trovare udid lu: >%(lu_udid)s<, in ssp di input per: "
">%(pool)s<"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:390
#, python-format
msgid ""
"k2aclient: during update_append_lu, while deleting LUs w/ udids: "
">%(lu_udids)s<, # attempts due to HTTP 412 exceeded: >%(retries)d<"
msgstr ""
"NV-A3B2A22 k2aclient: durante update_append_lu, durante eliminazione di "
"LU  con udid: >%(lu_udids)s<, numero di tentativi a causa di HTTP 412 "
"superato: >%(retries)d<"

#: paxes_cinder/k2aclient/v1/shell.py:55
#, python-format
msgid "k2aclient: during encoding unexpected type: >%s<"
msgstr "NV-AA592CA k2aclient: durante codifica tipo imprevisto: >%s<"

#: paxes_cinder/k2aclient/v1/shell.py:205
#: paxes_cinder/k2aclient/v1/shell.py:801
#: paxes_cinder/k2aclient/v1/shell.py:812
msgid "Id of the cluster."
msgstr "Id del cluster."

#: paxes_cinder/k2aclient/v1/shell.py:215
msgid "UUID of the cluster containing the LUs."
msgstr "UUID del cluster che contiene le LU."

#: paxes_cinder/k2aclient/v1/shell.py:218
msgid "UDID of the source logicalunit."
msgstr "UDID della LU di origine."

#: paxes_cinder/k2aclient/v1/shell.py:221
msgid "UDID of the destination logicalunit."
msgstr "UDID della LU di destinazione."

#: paxes_cinder/k2aclient/v1/shell.py:231
msgid "Id of the managedsystem to list logicalpartitions"
msgstr "Id del sistema gestito per cui elencare le partizioni logiche"

#: paxes_cinder/k2aclient/v1/shell.py:246
#: paxes_cinder/k2aclient/v1/shell.py:273
#: paxes_cinder/k2aclient/v1/shell.py:295
#: paxes_cinder/k2aclient/v1/shell.py:350
#: paxes_cinder/k2aclient/v1/shell.py:486
#: paxes_cinder/k2aclient/v1/shell.py:658
#: paxes_cinder/k2aclient/v1/shell.py:674
#: paxes_cinder/k2aclient/v1/shell.py:698
#: paxes_cinder/k2aclient/v1/shell.py:714
msgid "Id of the managedsystem."
msgstr "Id del sistema gestito."

#: paxes_cinder/k2aclient/v1/shell.py:249
#: paxes_cinder/k2aclient/v1/shell.py:262
#: paxes_cinder/k2aclient/v1/shell.py:617
#: paxes_cinder/k2aclient/v1/shell.py:634
msgid "Id of the logicalpartition."
msgstr "Id della partizione logica."

#: paxes_cinder/k2aclient/v1/shell.py:276
msgid "UDIDs of the logicalpartition."
msgstr "UDID della partizione logica."

#: paxes_cinder/k2aclient/v1/shell.py:313
#: paxes_cinder/k2aclient/v1/shell.py:324
#: paxes_cinder/k2aclient/v1/shell.py:347
msgid "Id of the managementconsole."
msgstr "Id della console di gestione."

#: paxes_cinder/k2aclient/v1/shell.py:327
#: paxes_cinder/k2aclient/v1/shell.py:356
msgid "Command to run."
msgstr "Comando da eseguire."

#: paxes_cinder/k2aclient/v1/shell.py:353
msgid "UUID of the virtualioserver."
msgstr "UUID del VIOS."

#: paxes_cinder/k2aclient/v1/shell.py:394
msgid "Id of the sharedstoragepool."
msgstr "Id del pool di memoria condiviso."

#: paxes_cinder/k2aclient/v1/shell.py:405
#: paxes_cinder/k2aclient/v1/shell.py:443
#: paxes_cinder/k2aclient/v1/shell.py:456
msgid "UUID of the sharedstoragepool."
msgstr "UUID del pool di memoria condiviso."

#: paxes_cinder/k2aclient/v1/shell.py:408
msgid "Name of the new logicalunit."
msgstr "Nome della nuova unità logica."

#: paxes_cinder/k2aclient/v1/shell.py:411
msgid "Capacity of the new logicalunit."
msgstr "Capacità della nuova unità logica."

#: paxes_cinder/k2aclient/v1/shell.py:414
msgid "Optional flag to control whether the new logicalunit will be thick or thin"
msgstr "Indicatore facoltativo per controllare se la nuova LU sarà thick o thin"

#: paxes_cinder/k2aclient/v1/shell.py:419
msgid "LogicalUnitType: VirtualIO_Disk | VirtualIO_Image"
msgstr "TipoUnitàLogica: DiscoIO_Virtuale | ImmagineIO_Virtuale"

#: paxes_cinder/k2aclient/v1/shell.py:423
msgid "Optional udid of LU to clone from, new if omitted"
msgstr "udid facoltativo della LU da cui clonare, nuovo se omesso"

#: paxes_cinder/k2aclient/v1/shell.py:446
msgid "UDIDs of the logicalunit."
msgstr "UDID della LU."

#: paxes_cinder/k2aclient/v1/shell.py:459
msgid "Optional flag to control whether full details should be output"
msgstr "Indicatore facoltativo per controllare se vanno emessi i dettagli completi"

#: paxes_cinder/k2aclient/v1/shell.py:471
msgid "Id of the managedsystem to list virtualioservers"
msgstr "Id del sistema gestito per cui elencare i VIOS"

#: paxes_cinder/k2aclient/v1/shell.py:489
#: paxes_cinder/k2aclient/v1/shell.py:513
msgid "Id of the virtualioserver."
msgstr "Id del VIOS."

#: paxes_cinder/k2aclient/v1/shell.py:493
msgid ""
"Optional extended attributes Valid values include: All, Advanced, "
"Hypervisor, SystemNetwork, ViosStorage, ViosNetwork, ViosFCMapping, "
"ViosSCSIMapping, and None May be used multiple times. \"All\" if omitted"
msgstr ""
"I valori validi per gli attributi estesi facoltativi includono: All, "
"Advanced, Hypervisor, SystemNetwork, ViosStorage, ViosNetwork, "
"ViosFCMapping, ViosSCSIMapping e nessuno, utilizzabili più volte. \"All\""
" se omesso"

#: paxes_cinder/k2aclient/v1/shell.py:608
msgid "Id of the logicalpartition to list clientnetworkadapters"
msgstr "Id della partizione logica per cui elencare gli adattatori di rete client."

#: paxes_cinder/k2aclient/v1/shell.py:620
msgid "Id of the clientnetworkadapter."
msgstr "Id dell'adattatore di rete client"

#: paxes_cinder/k2aclient/v1/shell.py:637
msgid "UDIDs of the clientnetworkadapter."
msgstr "Gli UDID dell'adattatore di rete client."

#: paxes_cinder/k2aclient/v1/shell.py:649
msgid "Id of the managedsystem to list virtualnetworks"
msgstr "Id del sistema gestito per cui elencare le reti virtuali"

#: paxes_cinder/k2aclient/v1/shell.py:661
msgid "Id of the virtualnetwork."
msgstr "Id della rete virtuale."

#: paxes_cinder/k2aclient/v1/shell.py:677
msgid "UDIDs of the virtualnetwork."
msgstr "Gli UDID della rete virtuale."

#: paxes_cinder/k2aclient/v1/shell.py:689
msgid "Id of the managedsystem to list virtualswitchs"
msgstr "Id del sistema gestito per cui elencare gli switch virtuali"

#: paxes_cinder/k2aclient/v1/shell.py:701
msgid "Id of the virtualswitch."
msgstr "Id dello switch virtuale."

#: paxes_cinder/k2aclient/v1/shell.py:717
msgid "UDIDs of the virtualswitch."
msgstr "Gli UDID dello switch virtuale."

#: paxes_cinder/k2aclient/v1/shell.py:740
msgid "Id of the file."
msgstr "Id del file."

#: paxes_cinder/k2aclient/v1/shell.py:750
msgid "Ids of the files."
msgstr "Id dei file."

#: paxes_cinder/k2aclient/v1/shell.py:761
msgid "/rest/api/uom<uomresource>."
msgstr "/rest/api/uom<uomresource>."

#: paxes_cinder/k2aclient/v1/shell.py:766
msgid "Send output to file"
msgstr "Inviare l'output al file"

#: paxes_cinder/k2aclient/v1/shell.py:782
msgid "Read cinder ssp conf files and report on health"
msgstr "Leggere i file conf ssp cinder e notificare sull'integrità"

#: paxes_cinder/k2aclient/v1/shell.py:815
#: paxes_cinder/k2aclient/v1/shell.py:843
msgid "VIOS password for all VIOS defaults to \"padmin\""
msgstr "Password VIOS per tutti i VIOS impostata sul valore predefinito \"padmin\""

#: paxes_cinder/k2aclient/v1/shell.py:820
#: paxes_cinder/k2aclient/v1/shell.py:848
msgid "Target directory for snapsdefaults to \"/tmp/vios-snap\""
msgstr ""
"Directory di destinazione per snap impostata sul valore predefinito "
"\"/tmp/vios-snap\""

#: paxes_cinder/k2aclient/v1/shell.py:839
msgid "list of vios ips expressed as jsoneg '[\"9.47.161.157\"]'"
msgstr "elenco di ip vios espresso come json: '[\"9.47.161.157\"]'"

#: paxes_cinder/k2aclient/v1/v1k2creater.py:170
#, python-format
msgid "k2aclient: during process_root, unrecognized service: >%s<"
msgstr "NV-1FC12D8 k2aclient: durante process_root, servizio sconosciuto: >%s<"

#: paxes_cinder/k2aclient/v1/v1k2loader.py:61
#, python-format
msgid ""
"k2aclient: during k2 deserialization, for type: >%(pcname)s<, k2 gave "
"unknown attr: >%(us_tag)s<, is there a schema mismatch?, will skip ..."
msgstr ""
"NV-A18BFC5 k2aclient: durante deserializzazione k2, per tipo: "
">%(pcname)s<, k2 ha fornito attr sconosciuto: >%(us_tag)s<, c'è una "
"mancata corrispondenza dello schema? viene ignorato ..."

#: paxes_cinder/k2aclient/v1/v1k2loader.py:77
#, python-format
msgid ""
"k2aclient: during k2 deserialization, for type: >%(pcname)s<, k2 attr: "
">%(us_tag)s<: is listed as scalar, but maybe its not?, is there a schema "
"mismatch?, will replace existing scalar w/ next value ..."
msgstr ""
"k2aclient: durante deserializzazione k2, per tipo: >%(pcname)s<, attr k2:"
" >%(us_tag)s<: elencato come scalare, ma forse non lo è? c'è una mancata "
"corrispondenza dello schema? viene sostituito il valore scalare esistente"
" con il valore successivo..."

#: paxes_cinder/k2aclient/v1/v1k2loader.py:131
#, python-format
msgid ""
"k2aclient: during k2 deserialization, while processing: k2 type: "
">%(parent_tag)s<, there is no definition for k2 type: >%(k2type)s<, is "
"there a schema mismatch?, will skip ..."
msgstr ""
"k2aclient: durante deserializzazione k2, durante elaborazione: tipo k2: "
">%(parent_tag)s<, nessuna definizione per tipo k2: >%(k2type)s<, c'è una "
"mancata corrispondenza dello schema? viene ignorato ..."

#: paxes_cinder/k2aclient/v1/v1k2loader.py:190
#: paxes_cinder/k2aclient/v1/v1k2loader.py:199
msgid "k2aclient:"
msgstr "NV-E561712 k2aclient:"

#: paxes_cinder/k2aclient/v1/virtualioserver_manager.py:280
#, python-format
msgid ""
"k2aclient: during lua_recovery, for device_id: >%(device_id)s<, "
"experienced job failure, job_id: >%(jresponse.job_id)s<, status: "
">%(jresponse.status)s<, input K2 job diagnostics have been written to: "
">%(diagfspeci)s<, response k2 job diagnostics have been written to: "
">%(diagfspec)s<"
msgstr ""
"k2aclient: durante lua_recovery, per id dispositivo: >%(device_id)s<, "
"verificatosi errore lavoro, id lavoro: >%(jresponse.job_id)s<, stato: "
">%(jresponse.status)s<, diagnostica lavoro K2 input scritta in: "
">%(diagfspeci)s<, diagnostica lavoro K2 risposta scritta in: "
">%(diagfspec)s<"

#: paxes_cinder/k2aclient/v1/web_file_manager.py:83
msgid ""
"k2aclient: during file upload, filename: >%(wf.filename)s<, id: "
">%(wf.id)s<, file_uuid: >%(wf.file_uuid)s<, file_enum_type: "
">%(wf.file_enum_type)s<"
msgstr ""
"k2aclient: durante caricamento file, nome file: >%(wf.filename)s<, id: "
">%(wf.id)s<, uuid file: >%(wf.file_uuid)s<, tipo enum file: "
">%(wf.file_enum_type)s<"

#: paxes_cinder/k2aclient/v1/web_job_manager.py:65
#, python-format
msgid ""
"k2aclient: during %(jobtype)s, retry job, job_id: >%(job_id)s<, status: "
">%(status)s<,"
msgstr ""
"NV-FBECCFD k2aclient: durante %(jobtype)s, viene ritentato il lavoro, id "
"lavoro: >%(job_id)s<, stato: >%(status)s<,"

#: paxes_cinder/k2aclient/v1/web_job_manager.py:77
#, python-format
msgid ""
"k2aclient: during %(jobtype)s, too many retries, maximum number of "
"retries: >%(maxretries)d<, job_id: >%(job_id)s<, status: >%(status)s<,"
msgstr ""
"k2aclient: durante %(jobtype)s, troppi tentativi, numero massimo di "
"tentativi: >%(maxretries)d<, id lavoro: >%(job_id)s<, stato: "
">%(status)s<,"

#: paxes_cinder/scheduler/host_manager.py:59
#, python-format
msgid "clean up host_state_map: %(host)shost"
msgstr "NV-F9D1534 cleanup host_state_map: %(host)shost"

#: paxes_cinder/scheduler/sched_drv.py:56
#, python-format
msgid "volume request: requested size: %(size)s. "
msgstr "richiesta volume: dimensione richiesta: %(size)s. "

#: paxes_cinder/scheduler/sched_drv.py:62
#, python-format
msgid ""
"{host: %(hostname)s, free_capacity: %(free_cap)s, total_capacity: "
"%(total)s, reserved_percentage: %(reserved)s, last update: "
"%(time_updated)s}"
msgstr ""
"{host: %(hostname)s, capacità libera: %(free_cap)s, capacità totale: "
"%(total)s, percentuale riservata: %(reserved)s, ultimo aggiornamento: "
"%(time_updated)s}"

#: paxes_cinder/scheduler/sched_drv.py:72
msgid "request exceeds capacity: info"
msgstr "NV-DBCC600 la richiesta supera la capacità: info"

#: paxes_cinder/scheduler/sched_drv.py:75
msgid "No storage has been registered. "
msgstr "NV-96E101B Nessuna memoria registrata. "

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:67
msgid ""
"Free capacity not set: Volume node is either still under initialization "
"or the node info collection is broken."
msgstr ""
"NV-872554F Capacità libera non impostata: il nodo volume è ancora in fase"
" di inizializzazione o la raccolta di informazioni sul nodo è stata "
"interrotta."

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:99
msgid "missing default_volume_type"
msgstr "NV-404930C default_volume_type mancante"

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:106
#, python-format
msgid ""
"missing valid rsize on                                 "
"%(default)svolume_type: %(vol_type)s"
msgstr ""
"NV-B717E15 rsize valido mancante su                                "
"%(default)svolume_type: %(vol_type)s"

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:117
#, python-format
msgid ""
"Insufficient free space for volume creation (requested / avail / rsize): "
"%(requested)s/%(available)s/%(rsize)s"
msgstr ""
"NV-5CC98A1 Spazio libero insufficiente per la creazione di volumi "
"(richiesto / disponibile / rsize): %(requested)s/%(available)s/%(rsize)s"

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:124
#, python-format
msgid ""
"Sufficient free space for volume creation (requested / avail / rsize): "
"%(requested)s/%(available)s/%(rsize)s"
msgstr ""
"NV-D0E32D8 Spazio libero sufficiente per la creazione di volumi "
"(richiesto / disponibile / rsize): %(requested)s/%(available)s/%(rsize)s"

#: paxes_cinder/scohack/scohack_http.py:150
#, python-format
msgid "BadStoreUri: credentials '%(creds)s' not well-formatted."
msgstr ""
"NV-5991AD7 UriArchivioErrato: credenziali '%(creds)s' non scritte "
"correttamente."

#: paxes_cinder/scohack/scohack_http.py:160
msgid "BadStoreUri: no address specified in HTTP URL"
msgstr "NV-2A5D3E2 UriArchivioErrato: nessun indirizzo specificato nell'URL HTTP"

#: paxes_cinder/scohack/scohack_http.py:295
#, python-format
msgid "MaxRedirectsExceeded: redirects: >%(max)d<"
msgstr "NV-30617DF MaxReindirizzamentiSuperato: reindirizza: >%(max)d<"

#: paxes_cinder/scohack/scohack_http.py:308
#, python-format
msgid "HTTP URL returned a %(status)s status code."
msgstr "L'URL HTTP ha restituito un codice stato %(status)s."

#: paxes_cinder/scohack/scohack_http.py:310
#: paxes_cinder/scohack/scohack_http.py:322
#, python-format
msgid "BadStoreUri: loc.path: >%(path)s<, reason: >%(reason)s<"
msgstr "NV-0E3AB46 UriArchivioErrato: loc.path: >%(path)s<, motivo: >%(reason)s<"

#: paxes_cinder/scohack/scohack_location.py:50
#, python-format
msgid "exception.UnknownScheme: scheme: >%(scheme)s<"
msgstr "NV-B8DA628 exception.UnknownScheme: schema: >%(scheme)s<"

#: paxes_cinder/scohack/scohack_scohack.py:77
msgid "URI must start with scohack://"
msgstr "NV-DF4522D L'URI deve iniziare con scohack://"

#: paxes_cinder/scohack/scohack_scohack.py:79
#, python-format
msgid "BadStore: uri: >%(uri)s<, reason: >%(reason)s<"
msgstr "NV-7D2A4E2 ArchivioErrato: uri: >%(uri)s<, motivo: >%(reason)s<"

#: paxes_cinder/scohack/scohack_scohack.py:93
#, python-format
msgid "x-scg-vios-id: >%(id)s< not of form 'ttttmmm_sssssssnnn'"
msgstr "NV-9CCE26B x-scg-vios-id: >%(id)s< non nel formato 'ttttmmm_sssssssnnn'"

#: paxes_cinder/scohack/scohack_scohack.py:106
#, python-format
msgid "scohack: x-scg-vios-id: cant list ManagedSystem: >%(ex)s<"
msgstr ""
"NV-405AA27 scohack: x-scg-vios-id: impossibile elencare sistema gestito: "
">%(ex)s<"

#: paxes_cinder/scohack/scohack_scohack.py:121
#, python-format
msgid "scohack: x-scg-vios-id: cant find ManagedSystem for: >%(id)s<"
msgstr ""
"NV-708F8BE scohack: x-scg-vios-id: impossibile trovare sistema gestito "
"per: >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:129
#, python-format
msgid "scohack: x-scg-vios-id: cant list VirtualIoServer: >%(ex)s<"
msgstr "NV-2D6AE0A scohack: x-scg-vios-id: impossibile elencare VIOS: >%(ex)s<"

#: paxes_cinder/scohack/scohack_scohack.py:139
#, python-format
msgid "scohack: x-scg-vios-id: cant find VirtualIOServer for: >%(id)s<"
msgstr "NV-081426D scohack: x-scg-vios-id: impossibile trovare VIOS per: >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:162
msgid "scohack: cant list vios"
msgstr "NV-D40CA86 scohack: impossibile elencare vios"

#: paxes_cinder/scohack/scohack_scohack.py:168
msgid "scohack: no vios found"
msgstr "NV-ABFCCCD scohack: nessun vios trovato"

#: paxes_cinder/scohack/scohack_scohack.py:177
#, python-format
msgid "scohack: cant list vios for ms: >%(id)s<"
msgstr "NV-D6ED6BF scohack: impossibile elencare vios per ms: >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:184
#, python-format
msgid "scohack: no vios found for ms: >%(id)s<"
msgstr "NV-0FD0B8A scohack: nessun vios trovato per ms: >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:195
#, python-format
msgid "scohack: for ms: >%(mid)s<, cant find vios: >%(vid)s<"
msgstr "NV-AD83B35 scohack: per ms: >%(mid)s<, impossibile trovare vios: >%(vid)s<"

#: paxes_cinder/scohack/scohack_scohack.py:204
#, python-format
msgid "scohack: cant find vios: >%(vid)s<"
msgstr "NV-3704F44 scohack: impossibile trovare vios: >%(vid)s<"

#: paxes_cinder/scohack/scohack_scohack.py:328
#, python-format
msgid ""
"scohack: only single hmc is supported: prev: >%(prev_id)s<, new: "
">%(new_id)s<"
msgstr ""
"NV-185C13E scohack: supportata solo hmc singola: prec: >%(prev_id)s<, "
"nuova: >%(new_id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:339
#, python-format
msgid "scohack: no HMC for id: >%(id)s<"
msgstr "NV-628D2F6 scohack: nessuna HMC per id: >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:352
#, python-format
msgid ""
"scohack: managemenconsole: >%(mc)s< could not be retrieved, hdisks will "
"not be cleaned up, msg: >%(msg)s<"
msgstr ""
"scohack: console di gestione: >%(mc)s< impossibile richiamare, non verrà "
"eseguito il cleanup degli hdisk, msg: >%(msg)s<"

#: paxes_cinder/scohack/scohack_scohack.py:383
#, python-format
msgid "scohack: vios: >%(vios)s<, volume: >%(vol)s<"
msgstr "NV-22A4C11 scohack: vios: >%(vios)s<, volume: >%(vol)s<"

#: paxes_cinder/scohack/scohack_scohack.py:400
#, python-format
msgid "scohack: image upload: hdisk: >%(hdisk)s<, vios: >%(vios)s<"
msgstr ""
"NV-B86BF01 scohack: caricamento immagine: hdisk: >%(hdisk)s<, vios: "
">%(vios)s<"

#: paxes_cinder/scohack/scohack_scohack.py:417
#, python-format
msgid "scohack: volume not found: >%(volume)s<"
msgstr "NV-CDC6DBB scohack: volume non trovato: >%(volume)s<"

#: paxes_cinder/scohack/scohack_scohack.py:428
#, python-format
msgid "scohack: volume: invalid status: >%(status)s<"
msgstr "NV-D365509 scohack: volume: stato non valido: >%(status)s<"

#: paxes_cinder/scohack/scohack_scohack.py:445
#, python-format
msgid "scohack: no ports for vios: >%(vios)s<"
msgstr "NV-230F42F scohack: nessuna porta per vios: >%(vios)s<"

#: paxes_cinder/scohack/scohack_scohack.py:461
#, python-format
msgid "scohack: failed to connect to volume >%(volume_id)s< "
msgstr "NV-E7095A2 scohack: connessione non riuscita al volume >%(volume_id)s< "

#: paxes_cinder/scohack/scohack_scohack.py:471
#, python-format
msgid ""
"scohack: for target volume: >%(volume)s<, bad connection: >%(info)s<, no "
"target_lun"
msgstr ""
"NV-79C5617 scohack: per il volume di destinazione: >%(volume)s<, "
"connessione non corretta: >%(info)s<, nessun lun di destinazione"

#: paxes_cinder/scohack/scohack_scohack.py:487
#, python-format
msgid ""
"scohack: for target volume: >%(volume)s<, no target wwpn found in "
"connection: >%(info)s< "
msgstr ""
"NV-5C2B384 scohack: per il volume di destinazione: >%(volume)s<, nessun "
"wwpn di destinazione trovato nella connessione: >%(info)s< "

#: paxes_cinder/scohack/scohack_scohack.py:506
#, python-format
msgid "scohack: target volume: >%(volume)s<, does not have page83 data"
msgstr ""
"NV-33E8084 scohack: volume di destinazione: >%(volume)s<, non ha i dati "
"pagina 83"

#: paxes_cinder/scohack/scohack_scohack.py:514
#, python-format
msgid "scohack: start luarecovery: deviceid: >%(id)s< , itls: >%(itls)s<"
msgstr ""
"NV-0A59DDD scohack: avvio luarecovery: id dispositivo: >%(id)s< , itl: "
">%(itls)s<"

#: paxes_cinder/scohack/scohack_scohack.py:525
#, python-format
msgid "scohack: lua_recovery job failed for target volume: >%(volume)s<"
msgstr ""
"NV-D94C9A2 scohack: lavoro lua_recovery non riuscito per volume di "
"destinazione: >%(volume)s<"

#: paxes_cinder/scohack/scohack_scohack.py:538
#, python-format
msgid "scohack: luarcovery job status: >%(status)s<, result: >%(res)s<"
msgstr ""
"NV-FC7E239 scohack: stato lavoro luarcovery: >%(status)s<, risultato: "
">%(res)s<"

#: paxes_cinder/scohack/scohack_scohack.py:544
#, python-format
msgid ""
"scohack: lua_recovery job internal error, device_list is invalid device "
"list: >%(lua_list)s<"
msgstr ""
"NV-610160F scohack: errore interno lavoro lua_recovery, device_list non è"
" un elenco dispositivi valido: >%(lua_list)s<"

#: paxes_cinder/scohack/scohack_scohack.py:552
#, python-format
msgid ""
"scohack: lua_recovery job returned multiple devices device list: "
">%(lua_list)s<, will select first ..."
msgstr ""
"NV-3A4481D scohack: il lavoro lua_recovery ha restituito più elenchi "
"dispositivi: >%(lua_list)s<, viene selezionato il primo ..."

#: paxes_cinder/scohack/scohack_scohack.py:562
#, python-format
msgid ""
"This means that a device was found from an ITL nexus and it was "
"determined to be in use by the VIOS. The most likely cause is that a "
"virtual device was not removed from a previous deploy. The VIOS took no "
"action in this case. device: >%(dev)s<"
msgstr ""
"Ciò significa che un dispositivo è stato trovato da un nodo ITL ed è "
"stato determinato essere in uso da parte del VIOS. La causa più probabile"
" è che un dispositivo virtuale non è stato rimosso da una distribuzione "
"precedente. Il VIOS non ha eseguito alcuna azione in questo caso. "
"dispositivo: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:572
#, python-format
msgid ""
"This means that the ITL nexus is not consider reliable and some error "
"occurred that prevents the VIOS from determining making a decision on "
"safely removing a device. The VIOS took no action in this case. Perhaps "
"try to remove the offending hdisk from the VIOS, with rmdev -d -l hdiskx."
" device: >%(dev)s<"
msgstr ""
"NV-DC7D321 Ciò significa che il nodo ITL non è considerato affidabile e "
"si sono verificati degli errori che impediscono al VIOS di determinare se"
" sia sicuro rimuovere un dispositivo. Il VIOS non ha intrapreso azioni in"
" questo caso. Una soluzione possibile consiste nel rimuovere l'hdisk che "
"crea problemi dal VIOS, con rmdev -d -l hdiskx. dispositivo: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:585
#, python-format
msgid ""
"This means the information provided and action taken by the VIOS was "
"sufficient to find the storage. pvName, and uniqueID elements will follow"
" in the data stream. device: >%(dev)s<"
msgstr ""
"NV-8DB8D33 Ciò significa che le informazioni fornite e l'azione "
"intrapresa dal VIOS non sono state sufficienti per trovare la memoria. "
"Gli elementi pvName e uniqueID seguiranno nel flusso di dati. "
"dispositivo: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:593
#, python-format
msgid ""
"This means some new storage element was found at the ITL nexus but VIOS "
"could not determine if it is the storage of interest to the management "
"tool. device: >%(dev)s<"
msgstr ""
"NV-36ADD00 Ciò significa che sono stati trovati alcuni nuovi elementi di "
"memoria nel nodo ITL, ma il VIOS non è riuscito a determinare se si "
"tratta della memoria che interessa allo strumento di gestione. "
"dispositivo: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:602
#, python-format
msgid ""
"The VIOS could not determine if this is logical unit of interest to the "
"management tool however did find a device from the ITL nexus list. "
"device: >%(dev)s<"
msgstr ""
"NV-6761BFF Il VIOS non è riuscito a determinare se si tratta dell'unità "
"logica che interessa allo strumento di gestione, tuttavia ha trovato un "
"dispositivo dall'elenco nodi ITL. dispositivo: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:611
#, python-format
msgid ""
"The VIOS could not find a device from the itl nexus list. It could be "
"some SCSI or transport error occurred during configuration or the ITL "
"nexus list was incorrect. device: >%(dev)s<"
msgstr ""
"NV-2479600 Il VIOS non è riuscito a trovare un dispositivo dall'elenco "
"nodi ITL. Potrebbe trattarsi di un errore di trasporto o SCSI "
"verificatosi durante a configurazione o l'elenco di nodi ITL non era "
"corretto. dispositivo: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:622
#, python-format
msgid ""
"Unknown device status. Severe internal error contact NCO. device: "
">%(dev)s<"
msgstr ""
"NV-2EF1D11 Stato unità sconosciuto. Grave errore interno contattare NCO. "
"dispositivo: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:638
#, python-format
msgid "scohack: failed to find device name: >%(dev)s<"
msgstr "NV-B6E8402 scohack: impossibile trovare il nome dispositivo: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:643
#, python-format
msgid "scohack: found device name: >%(dev)s<"
msgstr "NV-32CF4C2 scohack: nome dispositivo trovato: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:665
#, python-format
msgid "scohack: hdisk_uuid: >%(hdisk)s<, checksum not specified"
msgstr "NV-D85ABDC scohack: hdisk_uuid: >%(hdisk)s<, checksum non specificato"

#: paxes_cinder/scohack/scohack_scohack.py:672
#, python-format
msgid "scohack: hdisk_uuid: >%(hdisk)s<, size not specified"
msgstr "NV-9783CB3 scohack: hdisk_uuid: >%(hdisk)s<, dimensione non specificata"

#: paxes_cinder/scohack/scohack_scohack.py:694
#, python-format
msgid ""
"scohack: image upload complete for hdisk_uuid: >%(hdisk)s<, webfile id: "
">%(wid)s<, actual size: >%(size)s< bytes, elapsed time: >%(time)d< "
"seconds, rate: >%(rate)f< minutes/GB"
msgstr ""
"scohack: caricamento immagine completato per uuid_hdisk: >%(hdisk)s<, id "
"fileweb: >%(wid)s<, dimensione effettiva: >%(size)s< byte, tempo "
"trascorso: >%(time)d< secondi, velocità: >%(rate)f< minuti/GB"

#: paxes_cinder/scohack/scohack_scohack.py:709
#, python-format
msgid ""
"scohack:  mismatch: expected_file_size_in_bytes: >%e_size)d<, "
"current_file_size_in_bytes: >%(c_size)d<"
msgstr ""
"NV-E2ACA08 scohack:  mancata corrispondenza: dim_file_prevista_in_byte: "
">%e_size)d<, dim_file_corrente_in_byte: >%(c_size)d<"

#: paxes_cinder/scohack/scohack_scohack.py:740
#, python-format
msgid ""
"scohack: cleanup failure for: >%(hdisk)s<, job status: >%(status)s<, "
"response: >%(res)s< continuing ..."
msgstr ""
"NV-C9A426B scohack: errore di cleanup per: >%(hdisk)s<, stato lavoro: "
">%(status)s<, risposta: >%(res)s< si procede..."

#: paxes_cinder/scohack/scohack_scohack.py:752
#, python-format
msgid ""
"scohack: for hdisk_uuid: >%(hdisk)s<  no managementconsole, hisks will "
"not be cleaned up"
msgstr ""
"NV-508BE83 scohack: per uuid_hdisk: >%(hdisk)s<  nessuna console di "
"gestione, nessun cleanup per hisks"

#: paxes_cinder/scohack/scohack_scohack.py:758
#: paxes_cinder/scohack/scohack_scohack.py:768
#, python-format
msgid "scohack: for hdisk_uuid: >%(hdisk)s< cleanup failed, msg: >%(ex)s<"
msgstr ""
"NV-B37BCB5 scohack: per uuid_hdisk: >%(hdisk)s< cleanup non riuscito, "
"msg: >%(ex)s<"

#: paxes_cinder/scohack/scohack_scohack.py:772
#, python-format
msgid "scohack: upload failed for hdisk_uuid: >%(dsk)s<"
msgstr "NV-D7A600C scohack: caricamento non riuscito per uuid_hdisk: >%(dsk)s<"

#: paxes_cinder/scohack/scohack_utils.py:47
#, python-format
msgid "Error: cooperative_iter exception %(error)s"
msgstr "NV-23E8986 Errore: eccezione cooperative_iter %(error)s"

#: paxes_cinder/volume/__init__.py:46
#, python-format
msgid ""
"cinder volume_create interface has been changed. PowerVC monkey patch for"
" volume clone won't work. function: %(fx)s, arguments: %(args)s"
msgstr ""
"NV-7A6F9A4 Interfaccia volume_create cinder modificata. Patch monkey "
"PowerVC per clone volume non funzionerà. funzione: %(fx)s, argomenti: "
"%(args)s"

#: paxes_cinder/volume/__init__.py:61
#, python-format
msgid ""
"Monkey patched volume clone by paxes volume_create_decorator(). Source "
"Volume ID: %(svol)s, volume type name: %(voltpnm)s, volume type ID: "
"%(voltpid)s"
msgstr ""
"NV-D17192A Patch monkey per clone volume apportata da paxes "
"volume_create_decorator(). ID volume origine: %(svol)s, nome tipo volume:"
" %(voltpnm)s, ID tipo volume: %(voltpid)s"

#: paxes_cinder/volume/__init__.py:94
#, python-format
msgid ""
"Failed to get the parameters from function "
"cinder.volume.volume_types.create(). Default quota didn't set for the "
"storage template. Error: %(err)s"
msgstr ""
"NV-A4934EA Impossibile ottenere i parametri dalla funzione "
"cinder.volume.volume_types.create(). Quota predefinita non impostata per "
"modello di memoria. Errore: %(err)s"

#: paxes_cinder/volume/__init__.py:114
#, python-format
msgid "Successfully set default quota for storage template %(vol_type)s"
msgstr ""
"NV-71868FF Quota predefinita per il modello di memoria %(vol_type)s "
"impostata correttamente"

#: paxes_cinder/volume/__init__.py:118
#, python-format
msgid ""
"Failed to set default quota for storage template %(vol_type)s, error: "
"%(err)s"
msgstr ""
"NV-D86E5F7 Impossibile impostare la quota predefinita per il modello di "
"memoria %(vol_type)s, errore: %(err)s"

#: paxes_cinder/volume/__init__.py:122
#, python-format
msgid ""
"Cannot set default quota for storage template %(vol_type) due to invalid "
"Parameters from volume type create."
msgstr ""
"NV-D9BA448 Impossibile impostare la quota predefinita per il modello di "
"memoria %(vol_type)  a causa di parametri non validi dalla creazione tipo"
" volume."

#: paxes_cinder/volume/__init__.py:175
#, python-format
msgid "Error getting data volumes: %s "
msgstr "NV-7627301 Errore nel richiamo dei volumi di dati: %s "

#: paxes_cinder/volume/manager.py:89
#, python-format
msgid "Cannot perform direct SAN operation on disk with prefix %(prefix)s"
msgstr ""
"NV-1701BDD Impossibile eseguire l'operazione SAN diretta sul disco con "
"prefisso %(prefix)s"

#: paxes_cinder/volume/manager.py:100
msgid "Driver still initializing, wait..."
msgstr "NV-C6CA9E0 Driver ancora in fase di inizializzazione, attendere..."

#: paxes_cinder/volume/manager.py:102
#, python-format
msgid "Try again: %s"
msgstr "NV-FEE7BD0 Riprovare: %s"

#: paxes_cinder/volume/manager.py:172
#, python-format
msgid "Fabric {fabric_name} ({user}@{ip}:{port}): %(message)s"
msgstr "NV-0A01336 Fabric {nome_fabric} ({utente}@{ip}:{porta}): %(message)s"

#: paxes_cinder/volume/manager.py:188
#, python-format
msgid ""
"Storage Provider {storage_provider_hostname} ({user}@{ip}:{port}) "
"{volume_id}: %(message)s"
msgstr ""
"NV-E1A972C Provider di memoria {nomehost_provider_memoria} "
"({utente}@{ip}:{porta}) {id_volume}: %(message)s"

#: paxes_cinder/volume/manager.py:223
msgid ""
"The volume is already attached to another virtual server, possibly one "
"that is not managed by PowerVC."
msgstr ""
"Il volume è già collegato a un altro server virtuale, probabilmente uno "
"non gestito da PowerVC."

#: paxes_cinder/volume/manager.py:227
msgid ""
"The volume cannot be deleted because it is either mapped to a host or "
"part of a flashcopy or remote copy operation."
msgstr ""
"Il volume non può essere eliminato perché è associato a un host o fa "
"parte di una flashcopy o un'operazione di copia remota."

#: paxes_cinder/volume/manager.py:239
#, python-format
msgid "%(error_prefix)s failure for volume {volume_id}: %(error)s"
msgstr "%(error_prefix)s errore per volume {id_volume}: %(error)s"

#: paxes_cinder/volume/manager.py:244
#, python-format
msgid ""
"%(error_prefix)s failure for volume {volume_id}.Command %(cmd)s, error "
"%(error)s"
msgstr ""
"%(error_prefix)s errore per volume {id_volume}. Comando %(cmd)s, errore "
"%(error)s"

#: paxes_cinder/volume/manager.py:393
#, python-format
msgid "Resuming deletion of volume %s"
msgstr "NV-E253654 Ripresa dell'eliminazione del volume %s"

#: paxes_cinder/volume/manager.py:396
#, python-format
msgid ""
"Failed to delete volume %(volid)s during volume service startup. Error: "
"%(error)s"
msgstr ""
"NV-CCA27AC Non è stato possibile eliminare il volume %(volid)s durante "
"l'avvio del servizio volume. Errore: %(error)s"

#: paxes_cinder/volume/manager.py:410
#, python-format
msgid "Processing volume that was left in the attaching state. Volume id: %(id)s"
msgstr ""
"NV-89FC9B0 Elaborazione del volume che è stato lasciato in stato di "
"collegamento. ID volume: %(id)s"

#: paxes_cinder/volume/manager.py:483
#, python-format
msgid ""
"_volume_attach_rollback: Volume %(id)s is missing restricted metadata to "
"recover the attaching state."
msgstr ""
"NV-C8F1D06 _volume_attach_rollback: Nel volume %(id)s mancano i metadati "
"limitati per il ripristino dello stato di collegamento."

#: paxes_cinder/volume/manager.py:487
#, python-format
msgid ""
"_volume_attach_rollback: No attach operation  to rollback for volume "
"%(id)s"
msgstr ""
"NV-77AEEA1 _volume_attach_rollback: Nessuna operazione di collegamento "
"per il rollback per il volume %(id)s"

#: paxes_cinder/volume/manager.py:493
#, python-format
msgid ""
"_volume_attach_rollback: Invalid connector %(conn)s in volume %(id)s "
"restrict metadata. Rollback without termination"
msgstr ""
"NV-4096184 _volume_attach_rollback: Connettore %(conn)s non valido nei "
"metadati limitati del volume %(id)s. Rollback senza terminazione"

#: paxes_cinder/volume/manager.py:498
#, python-format
msgid "_volume_attach_rollback: Roll back attaching state for volume %(id)s."
msgstr ""
"NV-1EB0444 _volume_attach_rollback: Rollback stato di collegamento per il"
" volume %(id)s."

#: paxes_cinder/volume/manager.py:518
#, python-format
msgid ""
"_volume_attach_rollback: Finished. Volume %(id)s has rolled back to "
"available state."
msgstr ""
"NV-1E08B26 _volume_attach_rollback: Finito. Eseguito il rollback del "
"volume %(id)s allo stato disponibile."

#: paxes_cinder/volume/manager.py:600
#, python-format
msgid ""
"The volume detach didn't finish successfully before cinder service was "
"restarted. volume id: %(id)s"
msgstr ""
"NV-333B81A Scollegamento volume non terminato correttamente prima che il "
"servizio cinder fosse riavviato. ID volume: %(id)s"

#: paxes_cinder/volume/manager.py:633
msgid "Unable to initialize host, driver is uninitialized"
msgstr "NV-7F33CBC Impossibile inizializzare l'host, il driver non è inizializzato"

#: paxes_cinder/volume/manager.py:650
msgid "update default quota class..."
msgstr "NV-392B903 aggiornamento classe quota predefinita..."

#: paxes_cinder/volume/manager.py:652
msgid "Post init_host processing and update volume status."
msgstr ""
"NV-6EC3032 Elaborazione postinizializzazione host e aggiornamento stato "
"volume."

#: paxes_cinder/volume/manager.py:656
#, python-format
msgid "Error happened during post init_host volume processing. Error: %s"
msgstr ""
"NV-B263BC8 Errore durante l'elaborazione postinizializzazione volume "
"host. Errore: %s"

#: paxes_cinder/volume/manager.py:660
#, python-format
msgid "Rollback volume still attaching during init_host: %d volumes"
msgstr ""
"NV-BDEAFA8 Rollback volume ancora in fase di collegamento durante "
"init_host: %d volumi"

#: paxes_cinder/volume/manager.py:665
#, python-format
msgid "Resume volume deletion during init_host: %d volumes"
msgstr "NV-6BC64FF Ripresa eliminazione volume durante init_host: %d volumi"

#: paxes_cinder/volume/manager.py:719
msgid "Caught Exception Refreshing Driver Status "
msgstr "Rilevata eccezione durante l'aggiornamento dello stato del driver "

#: paxes_cinder/volume/manager.py:755
msgid "Caught Exception trying to update Storage Node in DB"
msgstr ""
"NV-36093B5 Rilevata eccezione durante il tentativo di aggiornare il nodo "
"di memoria nel DB"

#: paxes_cinder/volume/manager.py:793
msgid "Unable to retrieve Default Volume Type"
msgstr "NV-544BC4C Impossibile richiamare il tipo di volume predefinito"

#: paxes_cinder/volume/manager.py:850
#, python-format
msgid "volume %s: removing export"
msgstr "NV-BAF02FC volume %s: rimozione esportazione"

#: paxes_cinder/volume/manager.py:852
#, python-format
msgid "volume %s: deleting"
msgstr "NV-4F406DE volume %s: eliminazione"

#: paxes_cinder/volume/manager.py:855
#, python-format
msgid "volume %s: volume is busy"
msgstr "NV-3431BA6 volume %s: il volume è occupato"

#: paxes_cinder/volume/manager.py:858
#, python-format
msgid "Fail to remove_export or delete_volume: %sname"
msgstr "NV-E98201D Esecuzione remove_export o delete_volume non riuscita: %snome"

#: paxes_cinder/volume/manager.py:862
#, python-format
msgid "Volume %s: deletion failed with exception "
msgstr "NV-137591B Volume %s: eliminazione non riuscita con eccezione "

#: paxes_cinder/volume/manager.py:954
#, python-format
msgid ""
"failed checking whether                              volume %(vol_id)s "
"backs an image, metadata=%(mdata)s"
msgstr ""
"NV-BE4D3EE L'operazione che verifica se il volume %(vol_id)s supporta "
"un'immagine ha avuto esito negativo, metadati=%(mdata)s"

#: paxes_cinder/volume/manager.py:991
#, python-format
msgid ""
"volume %(volid)s has unfinished attach transaction. Rolling back before "
"deleting the volume."
msgstr ""
"NV-331CBBA volume %(volid)s non ha terminato la transazione di "
"collegamento. Rollback prima di eliminare il volume."

#: paxes_cinder/volume/manager.py:1035
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to extend volume by %(s_size)sG, "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""
"NV-521C07E Quota superata per %(s_pid)s, tentato di estendere il volume "
"per %(s_size)sG, (%(d_consumed)dG di %(d_quota)dG già consumati)"

#: paxes_cinder/volume/manager.py:1091
#, python-format
msgid ""
"The host %(hostid)s for boot volume %(volid)s  does not support extend "
"volume."
msgstr ""
"NV-37CDE0F L'host %(hostid)s per il volume di avvio %(volid)s  non "
"supporta l'estensione volume."

#: paxes_cinder/volume/manager.py:1145
#, python-format
msgid "Start attach transaction for volume %(id)s."
msgstr "NV-1CBB13C Avviare la transazione di collegamento per il volume %(id)s."

#: paxes_cinder/volume/manager.py:1175
#, python-format
msgid "Driver returned %s"
msgstr "NV-B695526 Il driver ha restituito %s"

#: paxes_cinder/volume/manager.py:1208
#, python-format
msgid "Successfully attached the volume %(id)s. Clean up transaction."
msgstr ""
"NV-F606087 Volume %(id)s collegato correttamente. Cleanup della "
"transazione."

#: paxes_cinder/volume/drivers/paxes_san.py:162
#, python-format
msgid "Waiting %(seconds)d seconds before next attempt..."
msgstr "NV-0553DA5 Attesa di %(seconds)d prima del tentativo successivo..."

#: paxes_cinder/volume/drivers/paxes_san.py:182
#, python-format
msgid "Error running SSH command: %s"
msgstr "NV-052C0AB Errore durante l'esecuzione del comando SSH: %s"

#: paxes_cinder/volume/drivers/emc/emc_common_product.py:35
msgid "Updating volume status"
msgstr "NV-A56DF8D Aggiornamento dello stato del volume"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:89
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1374
msgid "protocol must be specified as '<in> iSCSI' or '<in> FC'"
msgstr "il protocollo deve essere specificato come '<in> iSCSI' o '<in> FC'"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:123
msgid "Entering create_volume."
msgstr "NV-4C5AEEB Entrata in create_volume."

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:127
#, python-format
msgid "Create Volume: %(volume)s  Size: %(size)lu"
msgstr "NV-403E8FC Creare il volume: %(volume)s  Dimensione: %(size)lu"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:157
#, python-format
msgid ""
"Unsupported element_type value %(element_type)s.  Specify a supported "
"element_type value and resubmit the request."
msgstr ""
"NV-AC11F99 Valore element_type %(element_type)s non supportato. "
"Specificare un valore supportato e ripetere la richiesta."

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:164
#, python-format
msgid "Create Volume: %(volume)s  Storage type: %(storage_type)s"
msgstr "NV-4E4E2BB Creare il volume: %(volume)s  Tipo di memoria: %(storage_type)s"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:171
#, python-format
msgid ""
"Create Volume: %(volume)s  Pool: %(pool)s,  Element Type: "
"%(element_type)s, Storage System: %(storage_system)s"
msgstr ""
"NV-723484A Creare il volume: %(volume)s  Pool: %(pool)s,  Tipo di "
"elemento: %(element_type)s, Sistema di memoria: %(storage_system)s"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:182
#, python-format
msgid ""
"Error Create Volume: %(volumename)s. Storage Configuration Service not "
"found for pool %(storage_type)s."
msgstr ""
"NV-0EFA73A Errore durante la creazione del volume: %(volumename)s. "
"Servizio di configurazione memoria non trovato per il pool "
"%(storage_type)s."

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:190
#, python-format
msgid ""
"Create Volume: %(name)s  Method: CreateOrModifyElementFromStoragePool  "
"ConfigServicie: %(service)s  ElementName: %(name)s  InPool: %(pool)s  "
"ElementType: %(element_type)s  Size: %(size)lu"
msgstr ""
"NV-6E312B4 Creare volume: %(name)s  Metodo: "
"CreateOrModifyElementFromStoragePool  ServizioConfig: %(service)s  "
"NomeElemento: %(name)s  InPool: %(pool)s  TipoElemento: %(element_type)s"
"  Dimensione: %(size)lu"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:206
#, python-format
msgid "Create Volume: %(volumename)s  Return code: %(rc)lu"
msgstr "NV-0214C49 Creare volume: %(volumename)s  Codice di ritorno: %(rc)lu"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:213
#, python-format
msgid ""
"Error Create Volume: %(volumename)s.  Return code: %(rc)lu.  Error: "
"%(error)s"
msgstr ""
"NV-227D3AC Errore creazione volume: %(volumename)s.  Codice di ritorno: "
"%(rc)lu.  Errore: %(error)s"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:220
#, python-format
msgid "Leaving create_volume: %(volumename)s  Return code: %(rc)lu"
msgstr ""
"NV-C5C5CCC Uscita da create_volume: %(volumename)s  Codice di ritorno: "
"%(rc)lu"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:235
#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:259
msgid "Could not establish ecom connection"
msgstr "NV-930992B Impossibile stabilire una connessione ecom"

#: paxes_cinder/volume/drivers/ssp/ssp.py:177
#, python-format
msgid "ssp:  no matching HMC was found in the DB for host: >%s<"
msgstr "NV-BFBE123 ssp: nessuna HMC corrispondente trovata nel DB per l'host: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:248
#, python-format
msgid "ssp: during create default volume type, DB error: >%s<"
msgstr ""
"NV-FA1BBE8 ssp: durante la creazione del tipo di volume predefinito, "
"errore DB: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:279
#, python-format
msgid ""
"ssp: during _create_lu for LU: (name: >%(name)s<, size: >%(size)s<, thin:"
" >%(thin)s<), ssp_udid: >%(ssp_udid)s< is not same as extra_spec "
"shared_storage_pool: >%(extra_spec_ssp_id)s<"
msgstr ""
"ssp: durante _create_lu per LU: (nome: >%(name)s<, dimensione: "
">%(size)s<, thin: >%(thin)s<), udid ssp: >%(ssp_udid)s< non uguale a "
"extra_spec shared_storage_pool: >%(extra_spec_ssp_id)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:299
#, python-format
msgid ""
"ssp: failed during _create_lu for LU: (name: >%(name)s<, size: "
">%(size)s<, thin: >%(thin)s<), message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: non riuscito durante _create_lu per LU: (nome: >%(name)s<, "
"dimensione: >%(size)s<, thin: >%(thin)s<), messaggio: >%(e)s<, k2xa: "
">%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:329
#, python-format
msgid ""
"ssp: during _create_lu job for LU: (name: >%(name)s<, size: >%(size)s<, "
"thin: >%(thin)s<), ssp_udid: >%(ssp_udid)s< is not same as extra_spec "
"shared_storage_pool: >%(extra_spec_ssp_id)s<"
msgstr ""
"ssp: durante lavoro _create_lu per LU: (nome: >%(name)s<, dimensione: "
">%(size)s<, thin: >%(thin)s<), udid ssp: >%(ssp_udid)s< non uguale a "
"extra_spec shared_storage_pool: >%(extra_spec_ssp_id)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:351
#, python-format
msgid ""
"ssp: failure during _create_lu, create parameters: name: >%(name)s<, "
"size: >%(size)s<, thin: >%(thin)s<, logicalunittype: "
">%(logicalunittype)s<, message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: errore durante _create_lu, parametri creazione: nome: >%(name)s<, "
"dimensione: >%(size)s<, thin: >%(thin)s<, tipounitàlogica: "
">%(logicalunittype)s<, messaggio: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:366
#, python-format
msgid ""
"ssp: failure during _create_lu job, expecting COMPLETED_OK, but for "
"job_id: >%(job_id)s< got status: >%(status)s< create parameters: name: "
">%(name)s<, size: >%(size)s<, thin: >%(thin)s<, logicalunittype: "
">%(logicalunittype)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-76A9409 ssp: errore durante lavoro _create_lu, previsto COMPLETED_OK, "
"ma per id lavoro: >%(job_id)s< ottenuto stato: >%(status)s< parametri "
"creazione: nome: >%(name)s<, dimensione: >%(size)s<, thin: >%(thin)s<, "
"tipounitàlogica: >%(logicalunittype)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:382
#, python-format
msgid ""
"ssp: create complete, job_id: >%(job_id)s<, name: >%(name)s<, size: "
">%(size)s<, thin: >%(thin)s<, logicalunittype: >%(logicalunittype)s<, "
"k2xa: >%(k2xa)s<"
msgstr ""
"NV-9FEEE64 ssp: creazione completata, id lavoro: >%(job_id)s<, nome: "
">%(name)s<, dimensione: >%(size)s<, thin: >%(thin)s<, tipounitàlogica: "
">%(logicalunittype)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:416
#, python-format
msgid ""
"ssp: failed during _delete_lu of LU w/ with unique_device_id: "
">%(lu_udid)s<,  message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: errore durante _delete_lu di LU con id dispositivo univoco: "
">%(lu_udid)s<,  messaggio: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:431
#, python-format
msgid ""
"ssp: during _clone_lu_by_name, couldnt find lu with src_lu_name: "
">%(src_lu_name)s<, tgt_lu_name: >%(tgt_lu_name)s<"
msgstr ""
"ssp: durante _clone_lu_by_name, impossibile trovare lu con nome lu "
"origine: >%(src_lu_name)s<, nome lu destinazione: >%(tgt_lu_name)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:439
#, python-format
msgid ""
"ssp: during _clone_lu_by_name, found too many lus with src_lu_name: "
">%(src_lu_name)s<, tgt_lu_name: >%(tgt_lu_name)s<"
msgstr ""
"NV-8FDE368 ssp: durante _clone_lu_by_name, trovate troppe lu con nome lu "
"origine: >%(src_lu_name)s<, nome lu destinazione: >%(tgt_lu_name)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:469
#, python-format
msgid ""
"ssp: failure during _clone_lu_bj, clone parameters: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s< msg: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: errore durante _clone_lu_bj, parametri clonazione: udid lu origine: "
">%(src_lu_udid)s<, nome lu destinazione: >%(tgt_lu_name)s< dimensione lu "
"destinazione: >%(tgt_lu_size)s< msg: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:485
#: paxes_cinder/volume/drivers/ssp/ssp.py:547
#, python-format
msgid ""
"ssp: apparent failure during _clone_lu_bj, expecting COMPLETED_OK, but "
"for job_id: >%(job_id)s< got status: >%(status)s< clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-64234D9 ssp: errore apparente durante _clone_lu_bj, previsto "
"COMPLETED_OK, ma per id lavoro: >%(job_id)s< ottenuto stato: >%(status)s<"
" parametri clonazione: udid lu origine: >%(src_lu_udid)s<, nome lu "
"destinazione: >%(tgt_lu_name)s< dimensione lu destinazione: "
">%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:509
#, python-format
msgid ""
"ssp: failure during _clone_lu_bj, during create, clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s< message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: errore durante _clone_lu_bj, durante creazione, parametri "
"clonazione: udid lu origine: >%(src_lu_udid)s<, nome lu destinazione: "
">%(tgt_lu_name)s< dimensione lu destinazione: >%(tgt_lu_size)s< "
"messaggio: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:530
#, python-format
msgid ""
"ssp: failure during _clone_lu_bj, during clone, clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s< message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: errore durante _clone_lu_bj, durante clonazione, parametri "
"clonazione: udid lu origine: >%(src_lu_udid)s<, nome lu destinazione: "
">%(tgt_lu_name)s< dimensione lu destinazione: >%(tgt_lu_size)s< "
"messaggio: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:576
#, python-format
msgid ""
"ssp: failure during _clone_lu_bp, clone parameters: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s< message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: errore durante _clone_lu_bp, parametri clonazione: udid lu origine: "
">%(src_lu_udid)s<, nome lu destinazione: >%(tgt_lu_name)s< dimensione lu "
"destinazione: >%(tgt_lu_size)s< messaggio: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:591
#, python-format
msgid ""
"ssp: apparent failure during _clone_lu_bp, expecting COMPLETED_OK, but "
"for job_id: >%(job_id)s< got status: >%(status)s< clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-21DAFDD ssp: errore apparente durante _clone_lu_bp, previsto "
"COMPLETED_OK, ma per id lavoro: >%(job_id)s< ottenuto stato: >%(status)s<"
" parametri clonazione: udid lu origine: >%(src_lu_udid)s<, nome lu "
"destinazione: >%(tgt_lu_name)s< dimensione lu destinazione: "
">%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:606
#, python-format
msgid ""
"ssp: clone complete, job_id: >%(job_id)s<, src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-330DF39 ssp: clonazione completata, id lavoro: >%(job_id)s<, udid lu "
"origine: >%(src_lu_udid)s<, nome lu destinazione: >%(tgt_lu_name)s< "
"dimensione lu destinazione: >%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:625
msgid "ssp: driver not yet initialized"
msgstr "NV-767C35B ssp: driver non ancora inizializzato"

#: paxes_cinder/volume/drivers/ssp/ssp.py:634
#, python-format
msgid ""
"K2 GET SharedStoragePool time: >%(delta)f< is bigger or equal to "
"update_stats periodic interval: >%(periodic_interval)d<"
msgstr ""
"NV-BB646A1 Tempo GET K2 pool di memoria condiviso: >%(delta)f< superiore "
"o uguale a intervallo periodico di update_stats: >%(periodic_interval)d<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:641
#, python-format
msgid ""
"ssp: during get_volume_stats, failed to refresh shared storage pool with "
"ssp_id: >%(self._ssp.id)s<, message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: durante get_volume_stats, impossibile aggiornare il pool di memoria "
"condiviso con id ssp: >%(self._ssp.id)s<, messaggio: >%(e)s<, k2xa: "
">%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:680
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, while performing vios cluster check, "
"failed to refresh cluster id: >%(self._cluster.id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-AC40CF2 ssp: durante %(duringwhatstage)s, durante l'esecuzione del "
"controllo cluster vios, aggiornamento id cluster: >%(self._cluster.id)s< "
"non riuscito, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:707
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, for vios id: >%(vios.id)s<, "
"OperatingSystemVersion: >%(os_version)s<"
msgstr ""
"ssp: durante %(duringwhatstage)s, per id vios: >%(vios.id)s<, "
"VersioneSistemaOperativo: >%(os_version)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:719
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, vios id: >%(vios.id)s<, running and "
"active"
msgstr ""
"ssp: durante %(duringwhatstage)s, id vios: >%(vios.id)s<, in esecuzione e"
" attivo"

#: paxes_cinder/volume/drivers/ssp/ssp.py:727
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, for cluster id: >%(self._cluster.id)s<, "
"vios state issue, vios id: >%(vios.id)s<: PartitionState: "
">%(vios.partition_state)s< ResourceMonitoringControlState: "
">%(vios.rmc_state)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: durante %(duringwhatstage)s, per id cluster: >%(self._cluster.id)s<,"
" problema di stato vios, id vios: >%(vios.id)s<: StatoPartizione: "
">%(vios.partition_state)s< StatoControlloMonitorRisorsa: "
">%(vios.rmc_state)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:751
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, could not find restricted metadata for "
"volume id: >%(volume_id)s<"
msgstr ""
"ssp: durante %(duringwhatstage)s, impossibile trovare metadati limitati "
"per id volume: >%(volume_id)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:767
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, failed to refresh shared storage pool "
"with ssp_id: >%(self._ssp.id)s<, message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: durante %(duringwhatstage)s, impossibile aggiornare il pool di "
"memoria condiviso con id ssp: >%(self._ssp.id)s<, messaggio: >%(e)s<, "
"k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:780
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, couldnt find lu for volume_id: "
">%(volume_id)s< with: unique_device_id: >%(lu_udid)s< and unit_name: "
">%(lu_name)s<"
msgstr ""
"ssp: durante %(duringwhatstage)s, impossibile trovare lu per id volume: "
">%(volume_id)s< con: id dispositivo univoco: >%(lu_udid)s< e nome unità: "
">%(lu_name)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:791
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, found too many lus for volume_id: "
">%(volume_id)s< with: unique_device_id: >%(lu_udid)s< and unit_name: "
">%(lu_name)s<"
msgstr ""
"NV-338EFD0 ssp: durante %(duringwhatstage)s, trovate troppe lu per id "
"volume: >%(volume_id)s< con: id dispositivo univoco: >%(lu_udid)s< e nome"
" unità: >%(lu_name)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:805
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:342
msgid "enter: do_setup"
msgstr "NV-9097266 enter: do_setup"

#: paxes_cinder/volume/drivers/ssp/ssp.py:825
msgid "ssp: failure during do_setup, cant find hmc."
msgstr "NV-AE8B2E2 ssp: errore durante do_setup, impossibile trovare hmc."

#: paxes_cinder/volume/drivers/ssp/ssp.py:853
#, python-format
msgid ""
"ssp: during do_setup, failed to obtain k2client, k2_url: >%(k2_url)s<, "
"k2_username: >%(k2_username)s<"
msgstr ""
"ssp: durante do_setup, impossibile ottenere k2client, k2_url: "
">%(k2_url)s<, k2_username: >%(k2_username)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:866
#, python-format
msgid ""
"ssp: during do_setup, using hmc_uuid: >%(hmc_uuid)s<, failed to retrieve "
"managementconsole, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: durante do_setup, utilizzando uuid hmc: >%(hmc_uuid)s<, richiamo "
"console di gestione non riuscito, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:875
#, python-format
msgid "ssp: during do_setup, hmc version: >%s<"
msgstr "NV-3F31730 ssp: durante do_setup, versione hmc: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:885
#, python-format
msgid ""
"ssp: during do_setup, using k2_url: >%(k2_url)s<, failed to retrieve "
"cluster, cluster_id: >%(cluster_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: durante do_setup, utilizzando url k2: >%(k2_url)s<, richiamo cluster"
" non riuscito, id cluster: >%(cluster_id)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:904
#, python-format
msgid ""
"ssp: during do_setup, using k2_url: >%(k2_url)s< and cluster_id: "
">%(cluster_id)s< failed to retrieve shared storage pool with ssp_ip: "
">%(ssp_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: durante do_setup, utilizzando url k2: >%(k2_url)s< e id cluster: "
">%(cluster_id)s< richiamo pool di memoria condiviso non riuscito con ip "
"ssp: >%(ssp_id)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:923
#, python-format
msgid "ssp: during do_setup, creating default volume type: >%s<"
msgstr "NV-379E7B0 ssp: durante do_setup, creazione tipo volume predefinito: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:928
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:487
msgid "leave: do_setup"
msgstr "NV-F492AE8 leave: do_setup"

#: paxes_cinder/volume/drivers/ssp/ssp.py:931
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:580
msgid "leave: check_for_setup_error"
msgstr "NV-1C79D46 leave: check_for_setup_error"

#: paxes_cinder/volume/drivers/ssp/ssp.py:981
#: paxes_cinder/volume/drivers/ssp/ssp.py:1009
#: paxes_cinder/volume/drivers/ssp/ssp.py:1050
#: paxes_cinder/volume/drivers/ssp/ssp.py:1149
#: paxes_cinder/volume/drivers/ssp/ssp_product.py:48
#: paxes_cinder/volume/drivers/ssp/ssp_product.py:73
#: paxes_cinder/volume/drivers/ssp/ssp_product.py:145
#, python-format
msgid "ssp: exception: >%s<"
msgstr "NV-31FED69 ssp: eccezione: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:982
msgid "ssp: failed during create_volume"
msgstr "NV-E4EE3DB ssp: errore durante create_volume"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1010
#, python-format
msgid ""
"ssp: failed during delete_volume, lu_udid: >%(lu_udid)s< lu_name: "
">%(lu_name)s< volume id: >%(volume_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-41060EC ssp: errore durante delete_volume, udid lu: >%(lu_udid)s< nome"
" lu: >%(lu_name)s< id volume: >%(volume_id)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1029
#, python-format
msgid "ssp: during create_snapshot, cant find volume_id: >%s<"
msgstr ""
"NV-FDA9D85 ssp: durante create_snapshot, impossibile trovare id volume: "
">%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1051
#, python-format
msgid ""
"ssp: failure during create_snapshot: lu_udid: >%(src_lu_udid)s< lu_name: "
">%(src_lu_name)s< volume id: >%(source_vol_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-ACF24A1 ssp: errore durante create_snapshot: udid lu: "
">%(src_lu_udid)s< nome lu: >%(src_lu_name)s< id volume: "
">%(source_vol_id)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1070
#, python-format
msgid "ssp: during delete_snapshot, couldnt find lu with unit_name: >%s<"
msgstr ""
"NV-FCB5EA8 ssp: durante delete_snapshot, impossibile trovare lu con nome "
"unità: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1077
#, python-format
msgid "ssp: during delete_snapshot, found too many lus with unit_name: >%s<"
msgstr ""
"NV-66B083E ssp: durante delete_snapshot, trovate troppe lu con nome "
"unità: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1105
#, python-format
msgid ""
"ssp: error during create_volume_from_snapshot: snapshot with name: "
">%(snapshot_name)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-F6CFF00 ssp: errore durante create_volume_from_snapshot: istantanea "
"con nome: >%(snapshot_name)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1150
#, python-format
msgid ""
"ssp:  error during create_cloned_volume: src_lu_udid: >%(src_lu_udid)s< "
"src_lu_name: >%(src_lu_name)s< volume id: >%(src_volume_id)s<, k2xa: "
">%(k2xa)s<"
msgstr ""
"NV-24854A9 ssp: errore durante create_cloned_volume: udid lu origine: "
">%(src_lu_udid)s< nome lu origine: >%(src_lu_name)s< id volume: "
">%(src_volume_id)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1211
#, python-format
msgid "stats = %(stats)s"
msgstr "NV-898A2AA statistiche = %(stats)s"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:49
#, python-format
msgid ""
"ssp: while discovering mapped LUs, failed to refresh cluster with "
"cluster_id: >%(self._cluster.id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-347194B ssp: durante il rilevamento delle LU associate, impossibile "
"aggiornare il cluster con id: >%(self._cluster.id)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:59
#, python-format
msgid "Node >%s< has no virtual_io_server. Skipping."
msgstr "NV-C3FDDFD Il nodo >%s< non ha virtual_io_server. Ignorato."

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:74
#, python-format
msgid ""
"ssp: while discovering mapped LUs, in cluster with cluster_id: "
">%(self._cluster.id)s< failed to retrieve vios with managedsystem_id: "
">%(ms_id)s< and virtualioserver_id: >%(vios_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-F12DD40 ssp: durante il rilevamento delle LU associate, nel cluster "
"con id: >%(self._cluster.id)s< impossibile richiamare vios con id sistema"
" gestito: >%(ms_id)s< e id vios: >%(vios_id)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:115
msgid ""
"No volume statistics available, either driver has not been initialized or"
" there is a problem w/ the driver, check cinder logs."
msgstr ""
"NV-A8A5D70 Non sono disponibili statistiche di volume, il driver non è "
"stato inizializzato o esiste un problema con il driver, controllare i log"
" cinder. "

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:146
#, python-format
msgid ""
"ssp: while discovering volumes, failed to refresh shared storage pool "
"with ssp_id: >%(self._ssp.id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-7BF09DB ssp: durante il rilevamento dei volumi, impossibile aggiornare"
" il pool di memoria condivisa con id: >%(self._ssp.id)s<, k2xa: "
">%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:173
msgid ""
"This volume is not a candidate for management because it is already "
"attached to a virtual machine.  To manage this volume with PowerVC, you "
"must bring the virtual machine under management.  Select to manage the "
"virtual machine that has the volume attached.  The attached volume will "
"be automatically included for management."
msgstr ""
"Questo volume non è un candidato per la gestione poiché è già collegato a"
" una macchina virtuale. Per gestire questo volume con PowerVC, è "
"necessario portare la macchina virtuale sotto la gestione. Selezionare di"
" gestire la macchina virtuale che ha il volume collegato. Il volume "
"collegato verrà automaticamente incluso per la gestione. "

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:184
#, python-format
msgid ""
"ssp: during Logical Unit discovery, ssp_id: >%(ssp_id)s<, "
"lu_unique_device_id: >%(lu_unique_device_id)s<, lu_unit_name: "
">%(lu_unit_name)s<, volume is in use and not available for management, "
"k2xa: >%(k2xa)s<"
msgstr ""
"ssp: durante il rilevamento dell'unità logica, id ssp: >%(ssp_id)s<, id "
"dispositivo univoco lu: >%(lu_unique_device_id)s<, nome unità lu: "
">%(lu_unit_name)s<, il volume è in uso e non è disponibile per la "
"gestione, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:200
msgid ""
"Because it is of type VirtualIO_Image, this volume is not a candidate for"
" management. Perhaps, while deleting a PowerVC image, someone chose not "
"to delete the backing storage? If you wish to work with the underlying "
"Shared Storage Pool Logical Unit please use the HMC or VIOS commands."
msgstr ""
"A causa del tipo VirtualIO_Image, questo volume non è un candidato per la"
" gestione. È possibile che, durante l'eliminazione di un'immagine "
"PowerVC, qualcuno abbia scelto di non eliminare la memoria di supporto? "
"Se si desidera gestire l'unità logica (LU) pool di memoria condivisa "
"(SSP) sottostante, utilizzare i comandi HMC o VIOS. "

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:210
#, python-format
msgid ""
"ssp: during Logical Unit discovery, ssp_id: >%(ssp_id)s<, "
"lu_unique_device_id: >%(lu_unique_device_id)s<, lu_unit_name: "
">%(lu_unit_name)s<, volume is of type VirtualIO_Image and not available  "
"for management, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: durante il rilevamento dell'unità logica, id ssp: >%(ssp_id)s<, id "
"dispositivo univoco lu: >%(lu_unique_device_id)s<, nome unità lu: "
">%(lu_unit_name)s<, il volume è di tipo VirtualIO_Image e non è "
"disponibile per la gestione, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:240
#, python-format
msgid "WWPN on node %(node)s: %(wwpn)s"
msgstr "NV-D154765 WWPN sul nodo %(node)s: %(wwpn)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:299
#, python-format
msgid "Required keys %(required)s not found in vdisk dictionary %(dictionary)r"
msgstr ""
"Chiavi richieste %(required)s non trovate in dizionario vdisk "
"%(dictionary)r"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:349
msgid "do_setup: Could not get system name"
msgstr "NV-5732B20 do_setup: impossibile ottenere il nome sistema"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:361
#, python-format
msgid "do_setup: Pool %s does not exist"
msgstr "NV-1B3A18D do_setup: il pool %s non esiste"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:412
#, python-format
msgid ""
"Expected integers for node_count and vdisk_count, svcinfo lsiogrp "
"returned: %(node)s and %(vdisk)s"
msgstr ""
"NV-D7E5D72 Previsti numeri interi per node_count e vdisk_count, "
"restituito svcinfo lsiogrp: %(node)s e %(vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:475
msgid "do_setup: No configured nodes"
msgstr "do_setup: nessun nodo configurato"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:484
#, python-format
msgid "Creating default volume type '%s'"
msgstr "NV-5FF13AA Creazione del tipo di volume predefinito '%s'"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:541
msgid "enter: check_for_setup_error"
msgstr "enter: check_for_setup_error"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:545
msgid "Unable to determine system name"
msgstr "NV-82D9304 Impossibile determinare il nome sistema"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:548
msgid "Unable to determine system id"
msgstr "NV-3C12EE7 Impossibile determinare l'id sistema"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:551
msgid "Unable to determine pool extent size"
msgstr "NV-D455E3E Impossibile determinare la dimensione dell'estensione del pool"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:558
#, python-format
msgid "%s is not set"
msgstr "NV-6919A40 %s non è impostato"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:564
msgid ""
"Password or SSH private key is required for authentication: set either "
"san_password or san_private_key option"
msgstr ""
"NV-6FE00A0 La password o la chiave privata SSH è obbligatoria per "
"l'autenticazione: impostare l'opzione san_password o san_private_key"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:572
#, python-format
msgid ""
"Illegal value %d specified for storwize_svc_flashcopy_timeout: valid "
"values are between 0 and 600"
msgstr ""
"NV-F2E38D9 Valore non consentito %d specificato per "
"storwize_svc_flashcopy_timeout: i valori validi sono compresi tra 0 e 600"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:594
#, python-format
msgid "ensure_export: Volume %(volume_id)s does not reference a vdisk"
msgstr ""
"NV-EF2904A ensure_export: Il volume %(volume_id)s non fa riferimento a un"
" vdisk"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:601
#, python-format
msgid ""
"ensure_export: Volume %(volume_id)s references vdisk %(vdisk)s, which was"
" not found on storage"
msgstr ""
"NV-C3410C4 ensure_export: Il volume %(volume_id)s fa riferimento al vdisk"
" %(vdisk)s, non trovato nella memoria"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:627
#, python-format
msgid "enter: _get_chap_secret_for_host: host name %s"
msgstr "enter: _get_chap_secret_for_host: nome host %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:663
#, python-format
msgid ""
"leave: _get_chap_secret_for_host: host name %(host_name)s with secret "
"%(chap_secret)s"
msgstr ""
"leave: _get_chap_secret_for_host: nome host %(host_name)s con segreto "
"%(chap_secret)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:686
msgid "_create_host: Cannot clean host name. Host name is not unicode or string"
msgstr ""
"NV-ED84213 _create_host: impossibile eseguire il cleanup del nome host. "
"Il nome host non è unicode o una stringa"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:837
#, python-format
msgid "enter: _get_host_from_connector: prefix %s"
msgstr "enter: _get_host_from_connector: prefisso %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:865
#, python-format
msgid ""
"Continue to fall back processing after initial failure to make a host on "
"the SAN controller: %s"
msgstr ""
"NV-41DBBAB Continuare a rallentare l'elaborazione dopo l'errore iniziale "
"per creare un host sul controller SAN: %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:909
#, python-format
msgid "leave: _get_host_from_connector: host %s"
msgstr "leave: _get_host_from_connector: host %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:921
#, python-format
msgid "enter: _create_host: host %s"
msgstr "enter: _create_host: host %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:936
msgid "_create_host: No connector ports"
msgstr "_create_host: Nessuna porta connettore"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:969
#, python-format
msgid "leave: _create_host: host %(host)s - %(host_name)s"
msgstr "leave: _create_host: host %(host)s - %(host_name)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:992
#, python-format
msgid "enter: _map_vol_to_host: vdisk %(vdisk_id)s to host %(host_name)s"
msgstr "enter: _map_vol_to_host: vdisk %(vdisk_id)s per host %(host_name)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1022
msgid ""
"storwize_svc_multihostmap_enabled is set to False, Not allow multi host "
"mapping"
msgstr ""
"NV-ABB7D85 storwize_svc_multihostmap_enabled è impostato su False, Non "
"consentire associazione multihost"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1034
#, python-format
msgid "vdisk %s mapping to multi host"
msgstr "NV-45393AC vdisk %s si associa a più host"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1040
#, python-format
msgid ""
"leave: _map_vol_to_host: LUN %(result_lun)s, vdisk %(vdisk_id)s, host "
"%(host_name)s"
msgstr ""
"leave: _map_vol_to_host: LUN %(result_lun)s, vdisk %(vdisk_id)s, host "
"%(host_name)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1050
#, python-format
msgid "enter: _delete_host: host %s "
msgstr "enter: _delete_host: host %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1058
#, python-format
msgid "leave: _delete_host: host %s "
msgstr "leave: _delete_host: host %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1084
#, python-format
msgid ""
"The connector does not contain the required information: %(connector)s, "
"protocols %(protos)s"
msgstr ""
"NV-6A00D73 Il connettore non contiene le informazioni richieste: "
"%(connector)s, protocolli %(protos)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1105
#, python-format
msgid "Enter: initialize_connection: %s"
msgstr "NV-4DB79BA Enter: initialize_connection: %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1128
#, python-format
msgid "Did not find expected column name in lsvdisk: %s"
msgstr "NV-5EFF8EA Il nome colonna previsto non è stato trovato in lsvdisk: %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1130
#, python-format
msgid "initialize_connection: Missing volume attribute for vdisk %s"
msgstr ""
"NV-4FE8A8D initialize_connection: manca l'attributo del volume per vdisk "
"%s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1142
msgid "_create_host failed to return the host name."
msgstr "_create_host non è riuscito a restituire il nome host."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1164
#, python-format
msgid ""
"initialize_connection: No node found in I/O group %(gid)s for vdisk "
"%(vdisk_id)s"
msgstr ""
"NV-8182517 initialize_connection: Nessun nodo trovato nel gruppo I/O "
"%(gid)s per vdisk %(vdisk_id)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1173
#, python-format
msgid "initialize_connection: Did not find a preferred node for vdisk %s"
msgstr ""
"NV-1DB16EC initialize_connection: Non è stato trovato un nodo preferito "
"per vdisk %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1195
msgid ""
"Could not get FC connection information for the host-volume connection. "
"Is the host configured properly for FC connections?"
msgstr ""
"NV-D8556EE Impossibile ottenere le informazioni di connessione FC per la "
"connessione host-volume. L'host è configurato correttamente per le "
"connessioni FC?"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1210
#, python-format
msgid ""
"initialize_connection: Failed to collect return properties for volume "
"%(vol)s and connector %(conn)s.\n"
msgstr ""
"NV-0A9D0F9 initialize_connection: impossibile raccogliere le proprietà di"
" ritorno per il volume %(vol)s e il connettore %(conn)s.\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1215
#, python-format
msgid ""
"leave: initialize_connection:\n"
" volume: %(vol)s\n"
" connector %(conn)s\n"
" properties: %(prop)s"
msgstr ""
"leave: initialize_connection:\n"
" volume: %(vol)s\n"
" connettore %(conn)s\n"
" proprietà: %(prop)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1233
#, python-format
msgid "enter: terminate_connection: volume %(vol)s with connector %(conn)s"
msgstr "enter: terminate_connection: volume %(vol)s con connettore %(conn)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1246
#, python-format
msgid ""
"terminate_connection: vdisk mismatch: %(err)s. Performing no operation on"
" the storage controller"
msgstr ""
"NV-78DEE4C terminate_connection: mancata corrispondenza vdisk: %(err)s. "
"Non vengono eseguite operazioni sul controller di memoria"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1252
#, python-format
msgid ""
"terminate_connection: vdisk deleted: %(err)s. Performing no operation on "
"the storage controller"
msgstr ""
"NV-0E7CDF3 terminate_connection: vdisk eliminato: %(err)s. Non vengono "
"eseguite operazioni sul controller di memoria"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1265
#, python-format
msgid "Detach volume: failed to lookup host name for vdisk ID: %(vdisk)s"
msgstr ""
"NV-5D2DC5C Scollegamento volume: impossibile ricercare nel nome host l'ID"
" vdisk: %(vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1291
#, python-format
msgid ""
"There was an error when attempting to remove the host disk mappings for "
"volume ID %(vol)s and vdsik ID %(vdisk)s: %(err)s"
msgstr ""
"NV-07BAF93 Si è verificato un errore durante il tentativo di rimuovere le"
" associazioni disco host per l'ID volume %(vol)s e ID vdsik %(vdisk)s: "
"%(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1303
#, python-format
msgid ""
"terminate_connection: No mapping of vdisk %(vdisk_id)s to host "
"%(host_name)s found"
msgstr ""
"NV-0CD2F25 terminate_connection: Nessuna associazione di vdisk "
"%(vdisk_id)s a host %(host_name)s trovata"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1314
#, python-format
msgid "leave: terminate_connection: volume %(vol)s with connector %(conn)s"
msgstr "leave: terminate_connection: volume %(vol)s con connettore %(conn)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1414
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:118
#, python-format
msgid "enter: _create_vdisk: candidate names %s "
msgstr "NV-2D6FE98 enter: _create_vdisk: nomi candidati %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1470
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:218
#, python-format
msgid ""
"_create_vdisk %(name)s - did not find success message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"_create_vdisk %(name)s - non è stato trovato un messaggio di successo "
"nell'output CLI.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1477
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:225
#, python-format
msgid "leave: _create_vdisk: volume %(name)s ID %(id)s "
msgstr "NV-3A4E903 leave: _create_vdisk: volume %(name)s ID %(id)s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1499
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1513
#, python-format
msgid ""
"create FC mapping from %(source)s to %(target)s - did not find success "
"message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"
msgstr ""
"creare associazione FC da %(source)s a %(target)s - non è stato trovato "
"un messaggio di successo nell'output CLI.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1525
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1535
#, python-format
msgid ""
"create FC mapping from %(source)s to %(target)s - did not find mapping id"
" in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"
msgstr ""
"creare associazione FC da %(source)s a %(target)s - non è stato trovato "
"un id associazione nell'output CLI.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1550
#, python-format
msgid ""
"_prepare_fc_map: Failed to prepare FlashCopy from %(source)s to "
"%(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"NV-AD077CD _prepare_fc_map: impossibile preparare FlashCopy da %(source)s"
" a %(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1578
#, python-format
msgid ""
"Unexecpted mapping status %(status)s for mapping %(id)s. Attributes: "
"%(attr)s"
msgstr ""
"Stato associazione imprevisto %(status)s per l'associazione %(id)s. "
"Attributi: %(attr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1590
#, python-format
msgid ""
"Mapping %(id)s prepare failed to complete within the allotted %(to)d "
"seconds timeout. Terminating."
msgstr ""
"NV-46B21B5 La preparazione dell'associazione %(id)s non è stata "
"completata entro il timeout di %(to)d secondi assegnati. Chiusura in "
"corso."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1595
#, python-format
msgid ""
"_prepare_fc_map: Failed to start FlashCopy from %(source)s to %(target)s "
"with exception %(ex)s"
msgstr ""
"NV-B48FD34 _prepare_fc_map: impossibile avviare FlashCopy da %(source)s a"
" %(target)s con l'eccezione %(ex)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1602
#, python-format
msgid "_prepare_fc_map: %s"
msgstr "NV-956CB6C _prepare_fc_map: %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1609
#, python-format
msgid ""
"_start_fc_map: Failed to start FlashCopy from %(source)s to %(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"NV-FCBE987 _start_fc_map: impossibile avviare FlashCopy da %(source)s a "
"%(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1620
#, python-format
msgid ""
"enter: _run_flashcopy: execute FlashCopy from source %(source)s to target"
" %(target)s"
msgstr ""
"enter: _run_flashcopy: eseguire FlashCopy da origine %(source)s a "
"destinazione %(target)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1633
#, python-format
msgid "leave: _run_flashcopy: FlashCopy started from %(source)s to %(target)s"
msgstr "leave: _run_flashcopy: FlashCopy avviata da %(source)s a %(target)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1642
#, python-format
msgid ""
"enter: _create_copy: snapshot with possible names %(names)s from vdisk "
"%(src_vdisk)s"
msgstr ""
"enter: _create_copy: istantanea con nomi possibili %(names)s da vdisk "
"%(src_vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1650
#, python-format
msgid "_create_copy: Source vdisk %s does not exist"
msgstr "NV-8A48F71 _create_copy: vdisk origine %s non esiste"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1662
#, python-format
msgid ""
"_create_copy: cannot get source vdisk %(src)s capacity from vdisk "
"attributes %(attr)s"
msgstr ""
"_create_copy: impossibile ottenere la capacità di vdisk origine %(src)s "
"dagli attributi vdisk %(attr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1681
#, python-format
msgid "leave: _create_copy: snapshot vdisk %(tgt_vdisk)s from vdisk %(src_vdisk)s"
msgstr "leave: _create_copy: istantanea vdisk %(tgt_vdisk)s da vdisk %(src_vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1688
#, python-format
msgid "enter: _get_flashcopy_mapping_attributes: mapping %s"
msgstr "enter: _get_flashcopy_mapping_attributes: associazione %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1711
#, python-format
msgid ""
"leave: _get_flashcopy_mapping_attributes: mapping %(fc_map_id)s, "
"attributes %(attributes)s"
msgstr ""
"leave: _get_flashcopy_mapping_attributes: associazione %(fc_map_id)s, "
"attributi %(attributes)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1719
#, python-format
msgid "enter: _is_vdisk_defined: vdisk %s "
msgstr "enter: _is_vdisk_defined: vdisk %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1721
#, python-format
msgid "leave: _is_vdisk_defined: vdisk %(vdisk)s with %(str)s "
msgstr "leave: _is_vdisk_defined: vdisk %(vdisk)s con %(str)s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1764
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1228
#, python-format
msgid "%(map_id)s [vdisk %(src)s to vdisk %(tgt)s]"
msgstr "%(map_id)s [vdisk %(src)s a vdisk %(tgt)s]"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1777
#, python-format
msgid ""
"To delete vdisk %(vdisk_id)s, increasing copyrate of flashcopy mapping "
"%(map)s from 0 to %(copyrate)s and waiting for completion."
msgstr ""
"NV-0B06E40 Per eliminare il vdisk %(vdisk_id)s, aumentare la velocità di "
"copia dell'associazione flashcopy %(map)s da 0 a %(copyrate)s e attendere"
" il completamento."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1791
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1261
#, python-format
msgid "Vdisk %(id)s not involved in mapping %(src)s -> %(tgt)s"
msgstr "Vdisk %(id)s non coinvolto nell'associazione %(src)s -> %(tgt)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1798
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1268
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, flashcopy mapping %(map)s with "
"status '%(status)s' was removed."
msgstr ""
"NV-4CA8ED6 Per consentire l'eliminazione di vdisk %(vdisk_id)s, "
"l'associazione flashcopy %(map)s con stato '%(status)s' è stata rimossa."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1806
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1276
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, waiting for flashcopy mapping "
"%(map)s with status '%(status)s' to complete."
msgstr ""
"NV-E66FA4E Per consentire l'eliminazione di vdisk %(vdisk_id)s, attendere"
" che l'associazione flashcopy %(map)s con stato '%(status)s' venga "
"completata."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1816
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1286
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, forcing removal of flashcopy "
"mapping %(map)s with status '%(status)s'"
msgstr ""
"NV-824284E Per consentire l'eliminazione di vdisk %(vdisk_id)s, si forza "
"la rimozione dell'associazione flashcopy %(map)s con stato '%(status)s'"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1827
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1300
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, prepared flashcopy mapping "
"%(map)s was removed."
msgstr ""
"NV-211FA49 Per consentire l'eliminazione di vdisk %(vdisk_id)s, "
"l'associazione flashcopy preparata %(map)s è stata rimossa."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1835
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1310
#, python-format
msgid ""
"To delete vdisk %(vdisk_id)s, flashcopy mapping %(map)s with status "
"'idle_or_copied' was removed."
msgstr ""
"NV-DA08F03 Per eliminare vdisk %(vdisk_id)s, l'associazione flashcopy "
"%(map)s con stato 'idle_or_copied' è stata rimossa."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1841
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1318
#, python-format
msgid ""
"To delete vdisk %(vdisk_id)s, waiting for completion of flashcopy mapping"
" %(map)s, which is currently %(progress)s%% complete and has status "
"'%(status)s'."
msgstr ""
"NV-CE3069A Per eliminare vdisk %(vdisk_id)s, attendere il completamento "
"dell'associazione flashcopy %(map)s, attualmente completa al "
"%(progress)s%% e con stato '%(status)s'."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1881
msgid ""
"Flashcopy mapping copy rate is 0. Copy is not in progress. Return to "
"caller."
msgstr ""
"NV-45B5480 La velocità di copia associazione Flashcopy è 0. La copia non "
"è in corso. Restituita al chiamante."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1944
#, python-format
msgid "enter: _delete_vdisk: vdisk %s"
msgstr "enter: _delete_vdisk: vdisk %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1949
#, python-format
msgid "warning: Tried to delete vdisk %s but it does not exist."
msgstr "NV-E47B663 avvertenza: si è tentato di eliminare vdisk %s ma non esiste."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1955
#, python-format
msgid "Removing vdisk %(vdisk_id)s"
msgstr "NV-E18AA05 Rimozione di vdisk %(vdisk_id)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1968
#, python-format
msgid ""
"Hosts mapped to vdisk %(vdisk)s:\n"
"%(out)s"
msgstr ""
"NV-4159ED7 Host associati a vdisk %(vdisk)s:\n"
"%(out)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1974
#, python-format
msgid ""
"Existing FlashCopy mappings:\n"
"%(out)s"
msgstr ""
"NV-A345C87 Associazioni FlashCopy esistenti:\n"
"%(out)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1982
#, python-format
msgid "leave: _delete_vdisk: vdisk %s"
msgstr "leave: _delete_vdisk: vdisk %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1992
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2086
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2135
#, python-format
msgid "adding volume_type_id to volume=%s"
msgstr "NV-86F0410 aggiunta di volume_type_id a volume=%s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2014
#, python-format
msgid ""
"Starting deletion of volume %(volume_id)s.  There is no associated vdisk,"
" so no operation will be performed on the storage controller."
msgstr ""
"NV-04391FA Avvio eliminazione del volume %(volume_id)s.  Non ci sono "
"vdisk associati, quindi non verranno eseguite operazioni sul controller "
"di memoria."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2020
#, python-format
msgid "Starting deletion of volume %(volume_id)s, backed by vdisk %(vdisk_id)s"
msgstr ""
"NV-0C0C004 Avvio eliminazione del volume %(volume_id)s, supportato da "
"vdisk %(vdisk_id)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2032
#, python-format
msgid ""
"delete_volume: vdisk mismatch: %(err)s. Performing no operation on the "
"storage controller"
msgstr ""
"NV-D258084 delete_volume: mancata corrispondenza vdisk: %(err)s. Non "
"vengono eseguite operazioni sul controller di memoria"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2038
#, python-format
msgid ""
"delete_volume: vdisk deleted: %(err)s. Performing no operation on the "
"storage controller"
msgstr ""
"NV-FC2A0B0 delete_volume: vdisk eliminato: %(err)s. Non vengono eseguite "
"operazioni sul controller di memoria"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2075
msgid "create_volume_from_snapshot: Source and destination size differ."
msgstr ""
"NV-5A82296 create_volume_from_snapshot: la dimensione dell'origine e "
"della destinazione sono differenti."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2096
#, python-format
msgid "create_volume_from_snapshot:  Source vdisk %s does not exist"
msgstr "NV-4729BC4 create_volume_from_snapshot:  vdisk origine %s non esiste"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2123
msgid "create_cloned_volume: Source and destination size differ."
msgstr ""
"NV-4DD8AF7 create_cloned_volume: la dimensione dell'origine e della "
"destinazione sono differenti."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2164
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1025
#, python-format
msgid "enter: extend_volume: volume %s"
msgstr "NV-826757D enter: extend_volume: volume %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2174
msgid "extend_volume: Extending a volume with snapshots is not supported."
msgstr ""
"NV-E7C02C3 extend_volume: l'estensione di un volume con le istantanee non"
" è supportata."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2186
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1051
#, python-format
msgid "leave: extend_volume: volume %s"
msgstr "NV-0CDE488 leave: extend_volume: volume %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2202
#, python-format
msgid "enter: migrate_volume: id=%(id)s, host=%(host)s"
msgstr "enter: migrate_volume: id=%(id)s, host=%(host)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2234
msgid "migrate_volume started with more than one vdisk copy"
msgstr "migrate_volume avviato con più di una copia vdisk"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2252
#, python-format
msgid ""
"migrate_volume %(name)s - did not find success message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"migrate_volume %(name)s - non è stato trovato un messaggio di esito "
"positivo nell'output CLI.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2264
msgid "migrate_volume: Could not get vdisk copy data"
msgstr "NV-E8B0820 migrate_volume: impossibile ottenere i dati della copia vdisk"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2279
#, python-format
msgid "leave: migrate_volume: id=%(id)s, host=%(host)s"
msgstr "leave: migrate_volume: id=%(id)s, host=%(host)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2301
msgid "Updating volume stats"
msgstr "Aggiornamento statistiche volume"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2324
msgid "Could not get pool data from the storage"
msgstr "NV-675559D Impossibile ottenere i dati di pool dalla memoria"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2325
msgid "_update_volume_stats: Could not get storage pool data"
msgstr ""
"NV-F6BB258 _update_volume_stats: impossibile ottenere i dati del pool di "
"memoria"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2412
msgid ""
"Illegal value specified for storwize_svc_vol_rsize: set to either a "
"percentage (0-100) or -1"
msgstr ""
"NV-8977C50 Valore non consentito specificato per storwize_svc_vol_rsize: "
"impostare una percentuale (0-100) o su -1"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2418
msgid ""
"Illegal value specified for storwize_svc_vol_warning: set to a percentage"
" (0-100)"
msgstr ""
"NV-80C1898 Valore non consentito specificato per "
"storwize_svc_vol_warning: impostare una percentuale (0-100)"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2425
msgid ""
"Illegal value specified for storwize_svc_vol_grainsize: set to either 32,"
" 64, 128, or 256"
msgstr ""
"NV-8A90F92 Valore non consentito specificato per "
"storwize_svc_vol_grainsize: impostare su 32, 64, 128 o 256"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2432
msgid "System does not support compression"
msgstr "NV-90F35C9 Il sistema non supporta la compressione"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2437
msgid "If compression is set to True, rsize must also be set (not equal to -1)"
msgstr ""
"NV-102C98D Se la compressione è impostata su True, anche rsize deve "
"essere impostato (non uguale a -1)"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2443
#, python-format
msgid ""
"Illegal value %(prot)s specified for storwize_svc_connection_protocol: "
"valid values are %(enabled)s"
msgstr ""
"NV-5EBEB51 Valore %(prot)s non consentito specificato per "
"storwize_svc_connection_protocol: i valori validi sono %(enabled)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2451
#, python-format
msgid "I/O group %(iogrp)d is not valid; available I/O groups are %(avail)s"
msgstr ""
"NV-9E31DDB Il gruppo I/O %(iogrp)d non è valido; i gruppi I/O disponibili"
" sono %(avail)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2465
#, python-format
msgid "enter: _execute_command_and_parse_attributes:  command %s"
msgstr "enter: _execute_command_and_parse_attributes:  comando %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2477
#, python-format
msgid ""
"CLI Exception output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"NV-A3B1CA4 Output eccezione CLI:\n"
" comando: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2494
#, python-format
msgid ""
"leave: _execute_command_and_parse_attributes:\n"
"command: %(cmd)s\n"
"attributes: %(attr)s"
msgstr ""
"leave: _execute_command_and_parse_attributes:\n"
"comando: %(cmd)s\n"
"attributi: %(attr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2513
#, python-format
msgid ""
"_get_hdr_dic: attribute headers and values do not match.\n"
" Headers: %(header)s\n"
" Values: %(row)s"
msgstr ""
"_get_hdr_dic: le intestazioni e i valori dell'attributo non "
"corrispondono.\n"
" Intestazioni: %(header)s\n"
" Valori: %(row)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2521
#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
"stdout: %(out)s\n"
"stderr: %(err)s\n"
msgstr ""
"NV-39015B6 %(fun)s: non riuscito con un output CLI imprevisto.\n"
" Comando: %(cmd)s\n"
"stdout: %(out)s\n"
"stderr: %(err)s\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2535
#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"%(fun)s: non riuscito con un output CLI imprevisto.\n"
" Comando: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2543
#, python-format
msgid "Did not find expected column in %(fun)s: %(hdr)s"
msgstr "NV-BEC3CF8 La colonna prevista non è stata trovata in %(fun)s: %(hdr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:103
#, python-format
msgid ""
"StorwizeSVCProductDriver: start flashcopy mapping polling timer, polling "
"interval: %(intval)s seconds"
msgstr ""
"NV-796256C StorwizeSVCProductDriver: avvio timer di polling "
"dell'associazione flashcopy, intervallo di polling: %(intval)s secondi"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:328
#, python-format
msgid ""
"The volume %(name)s is in the error state and not a candidate for "
"management.  vdisk status: %(status)s  vdisk id: %(vdisk_id)s  vdisk uid:"
" %(vdisk_uid)s  "
msgstr ""
"Il volume %(name)s è in stato di errore e non è candidato per la "
"gestione. Stato vdisk: %(status)s  id vdisk: %(vdisk_id)s  uid vdisk: "
"%(vdisk_uid)s  "

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:592
#, python-format
msgid ""
"The connector %(connector)s does not contain the required keys, which are"
" %(expected_fc_keys)s.or %(expected_iscsi_keys)s"
msgstr ""
"Il connettore %(connector)s non contiene le chiavi richieste, cioè "
"%(expected_fc_keys)s o %(expected_iscsi_keys)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:647
#, python-format
msgid "Incorporating WWPNS for Node %(node_id)s: %(wwpns)s"
msgstr "NV-365ED6F Incorporamento WWPNS per nodo %(node_id)s: %(wwpns)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:659
#, python-format
msgid ""
"Attachment for host '%(host)s' to %(storage)s for volume %(volume)s "
"expects zoning between initiator WWPNs %(initiators)s and target WWPNs "
"%(targets)s"
msgstr ""
"NV-0F22247 Collegamento per host '%(host)s' a %(storage)s per volume "
"%(volume)s prevede la zonatura tra i WWPN iniziatori  %(initiators)s e i "
"WWPN di destinazione %(targets)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:721
#, python-format
msgid "Mapping initiator %(phy)s to node %(node)s"
msgstr "NV-5DC7B55 Associazione iniziatore %(phy)s al nodo %(node)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:766
#, python-format
msgid ""
"Fabric %(fabric)s does not have visibility to any WWPNs in node %(node)s,"
" part of iogrp %(iogrp)s of storage controller %(name)s. WWPNs visible on"
" the fabric are %(visible)s. WWPNs on the controller are %(available)s."
msgstr ""
"Il fabric %(fabric)s non ha visibilità per alcun WWPN nel nodo %(node)s, "
"parte di iogrp %(iogrp)s del controller di memoria %(name)s. WWPN "
"visibili sul fabric sono %(visible)s. WWPN sul controller sono "
"%(available)s."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:811
msgid "Zoning for single fabric, one initiator."
msgstr "NV-6E5D37F Zonatura per fabric singolo, un iniziatore."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:821
msgid "Zoning for single fabric, two initiators."
msgstr "NV-2E0EF21 Zonatura per fabric singolo, due iniziatori."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:835
#, python-format
msgid ""
"Zoning for single fabric, general case due to %(count)s initiators on "
"fabric."
msgstr ""
"NV-D9A5CD2 Zonatura per fabric singolo, caso generale a causa di "
"%(count)s iniziatori sul fabric."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:845
msgid "Zoning for dual fabric, one initiator per fabric."
msgstr "NV-EE35C79 Zonatura per fabric doppio, un iniziatore per fabric."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:864
msgid "Zoning for dual fabric, two initiators per fabric."
msgstr "NV-C638EFA Zonatura per fabric doppio, due iniziatori per fabric."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:884
#, python-format
msgid ""
"Zoning for dual fabric, general case due to %(count1)s initiators on "
"first fabric and %(count2)s initiators on second fabric."
msgstr ""
"NV-4351BA7 Zonatura per fabric doppio, caso generale a causa do "
"%(count1)s iniziatori sul primo fabric e %(count2)s iniziatori sul "
"secondo fabric."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:894
#, python-format
msgid "Zoning for general case due to %(count)s fabrics."
msgstr "NV-0733A1E Zonatura per caso generale a causa di %(count)s fabric."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:911
#, python-format
msgid "Creating zones: %r"
msgstr "NV-70BDC4D Creazione di zone: %r"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:923
#, python-format
msgid "Requested mapping for initiators  %(initiators)s and targets %(targets)s"
msgstr ""
"NV-35F3CC8 Associazione richiesta per iniziatori %(initiators)s e "
"destinazioni %(targets)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:941
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:950
#, python-format
msgid "Returned mapping is %(mapping)s"
msgstr "NV-10E28B0 L'associazione restituita è %(mapping)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:976
#, python-format
msgid "Terminating connection with parameters %(connector)sconnector"
msgstr "NV-4EFE246 Chiusura connessione con parametri %(connector)sconnector"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:986
#, python-format
msgid "Removing zones for initiators: %(initiator_list)s"
msgstr "NV-CC588B5 Rimozione zone per iniziatori: %(initiator_list)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:996
#, python-format
msgid ""
"There was a failure when the zone manager attempted to remove zones "
"created for WWPNs %(wwpns)s during detach of volume %(vol)s."
msgstr ""
"NV-AA064A4 Si è verificato un errore quando il gestore zone ha tentato di"
" rimuovere le zone create per i WWPN %(wwpns)s durante lo scollegamento "
"del volume %(vol)s."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1083
#, python-format
msgid "SSH Pool: %d free, %d waiting, in-flight commands:"
msgstr "NV-F9DD698 Pool SSH: %d liberi, %d in attesa, comandi in corso:"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1087
#, python-format
msgid " %(duration).2f %(commands)s"
msgstr "NV-98D8DC3  %(duration).2f %(commands)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1141
#, python-format
msgid ""
"vdisk %(vdsk)s has been added to the flashcopy mapping delete queue with "
"priority %(pri)s."
msgstr ""
"NV-38E83B6 vdisk %(vdsk)s aggiunto alla coda di eliminazione associazioni"
" flashcopy con priorità %(pri)s."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1149
#, python-format
msgid ""
"Successfully returned from flashcopy mapping waiter for vdisk %(vdsk)s, "
"returned value: %(ret)s, total wait time: %(wt)s seconds."
msgstr ""
"NV-62F28E6 Correttamente restituito dal waiter associazione flashcopy per"
" vdisk %(vdsk)s, valore restituito: %(ret)s, tempo di attesa totale: "
"%(wt)s secondi."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1166
#, python-format
msgid ""
"Exception happened when waiting for flashcopy mapping handling for vdisk "
"%(vdsk)s, total wait time: %(wt)s seconds."
msgstr ""
"NV-71EC636 Si è verificata un'eccezione durante l'attesa della gestione "
"dell'associazione flashcopy per vdisk %(vdsk)s, tempo di attesa totale: "
"%(wt)s secondi."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1172
#, python-format
msgid ""
"Removed flashcopy mappings waiter from waiting queue for vdisk %(vdsk)s "
"deletion."
msgstr ""
"NV-46703B0 Waiter di associazioni flashcopy rimosso dalla coda di attesa "
"per eliminazione vdisk %(vdsk)s."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1183
#, python-format
msgid "Flashcopy mapping delete queue: %(vdsks)s"
msgstr "NV-CA4A211 Coda di eliminazione associazione flashcopy: %(vdsks)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1193
#, python-format
msgid ""
"Flashcopy mapping delete queue: %(cnt)s vdisks pending delete, average "
"wait time: %(avg)s seconds"
msgstr ""
"NV-91BB641 Coda di eliminazione associazione flashcopy: %(cnt)s vdisk con"
" eliminazione in sospeso, tempo di attesa medio: %(avg)s secondi"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1242
#, python-format
msgid "fcmapping_handler: %(err)s"
msgstr "fcmapping_handler: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1245
#, python-format
msgid ""
"fcmapping_handler: to delete vdisk %(vdisk_id)s, increasing copyrate of "
"flashcopy mapping %(map)s from 0 to %(copyrate)s and waiting for "
"completion."
msgstr ""
"NV-EE5BEB1 fcmapping_handler: per eliminare il vdisk %(vdisk_id)s, "
"aumentare la velocità di copia dell'associazione flashcopy %(map)s da 0 a"
" %(copyrate)s e attendere il completamento."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1357
#, python-format
msgid ""
"Exception happened during processing flashcopy mapping per vdisk %(vdsk)s"
" deletion: %(err)s"
msgstr ""
"NV-71C30D1 Si è verificata un'eccezione durante l'elaborazione "
"dell'associazione flashcopy per eliminazione vdisk %(vdsk)s: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1387
#, python-format
msgid ""
"Duration of fcmapping_handler timer: %(runtime)s seconds, %(pct)s%% of "
"fixed polling interval."
msgstr ""
"NV-80870AC Durata timer fcmapping_handler: %(runtime)s secondi, %(pct)s%%"
" di intervallo di polling fisso."

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:93
#, python-format
msgid "Fabric names are not unique: %(fabric_names)s"
msgstr "NV-2ED2D0B Nomi fabric non univoci: %(fabric_names)s"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:261
#, python-format
msgid "Connection established to fabric %(f_name)s"
msgstr "NV-41B567C Connessione stabilita per il fabric %(f_name)s"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:376
#, python-format
msgid "Zones to be created for %(fabric)s are %(zones)r"
msgstr "NV-2E6EE4A Le zone da creare per %(fabric)s sono %(zones)r"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:410
#, python-format
msgid "%(fabric_descriptor)s: deleting zones %(zone_list)s"
msgstr "NV-C3FDFEA %(fabric_descriptor)s:eliminazione zone %(zone_list)s"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:449
#, python-format
msgid "Returned data from get_nameserver_info() is %(info)r"
msgstr "NV-7863F08 I dati restituiti da get_nameserver_info() sono %(info)r"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:122
msgid "Could not connect"
msgstr "NV-07C9AAF Impossibile connettersi"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:124
#, python-format
msgid "SSH Client created for %s"
msgstr "NV-08C2923 Client SSH creato per %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:187
#, python-format
msgid "Failed getting active zone set from %s"
msgstr "NV-373682A Richiamo serie di zone attive da %s non riuscito"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:218
msgid "Malformed zone configuration"
msgstr "NV-9BF2FBF Formato della configurazione della zona non corretto"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:220
#, python-format
msgid "Failed getting active zone set from fabric %s"
msgstr "NV-A5B77A2 Richiamo serie di zone attive dal fabric %s non riuscito"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:259
#, python-format
msgid "Add Zones - Zones passed: %s"
msgstr "NV-8A18A84 Aggiungere zone - Zone passate: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:267
#, python-format
msgid "Adding zone failed. Error in getting active zone set from fabric %s"
msgstr ""
"NV-C692314 Aggiunta della zona non riuscita. Errore durante il richiamo "
"della serie di zone attive dal fabric %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:276
#, python-format
msgid "Zone %(zoneName)s already contains required members"
msgstr "NV-EADDEDC La zona %(zoneName)s contiene già i membri richiesti"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:282
#, python-format
msgid "Deleted Zone before insert : %s"
msgstr "NV-4C9797D Zona eliminata prima dell'inserimento: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:286
#, python-format
msgid "Deleting zone failed %s"
msgstr "NV-C1A773E Eliminazione zona non riuscita %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:294
#, python-format
msgid "Adding zone, cmd to run %s"
msgstr "NV-D2B3DDC Aggiunta della zona, cmd da eseguire %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:301
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:304
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:338
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:341
#, python-format
msgid "Adding zone failed, cmd %s"
msgstr "NV-3F8FCCF Aggiunta della zona non riuscita, cmd %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:312
msgid "No new zones created"
msgstr "NV-145C307 Nessuna nuova zona creata"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:322
#, python-format
msgid "Zoneset create operation failed with output %s"
msgstr ""
"NV-0645570 Operazione di creazione serie di zone non riuscita con output "
"%s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:330
#, python-format
msgid "cfgAdd operation failed : %s"
msgstr "NV-C8F3EB6 Operazione cfgAdd non riuscita: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:343
msgid "Zoning completed"
msgstr "NV-BC5301E Zonatura completata"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:373
#, python-format
msgid "Failed getting active zones from fabric %s"
msgstr "NV-21CE132 Richiamo zone attive dal fabric %s non riuscito"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:395
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:398
#, python-format
msgid "Deleting zones failed, cmd %s"
msgstr "NV-AFACFBC Eliminazione di zone non riuscita, cmd %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:414
#, python-format
msgid "Failed collecting nsshow info for fabric %s"
msgstr "NV-6039569 Raccolta info nsshow per fabric %s non riuscita"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:421
#, python-format
msgid "Failed collecting nscamshow info for fabric %s"
msgstr "NV-A1992B9 Raccolta info nscamshow per fabric %s non riuscita"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:453
#, python-format
msgid "Problem: %(problem)s"
msgstr "NV-D20CB78 Problema: %(problem)s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:471
#, python-format
msgid "Will retry after %(seconds)s seconds..."
msgstr "NV-A7C85C7 Verrà effettuato un nuovo tentativo tra %(seconds)s secondi..."

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:490
#, python-format
msgid "Failed closing SSH connection %s"
msgstr "NV-3EA57B2 Chiusura connessione SSH %s non riuscita"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:512
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:561
#, python-format
msgid "running: '%s'"
msgstr "NV-081F69F in esecuzione: '%s'"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:521
#, python-format
msgid "Returned data was %r"
msgstr "NV-93F16B7 I dati restituiti erano %r"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:535
#, python-format
msgid "Error running command via ssh: %s"
msgstr "NV-20D0255 Errore durante l'esecuzione del comando mediante ssh: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:587
#, python-format
msgid "Error while checking zoning txn status: %s"
msgstr "NV-2D4C6DF Errore durante la verifica dello stato txn della zonatura: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:599
#, python-format
msgid "Executing: %s"
msgstr "NV-4EBB354 Esecuzione di: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:609
#, python-format
msgid "CLI execution returned: %s"
msgstr "NV-538FB7E Esecuzione CLI restituita: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:633
#, python-format
msgid "Error executing command %(cmd)s: %s"
msgstr "Errore durante l'esecuzione del comando %(cmd)s: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:648
#, python-format
msgid "Failed when executing command '%(cmd)s': %(err)s"
msgstr "NV-B5BA5A5 Errore durante l'esecuzione del comando '%(cmd)s': %(err)s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:670
#, python-format
msgid "Malformed nameserver output is: %s"
msgstr "NV-07E23F0 Output server nomi non corretto: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:672
msgid "Malformed nameserver info"
msgstr "NV-4331BBF Info server nomi non corrette"

