# Translations template for paxes_cinder.
# Copyright (C) 2014 NCO Corp.
# This file is distributed under the same license as the paxes_cinder
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: paxes_cinder 1.2.1.0\n"
"Report-Msgid-Bugs-To: nguyen1d@us.ibm.com\n"
"POT-Creation-Date: 2014-04-24 16:04-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: paxes_cinder/k2aclient/openstack/common/gettextutils.py:255
msgid "Message objects do not support addition."
msgstr "NV-C33F89C 메시지 오브젝트가 추가를 지원하지 않습니다."

#: paxes_cinder/k2aclient/openstack/common/gettextutils.py:264
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""
"NV-64408AE 비ascii 문자를 포함할 수 있으므로 메시지 오브젝트가 str()을 지원하지 않습니다. unicode() 또는"
" translate()를 대신 사용하십시오."

#: paxes_cinder/k2aclient/openstack/common/procutils.py:129
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr "NV-36AD129 utils.execute에 알 수 없는 키워드 인수를 가져옴: %r"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:144
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "NV-9F83237 명령(서브프로세스) 실행 중: %s"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:169
#: paxes_cinder/k2aclient/openstack/common/procutils.py:241
#, python-format
msgid "Result was %s"
msgstr "NV-E91D667 결과가 %s임"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:181
#, python-format
msgid "%r failed. Retrying."
msgstr "NV-E62FA94 %r에 실패했습니다. 재시도 중입니다."

#: paxes_cinder/k2aclient/openstack/common/procutils.py:220
#, python-format
msgid "Running cmd (SSH): %s"
msgstr "NV-F226973 명령(SSH) 실행 중: %s"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:222
msgid "Environment not supported over SSH"
msgstr "NV-5D0CD8B 환경이 SSH를 통해 지원되지 않음"

#: paxes_cinder/k2aclient/openstack/common/procutils.py:226
msgid "process_input not supported over SSH"
msgstr "NV-E78B011 process_input이 SSH를 통해 지원되지 않음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:512
#, python-format
msgid "DB error: %s"
msgstr "NV-B907287 DB 오류: %s"

#: paxes_cinder/k2aclient/shell.py:100
msgid "Print debugging output"
msgstr "디버깅 출력 인쇄"

#: paxes_cinder/api/plugins/__init__.py:31
#, python-format
msgid "Failed to load extension %(name)s: %(ex)s"
msgstr "NV-E1E174C 확장 %(name)s을(를) 로드하는 데 실패함: %(ex)s"

#: paxes_cinder/volume/manager.py:1275
#, python-format
msgid "Driver %s does not implement Discover Driver"
msgstr "NV-DA200A2 드라이버 %s이(가) 드라이버 감지를 구현하지 않음"

#: paxes_cinder/exception.py:16
#, python-format
msgid "Connection control failure: %(reason)s"
msgstr "NV-BFC4353 연결 제어 실패: %(reason)s"

#: paxes_cinder/exception.py:20
#, python-format
msgid "Zone operation failed: %(reason)s"
msgstr "NV-A619680 구역 조작에 실패함: %(reason)s"

#: paxes_cinder/exception.py:24
#, python-format
msgid "FC SAN Lookup failure: %(reason)s"
msgstr "NV-1316051 FC SAN 검색 실패: %(reason)s"

#: paxes_cinder/exception.py:32
#, python-format
msgid "Internal Misconfiguration detected: %(reason)s"
msgstr "NV-C9F5A2A 내부의 잘못된 구성이 발견됨: %(reason)s"

#: paxes_cinder/exception.py:58
#, python-format
msgid "Fabric '%(display_name)s' (%(username)s@%(ip)s:%(port)s)"
msgstr "NV-097D384 패브릭 '%(display_name)s' (%(username)s@%(ip)s:%(port)s)"

#: paxes_cinder/exception.py:93
#, python-format
msgid "%(descriptor)s: %(message)s"
msgstr "NV-12DC37C %(descriptor)s: %(message)s"

#: paxes_cinder/exception.py:142
#, python-format
msgid "%(problem)s: %(err)s"
msgstr "NV-7FA8022 %(problem)s: %(err)s"

#: paxes_cinder/exception.py:164
msgid "Could not authenticate with the specified credentials"
msgstr "NV-BB4FAEC 지정된 신임 정보로 인증할 수 없음"

#: paxes_cinder/exception.py:174
#, python-format
msgid "Timeout (%(timeout)s seconds) when attempting to connect"
msgstr "NV-3AB9750 연결 시도 시 제한시간 %(timeout)s초"

#: paxes_cinder/exception.py:184
#, python-format
msgid "Timeout (%(timeout)s seconds) when executing command %(cmd)s"
msgstr "NV-17277CD 명령 %(cmd)s 실행 시 제한시간 %(timeout)s초"

#: paxes_cinder/exception.py:193
#, python-format
msgid "Could not connect: %(error)s %(detail)s"
msgstr "NV-2251927 연결할 수 없음: %(error)s %(detail)s"

#: paxes_cinder/exception.py:201
#, python-format
msgid ""
"Another transaction was already in progress when attempting to execute "
"command '%(cmd)s'"
msgstr "NV-B3EE2A1 명령 '%(cmd)s' 실행을 시도할 때 다른 트랜잭션이 이미 진행 중임"

#: paxes_cinder/exception.py:209
#, python-format
msgid ""
"Zone DB exceeded size limits when executing command '%(cmd)s', which "
"returned '%(res)s'"
msgstr "NV-3D73335 명령 '%(cmd)s' 실행 시 구역 DB가 크기 한계를 초과함, '%(res)s'이(가) 리턴됨"

#: paxes_cinder/exception.py:218
#, python-format
msgid "The CLI command '%(cmd)s' returned an unexpected response '%(res)s'"
msgstr "NV-6BC3B8F CLI 명령 '%(cmd)s'에서 예상치 못한 응답 '%(res)s'을(를) 리턴함"

#: paxes_cinder/exception.py:240
#, python-format
msgid "Storage %(display_name)s (%(username)s@%(ip)s:%(port)s)"
msgstr "NV-FD8FAF8 스토리지 %(display_name)s (%(username)s@%(ip)s:%(port)s)"

#: paxes_cinder/exception.py:272
msgid "No more host definitions can be created"
msgstr "NV-FAE0982 추가 호스트 정의를 작성할 수 없음"

#: paxes_cinder/exception.py:281
msgid "No more flashcopy mappings can be created"
msgstr "NV-5071C44 추가 flashcopy 맵핑을 작성할 수 없음"

#: paxes_cinder/exception.py:289
msgid "Could not connect, possibly due to too many connections."
msgstr "NV-16C6099 연결할 수 없습니다. 연결이 너무 많을 수 있습니다."

#: paxes_cinder/exception.py:297
#, python-format
msgid ""
"Could not map vdisk %(vdisk_id)s to host %(host)s because it is already "
"mapped to another host"
msgstr ""
"NV-4B128AE 이미 다른 호스트에 맵핑되었으므로 vdisk %(vdisk_id)s을(를) 호스트 %(host)s에 맵핑할 수 "
"없음"

#: paxes_cinder/exception.py:312
#, python-format
msgid "vdisk %(vdisk_id)s does not exist"
msgstr "NV-8AE54C7 vdisk %(vdisk_id)s이(가) 없음"

#: paxes_cinder/exception.py:322
msgid "No common fabrics between virtual machine and storage"
msgstr "NV-E5685D0 가상 머신 및 스토리지 사이에 공통 패브릭이 없음"

#: paxes_cinder/exception.py:339
#, python-format
msgid ""
"vdisk %(vdisk_id)s has been deleted and recreated. Expected UID is "
"%(expected_uid)s, current UID is %(current_uid)s"
msgstr ""
"NV-78057E1 vdisk %(vdisk_id)s이(가) 삭제되어 재작성되었습니다. 예상 UID는 "
"%(expected_uid)s이고 현재 UID는 %(current_uid)s입니다."

#: paxes_cinder/exception.py:350
#, python-format
msgid ""
"Not enough space left on storage host %(host)s to extend the volume "
"%(volume_id)s"
msgstr "NV-EA431AC 스토리지 호스트 %(host)s에 남은 공간이 부족하므로 볼륨 %(volume_id)s을(를) 확장할 수 없음"

#: paxes_cinder/exception.py:360
msgid ""
"Flashcopy is in progress for boot volume, volume size didn't change. "
"Please try again later."
msgstr "NV-461A839 Flashcopy가 부트 볼륨에서 진행 중이고, 볼륨 크기가 변경되지 않았습니다. 나중에 다시 시도하십시오."

#: paxes_cinder/exception.py:367
#, python-format
msgid ""
"vdisk %(vdisk_id)s is source of snapshot flashcopy and fcmap %(fcmapid)s "
"cannot be removed."
msgstr ""
"NV-CB3AB35 vdisk %(vdisk_id)s이(가) 스냅샷 flashcopy의 소스이고 fcmap "
"%(fcmapid)s을(를) 제거할 수 없습니다."

#: paxes_cinder/db/sqlalchemy/migrate_repo/versions/001_ibm_paxes_v1r2.py:35
#, python-format
msgid "Exception creating table %(table)s: %(ex_str)s"
msgstr "테이블 %(table)s 작성 중 예외 발생: %(ex_str)s"

#: paxes_cinder/db/sqlalchemy/migrate_repo/versions/001_ibm_paxes_v1r2.py:55
#, python-format
msgid "Exception dropping table %(table)s: %(ex_str)s"
msgstr "테이블 %(table)s 삭제 중 예외 발생: %(ex_str)s"

#: paxes_cinder/fabric/map_initiators.py:70
msgid ""
"Could not obtain a fabric manager client. Fibre Channel switch fabrics "
"may not be registered."
msgstr "NV-6EF68AC 패브릭 관리자 클라이언트를 확보할 수 없습니다. 파이버 채널 스위치 패브릭이 등록되지 않을 수 있습니다."

#: paxes_cinder/fabric/map_initiators.py:85
#, python-format
msgid ""
"Unable to retrieve WWPN initiator information from one or more fabric "
"switches. Error: %(ex_str)s"
msgstr "하나 이상의 패브릭 스위치에서 WWPN 이니시에이터 정보를 검색할 수 없습니다. 오류: %(ex_str)s"

#: paxes_cinder/fabric/map_initiators.py:119
msgid "No fabrics registered."
msgstr "NV-0AA1511 패브릭이 등록되지 않았습니다."

#: paxes_cinder/fabric/map_initiators.py:124
msgid "No fabric names registered."
msgstr "NV-A4978F0 패브릭 이름이 등록되지 않았습니다."

#: paxes_cinder/k2aclient/client.py:104
msgid ", during get"
msgstr "NV-C758794 , get 중"

#: paxes_cinder/k2aclient/client.py:127
msgid ", during refresh"
msgstr "NV-A09A06D , 새로 고치는 중"

#: paxes_cinder/k2aclient/client.py:148
#: paxes_cinder/k2aclient/client.py:172
msgid ", during create"
msgstr "NV-16332E7 , 작성 중"

#: paxes_cinder/k2aclient/client.py:193
msgid ", during delete"
msgstr "NV-B5BE602 , 삭제 중"

#: paxes_cinder/k2aclient/client.py:207
msgid ", during runJob"
msgstr "NV-9A12874 , runJob 중"

#: paxes_cinder/k2aclient/client.py:219
msgid ", during readJob"
msgstr "NV-EA9B845 , readJob 중"

#: paxes_cinder/k2aclient/client.py:234
msgid ", during authenticate"
msgstr "NV-DD96084 , 인증 중"

#: paxes_cinder/k2aclient/client.py:247
#, python-format
msgid ""
"k2aclient: while obtaining client, invalid client version >%(version)s<. "
"must be one of: >%(versions)s<"
msgstr ""
"k2aclient: 클라이언트를 확보하는 중 클라이언트 버전 >%(version)s<이(가) 올바르지 않습니다. 다음 중 하나여야 "
"합니다. >%(versions)s<"

#: paxes_cinder/k2aclient/exceptions.py:46
#: paxes_cinder/k2aclient/exceptions.py:307
#, python-format
msgid ", exception diagnostics have been written to: >%s<"
msgstr ", 예외 진단이 다음에 기록됨: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:56
#, python-format
msgid "Other Exception off of K2: >%s<"
msgstr "NV-92A2EB5 K2에서 기타 예외 발생: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:58
#: paxes_cinder/k2aclient/exceptions.py:78
#: paxes_cinder/k2aclient/exceptions.py:88
#: paxes_cinder/k2aclient/exceptions.py:105
#, python-format
msgid ", during: >%s<"
msgstr ", 다음 수행 중: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:66
#, python-format
msgid "SSL exception off of K2: >%s<"
msgstr "NV-852F651 K2에서 SSL 예외 발생: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:76
#, python-format
msgid "Connection exception off of K2: >%s<"
msgstr "NV-DE65980 K2에서 연결 예외 발생: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:86
#, python-format
msgid "Timeout exception off of K2: >%s<"
msgstr "NV-DC27602 K2에서 제한시간 초과 예외 발생: >%s<"

#: paxes_cinder/k2aclient/exceptions.py:100
#, python-format
msgid "K2Error off of K2: >%(msg)s<, Status: >%(status)d<, k2Error: >%(k2error)s<"
msgstr "K2에서 K2Error 발생: >%(msg)s<, 상태: >%(status)d<, k2Error: >%(k2error)s<"

#: paxes_cinder/k2aclient/exceptions.py:122
msgid "Bad Request"
msgstr "잘못된 요청"

#: paxes_cinder/k2aclient/exceptions.py:130
msgid "Unauthorized"
msgstr "권한 없음"

#: paxes_cinder/k2aclient/exceptions.py:144
msgid "Forbidden"
msgstr "금지됨"

#: paxes_cinder/k2aclient/exceptions.py:158
msgid "Not Found"
msgstr "찾을 수 없음"

#: paxes_cinder/k2aclient/exceptions.py:167
msgid "Method Not Allowed"
msgstr "허용되지 않은 메소드"

#: paxes_cinder/k2aclient/exceptions.py:177
msgid "Not Acceptable"
msgstr "승인할 수 없음"

#: paxes_cinder/k2aclient/exceptions.py:189
msgid "Conflict"
msgstr "충돌"

#: paxes_cinder/k2aclient/exceptions.py:197
msgid "PreCondition failed"
msgstr "PreCondition 실패함"

#: paxes_cinder/k2aclient/exceptions.py:206
msgid "Request Body Too Large"
msgstr "요청 본문이 너무 큼"

#: paxes_cinder/k2aclient/exceptions.py:216
msgid "Unsupported Media Type"
msgstr "지원되지 않는 매체 유형"

#: paxes_cinder/k2aclient/exceptions.py:225
msgid "Internal Server Error"
msgstr "내부 서버 오류"

#: paxes_cinder/k2aclient/exceptions.py:235
msgid "Not Implemented"
msgstr "구현되지 않음"

#: paxes_cinder/k2aclient/exceptions.py:245
msgid "Service Unavailable"
msgstr "서비스를 사용할 수 없음"

#: paxes_cinder/k2aclient/exceptions.py:255
msgid "HTTP Version Not Supported"
msgstr "HTTP 버전이 지원되지 않음"

#: paxes_cinder/k2aclient/exceptions.py:263
msgid "Not Classified"
msgstr "분류되지 않음"

#: paxes_cinder/k2aclient/k2exclogger.py:114
#, python-format
msgid ""
"k2aclient: during FFDC, cant create k2 exception log directory: >%s<, "
"will disable k2 exception logging .."
msgstr ""
"NV-ED6E0F0 k2aclient: FFDC 중, k2 예외 로그 디렉토리를 작성할 수 없음: >%s<, k2 예외 로깅을 "
"사용하지 않습니다."

#: paxes_cinder/k2aclient/k2exclogger.py:123
#, python-format
msgid ""
"k2aclient: during FFDC, cant write to k2 exception log directory: >%s<, "
"will disable k2 exception logging .."
msgstr ""
"NV-6373107 k2aclient: FFDC 중, k2 예외 로그 디렉토리를 쓸 수 없음: >%s<, k2 예외 로깅을 사용하지"
" 않습니다."

#: paxes_cinder/k2aclient/k2exclogger.py:146
#, python-format
msgid ""
"k2aclient: during FFDC,  caught an exception while writing to log "
"directory: >%s<, will disable k2 exception logging .."
msgstr ""
"NV-3376E54 k2aclient: FFDC 중, 로그 디렉토리에 작성하는 중 예외 발생: >%s<, k2 예외 로깅을 사용하지"
" 않습니다."

#: paxes_cinder/k2aclient/shell.py:59
#, python-format
msgid ""
"k2aclient: error: %(errmsg)s\n"
"Try '%(mainp)s help %(subp)s' for more information.\n"
msgstr ""
"k2aclient: 오류: %(errmsg)s\n"
"자세한 정보는 '%(mainp)s help %(subp)s'(으)로 확인하십시오.\n"

#: paxes_cinder/k2aclient/shell.py:80
msgid "See \"k2a help COMMAND\" for help on a specific command."
msgstr "특정 명령에 대한 도움말은 \"k2a help COMMAND\"로 확인하십시오."

#: paxes_cinder/k2aclient/shell.py:106
msgid "Accepts 1,defaults to env[K2A_API_VERSION]."
msgstr "수락 1, env[K2A_API_VERSION]으로 기본값이 지정됩니다."

#: paxes_cinder/k2aclient/shell.py:109
msgid "Number of retries when attempting k2 operations."
msgstr "k2 조작을 시도하는 재시도 횟수."

#: paxes_cinder/k2aclient/shell.py:119
msgid "url for k2 hmc, defaults to env[K2_URL]."
msgstr "k2 hmc에 대한 url, env[K2_URL]로 기본값이 지정됩니다."

#: paxes_cinder/k2aclient/shell.py:125
msgid "k2 username, defaults to env[K2_USERNAME]."
msgstr "k2 사용자 이름, env[K2_USERNAME]으로 기본값이 지정됩니다."

#: paxes_cinder/k2aclient/shell.py:131
msgid "k2 password, defaults to env[K2_PASSWORD]."
msgstr "k2 비밀번호, env[K2_PASSWORD]로 기본값이 지정됩니다."

#: paxes_cinder/k2aclient/shell.py:138
msgid ""
"k2 auditmemento, defaults to, if set, env[K2_AUDITMEMENTO], otherwise to "
"\"k2a\"."
msgstr "k2 auditmemento, 설정된 경우 기본값: env[K2_AUDITMEMENTO], 그렇지 않은 경우: \"k2a\"."

#: paxes_cinder/k2aclient/shell.py:145
msgid "k2 certpath, defaults to, if set, env[K2_CERTPATH], otherwise to None."
msgstr "k2 certpath, 설정된 경우 기본값: env[K2_CERTPATH], 그렇지 않은 경우: 없음"

#: paxes_cinder/k2aclient/shell.py:152
msgid ""
"log directory, defaults to, if set, env[K2A_LOGDIR], otherwise to None. "
"None turnsoff file logging"
msgstr "로그 디렉토리, 설정된 경우 기본값: env[K2A_LOGDIR], 그렇지 않은 경우: 없음. 없음은 파일 로깅을 끕니다."

#: paxes_cinder/k2aclient/shell.py:171
msgid ""
"directory where k2aexc subdirectorywill be placedie \"<excdir>/k2aexc\", "
"defaults to, if set, env[K2A_EXCDIR], otherwise to /tmp"
msgstr ""
"k2aexc 서브디렉토리가 배치되는 디렉토리: \"<excdir>/k2aexc\", 설정된 경우 기본값: "
"env[K2A_EXCDIR], 그렇지 않은 경우: /tmp"

#: paxes_cinder/k2aclient/shell.py:309
msgid ""
"k2aclient: you must provide a url for a k2 hmc via either --k2-url or "
"env[K2_URL]"
msgstr "NV-D20F7FC k2aclient: --k2-url 또는 env[K2_URL]을 통해 k2에 대한 url을 제공해야 함"

#: paxes_cinder/k2aclient/shell.py:315
msgid ""
"k2aclient: you must provide a k2 username via either --k2-username or "
"env[K2_USERNAME]"
msgstr ""
"NV-996BCEC k2aclient: --k2-username 또는 env[K2_USERNAME]을 통해 k2 사용자 이름을 "
"제공해야 함"

#: paxes_cinder/k2aclient/shell.py:321
msgid ""
"k2aclient: you must provide a k2 password via either --k2-password or via"
" env[K2_PASSWORD]"
msgstr ""
"NV-EB948AA k2aclient: --k2-password 또는 env[K2_PASSWORD]를 통해 k2 비밀번호를 제공해야"
" 함"

#: paxes_cinder/k2aclient/shell.py:355
#, python-format
msgid "Display help for %s"
msgstr "%s에 대한 도움말 표시"

#: paxes_cinder/k2aclient/shell.py:364
#, python-format
msgid "k2aclient:>%s< is not a valid subcommand"
msgstr "NV-DAC982A k2aclient:>%s<이(가) 올바른 하위 명령이 아님"

#: paxes_cinder/k2aclient/shell.py:384
msgid "... terminating k2a client"
msgstr "NV-56344DF ... k2a 클라이언트 종료 중"

#: paxes_cinder/k2aclient/shell.py:389
#, python-format
msgid "ERROR: type: >%(type)s<, msg: >%(e)s<"
msgstr "NV-9BF8F90 오류: 유형: >%(type)s<, 메시지: >%(e)s<"

#: paxes_cinder/k2aclient/utils.py:101
#, python-format
msgid "k2aclient: no %(res)s with a name or ID of '%(name_or_id)s' exists."
msgstr "NV-63A28A2 k2aclient: %(res)s(이름 또는 ID: '%(name_or_id)s')이(가) 없습니다."

#: paxes_cinder/k2aclient/utils.py:108
#, python-format
msgid ""
"k2aclient: multiple %(res)s matches found for '%(name_or_id)s', use an ID"
" to be more specific."
msgstr ""
"NV-9ACDF38 k2aclient: 여러 %(res)s 일치 항목을 찾았습니다('%(name_or_id)s'과(와) 일치함). "
"보다 구체적인 ID를 사용하십시오."

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:144
#: paxes_cinder/k2aclient/v1/virtualioserver_manager.py:138
#, python-format
msgid "during directory preparation, cant create directory:  >%s<"
msgstr "NV-64A449C 디렉토리 준비 중에 디렉토리를 작성할 수 없음: >%s<"

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:150
#: paxes_cinder/k2aclient/v1/virtualioserver_manager.py:144
#, python-format
msgid "during directory preparation, cant write to directory:  >%s<"
msgstr "NV-C96CB61 디렉토리 준비 중에 디렉토리에 쓸 수 없음: >%s<"

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:181
#: paxes_cinder/k2aclient/k2asample/k2_ssp_etag_test.py:44
#: paxes_cinder/k2aclient/k2asample/tool_ssp_simulation.py:228
#, python-format
msgid "Node: >%s<, has no virtual_io_server, continuing ..."
msgstr "NV-60D657D 노드: >%s<에 virtual_io_server가 없음, 계속 중..."

#: paxes_cinder/k2aclient/k2asample/k2_ssp_cluster_vios_snap.py:192
#: paxes_cinder/k2aclient/k2asample/k2_ssp_etag_test.py:55
#: paxes_cinder/k2aclient/k2asample/tool_ssp_simulation.py:239
#, python-format
msgid "Failed to retrieve node: >%s<, msg: >%s<, continuing ..."
msgstr "NV-0B99A4D 노드: >%s< 검색 실패, 메시지: >%s<, 계속 중..."

#: paxes_cinder/k2aclient/openstack/common/lockutils.py:276
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s for method \"%(method)s\"..."
msgstr "NV-F6B31F1 \"%(method)s\" 메소드에 대한 %(path)s에 있는 파일 잠금 \"%(lock)s\" 해제..."

#: paxes_cinder/k2aclient/v1/cluster_manager.py:98
#, python-format
msgid ""
"k2aclient: during lu_linked_clone_of_lu, source_lu_udid: "
">%(source_lu_udid)s<, not in sharedstoragepool: >%(ssp.id)s<"
msgstr ""
"NV-69F0ACE k2aclient: lu_linked_clone_of_lu 중, source_lu_udid: "
">%(source_lu_udid)s<, sharedstoragepool에 있지 않음: >%(ssp.id)s<"

#: paxes_cinder/k2aclient/v1/cluster_manager.py:221
#, python-format
msgid ""
"k2aclient: for cluster id : >%(cluster.id)s<,  during lu_linked_clone, "
"for SourceUDID: >%(sourceUDID)s<, and DestinationUDID: "
">%(destinationUDID)s<, experienced job failure, job_id: "
">%(jresponse.job_id)s<, status: >%(jresponse.status)s<, input K2 job "
"diagnostics have been written to: >%(diagfspeci)s<, response k2 job "
"diagnostics have been written to: >%(diagfspec)s<"
msgstr ""
"k2aclient: 클러스터 id: >%(cluster.id)s<에 대해, lu_linked_clone 중, SourceUDID: "
">%(sourceUDID)s< 및 DestinationUDID: >%(destinationUDID)s<에서 작업 실패 발생, "
"job_id: >%(jresponse.job_id)s<, 상태: >%(jresponse.status)s<, 입력 K2 작업 진단이 "
">%(diagfspeci)s<에 기록됨, 응답 k2 작업 진단이 >%(diagfspec)s<에 기록됨"

#: paxes_cinder/k2aclient/v1/cluster_manager.py:335
#, python-format
msgid ""
"k2aclient: for cluster id : >%(cluster.id)s<,  during lu_create, for "
"lu_unit_name: >%(lu_unit_name)s<, with lu_unit_capacity: "
">%(lu_unit_capacity)s<, experienced job failure, job_id: "
">%(jresponse.job_id)s<, status: >%(jresponse.status)s<, input K2 job "
"diagnostics have been written to: >%(diagfspeci)s<, response k2 job "
"diagnostics have been written to: >%(diagfspec)s<"
msgstr ""
"k2aclient: 클러스터 id: >%(cluster.id)s<에 대해, lu_create 중, lu_unit_name: "
">%(lu_unit_name)s<, lu_unit_capacity: >%(lu_unit_capacity)s<에서 작업 실패 발생, "
"job_id: >%(jresponse.job_id)s<, 상태: >%(jresponse.status)s<, 입력 K2 작업 진단이 "
">%(diagfspeci)s<에 기록됨, 응답 k2 작업 진단이 >%(diagfspec)s<에 기록됨"

#: paxes_cinder/k2aclient/v1/logicalpartition_manager.py:126
#: paxes_cinder/k2aclient/v1/logicalpartition_manager.py:191
#, python-format
msgid ""
"k2aclient: during power_on, for LogicalPartition: "
">%(logicalpartition.id)s<, failed to power on due to job failure, job_id:"
" >%(jresponse.job_id)s<, status: >%(jresponse.status)s<, input K2 job "
"diagnostics have been written to: >%(diagfspeci)s<, response k2 job "
"diagnostics have been written to: >%(diagfspec)s<"
msgstr ""
"k2aclient: power_on 중, LogicalPartition: >%(logicalpartition.id)s<에서 작업 "
"실패로 인해 전원 켜기 실패, job_id: >%(jresponse.job_id)s<, 상태: "
">%(jresponse.status)s<, 입력 K2 작업 진단이 >%(diagfspeci)s<에 기록됨, 응답 k2 작업 진단이 "
">%(diagfspec)s<에 기록됨"

#: paxes_cinder/k2aclient/v1/managementconsole_manager.py:77
#, python-format
msgid ""
"CLIRunner: ManagementConsole: >%(mc.id)s<, failed to run cmd: >%(cmd)s< "
"due to job failure, job_id: >%(jresponse.job_id)s<, status: "
">%(jresponse.status)s<, input K2 job diagnostics have been written to: "
">%(diagfspeci)s<,  response k2 job diagnostics have been written to: "
">%(diagfspec)s<"
msgstr ""
"CLIRunner: ManagementConsole: >%(mc.id)s<, 작업 실패로 인해 >%(cmd)s< 명령 실행 실패, "
"job_id: >%(jresponse.job_id)s<, 상태: >%(jresponse.status)s<, 입력 K2 작업 진단이 "
">%(diagfspeci)s<에 기록됨, 응답 k2 작업 진단이 >%(diagfspec)s<에 기록됨"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:108
#, python-format
msgid ""
"SharedStoragePool: While attempting to access Cluster: >%s<, unable to "
"connect to HMC: >%s<"
msgstr "SharedStoragePool: 클러스터: >%s<에 액세스하는 중 HMC: >%s<에 연결할 수 없음"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:110
msgid "Check the HMC and its configuration."
msgstr "HMC 및 해당 구성을 확인하십시오."

#: paxes_cinder/k2aclient/v1/paxes_manager.py:111
#, python-format
msgid "SharedStoragePool: Able to connect to HMC: >%s< for Cluster: >%s<"
msgstr "SharedStoragePool: HMC: >%s<에 연결할 수 있음(클러스터: >%s<에서)"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:113
#, python-format
msgid "SharedStoragePool: Couldn't access Cluster: >%s<"
msgstr "SharedStoragePool: 클러스터에 액세스할 수 없음: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:114
msgid "Check the PowerVC SharedStoragePool configuration"
msgstr "PowerVC SharedStoragePool 구성 확인"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:115
#, python-format
msgid "SharedStoragePool: Couldn't access SharedStoragePool in Cluster: >%s<"
msgstr "SharedStoragePool: 클러스터에서 SharedStoragePool에 액세스할 수 없음: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:117
#: paxes_cinder/k2aclient/v1/paxes_manager.py:122
#: paxes_cinder/k2aclient/v1/paxes_manager.py:127
#: paxes_cinder/k2aclient/v1/paxes_manager.py:133
msgid "Diagnose and repair Cluster"
msgstr "진단 및 클러스터 수리"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:118
#, python-format
msgid ""
"SharedStoragePool: Successfully accessed SharedStoragePool in Cluster: "
">%s<"
msgstr "SharedStoragePool: 클러스터에서 SharedStoragePool에 액세스함: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:120
#, python-format
msgid "SharedStoragePool: Unable to create LogicalUnits in Cluster: >%s<"
msgstr "SharedStoragePool: 클러스터에서 LogicalUnits를 작성할 수 없음: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:123
#, python-format
msgid "SharedStoragePool: LogicalUnit creation functional in Cluster: >%s<"
msgstr "SharedStoragePool: 클러스터에서 LogicalUnit 작성 기능: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:125
#, python-format
msgid "SharedStoragePool: Unable to clone LogicalUnits in Cluster: >%s<"
msgstr "SharedStoragePool: 클러스터에서 LogicalUnits를 복제할 수 없음: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:128
#, python-format
msgid ""
"SharedStoragePool: Unable to clone LogicalUnits in Cluster: >%s<, status:"
" >%s<"
msgstr "SharedStoragePool: 클러스터에서 LogicalUnits를 복제할 수 없음: >%s<, 상태: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:130
#, python-format
msgid "Clone functional in Cluster: >%s<"
msgstr "클러스터에서 기능 복제: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:131
#, python-format
msgid "SharedStoragePool: Unable to delete LogicalUnits in Cluster: >%s<"
msgstr "SharedStoragePool: 클러스터에서 LogicalUnits를 삭제할 수 없음: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:134
#, python-format
msgid "SharedStoragePool: LogicalUnit deletion functional in Cluster: >%s<"
msgstr "SharedStoragePool: 클러스터에서 LogicalUnit 삭제 기능: >%s<"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:136
msgid "SharedStoragePool: Not Attempted"
msgstr "SharedStoragePool: 시도되지 않음"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:143
msgid "HMC connectivity"
msgstr "HMC 연결"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:144
msgid "Test connection to an HMC managing the SharedStoragePool"
msgstr "SharedStoragePool을 관리하는 HMC에 대한 연결 테스트"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:147
msgid "Cluster and SharedStoragePool accessibility"
msgstr "클러스터 및 SharedStoragePool 액세스 용이성"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:148
msgid "Test the accessibility of a SharedStoragePool"
msgstr "SharedStoragePool의 액세스 용이성 테스트"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:151
msgid "Create SharedStoragePool LogicalUnits"
msgstr "SharedStoragePool LogicalUnits 작성"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:152
msgid "Test the capability to create SharedStoragePool LogicalUnits"
msgstr "SharedStoragePool LogicalUnits를 작성할 기능 테스트"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:155
msgid "Clone LogicalUnits"
msgstr "LogicalUnits 복제"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:156
msgid "Test the capability to perform a clone"
msgstr "복제를 수행할 기능 테스트"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:159
msgid "Delete SharedStoragePool LogicalUnits"
msgstr "SharedStoragePool LogicalUnits 삭제"

#: paxes_cinder/k2aclient/v1/paxes_manager.py:160
msgid "Test the capability to delete SharedStoragePool LogicalUnits"
msgstr "SharedStoragePool LogicalUnits를 삭제할 기능 테스트"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:112
#, python-format
msgid ""
"k2aclient: during updated_append_lus, cannot update K2 object(s) obtained"
" from a list operation, for ssp: >%s<"
msgstr ""
"NV-CEE080E k2aclient: updated_append_lus 중, 목록 조작에서 확보한 K2 오브젝트를 업데이트할 수 "
"없음, ssp의 경우: >%s<"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:158
#, python-format
msgid "k2aclient: during updated_append_lus, wrong length of lu input tuple: >%d<"
msgstr "NV-B8F5AF7 k2aclient: updated_append_lus 중, lu 입력 튜플 길이가 잘못됨: >%d<"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:192
#, python-format
msgid ""
"k2aclient:  during updated_append_lus, request to add LU unit_name: >%s< "
"failed, name must be unique"
msgstr ""
"NV-F6B87FC k2aclient: updated_append_lus 중, LU unit_name: >%s< 추가 요청 실패, "
"고유해야 함"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:224
#, python-format
msgid ""
"k2aclient: during updated_append_lus, while adding LUs named: "
">%(lunames)s<,  # attempts due to HTTP 412 exceeded: "
">%(self.api.retries)d<"
msgstr ""
"NV-01A9381 k2aclient: updated_append_lus 중, 이름이 >%(lunames)s<인 LU 추가, "
"HTTP 412로 인해 초과된 시도 횟수: >%(self.api.retries)d<"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:260
#, python-format
msgid ""
"k2aclient: during updated_append_lus, cant handle K2 response, K2 "
"reported successful creation of >%(lenlus)d<  lus named: >%(lunames)s<,  "
"attempts: >%(attempts)d<  but only >%(lustoadd)d< LUs were found."
msgstr ""
"k2aclient: updated_append_lus 중, K2 응답을 처리할 수 없음, K2에서 >%(lenlus)d< "
"lu(이름: >%(lunames)s<)의 작성 성공을 보고함, 시도: >%(attempts)d< 그러나 >%(lustoadd)d< "
"LU만 찾았습니다."

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:276
#, python-format
msgid ""
"k2aclient: during updated_append_lus, cant handle K2 response, K2 "
"reported successful creation of >%(lenlus)d< lus named: >%(lunames)s<, "
"attempts: >%(attempts)d< but >%(lustoadd)d< extra LUs were returned."
msgstr ""
"k2aclient: updated_append_lus 중, K2 응답을 처리할 수 없음, K2에서 >%(lenlus)d< "
"lu(이름: >%(lunames)s<)의 작성 성공을 보고함, 시도: >%(attempts)d< 그러나 추가 "
">%(lustoadd)d< LU가 리턴되었습니다."

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:369
#, python-format
msgid ""
"k2aclient: during update_append_lu, programming error, could not find "
"lu_udid: >%(lu_udid)s<, in input ssp for: >%(pool)s<"
msgstr ""
"k2aclient: update_append_lu 중, 프로그래밍 오류, 입력 ssp: >%(lu_udid)s<에 대해 "
"lu_udid: >%(pool)s<을(를) 찾을 수 없음"

#: paxes_cinder/k2aclient/v1/sharedstoragepool_manager.py:390
#, python-format
msgid ""
"k2aclient: during update_append_lu, while deleting LUs w/ udids: "
">%(lu_udids)s<, # attempts due to HTTP 412 exceeded: >%(retries)d<"
msgstr ""
"NV-A3B2A22 k2aclient: update_append_lu 중, udids: >%(lu_udids)s<인 LU 삭제 중,"
" HTTP 412로 인해 초과된 시도 횟수: >%(retries)d<"

#: paxes_cinder/k2aclient/v1/shell.py:55
#, python-format
msgid "k2aclient: during encoding unexpected type: >%s<"
msgstr "NV-AA592CA k2aclient: 인코딩 중, 예상치 않은 유형: >%s<"

#: paxes_cinder/k2aclient/v1/shell.py:205
#: paxes_cinder/k2aclient/v1/shell.py:801
#: paxes_cinder/k2aclient/v1/shell.py:812
msgid "Id of the cluster."
msgstr "클러스터의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:215
msgid "UUID of the cluster containing the LUs."
msgstr "LU를 포함하는 클러스터의 UUID."

#: paxes_cinder/k2aclient/v1/shell.py:218
msgid "UDID of the source logicalunit."
msgstr "소스 logicalunit의 UDID."

#: paxes_cinder/k2aclient/v1/shell.py:221
msgid "UDID of the destination logicalunit."
msgstr "목적지 logicalunit의 UDID."

#: paxes_cinder/k2aclient/v1/shell.py:231
msgid "Id of the managedsystem to list logicalpartitions"
msgstr "logicalpartitions를 나열하는 managedsystem의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:246
#: paxes_cinder/k2aclient/v1/shell.py:273
#: paxes_cinder/k2aclient/v1/shell.py:295
#: paxes_cinder/k2aclient/v1/shell.py:350
#: paxes_cinder/k2aclient/v1/shell.py:486
#: paxes_cinder/k2aclient/v1/shell.py:658
#: paxes_cinder/k2aclient/v1/shell.py:674
#: paxes_cinder/k2aclient/v1/shell.py:698
#: paxes_cinder/k2aclient/v1/shell.py:714
msgid "Id of the managedsystem."
msgstr "managedsystem의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:249
#: paxes_cinder/k2aclient/v1/shell.py:262
#: paxes_cinder/k2aclient/v1/shell.py:617
#: paxes_cinder/k2aclient/v1/shell.py:634
msgid "Id of the logicalpartition."
msgstr "logicalpartition의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:276
msgid "UDIDs of the logicalpartition."
msgstr "logicalpartition의 UDID."

#: paxes_cinder/k2aclient/v1/shell.py:313
#: paxes_cinder/k2aclient/v1/shell.py:324
#: paxes_cinder/k2aclient/v1/shell.py:347
msgid "Id of the managementconsole."
msgstr "managementconsole의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:327
#: paxes_cinder/k2aclient/v1/shell.py:356
msgid "Command to run."
msgstr "실행할 명령."

#: paxes_cinder/k2aclient/v1/shell.py:353
msgid "UUID of the virtualioserver."
msgstr "virtualioserver의 UUID."

#: paxes_cinder/k2aclient/v1/shell.py:394
msgid "Id of the sharedstoragepool."
msgstr "sharedstoragepool의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:405
#: paxes_cinder/k2aclient/v1/shell.py:443
#: paxes_cinder/k2aclient/v1/shell.py:456
msgid "UUID of the sharedstoragepool."
msgstr "sharedstoragepool의 UUID."

#: paxes_cinder/k2aclient/v1/shell.py:408
msgid "Name of the new logicalunit."
msgstr "새 logicalunit의 이름."

#: paxes_cinder/k2aclient/v1/shell.py:411
msgid "Capacity of the new logicalunit."
msgstr "새 logicalunit의 용량."

#: paxes_cinder/k2aclient/v1/shell.py:414
msgid "Optional flag to control whether the new logicalunit will be thick or thin"
msgstr "새 logicalunit의 종류(씩 또는 씬)를 제어하는 선택적 플래그"

#: paxes_cinder/k2aclient/v1/shell.py:419
msgid "LogicalUnitType: VirtualIO_Disk | VirtualIO_Image"
msgstr "LogicalUnitType: VirtualIO_Disk | VirtualIO_Image"

#: paxes_cinder/k2aclient/v1/shell.py:423
msgid "Optional udid of LU to clone from, new if omitted"
msgstr "복제를 시작할 LU의 선택적 udid, 생략한 경우 새로 작성"

#: paxes_cinder/k2aclient/v1/shell.py:446
msgid "UDIDs of the logicalunit."
msgstr "logicalunit의 UDID."

#: paxes_cinder/k2aclient/v1/shell.py:459
msgid "Optional flag to control whether full details should be output"
msgstr "전체 세부사항을 출력하는지 여부를 제어하는 선택적 플래그"

#: paxes_cinder/k2aclient/v1/shell.py:471
msgid "Id of the managedsystem to list virtualioservers"
msgstr "virtualioservers를 나열하는 managedsystem의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:489
#: paxes_cinder/k2aclient/v1/shell.py:513
msgid "Id of the virtualioserver."
msgstr "virtualioserver의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:493
msgid ""
"Optional extended attributes Valid values include: All, Advanced, "
"Hypervisor, SystemNetwork, ViosStorage, ViosNetwork, ViosFCMapping, "
"ViosSCSIMapping, and None May be used multiple times. \"All\" if omitted"
msgstr ""
"선택적 확장 속성 올바른 값: All, Advanced, Hypervisor, SystemNetwork, ViosStorage, "
"ViosNetwork, ViosFCMapping, ViosSCSIMapping, None 여러 번 사용될 수 있습니다. 생략된 경우"
" \"All\"이 사용됩니다."

#: paxes_cinder/k2aclient/v1/shell.py:608
msgid "Id of the logicalpartition to list clientnetworkadapters"
msgstr "clientnetworkadapters를 나열하는 logicalpartition의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:620
msgid "Id of the clientnetworkadapter."
msgstr "clientnetworkadapter의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:637
msgid "UDIDs of the clientnetworkadapter."
msgstr "clientnetworkadapter의 UDID."

#: paxes_cinder/k2aclient/v1/shell.py:649
msgid "Id of the managedsystem to list virtualnetworks"
msgstr "virtualnetworks를 나열하는 managedsystem의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:661
msgid "Id of the virtualnetwork."
msgstr "virtualnetwork의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:677
msgid "UDIDs of the virtualnetwork."
msgstr "virtualnetwork의 UDID."

#: paxes_cinder/k2aclient/v1/shell.py:689
msgid "Id of the managedsystem to list virtualswitchs"
msgstr "virtualswitchs를 나열하는 managedsystem의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:701
msgid "Id of the virtualswitch."
msgstr "virtualswitch의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:717
msgid "UDIDs of the virtualswitch."
msgstr "virtualswitch의 UDID."

#: paxes_cinder/k2aclient/v1/shell.py:740
msgid "Id of the file."
msgstr "파일의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:750
msgid "Ids of the files."
msgstr "파일의 Id."

#: paxes_cinder/k2aclient/v1/shell.py:761
msgid "/rest/api/uom<uomresource>."
msgstr "/rest/api/uom<uomresource>."

#: paxes_cinder/k2aclient/v1/shell.py:766
msgid "Send output to file"
msgstr "파일에 출력 전송"

#: paxes_cinder/k2aclient/v1/shell.py:782
msgid "Read cinder ssp conf files and report on health"
msgstr "cinder ssp 구성 파일을 읽고 상태 보고"

#: paxes_cinder/k2aclient/v1/shell.py:815
#: paxes_cinder/k2aclient/v1/shell.py:843
msgid "VIOS password for all VIOS defaults to \"padmin\""
msgstr "모든 VIOS의 VIOS 비밀번호가 \"padmin\"으로 기본 설정"

#: paxes_cinder/k2aclient/v1/shell.py:820
#: paxes_cinder/k2aclient/v1/shell.py:848
msgid "Target directory for snapsdefaults to \"/tmp/vios-snap\""
msgstr "스냅의 대상 디렉토리가 \"/tmp/vios-snap\"로 기본 설정"

#: paxes_cinder/k2aclient/v1/shell.py:839
msgid "list of vios ips expressed as jsoneg '[\"9.47.161.157\"]'"
msgstr "vios ips 목록이 jsoneg '[\"9.47.161.157\"]'로 표시됨"

#: paxes_cinder/k2aclient/v1/v1k2creater.py:170
#, python-format
msgid "k2aclient: during process_root, unrecognized service: >%s<"
msgstr "NV-1FC12D8 k2aclient: process_root 중, 인식되지 않은 서비스: >%s<"

#: paxes_cinder/k2aclient/v1/v1k2loader.py:61
#, python-format
msgid ""
"k2aclient: during k2 deserialization, for type: >%(pcname)s<, k2 gave "
"unknown attr: >%(us_tag)s<, is there a schema mismatch?, will skip ..."
msgstr ""
"NV-A18BFC5 k2aclient: k2 역직렬화 중, 유형: >%(pcname)s<에서 k2가 알 수 없는 속성 제공: "
">%(us_tag)s<, 스키마가 불일치합니까? 이 경우 건너뜁니다."

#: paxes_cinder/k2aclient/v1/v1k2loader.py:77
#, python-format
msgid ""
"k2aclient: during k2 deserialization, for type: >%(pcname)s<, k2 attr: "
">%(us_tag)s<: is listed as scalar, but maybe its not?, is there a schema "
"mismatch?, will replace existing scalar w/ next value ..."
msgstr ""
"k2aclient: k2 역직렬화 중, 유형: >%(pcname)s<에서 k2 속성: >%(us_tag)s<: 스칼라로 나열되지만 "
"아닐 수도 있습니다. 스키마가 불일치합니까? 이 경우 다음 값으로 기존 스칼라를 대체합니다."

#: paxes_cinder/k2aclient/v1/v1k2loader.py:131
#, python-format
msgid ""
"k2aclient: during k2 deserialization, while processing: k2 type: "
">%(parent_tag)s<, there is no definition for k2 type: >%(k2type)s<, is "
"there a schema mismatch?, will skip ..."
msgstr ""
"k2aclient: k2 역직렬화 중, 처리: k2 유형: >%(parent_tag)s<, k2 유형에 대한 정의가 없음: "
">%(k2type)s<, 스키마가 불일치합니까? 이 경우 건너뜁니다."

#: paxes_cinder/k2aclient/v1/v1k2loader.py:190
#: paxes_cinder/k2aclient/v1/v1k2loader.py:199
msgid "k2aclient:"
msgstr "NV-E561712 k2aclient:"

#: paxes_cinder/k2aclient/v1/virtualioserver_manager.py:280
#, python-format
msgid ""
"k2aclient: during lua_recovery, for device_id: >%(device_id)s<, "
"experienced job failure, job_id: >%(jresponse.job_id)s<, status: "
">%(jresponse.status)s<, input K2 job diagnostics have been written to: "
">%(diagfspeci)s<, response k2 job diagnostics have been written to: "
">%(diagfspec)s<"
msgstr ""
"k2aclient: device_id: >%(device_id)s<에 대한 lua_recovery 중, 작업 실패 발생, "
"job_id: >%(jresponse.job_id)s<, 상태: >%(jresponse.status)s<, 입력 K2 작업 진단이 "
">%(diagfspeci)s<에 기록됨, 응답 k2 작업 진단이 >%(diagfspec)s<에 기록됨"

#: paxes_cinder/k2aclient/v1/web_file_manager.py:83
msgid ""
"k2aclient: during file upload, filename: >%(wf.filename)s<, id: "
">%(wf.id)s<, file_uuid: >%(wf.file_uuid)s<, file_enum_type: "
">%(wf.file_enum_type)s<"
msgstr ""
"k2aclient: 파일 업로드 중, 파일 이름: >%(wf.filename)s<, id: >%(wf.id)s<, "
"file_uuid: >%(wf.file_uuid)s<, file_enum_type: >%(wf.file_enum_type)s<"

#: paxes_cinder/k2aclient/v1/web_job_manager.py:65
#, python-format
msgid ""
"k2aclient: during %(jobtype)s, retry job, job_id: >%(job_id)s<, status: "
">%(status)s<,"
msgstr ""
"NV-FBECCFD k2aclient: %(jobtype)s 중, 작업 재시도, job_id: >%(job_id)s<, 상태: "
">%(status)s<,"

#: paxes_cinder/k2aclient/v1/web_job_manager.py:77
#, python-format
msgid ""
"k2aclient: during %(jobtype)s, too many retries, maximum number of "
"retries: >%(maxretries)d<, job_id: >%(job_id)s<, status: >%(status)s<,"
msgstr ""
"k2aclient: %(jobtype)s 중, 너무 많은 재시도, 최대 재시도 횟수: >%(maxretries)d<, job_id:"
" >%(job_id)s<, 상태: >%(status)s<,"

#: paxes_cinder/scheduler/host_manager.py:59
#, python-format
msgid "clean up host_state_map: %(host)shost"
msgstr "NV-F9D1534 host_state_map 정리: %(host)shost"

#: paxes_cinder/scheduler/sched_drv.py:56
#, python-format
msgid "volume request: requested size: %(size)s. "
msgstr "볼륨 요청: 요청된 크기: %(size)s. "

#: paxes_cinder/scheduler/sched_drv.py:62
#, python-format
msgid ""
"{host: %(hostname)s, free_capacity: %(free_cap)s, total_capacity: "
"%(total)s, reserved_percentage: %(reserved)s, last update: "
"%(time_updated)s}"
msgstr ""
"{호스트: %(hostname)s, free_capacity: %(free_cap)s, total_capacity: "
"%(total)s, reserved_percentage: %(reserved)s, 마지막 업데이트 날짜: "
"%(time_updated)s}"

#: paxes_cinder/scheduler/sched_drv.py:72
msgid "request exceeds capacity: info"
msgstr "NV-DBCC600 요청에서 용량 초과: 정보"

#: paxes_cinder/scheduler/sched_drv.py:75
msgid "No storage has been registered. "
msgstr "NV-96E101B 스토리지가 등록되지 않았습니다. "

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:67
msgid ""
"Free capacity not set: Volume node is either still under initialization "
"or the node info collection is broken."
msgstr "NV-872554F 여유 용량이 설정되지 않음: 볼륨 노드가 아직 초기화 중이거나 노드 정보 콜렉션이 중단되었습니다."

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:99
msgid "missing default_volume_type"
msgstr "NV-404930C default_volume_type 누락"

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:106
#, python-format
msgid ""
"missing valid rsize on                                 "
"%(default)svolume_type: %(vol_type)s"
msgstr "NV-B717E15 %(default)svolume_type: %(vol_type)s에서 올바른 rsize 누락"

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:117
#, python-format
msgid ""
"Insufficient free space for volume creation (requested / avail / rsize): "
"%(requested)s/%(available)s/%(rsize)s"
msgstr ""
"NV-5CC98A1 볼륨 작성 시 필요한 여유 공간이 충분하지 않음(요청됨/사용 가능/rsize): "
"%(requested)s/%(available)s/%(rsize)s"

#: paxes_cinder/scheduler/filters/paxes_capacity_filter.py:124
#, python-format
msgid ""
"Sufficient free space for volume creation (requested / avail / rsize): "
"%(requested)s/%(available)s/%(rsize)s"
msgstr ""
"NV-D0E32D8 볼륨 작성 시 필요한 여유 공간이 충분함(요청됨/사용 가능/rsize): "
"%(requested)s/%(available)s/%(rsize)s"

#: paxes_cinder/scohack/scohack_http.py:150
#, python-format
msgid "BadStoreUri: credentials '%(creds)s' not well-formatted."
msgstr "NV-5991AD7 BadStoreUri: 신임 정보 '%(creds)s'이(가) 잘못 형식화되었습니다."

#: paxes_cinder/scohack/scohack_http.py:160
msgid "BadStoreUri: no address specified in HTTP URL"
msgstr "NV-2A5D3E2 BadStoreUri: HTTP URL에 지정된 주소가 없음"

#: paxes_cinder/scohack/scohack_http.py:295
#, python-format
msgid "MaxRedirectsExceeded: redirects: >%(max)d<"
msgstr "NV-30617DF MaxRedirectsExceeded: 경로 재지정: >%(max)d<"

#: paxes_cinder/scohack/scohack_http.py:308
#, python-format
msgid "HTTP URL returned a %(status)s status code."
msgstr "HTTP URL에서 %(status)s 상태 코드를 리턴했습니다."

#: paxes_cinder/scohack/scohack_http.py:310
#: paxes_cinder/scohack/scohack_http.py:322
#, python-format
msgid "BadStoreUri: loc.path: >%(path)s<, reason: >%(reason)s<"
msgstr "NV-0E3AB46 BadStoreUri: loc.path: >%(path)s<, 이유: >%(reason)s<"

#: paxes_cinder/scohack/scohack_location.py:50
#, python-format
msgid "exception.UnknownScheme: scheme: >%(scheme)s<"
msgstr "NV-B8DA628 exception.UnknownScheme: 스킴: >%(scheme)s<"

#: paxes_cinder/scohack/scohack_scohack.py:77
msgid "URI must start with scohack://"
msgstr "NV-DF4522D URI는 scohack://로 시작해야 함"

#: paxes_cinder/scohack/scohack_scohack.py:79
#, python-format
msgid "BadStore: uri: >%(uri)s<, reason: >%(reason)s<"
msgstr "NV-7D2A4E2 BadStore: uri: >%(uri)s<, 이유: >%(reason)s<"

#: paxes_cinder/scohack/scohack_scohack.py:93
#, python-format
msgid "x-scg-vios-id: >%(id)s< not of form 'ttttmmm_sssssssnnn'"
msgstr "NV-9CCE26B x-scg-vios-id: >%(id)s<('ttttmmm_sssssssnnn' 양식이 아님)"

#: paxes_cinder/scohack/scohack_scohack.py:106
#, python-format
msgid "scohack: x-scg-vios-id: cant list ManagedSystem: >%(ex)s<"
msgstr "NV-405AA27 scohack: x-scg-vios-id: ManagedSystem을 나열할 수 없음: >%(ex)s<"

#: paxes_cinder/scohack/scohack_scohack.py:121
#, python-format
msgid "scohack: x-scg-vios-id: cant find ManagedSystem for: >%(id)s<"
msgstr "NV-708F8BE scohack: x-scg-vios-id: 다음에 대한 ManagedSystem을 찾을 수 없음: >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:129
#, python-format
msgid "scohack: x-scg-vios-id: cant list VirtualIoServer: >%(ex)s<"
msgstr "NV-2D6AE0A scohack: x-scg-vios-id: VirtualIoServer를 나열할 수 없음: >%(ex)s<"

#: paxes_cinder/scohack/scohack_scohack.py:139
#, python-format
msgid "scohack: x-scg-vios-id: cant find VirtualIOServer for: >%(id)s<"
msgstr ""
"NV-081426D scohack: x-scg-vios-id: 다음에 대한 VirtualIOServer를 찾을 수 없음: "
">%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:162
msgid "scohack: cant list vios"
msgstr "NV-D40CA86 scohack: vios를 나열할 수 없음"

#: paxes_cinder/scohack/scohack_scohack.py:168
msgid "scohack: no vios found"
msgstr "NV-ABFCCCD scohack: vios를 찾을 수 없음"

#: paxes_cinder/scohack/scohack_scohack.py:177
#, python-format
msgid "scohack: cant list vios for ms: >%(id)s<"
msgstr "NV-D6ED6BF scohack: ms에 대한 vios를 나열할 수 없음: >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:184
#, python-format
msgid "scohack: no vios found for ms: >%(id)s<"
msgstr "NV-0FD0B8A scohack: ms에 대한 vios를 찾을 수 없음: >%(id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:195
#, python-format
msgid "scohack: for ms: >%(mid)s<, cant find vios: >%(vid)s<"
msgstr "NV-AD83B35 scohack: ms: >%(mid)s<의 경우, vios를 찾을 수 없음: >%(vid)s<"

#: paxes_cinder/scohack/scohack_scohack.py:204
#, python-format
msgid "scohack: cant find vios: >%(vid)s<"
msgstr "NV-3704F44 scohack: vios를 찾을 수 없음: >%(vid)s<"

#: paxes_cinder/scohack/scohack_scohack.py:328
#, python-format
msgid ""
"scohack: only single hmc is supported: prev: >%(prev_id)s<, new: "
">%(new_id)s<"
msgstr "NV-185C13E scohack: 하나의 hmc만 지원됨: 이전: >%(prev_id)s<, 신규: >%(new_id)s<"

#: paxes_cinder/scohack/scohack_scohack.py:339
#, python-format
msgid "scohack: no HMC for id: >%(id)s<"
msgstr "NV-628D2F6 scohack: id: >%(id)s<에 대한 HMC가 없음"

#: paxes_cinder/scohack/scohack_scohack.py:352
#, python-format
msgid ""
"scohack: managemenconsole: >%(mc)s< could not be retrieved, hdisks will "
"not be cleaned up, msg: >%(msg)s<"
msgstr ""
"scohack: managemenconsole: >%(mc)s<을(를) 검색할 수 없음, hdisk는 정리되지 않음, 메시지: "
">%(msg)s<"

#: paxes_cinder/scohack/scohack_scohack.py:383
#, python-format
msgid "scohack: vios: >%(vios)s<, volume: >%(vol)s<"
msgstr "NV-22A4C11 scohack: vios: >%(vios)s<, 볼륨: >%(vol)s<"

#: paxes_cinder/scohack/scohack_scohack.py:400
#, python-format
msgid "scohack: image upload: hdisk: >%(hdisk)s<, vios: >%(vios)s<"
msgstr "NV-B86BF01 scohack: 이미지 업로드: hdisk: >%(hdisk)s<, vios: >%(vios)s<"

#: paxes_cinder/scohack/scohack_scohack.py:417
#, python-format
msgid "scohack: volume not found: >%(volume)s<"
msgstr "NV-CDC6DBB scohack: 볼륨을 찾을 수 없음: >%(volume)s<"

#: paxes_cinder/scohack/scohack_scohack.py:428
#, python-format
msgid "scohack: volume: invalid status: >%(status)s<"
msgstr "NV-D365509 scohack: volume: 올바르지 않은 상태: >%(status)s<"

#: paxes_cinder/scohack/scohack_scohack.py:445
#, python-format
msgid "scohack: no ports for vios: >%(vios)s<"
msgstr "NV-230F42F scohack: vios: >%(vios)s<에 대한 포트가 없음"

#: paxes_cinder/scohack/scohack_scohack.py:461
#, python-format
msgid "scohack: failed to connect to volume >%(volume_id)s< "
msgstr "NV-E7095A2 scohack: 볼륨 >%(volume_id)s< 연결 실패 "

#: paxes_cinder/scohack/scohack_scohack.py:471
#, python-format
msgid ""
"scohack: for target volume: >%(volume)s<, bad connection: >%(info)s<, no "
"target_lun"
msgstr ""
"NV-79C5617 scohack: 대상 볼륨: >%(volume)s<의 경우, 잘못된 연결: >%(info)s<, "
"target_lun 없음"

#: paxes_cinder/scohack/scohack_scohack.py:487
#, python-format
msgid ""
"scohack: for target volume: >%(volume)s<, no target wwpn found in "
"connection: >%(info)s< "
msgstr ""
"NV-5C2B384 scohack: 대상 볼륨: >%(volume)s<의 경우, 연결에서 대상 wwpn을 찾을 수 없음: "
">%(info)s<"

#: paxes_cinder/scohack/scohack_scohack.py:506
#, python-format
msgid "scohack: target volume: >%(volume)s<, does not have page83 data"
msgstr "NV-33E8084 scohack: 대상 볼륨: >%(volume)s<에 page83 데이터가 없음"

#: paxes_cinder/scohack/scohack_scohack.py:514
#, python-format
msgid "scohack: start luarecovery: deviceid: >%(id)s< , itls: >%(itls)s<"
msgstr "NV-0A59DDD scohack: luarecovery 시작: deviceid: >%(id)s< , itls: >%(itls)s<"

#: paxes_cinder/scohack/scohack_scohack.py:525
#, python-format
msgid "scohack: lua_recovery job failed for target volume: >%(volume)s<"
msgstr "NV-D94C9A2 scohack: 대상 볼륨: >%(volume)s<에 대한 lua_recovery 작업 실패"

#: paxes_cinder/scohack/scohack_scohack.py:538
#, python-format
msgid "scohack: luarcovery job status: >%(status)s<, result: >%(res)s<"
msgstr "NV-FC7E239 scohack: luarcovery 작업 상태: >%(status)s<, 결과: >%(res)s<"

#: paxes_cinder/scohack/scohack_scohack.py:544
#, python-format
msgid ""
"scohack: lua_recovery job internal error, device_list is invalid device "
"list: >%(lua_list)s<"
msgstr ""
"NV-610160F scohack: lua_recovery 작업 내부 오류, device_list가 올바르지 않은 장치 목록임: "
">%(lua_list)s<"

#: paxes_cinder/scohack/scohack_scohack.py:552
#, python-format
msgid ""
"scohack: lua_recovery job returned multiple devices device list: "
">%(lua_list)s<, will select first ..."
msgstr ""
"NV-3A4481D scohack: lua_recovery 작업에서 여러 장치 목록을 리턴함: >%(lua_list)s<, 첫 번째"
" 항목 선택..."

#: paxes_cinder/scohack/scohack_scohack.py:562
#, python-format
msgid ""
"This means that a device was found from an ITL nexus and it was "
"determined to be in use by the VIOS. The most likely cause is that a "
"virtual device was not removed from a previous deploy. The VIOS took no "
"action in this case. device: >%(dev)s<"
msgstr ""
"즉, ITL nexus에서 장치를 찾았으며 VIOS에서 사용할 항목으로 판별되었음을 의미합니다. 가능한 원인은 가상 장치가 이전 "
"배치에서 제거되지 않았기 때문입니다. VIOS는 이 경우 아무런 조치를 취하지 않습니다. 장치 :>%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:572
#, python-format
msgid ""
"This means that the ITL nexus is not consider reliable and some error "
"occurred that prevents the VIOS from determining making a decision on "
"safely removing a device. The VIOS took no action in this case. Perhaps "
"try to remove the offending hdisk from the VIOS, with rmdev -d -l hdiskx."
" device: >%(dev)s<"
msgstr ""
"NV-DC7D321 즉, ITL nexus가 불안정하며 VIOS에서 장치를 안전하게 제거하는 의사결정을 내리지 못하도록 방해하는 몇"
" 가지 오류가 발생했음을 의미합니다. 이 경우 VIOS는 아무런 조치를 취하지 않습니다. rmdev -d -l hdiskx로 "
"VIOS에서 문제가 되는 hdisk를 제거할 수 있습니다. 장치: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:585
#, python-format
msgid ""
"This means the information provided and action taken by the VIOS was "
"sufficient to find the storage. pvName, and uniqueID elements will follow"
" in the data stream. device: >%(dev)s<"
msgstr ""
"NV-8DB8D33 즉, VIOS에서 제공한 정보와 수행한 조치가 스토리지를 찾는 데 충분함을 의미합니다. pvName 및 "
"uniqueID 요소는 데이터 스트림에서 뒤에 나옵니다. 장치: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:593
#, python-format
msgid ""
"This means some new storage element was found at the ITL nexus but VIOS "
"could not determine if it is the storage of interest to the management "
"tool. device: >%(dev)s<"
msgstr ""
"NV-36ADD00 즉, ITL nexus에서 몇 가지 새 스토리지 요소를 찾았지만 VIOS에서 관리 도구에 중요한 스토리지인지 "
"여부를 판별할 수 없습니다. 장치: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:602
#, python-format
msgid ""
"The VIOS could not determine if this is logical unit of interest to the "
"management tool however did find a device from the ITL nexus list. "
"device: >%(dev)s<"
msgstr ""
"NV-6761BFF VIOS에서 관리 도구에 중요한 논리 장치인지를 판별할 수 없지만 ITL nexus 목록에서 장치를 찾았습니다."
" 장치: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:611
#, python-format
msgid ""
"The VIOS could not find a device from the itl nexus list. It could be "
"some SCSI or transport error occurred during configuration or the ITL "
"nexus list was incorrect. device: >%(dev)s<"
msgstr ""
"NV-2479600 VIOS가 itl nexus 목록에서 장치를 찾을 수 없습니다. 구성 중 몇 가지 SCSI 또는 전송 오류가 "
"발생했거나 ITL nexus 목록이 올바르지 않습니다. 장치: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:622
#, python-format
msgid ""
"Unknown device status. Severe internal error contact NCO. device: "
">%(dev)s<"
msgstr "NV-2EF1D11 알 수 없는 장치 상태. 심각한 내부 오류. NCO 에 문의하십시오. 장치: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:638
#, python-format
msgid "scohack: failed to find device name: >%(dev)s<"
msgstr "NV-B6E8402 scohack: 장치 이름을 찾을 수 없음: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:643
#, python-format
msgid "scohack: found device name: >%(dev)s<"
msgstr "NV-32CF4C2 scohack: 장치 이름을 찾음: >%(dev)s<"

#: paxes_cinder/scohack/scohack_scohack.py:665
#, python-format
msgid "scohack: hdisk_uuid: >%(hdisk)s<, checksum not specified"
msgstr "NV-D85ABDC scohack: hdisk_uuid: >%(hdisk)s<, 체크섬이 지정되지 않음"

#: paxes_cinder/scohack/scohack_scohack.py:672
#, python-format
msgid "scohack: hdisk_uuid: >%(hdisk)s<, size not specified"
msgstr "NV-9783CB3 scohack: hdisk_uuid: >%(hdisk)s<, 크기가 지정되지 않음"

#: paxes_cinder/scohack/scohack_scohack.py:694
#, python-format
msgid ""
"scohack: image upload complete for hdisk_uuid: >%(hdisk)s<, webfile id: "
">%(wid)s<, actual size: >%(size)s< bytes, elapsed time: >%(time)d< "
"seconds, rate: >%(rate)f< minutes/GB"
msgstr ""
"scohack: hdisk_uuid: >%(hdisk)s<에 대한 이미지 업로드 완료, 웹 파일 id: >%(wid)s<, 실제 "
"크기: >%(size)s<바이트, 경과 시간: >%(time)d<초, 비율: >%(rate)f<분/GB"

#: paxes_cinder/scohack/scohack_scohack.py:709
#, python-format
msgid ""
"scohack:  mismatch: expected_file_size_in_bytes: >%e_size)d<, "
"current_file_size_in_bytes: >%(c_size)d<"
msgstr ""
"NV-E2ACA08 scohack: 불일치: expected_file_size_in_bytes: >%e_size)d<, "
"current_file_size_in_bytes: >%(c_size)d<"

#: paxes_cinder/scohack/scohack_scohack.py:740
#, python-format
msgid ""
"scohack: cleanup failure for: >%(hdisk)s<, job status: >%(status)s<, "
"response: >%(res)s< continuing ..."
msgstr ""
"NV-C9A426B scohack: >%(hdisk)s<에 대한 정리 실패, 작업 상태: >%(status)s<, 응답: "
">%(res)s< 계속 중..."

#: paxes_cinder/scohack/scohack_scohack.py:752
#, python-format
msgid ""
"scohack: for hdisk_uuid: >%(hdisk)s<  no managementconsole, hisks will "
"not be cleaned up"
msgstr ""
"NV-508BE83 scohack: hdisk_uuid: >%(hdisk)s<의 경우, managementconsole 없음, "
"hdisk가 정리되지 않음"

#: paxes_cinder/scohack/scohack_scohack.py:758
#: paxes_cinder/scohack/scohack_scohack.py:768
#, python-format
msgid "scohack: for hdisk_uuid: >%(hdisk)s< cleanup failed, msg: >%(ex)s<"
msgstr "NV-B37BCB5 scohack: hdisk_uuid: >%(hdisk)s< 정리 실패, 메시지: >%(ex)s<"

#: paxes_cinder/scohack/scohack_scohack.py:772
#, python-format
msgid "scohack: upload failed for hdisk_uuid: >%(dsk)s<"
msgstr "NV-D7A600C scohack: hdisk_uuid: >%(dsk)s<에 대한 업로드 실패"

#: paxes_cinder/scohack/scohack_utils.py:47
#, python-format
msgid "Error: cooperative_iter exception %(error)s"
msgstr "NV-23E8986 오류: cooperative_iter 예외 %(error)s"

#: paxes_cinder/volume/__init__.py:46
#, python-format
msgid ""
"cinder volume_create interface has been changed. PowerVC monkey patch for"
" volume clone won't work. function: %(fx)s, arguments: %(args)s"
msgstr ""
"NV-7A6F9A4 cinder volume_create 인터페이스가 변경되었습니다. 볼륨에 대한 PowerVC monkey 패치가"
" 작동하지 않습니다. 함수: %(fx)s, 인수: %(args)s"

#: paxes_cinder/volume/__init__.py:61
#, python-format
msgid ""
"Monkey patched volume clone by paxes volume_create_decorator(). Source "
"Volume ID: %(svol)s, volume type name: %(voltpnm)s, volume type ID: "
"%(voltpid)s"
msgstr ""
"NV-D17192A paxes volume_create_decorator()에 의해 Monkey 패치된 볼륨 복제. 소스 볼륨 "
"ID: %(svol)s, 볼륨 유형 이름: %(voltpnm)s, 볼륨 유형 ID: %(voltpid)s"

#: paxes_cinder/volume/__init__.py:94
#, python-format
msgid ""
"Failed to get the parameters from function "
"cinder.volume.volume_types.create(). Default quota didn't set for the "
"storage template. Error: %(err)s"
msgstr ""
"NV-A4934EA 함수 cinder.volume.volume_types.create()에서 매개변수를 가져오지 못했습니다. "
"스토리지 템플리트에 대한 기본 할당이 설정되지 않았습니다. 오류: %(err)s"

#: paxes_cinder/volume/__init__.py:114
#, python-format
msgid "Successfully set default quota for storage template %(vol_type)s"
msgstr "NV-71868FF 스토리지 템플리트 %(vol_type)s에 대한 기본 할당 설정"

#: paxes_cinder/volume/__init__.py:118
#, python-format
msgid ""
"Failed to set default quota for storage template %(vol_type)s, error: "
"%(err)s"
msgstr "NV-D86E5F7 스토리지 템플리트 %(vol_type)s에 대한 기본 할당 설정 실패, 오류: %(err)s"

#: paxes_cinder/volume/__init__.py:122
#, python-format
msgid ""
"Cannot set default quota for storage template %(vol_type) due to invalid "
"Parameters from volume type create."
msgstr ""
"NV-D9BA448 볼륨 유형 작성의 매개변수가 올바르지 않으므로 스토리지 템플리트 %(vol_type) 에 대한 기본 할당을 "
"설정할 수 없습니다."

#: paxes_cinder/volume/__init__.py:175
#, python-format
msgid "Error getting data volumes: %s "
msgstr "NV-7627301 데이터 볼륨을 가져오는 중 오류 발생: %s "

#: paxes_cinder/volume/manager.py:89
#, python-format
msgid "Cannot perform direct SAN operation on disk with prefix %(prefix)s"
msgstr "NV-1701BDD 접두부가 %(prefix)s인 디스크에서 직접 SAN 조작을 수행할 수 없음"

#: paxes_cinder/volume/manager.py:100
msgid "Driver still initializing, wait..."
msgstr "NV-C6CA9E0 드라이버가 아직 초기화 중입니다. 기다려 주십시오..."

#: paxes_cinder/volume/manager.py:102
#, python-format
msgid "Try again: %s"
msgstr "NV-FEE7BD0 다시 시도: %s"

#: paxes_cinder/volume/manager.py:172
#, python-format
msgid "Fabric {fabric_name} ({user}@{ip}:{port}): %(message)s"
msgstr "NV-0A01336 패브릭 {fabric_name} ({user}@{ip}:{port}): %(message)s"

#: paxes_cinder/volume/manager.py:188
#, python-format
msgid ""
"Storage Provider {storage_provider_hostname} ({user}@{ip}:{port}) "
"{volume_id}: %(message)s"
msgstr ""
"NV-E1A972C 스토리지 제공자 {storage_provider_hostname} ({user}@{ip}:{port}) "
"{volume_id}: %(message)s"

#: paxes_cinder/volume/manager.py:223
msgid ""
"The volume is already attached to another virtual server, possibly one "
"that is not managed by PowerVC."
msgstr "볼륨이 이미 다른 가상 서버에 연결되었습니다. PowerVC에서 관리하지 않는 가상 서버일 수 있습니다."

#: paxes_cinder/volume/manager.py:227
msgid ""
"The volume cannot be deleted because it is either mapped to a host or "
"part of a flashcopy or remote copy operation."
msgstr "볼륨이 호스트나 flashcopy 또는 원격 복사 조작 중에 맵핑되었으므로 볼륨을 삭제할 수 없습니다."

#: paxes_cinder/volume/manager.py:239
#, python-format
msgid "%(error_prefix)s failure for volume {volume_id}: %(error)s"
msgstr "볼륨 {volume_id}에 대한 %(error_prefix)s 실패: %(error)s"

#: paxes_cinder/volume/manager.py:244
#, python-format
msgid ""
"%(error_prefix)s failure for volume {volume_id}.Command %(cmd)s, error "
"%(error)s"
msgstr "볼륨 {volume_id}에 대한 %(error_prefix)s 실패. 명령 %(cmd)s, 오류 %(error)s"

#: paxes_cinder/volume/manager.py:393
#, python-format
msgid "Resuming deletion of volume %s"
msgstr "NV-E253654 볼륨 %s의 삭제 재개 중"

#: paxes_cinder/volume/manager.py:396
#, python-format
msgid ""
"Failed to delete volume %(volid)s during volume service startup. Error: "
"%(error)s"
msgstr "NV-CCA27AC 볼륨 서비스 시작 중 볼륨 %(volid)s 삭제 실패. 오류: %(error)s"

#: paxes_cinder/volume/manager.py:410
#, python-format
msgid "Processing volume that was left in the attaching state. Volume id: %(id)s"
msgstr "NV-89FC9B0 첨부된 상태로 남겨진 볼륨 처리 중. 볼륨 id: %(id)s"

#: paxes_cinder/volume/manager.py:483
#, python-format
msgid ""
"_volume_attach_rollback: Volume %(id)s is missing restricted metadata to "
"recover the attaching state."
msgstr ""
"NV-C8F1D06 _volume_attach_rollback: 볼륨 %(id)s에서 첨부 상태를 복구하기 위해 제한된 메타데이터가"
" 누락되었습니다."

#: paxes_cinder/volume/manager.py:487
#, python-format
msgid ""
"_volume_attach_rollback: No attach operation  to rollback for volume "
"%(id)s"
msgstr "NV-77AEEA1 _volume_attach_rollback: 볼륨 %(id)s에 대해 롤백할 첨부 조작이 없음"

#: paxes_cinder/volume/manager.py:493
#, python-format
msgid ""
"_volume_attach_rollback: Invalid connector %(conn)s in volume %(id)s "
"restrict metadata. Rollback without termination"
msgstr ""
"NV-4096184 _volume_attach_rollback: 볼륨 %(id)s 제한 메타데이터에서 커넥터 %(conn)s이(가)"
" 올바르지 않습니다. 종료 없이 롤백됩니다."

#: paxes_cinder/volume/manager.py:498
#, python-format
msgid "_volume_attach_rollback: Roll back attaching state for volume %(id)s."
msgstr "NV-1EB0444 _volume_attach_rollback: 볼륨 %(id)s에 대한 첨부 상태를 롤백합니다."

#: paxes_cinder/volume/manager.py:518
#, python-format
msgid ""
"_volume_attach_rollback: Finished. Volume %(id)s has rolled back to "
"available state."
msgstr ""
"NV-1E08B26 _volume_attach_rollback: 완료되었습니다. 볼륨 %(id)s이(가) 사용 가능한 상태로 "
"롤백됩니다."

#: paxes_cinder/volume/manager.py:600
#, python-format
msgid ""
"The volume detach didn't finish successfully before cinder service was "
"restarted. volume id: %(id)s"
msgstr "NV-333B81A cinder 서비스가 다시 시작되기 전에 볼륨 분리가 완료되지 않았습니다. 볼륨 id: %(id)s"

#: paxes_cinder/volume/manager.py:633
msgid "Unable to initialize host, driver is uninitialized"
msgstr "NV-7F33CBC 호스트를 초기화할 수 없음, 드라이버가 초기화되지 않음"

#: paxes_cinder/volume/manager.py:650
msgid "update default quota class..."
msgstr "NV-392B903 기본 할당 클래스 업데이트..."

#: paxes_cinder/volume/manager.py:652
msgid "Post init_host processing and update volume status."
msgstr "NV-6EC3032 init_host 처리 후 볼륨 상태를 업데이트합니다."

#: paxes_cinder/volume/manager.py:656
#, python-format
msgid "Error happened during post init_host volume processing. Error: %s"
msgstr "NV-B263BC8 사후 init_host 볼륨 처리 중 오류가 발생했습니다. 오류: %s"

#: paxes_cinder/volume/manager.py:660
#, python-format
msgid "Rollback volume still attaching during init_host: %d volumes"
msgstr "NV-BDEAFA8 init_host: %d 볼륨 중 볼륨 롤백이 계속 첨부 중"

#: paxes_cinder/volume/manager.py:665
#, python-format
msgid "Resume volume deletion during init_host: %d volumes"
msgstr "NV-6BC64FF init_host: %d 볼륨 중 볼륨 삭제 재개"

#: paxes_cinder/volume/manager.py:719
msgid "Caught Exception Refreshing Driver Status "
msgstr "드라이버 상태를 새로 고치는 중 예외 발생 "

#: paxes_cinder/volume/manager.py:755
msgid "Caught Exception trying to update Storage Node in DB"
msgstr "NV-36093B5 DB에서 스토리지 노드를 업데이트하는 중 예외 발생"

#: paxes_cinder/volume/manager.py:793
msgid "Unable to retrieve Default Volume Type"
msgstr "NV-544BC4C 기본 볼륨 유형을 검색할 수 없음"

#: paxes_cinder/volume/manager.py:850
#, python-format
msgid "volume %s: removing export"
msgstr "NV-BAF02FC 볼륨 %s: 내보내기 제거 중"

#: paxes_cinder/volume/manager.py:852
#, python-format
msgid "volume %s: deleting"
msgstr "NV-4F406DE 볼륨 %s: 삭제 중"

#: paxes_cinder/volume/manager.py:855
#, python-format
msgid "volume %s: volume is busy"
msgstr "NV-3431BA6 볼륨 %s: 볼륨이 사용 중임"

#: paxes_cinder/volume/manager.py:858
#, python-format
msgid "Fail to remove_export or delete_volume: %sname"
msgstr "NV-E98201D remove_export 또는 delete_volume 실패: %sname"

#: paxes_cinder/volume/manager.py:862
#, python-format
msgid "Volume %s: deletion failed with exception "
msgstr "NV-137591B 볼륨 %s: 예외로 삭제 실패 "

#: paxes_cinder/volume/manager.py:954
#, python-format
msgid ""
"failed checking whether                              volume %(vol_id)s "
"backs an image, metadata=%(mdata)s"
msgstr "NV-BE4D3EE 볼륨 %(vol_id)s에서 이미지를 지원하는지 여부를 확인할 수 없음, 메타데이터=%(mdata)s"

#: paxes_cinder/volume/manager.py:991
#, python-format
msgid ""
"volume %(volid)s has unfinished attach transaction. Rolling back before "
"deleting the volume."
msgstr "NV-331CBBA 볼륨 %(volid)s에서 첨부 트랜잭션을 완료하지 않았습니다. 볼륨을 삭제하기 전에 롤백합니다."

#: paxes_cinder/volume/manager.py:1035
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to extend volume by %(s_size)sG, "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""
"NV-521C07E %(s_pid)s에 대한 할당이 초과됨, %(s_size)sG만큼 볼륨 확장 시도, "
"(%(d_consumed)dG/%(d_quota)dG가 이미 이용됨)"

#: paxes_cinder/volume/manager.py:1091
#, python-format
msgid ""
"The host %(hostid)s for boot volume %(volid)s  does not support extend "
"volume."
msgstr "NV-37CDE0F 부트 볼륨 %(volid)s에 대한 호스트 %(hostid)s에서 확장 볼륨을 지원하지 않습니다."

#: paxes_cinder/volume/manager.py:1145
#, python-format
msgid "Start attach transaction for volume %(id)s."
msgstr "NV-1CBB13C 볼륨 %(id)s에 대한 첨부 트랜잭션을 시작합니다."

#: paxes_cinder/volume/manager.py:1175
#, python-format
msgid "Driver returned %s"
msgstr "NV-B695526 드라이버에서 %s 리턴"

#: paxes_cinder/volume/manager.py:1208
#, python-format
msgid "Successfully attached the volume %(id)s. Clean up transaction."
msgstr "NV-F606087 볼륨 %(id)s을(를) 첨부했습니다. 트랜잭션을 정리합니다."

#: paxes_cinder/volume/drivers/paxes_san.py:162
#, python-format
msgid "Waiting %(seconds)d seconds before next attempt..."
msgstr "NV-0553DA5 다음 시도 전에 %(seconds)d초 대기 중..."

#: paxes_cinder/volume/drivers/paxes_san.py:182
#, python-format
msgid "Error running SSH command: %s"
msgstr "NV-052C0AB SSH 명령 실행 중 오류 발생: %s"

#: paxes_cinder/volume/drivers/emc/emc_common_product.py:35
msgid "Updating volume status"
msgstr "NV-A56DF8D 볼륨 상태 업데이트"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:89
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1374
msgid "protocol must be specified as '<in> iSCSI' or '<in> FC'"
msgstr "프로토콜이 '<in> iSCSI' 또는 '<in> FC'로 지정되어야 함"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:123
msgid "Entering create_volume."
msgstr "NV-4C5AEEB create_volume을 입력합니다."

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:127
#, python-format
msgid "Create Volume: %(volume)s  Size: %(size)lu"
msgstr "NV-403E8FC 볼륨: %(volume)s 크기: %(size)lu 작성"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:157
#, python-format
msgid ""
"Unsupported element_type value %(element_type)s.  Specify a supported "
"element_type value and resubmit the request."
msgstr ""
"NV-AC11F99 지원되지 않는 element_type 값 %(element_type)s. 지원되는 element_type 값을 "
"지정하고 요청을 다시 제출하십시오."

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:164
#, python-format
msgid "Create Volume: %(volume)s  Storage type: %(storage_type)s"
msgstr "NV-4E4E2BB 볼륨: %(volume)s 스토리지 유형: %(storage_type)s 작성"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:171
#, python-format
msgid ""
"Create Volume: %(volume)s  Pool: %(pool)s,  Element Type: "
"%(element_type)s, Storage System: %(storage_system)s"
msgstr ""
"NV-723484A 볼륨: %(volume)s 풀: %(pool)s, 요소 유형: %(element_type)s, 스토리지 시스템:"
" %(storage_system)s 작성"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:182
#, python-format
msgid ""
"Error Create Volume: %(volumename)s. Storage Configuration Service not "
"found for pool %(storage_type)s."
msgstr ""
"NV-0EFA73A %(volumename)s 볼륨 작성에 오류가 발생했습니다. %(storage_type)s 풀에 대한 스토리지 "
"구성 서비스를 찾을 수 없습니다. "

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:190
#, python-format
msgid ""
"Create Volume: %(name)s  Method: CreateOrModifyElementFromStoragePool  "
"ConfigServicie: %(service)s  ElementName: %(name)s  InPool: %(pool)s  "
"ElementType: %(element_type)s  Size: %(size)lu"
msgstr ""
"NV-6E312B4 볼륨: %(name)s 메소드: CreateOrModifyElementFromStoragePool "
"ConfigServicie: %(service)s ElementName: %(name)s InPool: %(pool)s "
"ElementType: %(element_type)s 크기: %(size)lu 작성"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:206
#, python-format
msgid "Create Volume: %(volumename)s  Return code: %(rc)lu"
msgstr "NV-0214C49 볼륨: %(volumename)s 리턴 코드: %(rc)lu 작성"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:213
#, python-format
msgid ""
"Error Create Volume: %(volumename)s.  Return code: %(rc)lu.  Error: "
"%(error)s"
msgstr "NV-227D3AC %(volumename)s 볼륨 작성 시 오류 발생. 리턴 코드: %(rc)lu. 오류: %(error)s"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:220
#, python-format
msgid "Leaving create_volume: %(volumename)s  Return code: %(rc)lu"
msgstr "NV-C5C5CCC 나가기: create_volume: %(volumename)s. 리턴 코드: %(rc)lu"

#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:235
#: paxes_cinder/volume/drivers/emc/emc_smis_product.py:259
msgid "Could not establish ecom connection"
msgstr "NV-930992B ecom 연결을 설정할 수 없음"

#: paxes_cinder/volume/drivers/ssp/ssp.py:177
#, python-format
msgid "ssp:  no matching HMC was found in the DB for host: >%s<"
msgstr "NV-BFBE123 ssp: 일치하는 HMC를 호스트의 DB에서 찾을 수 없음: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:248
#, python-format
msgid "ssp: during create default volume type, DB error: >%s<"
msgstr "NV-FA1BBE8 ssp: 기본 볼륨 유형 작성 중, DB 오류: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:279
#, python-format
msgid ""
"ssp: during _create_lu for LU: (name: >%(name)s<, size: >%(size)s<, thin:"
" >%(thin)s<), ssp_udid: >%(ssp_udid)s< is not same as extra_spec "
"shared_storage_pool: >%(extra_spec_ssp_id)s<"
msgstr ""
"ssp: LU(이름: >%(name)s<, 크기: >%(size)s<, 씬: >%(thin)s<)에 대한 _create_lu 중, "
"ssp_udid: >%(ssp_udid)s<이(가) extra_spec shared_storage_pool: "
">%(extra_spec_ssp_id)s<과(와) 같지 않음"

#: paxes_cinder/volume/drivers/ssp/ssp.py:299
#, python-format
msgid ""
"ssp: failed during _create_lu for LU: (name: >%(name)s<, size: "
">%(size)s<, thin: >%(thin)s<), message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: LU(이름: >%(name)s<, 크기: >%(size)s<, 씬: >%(thin)s<)에 대한 _create_lu 중 "
"실패, 메시지: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:329
#, python-format
msgid ""
"ssp: during _create_lu job for LU: (name: >%(name)s<, size: >%(size)s<, "
"thin: >%(thin)s<), ssp_udid: >%(ssp_udid)s< is not same as extra_spec "
"shared_storage_pool: >%(extra_spec_ssp_id)s<"
msgstr ""
"ssp: LU(이름: >%(name)s<, 크기: >%(size)s<, 씬: >%(thin)s<)에 대한 _create_lu 작업 "
"중, ssp_udid: >%(ssp_udid)s<이(가) extra_spec shared_storage_pool: "
">%(extra_spec_ssp_id)s<과(와) 같지 않음"

#: paxes_cinder/volume/drivers/ssp/ssp.py:351
#, python-format
msgid ""
"ssp: failure during _create_lu, create parameters: name: >%(name)s<, "
"size: >%(size)s<, thin: >%(thin)s<, logicalunittype: "
">%(logicalunittype)s<, message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: _create_lu 중 실패, 작성 매개변수: 이름: >%(name)s<, 크기: >%(size)s<, 씬: "
">%(thin)s<, logicalunittype: >%(logicalunittype)s<, 메시지: >%(e)s<, k2xa: "
">%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:366
#, python-format
msgid ""
"ssp: failure during _create_lu job, expecting COMPLETED_OK, but for "
"job_id: >%(job_id)s< got status: >%(status)s< create parameters: name: "
">%(name)s<, size: >%(size)s<, thin: >%(thin)s<, logicalunittype: "
">%(logicalunittype)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-76A9409 ssp: _create_lu 작업 중 실패, COMPLETED_OK가 예상되지만 job_id: "
">%(job_id)s<에 대해 수신된 상태: >%(status)s< 작성 매개변수: 이름: >%(name)s<, 크기: "
">%(size)s<, 씬: >%(thin)s<, logicalunittype: >%(logicalunittype)s<, k2xa: "
">%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:382
#, python-format
msgid ""
"ssp: create complete, job_id: >%(job_id)s<, name: >%(name)s<, size: "
">%(size)s<, thin: >%(thin)s<, logicalunittype: >%(logicalunittype)s<, "
"k2xa: >%(k2xa)s<"
msgstr ""
"NV-9FEEE64 ssp: 작성 완료, job_id: >%(job_id)s<, 이름: >%(name)s<, 크기: "
">%(size)s<, 씬: >%(thin)s<, >%(logicalunittype)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:416
#, python-format
msgid ""
"ssp: failed during _delete_lu of LU w/ with unique_device_id: "
">%(lu_udid)s<,  message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: unique_device_id: >%(lu_udid)s<인 LU의 _delete_lu 중 실패, 메시지: >%(e)s<, "
"k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:431
#, python-format
msgid ""
"ssp: during _clone_lu_by_name, couldnt find lu with src_lu_name: "
">%(src_lu_name)s<, tgt_lu_name: >%(tgt_lu_name)s<"
msgstr ""
"ssp: _clone_lu_by_name 중, src_lu_name: >%(src_lu_name)s<, tgt_lu_name: "
">%(tgt_lu_name)s<의 lu를 찾을 수 없음"

#: paxes_cinder/volume/drivers/ssp/ssp.py:439
#, python-format
msgid ""
"ssp: during _clone_lu_by_name, found too many lus with src_lu_name: "
">%(src_lu_name)s<, tgt_lu_name: >%(tgt_lu_name)s<"
msgstr ""
"NV-8FDE368 ssp: _clone_lu_by_name 중, src_lu_name: >%(src_lu_name)s<, "
"tgt_lu_name: >%(tgt_lu_name)s<의 lu가 너무 많음"

#: paxes_cinder/volume/drivers/ssp/ssp.py:469
#, python-format
msgid ""
"ssp: failure during _clone_lu_bj, clone parameters: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s< msg: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: _clone_lu_bj 중 실패, 복제 매개변수: src_lu_udid: >%(src_lu_udid)s<, "
"tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: >%(tgt_lu_size)s< 메시지: "
">%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:485
#: paxes_cinder/volume/drivers/ssp/ssp.py:547
#, python-format
msgid ""
"ssp: apparent failure during _clone_lu_bj, expecting COMPLETED_OK, but "
"for job_id: >%(job_id)s< got status: >%(status)s< clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-64234D9 ssp: _clone_lu_bj 중 명백한 실패, COMPLETED_OK가 예상되지만 job_id: "
">%(job_id)s<에 대해 수신된 상태: >%(status)s< 복제 매개변수: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:509
#, python-format
msgid ""
"ssp: failure during _clone_lu_bj, during create, clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s< message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: _clone_lu_bj 중, 작성 중 실패, 복제 매개변수: src_lu_udid: >%(src_lu_udid)s<, "
"tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: >%(tgt_lu_size)s< 메시지: "
">%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:530
#, python-format
msgid ""
"ssp: failure during _clone_lu_bj, during clone, clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s< message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: _clone_lu_bj 중, 복제 중 실패, 복제 매개변수: src_lu_udid: >%(src_lu_udid)s<, "
"tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: >%(tgt_lu_size)s< 메시지: "
">%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:576
#, python-format
msgid ""
"ssp: failure during _clone_lu_bp, clone parameters: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s< message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: _clone_lu_bp 중 실패, 복제 매개변수: src_lu_udid: >%(src_lu_udid)s<, "
"tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: >%(tgt_lu_size)s< 메시지: "
">%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:591
#, python-format
msgid ""
"ssp: apparent failure during _clone_lu_bp, expecting COMPLETED_OK, but "
"for job_id: >%(job_id)s< got status: >%(status)s< clone parameters: "
"src_lu_udid: >%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< "
"tgt_lu_size: >%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-21DAFDD ssp: _clone_lu_bp 중 명백한 실패, COMPLETED_OK가 예상되지만 job_id: "
">%(job_id)s<에 대해 수신된 상태: >%(status)s< 복제 매개변수: src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:606
#, python-format
msgid ""
"ssp: clone complete, job_id: >%(job_id)s<, src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-330DF39 ssp: 복제 완료, job_id: >%(job_id)s<, src_lu_udid: "
">%(src_lu_udid)s<, tgt_lu_name: >%(tgt_lu_name)s< tgt_lu_size: "
">%(tgt_lu_size)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:625
msgid "ssp: driver not yet initialized"
msgstr "NV-767C35B ssp: 드라이버가 아직 초기화되지 않음"

#: paxes_cinder/volume/drivers/ssp/ssp.py:634
#, python-format
msgid ""
"K2 GET SharedStoragePool time: >%(delta)f< is bigger or equal to "
"update_stats periodic interval: >%(periodic_interval)d<"
msgstr ""
"NV-BB646A1 K2 GET SharedStoragePool 시간: >%(delta)f<이(가) update_stats 정기 "
"간격: >%(periodic_interval)d<보다 크거나 같음"

#: paxes_cinder/volume/drivers/ssp/ssp.py:641
#, python-format
msgid ""
"ssp: during get_volume_stats, failed to refresh shared storage pool with "
"ssp_id: >%(self._ssp.id)s<, message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: get_volume_stats 중 ssp_id: >%(self._ssp.id)s<인 공유 스토리지 풀 새로 고치기 실패, "
"메시지: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:680
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, while performing vios cluster check, "
"failed to refresh cluster id: >%(self._cluster.id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-AC40CF2 ssp: %(duringwhatstage)s 중, vios 클러스터 검사 수행 중 클러스터 id: "
">%(self._cluster.id)s< 새로 고치기 실패, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:707
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, for vios id: >%(vios.id)s<, "
"OperatingSystemVersion: >%(os_version)s<"
msgstr ""
"ssp: vios id: >%(vios.id)s<에 대한 %(duringwhatstage)s 중, "
"OperatingSystemVersion: >%(os_version)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:719
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, vios id: >%(vios.id)s<, running and "
"active"
msgstr "ssp: %(duringwhatstage)s 중, vios id: >%(vios.id)s<, 실행 및 사용 중"

#: paxes_cinder/volume/drivers/ssp/ssp.py:727
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, for cluster id: >%(self._cluster.id)s<, "
"vios state issue, vios id: >%(vios.id)s<: PartitionState: "
">%(vios.partition_state)s< ResourceMonitoringControlState: "
">%(vios.rmc_state)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: 클러스터 id: >%(self._cluster.id)s<에 대한 %(duringwhatstage)s 중, vios 상태 "
"문제, vios id: >%(vios.id)s<: PartitionState: >%(vios.partition_state)s< "
"ResourceMonitoringControlState: >%(vios.rmc_state)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:751
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, could not find restricted metadata for "
"volume id: >%(volume_id)s<"
msgstr "ssp: %(duringwhatstage)s 중, 볼륨 id: >%(volume_id)s<에 대한 제한된 메타데이터를 찾을 수 없음"

#: paxes_cinder/volume/drivers/ssp/ssp.py:767
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, failed to refresh shared storage pool "
"with ssp_id: >%(self._ssp.id)s<, message: >%(e)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: %(duringwhatstage)s 중 ssp_id: >%(self._ssp.id)s<인 공유 스토리지 풀 새로 고치기 "
"실패, 메시지: >%(e)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:780
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, couldnt find lu for volume_id: "
">%(volume_id)s< with: unique_device_id: >%(lu_udid)s< and unit_name: "
">%(lu_name)s<"
msgstr ""
"ssp: %(duringwhatstage)s 중, volume_id: >%(volume_id)s<, unique_device_id:"
" >%(lu_udid)s<, unit_name: >%(lu_name)s<에 대한 lu를 찾을 수 없음"

#: paxes_cinder/volume/drivers/ssp/ssp.py:791
#, python-format
msgid ""
"ssp: during %(duringwhatstage)s, found too many lus for volume_id: "
">%(volume_id)s< with: unique_device_id: >%(lu_udid)s< and unit_name: "
">%(lu_name)s<"
msgstr ""
"NV-338EFD0 ssp: %(duringwhatstage)s 중, volume_id: >%(volume_id)s<, "
"unique_device_id: >%(lu_udid)s<, unit_name: >%(lu_name)s<에 대한 lu가 너무 많이 "
"발견됨"

#: paxes_cinder/volume/drivers/ssp/ssp.py:805
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:342
msgid "enter: do_setup"
msgstr "NV-9097266 입력: do_setup"

#: paxes_cinder/volume/drivers/ssp/ssp.py:825
msgid "ssp: failure during do_setup, cant find hmc."
msgstr "NV-AE8B2E2 ssp: do_setup 중 실패, hmc를 찾을 수 없습니다."

#: paxes_cinder/volume/drivers/ssp/ssp.py:853
#, python-format
msgid ""
"ssp: during do_setup, failed to obtain k2client, k2_url: >%(k2_url)s<, "
"k2_username: >%(k2_username)s<"
msgstr ""
"ssp: do_setup 중, k2client를 확보할 수 없음, k2_url: >%(k2_url)s<, k2_username: "
">%(k2_username)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:866
#, python-format
msgid ""
"ssp: during do_setup, using hmc_uuid: >%(hmc_uuid)s<, failed to retrieve "
"managementconsole, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: do_setup 중, hmc_uuid: >%(hmc_uuid)s<을(를) 사용하여 managementconsole을 검색할"
" 수 없음, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:875
#, python-format
msgid "ssp: during do_setup, hmc version: >%s<"
msgstr "NV-3F31730 ssp: do_setup 중, hmc 버전: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:885
#, python-format
msgid ""
"ssp: during do_setup, using k2_url: >%(k2_url)s<, failed to retrieve "
"cluster, cluster_id: >%(cluster_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: do_setup 중, k2_url: >%(k2_url)s<을(를) 사용하여 cluster_id: "
">%(cluster_id)s<인 클러스터를 검색할 수 없음, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:904
#, python-format
msgid ""
"ssp: during do_setup, using k2_url: >%(k2_url)s< and cluster_id: "
">%(cluster_id)s< failed to retrieve shared storage pool with ssp_ip: "
">%(ssp_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: do_setup 중, k2_url: >%(k2_url)s< 및 cluster_id: >%(cluster_id)s<을(를) "
"사용하여 ssp_ip: >%(ssp_id)s<인 공유 스토리지 풀을 검색할 수 없음, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:923
#, python-format
msgid "ssp: during do_setup, creating default volume type: >%s<"
msgstr "NV-379E7B0 ssp: do_setup 중, 기본 볼륨 유형: >%s< 작성 중"

#: paxes_cinder/volume/drivers/ssp/ssp.py:928
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:487
msgid "leave: do_setup"
msgstr "NV-F492AE8 나가기: do_setup"

#: paxes_cinder/volume/drivers/ssp/ssp.py:931
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:580
msgid "leave: check_for_setup_error"
msgstr "NV-1C79D46 나가기: check_for_setup_error"

#: paxes_cinder/volume/drivers/ssp/ssp.py:981
#: paxes_cinder/volume/drivers/ssp/ssp.py:1009
#: paxes_cinder/volume/drivers/ssp/ssp.py:1050
#: paxes_cinder/volume/drivers/ssp/ssp.py:1149
#: paxes_cinder/volume/drivers/ssp/ssp_product.py:48
#: paxes_cinder/volume/drivers/ssp/ssp_product.py:73
#: paxes_cinder/volume/drivers/ssp/ssp_product.py:145
#, python-format
msgid "ssp: exception: >%s<"
msgstr "NV-31FED69 ssp: 예외: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:982
msgid "ssp: failed during create_volume"
msgstr "NV-E4EE3DB ssp: create_volume 중 실패함"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1010
#, python-format
msgid ""
"ssp: failed during delete_volume, lu_udid: >%(lu_udid)s< lu_name: "
">%(lu_name)s< volume id: >%(volume_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-41060EC ssp: delete_volume 중 실패, lu_udid: >%(lu_udid)s< lu_name: "
">%(lu_name)s< 볼륨 id: >%(volume_id)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1029
#, python-format
msgid "ssp: during create_snapshot, cant find volume_id: >%s<"
msgstr "NV-FDA9D85 ssp: create_snapshot 중, volume_id를 찾을 수 없음: >%s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1051
#, python-format
msgid ""
"ssp: failure during create_snapshot: lu_udid: >%(src_lu_udid)s< lu_name: "
">%(src_lu_name)s< volume id: >%(source_vol_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-ACF24A1 ssp: create_snapshot 중 실패: lu_udid: >%(src_lu_udid)s< lu_name:"
" >%(src_lu_name)s< 볼륨 id: >%(source_vol_id)s<, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1070
#, python-format
msgid "ssp: during delete_snapshot, couldnt find lu with unit_name: >%s<"
msgstr "NV-FCB5EA8 ssp: delete_snapshot 중, unit_name: >%s<인 lu를 찾을 수 없음"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1077
#, python-format
msgid "ssp: during delete_snapshot, found too many lus with unit_name: >%s<"
msgstr "NV-66B083E ssp: delete_snapshot 중, unit_name: >%s<인 lu가 너무 많음"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1105
#, python-format
msgid ""
"ssp: error during create_volume_from_snapshot: snapshot with name: "
">%(snapshot_name)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-F6CFF00 ssp: create_volume_from_snapshot 중 오류: 이름이 "
">%(snapshot_name)s<인 스냅샷, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1150
#, python-format
msgid ""
"ssp:  error during create_cloned_volume: src_lu_udid: >%(src_lu_udid)s< "
"src_lu_name: >%(src_lu_name)s< volume id: >%(src_volume_id)s<, k2xa: "
">%(k2xa)s<"
msgstr ""
"NV-24854A9 ssp: create_cloned_volume 중 실패: src_lu_udid: >%(src_lu_udid)s<"
" src_lu_name: >%(src_lu_name)s< 볼륨 id: >%(src_volume_id)s<, k2xa: "
">%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp.py:1211
#, python-format
msgid "stats = %(stats)s"
msgstr "NV-898A2AA stats = %(stats)s"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:49
#, python-format
msgid ""
"ssp: while discovering mapped LUs, failed to refresh cluster with "
"cluster_id: >%(self._cluster.id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-347194B ssp: 맵핑된 LU 검색 중, cluster_id: >%(self._cluster.id)s<인 클러스터를 새로"
" 고칠 수 없음, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:59
#, python-format
msgid "Node >%s< has no virtual_io_server. Skipping."
msgstr "NV-C3FDDFD 노드 >%s<에 virtual_io_server가 없습니다. 건너뜁니다."

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:74
#, python-format
msgid ""
"ssp: while discovering mapped LUs, in cluster with cluster_id: "
">%(self._cluster.id)s< failed to retrieve vios with managedsystem_id: "
">%(ms_id)s< and virtualioserver_id: >%(vios_id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-F12DD40 ssp: 맵핑된 LU 검색 중, cluster_id: >%(self._cluster.id)s<인 클러스터에서 "
"managedsystem_id: >%(ms_id)s< 및 virtualioserver_id: >%(vios_id)s<인 vios를 "
"검색할 수 없음, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:115
msgid ""
"No volume statistics available, either driver has not been initialized or"
" there is a problem w/ the driver, check cinder logs."
msgstr ""
"NV-A8A5D70 볼륨 통계가 없습니다. 드라이버가 초기화되지 않았거나 드라이버에 문제가 있습니다. cinder 로그를 "
"확인하십시오."

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:146
#, python-format
msgid ""
"ssp: while discovering volumes, failed to refresh shared storage pool "
"with ssp_id: >%(self._ssp.id)s<, k2xa: >%(k2xa)s<"
msgstr ""
"NV-7BF09DB ssp: 볼륨 검색 중, ssp_id: >%(self._ssp.id)s<인 공유 스토리지 풀을 새로 고칠 수 "
"없음, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:173
msgid ""
"This volume is not a candidate for management because it is already "
"attached to a virtual machine.  To manage this volume with PowerVC, you "
"must bring the virtual machine under management.  Select to manage the "
"virtual machine that has the volume attached.  The attached volume will "
"be automatically included for management."
msgstr ""
"이 볼륨은 이미 가상 머신에 연결되어 있기 때문에 관리 대상이 아닙니다. PowerVC를 사용하여 이 볼륨을 관리하려면 가상 머신을"
" 관리 대상으로 가져와야 합니다. 볼륨이 연결된 가상 머신을 관리하려면 선택하십시오. 연결된 볼륨은 자동으로 관리 대상으로 "
"포함됩니다."

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:184
#, python-format
msgid ""
"ssp: during Logical Unit discovery, ssp_id: >%(ssp_id)s<, "
"lu_unique_device_id: >%(lu_unique_device_id)s<, lu_unit_name: "
">%(lu_unit_name)s<, volume is in use and not available for management, "
"k2xa: >%(k2xa)s<"
msgstr ""
"ssp: 논리 장치 검색 중, ssp_id: >%(ssp_id)s<, lu_unique_device_id: "
">%(lu_unique_device_id)s<, lu_unit_name: >%(lu_unit_name)s<, 볼륨이 사용 중이며 "
"관리 대상으로 사용할 수 없음, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:200
msgid ""
"Because it is of type VirtualIO_Image, this volume is not a candidate for"
" management. Perhaps, while deleting a PowerVC image, someone chose not "
"to delete the backing storage? If you wish to work with the underlying "
"Shared Storage Pool Logical Unit please use the HMC or VIOS commands."
msgstr ""
"이 볼륨은 VirtualIO_Image 유형이므로 관리 대상이 아닙니다. PowerVC 이미지를 삭제하는 중에 누군가가 보조 "
"스토리지를 삭제하지 않도록 선택했을 수 있습니다. 기본 공유 스토리지 풀 논리 장치로 작업하려면 HMC 또는 VIOS 명령을 "
"사용하십시오."

#: paxes_cinder/volume/drivers/ssp/ssp_product.py:210
#, python-format
msgid ""
"ssp: during Logical Unit discovery, ssp_id: >%(ssp_id)s<, "
"lu_unique_device_id: >%(lu_unique_device_id)s<, lu_unit_name: "
">%(lu_unit_name)s<, volume is of type VirtualIO_Image and not available  "
"for management, k2xa: >%(k2xa)s<"
msgstr ""
"ssp: 논리 장치 검색 중, ssp_id: >%(ssp_id)s<, lu_unique_device_id: "
">%(lu_unique_device_id)s<, lu_unit_name: >%(lu_unit_name)s<, 볼륨이 "
"VirtualIO_Image 유형이며 관리 대상으로 사용할 수 없음, k2xa: >%(k2xa)s<"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:240
#, python-format
msgid "WWPN on node %(node)s: %(wwpn)s"
msgstr "NV-D154765 노드 %(node)s의 WWPN: %(wwpn)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:299
#, python-format
msgid "Required keys %(required)s not found in vdisk dictionary %(dictionary)r"
msgstr "필수 키 %(required)s이(가) vdisk 사전 %(dictionary)r에 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:349
msgid "do_setup: Could not get system name"
msgstr "NV-5732B20 do_setup: 시스템 이름을 가져올 수 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:361
#, python-format
msgid "do_setup: Pool %s does not exist"
msgstr "NV-1B3A18D do_setup: 풀 %s이(가) 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:412
#, python-format
msgid ""
"Expected integers for node_count and vdisk_count, svcinfo lsiogrp "
"returned: %(node)s and %(vdisk)s"
msgstr ""
"NV-D7E5D72 node_count 및 vdisk_count에 대해 정수가 예상되지만, svcinfo lsiogrp가 리턴됨: "
"%(node)s 및 %(vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:475
msgid "do_setup: No configured nodes"
msgstr "do_setup: 구성된 노드가 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:484
#, python-format
msgid "Creating default volume type '%s'"
msgstr "NV-5FF13AA 기본 볼륨 유형 '%s' 작성 중"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:541
msgid "enter: check_for_setup_error"
msgstr "입력: check_for_setup_error"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:545
msgid "Unable to determine system name"
msgstr "NV-82D9304 시스템 이름을 판별할 수 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:548
msgid "Unable to determine system id"
msgstr "NV-3C12EE7 시스템 id를 판별할 수 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:551
msgid "Unable to determine pool extent size"
msgstr "NV-D455E3E 풀 범위 크기를 판별할 수 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:558
#, python-format
msgid "%s is not set"
msgstr "NV-6919A40 %s이(가) 설정되지 않음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:564
msgid ""
"Password or SSH private key is required for authentication: set either "
"san_password or san_private_key option"
msgstr ""
"NV-6FE00A0 인증에 비밀번호 또는 SSH 개인용 키가 필요합니다. san_password 또는 san_private_key "
"옵션을 설정하십시오."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:572
#, python-format
msgid ""
"Illegal value %d specified for storwize_svc_flashcopy_timeout: valid "
"values are between 0 and 600"
msgstr ""
"NV-F2E38D9 storwize_svc_flashcopy_timeout에 올바르지 않은 값 %d이(가) 지정되었습니다. 올바른 "
"값은 0 - 600 사이의 값입니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:594
#, python-format
msgid "ensure_export: Volume %(volume_id)s does not reference a vdisk"
msgstr "NV-EF2904A ensure_export: 볼륨 %(volume_id)s에서 vdisk를 참조하지 않음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:601
#, python-format
msgid ""
"ensure_export: Volume %(volume_id)s references vdisk %(vdisk)s, which was"
" not found on storage"
msgstr ""
"NV-C3410C4 ensure_export: 볼륨 %(volume_id)s에서 스토리지에 없는 vdisk %(vdisk)s을(를)"
" 참조함"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:627
#, python-format
msgid "enter: _get_chap_secret_for_host: host name %s"
msgstr "입력: _get_chap_secret_for_host: 호스트 이름 %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:663
#, python-format
msgid ""
"leave: _get_chap_secret_for_host: host name %(host_name)s with secret "
"%(chap_secret)s"
msgstr ""
"나가기: _get_chap_secret_for_host: 시크릿 %(chap_secret)s이(가) 있는 호스트 이름 "
"%(host_name)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:686
msgid "_create_host: Cannot clean host name. Host name is not unicode or string"
msgstr "NV-ED84213 _create_host: 호스트 이름을 정리할 수 없습니다. 호스트 이름은 유니코드 또는 문자열이 아닙니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:837
#, python-format
msgid "enter: _get_host_from_connector: prefix %s"
msgstr "입력: _get_host_from_connector: 접두부 %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:865
#, python-format
msgid ""
"Continue to fall back processing after initial failure to make a host on "
"the SAN controller: %s"
msgstr "NV-41DBBAB SAN 제어기 %s에 호스트를 작성하는 시도가 처음 실패된 후 장애 조치 처리 계속"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:909
#, python-format
msgid "leave: _get_host_from_connector: host %s"
msgstr "나가기: _get_host_from_connector: 호스트 %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:921
#, python-format
msgid "enter: _create_host: host %s"
msgstr "입력: _create_host: 호스트 %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:936
msgid "_create_host: No connector ports"
msgstr "_create_host: 커넥터 포트가 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:969
#, python-format
msgid "leave: _create_host: host %(host)s - %(host_name)s"
msgstr "나가기: _create_host: 호스트 %(host)s - %(host_name)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:992
#, python-format
msgid "enter: _map_vol_to_host: vdisk %(vdisk_id)s to host %(host_name)s"
msgstr "입력: _map_vol_to_host: vdisk %(vdisk_id)s에서 호스트 %(host_name)s(으)로"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1022
msgid ""
"storwize_svc_multihostmap_enabled is set to False, Not allow multi host "
"mapping"
msgstr ""
"NV-ABB7D85 storwize_svc_multihostmap_enabled가 False로 설정됨, 다중 호스트 맵핑이 허용되지"
" 않음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1034
#, python-format
msgid "vdisk %s mapping to multi host"
msgstr "NV-45393AC 다중 호스트에 vdisk %s 맵핑"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1040
#, python-format
msgid ""
"leave: _map_vol_to_host: LUN %(result_lun)s, vdisk %(vdisk_id)s, host "
"%(host_name)s"
msgstr ""
"나가기: _map_vol_to_host: LUN %(result_lun)s, vdisk %(vdisk_id)s, 호스트 "
"%(host_name)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1050
#, python-format
msgid "enter: _delete_host: host %s "
msgstr "입력: _delete_host: 호스트 %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1058
#, python-format
msgid "leave: _delete_host: host %s "
msgstr "나가기: _delete_host: 호스트 %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1084
#, python-format
msgid ""
"The connector does not contain the required information: %(connector)s, "
"protocols %(protos)s"
msgstr "NV-6A00D73 커넥터가 필수 정보를 포함하지 않음: %(connector)s, 프로토콜 %(protos)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1105
#, python-format
msgid "Enter: initialize_connection: %s"
msgstr "NV-4DB79BA 입력: initialize_connection: %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1128
#, python-format
msgid "Did not find expected column name in lsvdisk: %s"
msgstr "NV-5EFF8EA lsvdisk %s에서 예상된 열 이름을 찾을 수 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1130
#, python-format
msgid "initialize_connection: Missing volume attribute for vdisk %s"
msgstr "NV-4FE8A8D initialize_connection: vdisk %s에 대한 볼륨 속성 누락"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1142
msgid "_create_host failed to return the host name."
msgstr "_create_host가 호스트 이름을 리턴하지 못함"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1164
#, python-format
msgid ""
"initialize_connection: No node found in I/O group %(gid)s for vdisk "
"%(vdisk_id)s"
msgstr ""
"NV-8182517 initialize_connection: vdisk %(vdisk_id)s에 대한 I/O 그룹 %(gid)s에서"
" 노드를 찾을 수 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1173
#, python-format
msgid "initialize_connection: Did not find a preferred node for vdisk %s"
msgstr "NV-1DB16EC initialize_connection: vdisk %s의 선호 노드를 찾지 못함"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1195
msgid ""
"Could not get FC connection information for the host-volume connection. "
"Is the host configured properly for FC connections?"
msgstr ""
"NV-D8556EE 호스트-볼륨 연결에 대한 FC 연결 정보를 가져올 수 없습니다. FC 연결에 대해 호스트가 올바르게 "
"구성되었습니까?"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1210
#, python-format
msgid ""
"initialize_connection: Failed to collect return properties for volume "
"%(vol)s and connector %(conn)s.\n"
msgstr ""
"NV-0A9D0F9 initialize_connection: %(vol)s 볼륨 및 %(conn)s 커넥터에 대한 리턴 특성을 "
"수집하는 데 실패했습니다.\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1215
#, python-format
msgid ""
"leave: initialize_connection:\n"
" volume: %(vol)s\n"
" connector %(conn)s\n"
" properties: %(prop)s"
msgstr ""
"나가기: initialize_connection:\n"
" 볼륨: %(vol)s\n"
" 커넥터: %(conn)s\n"
" 특성: %(prop)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1233
#, python-format
msgid "enter: terminate_connection: volume %(vol)s with connector %(conn)s"
msgstr "입력: terminate_connection: %(conn)s 커넥터가 있는 %(vol)s 볼륨"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1246
#, python-format
msgid ""
"terminate_connection: vdisk mismatch: %(err)s. Performing no operation on"
" the storage controller"
msgstr ""
"NV-78DEE4C terminate_connection: vdisk 불일치: %(err)s. 스토리지 제어기에서 조작이 수행되지 "
"않음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1252
#, python-format
msgid ""
"terminate_connection: vdisk deleted: %(err)s. Performing no operation on "
"the storage controller"
msgstr ""
"NV-0E7CDF3 terminate_connection: vdisk 삭제됨: %(err)s. 스토리지 제어기에서 조작이 수행되지 "
"않음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1265
#, python-format
msgid "Detach volume: failed to lookup host name for vdisk ID: %(vdisk)s"
msgstr "NV-5D2DC5C 볼륨 분리: vdisk ID: %(vdisk)s에 대한 호스트 이름 검색 실패"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1291
#, python-format
msgid ""
"There was an error when attempting to remove the host disk mappings for "
"volume ID %(vol)s and vdsik ID %(vdisk)s: %(err)s"
msgstr ""
"NV-07BAF93 볼륨 ID %(vol)s 및 vdsik ID %(vdisk)s에 대한 호스트 디스크 맵핑을 제거하려는 중에 오류"
" 발생: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1303
#, python-format
msgid ""
"terminate_connection: No mapping of vdisk %(vdisk_id)s to host "
"%(host_name)s found"
msgstr ""
"NV-0CD2F25 terminate_connection: vdisk %(vdisk_id)s의 호스트 %(host_name)s에 "
"대한 맵핑을 찾을 수 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1314
#, python-format
msgid "leave: terminate_connection: volume %(vol)s with connector %(conn)s"
msgstr "나가기: terminate_connection: %(conn)s 커넥터가 있는 %(vol)s 볼륨"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1414
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:118
#, python-format
msgid "enter: _create_vdisk: candidate names %s "
msgstr "NV-2D6FE98 입력: _create_vdisk: 후보 이름 %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1470
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:218
#, python-format
msgid ""
"_create_vdisk %(name)s - did not find success message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"_create_vdisk %(name)s - CLI 출력에서 성공 메시지를 찾을 수 없습니다. \n"
" stdout: %(out)s\n"
" stderr: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1477
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:225
#, python-format
msgid "leave: _create_vdisk: volume %(name)s ID %(id)s "
msgstr "NV-3A4E903 나가기: _create_vdisk: 볼륨 %(name)s ID %(id)s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1499
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1513
#, python-format
msgid ""
"create FC mapping from %(source)s to %(target)s - did not find success "
"message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"
msgstr ""
"%(source)s에서 %(target)s(으)로의 FC 맵핑 작성 - CLI 출력에서 성공 메시지를 찾을 수 없습니다. \n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1525
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1535
#, python-format
msgid ""
"create FC mapping from %(source)s to %(target)s - did not find mapping id"
" in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"
msgstr ""
"%(source)s에서 %(target)s(으)로의 FC 맵핑 작성 - CLI 출력에서 맵핑 ID를 찾을 수 없습니다. \n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1550
#, python-format
msgid ""
"_prepare_fc_map: Failed to prepare FlashCopy from %(source)s to "
"%(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"NV-AD077CD _prepare_fc_map: %(source)s에서 %(target)s(으)로의 FlashCopy를 준비하지 "
"못했습니다. \n"
"stdout: %(out)s\n"
" stderr: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1578
#, python-format
msgid ""
"Unexecpted mapping status %(status)s for mapping %(id)s. Attributes: "
"%(attr)s"
msgstr "%(id)s 맵핑에 대해 예상치 못한 맵핑 상태 %(status)s. 속성: %(attr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1590
#, python-format
msgid ""
"Mapping %(id)s prepare failed to complete within the allotted %(to)d "
"seconds timeout. Terminating."
msgstr "NV-46B21B5 %(id)s 준비 맵핑이 할당된 %(to)d초(제한시간) 내에 완료되지 못했습니다. 종료됩니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1595
#, python-format
msgid ""
"_prepare_fc_map: Failed to start FlashCopy from %(source)s to %(target)s "
"with exception %(ex)s"
msgstr ""
"NV-B48FD34 _prepare_fc_map: %(ex)s 예외와 함께 %(source)s에서 %(target)s(으)로의 "
"FlashCopy를 시작하지 못했습니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1602
#, python-format
msgid "_prepare_fc_map: %s"
msgstr "NV-956CB6C _prepare_fc_map: %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1609
#, python-format
msgid ""
"_start_fc_map: Failed to start FlashCopy from %(source)s to %(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"NV-FCBE987 _start_fc_map: %(source)s에서 %(target)s(으)로의 FlashCopy를 시작하지 "
"못했습니다.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1620
#, python-format
msgid ""
"enter: _run_flashcopy: execute FlashCopy from source %(source)s to target"
" %(target)s"
msgstr "입력: _run_flashcopy: %(source)s 소스에서 %(target)s 대상으로 FlashCopy를 실행함"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1633
#, python-format
msgid "leave: _run_flashcopy: FlashCopy started from %(source)s to %(target)s"
msgstr "나가기: _run_flashcopy: %(source)s에서 %(target)s(으)로 FlashCopy가 시작됨"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1642
#, python-format
msgid ""
"enter: _create_copy: snapshot with possible names %(names)s from vdisk "
"%(src_vdisk)s"
msgstr "입력: vdisk %(src_vdisk)s(으)로부터 _create_copy: 가능한 이름이 %(names)s인 스냅샷"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1650
#, python-format
msgid "_create_copy: Source vdisk %s does not exist"
msgstr "NV-8A48F71 _create_copy: 소스 vdisk %s이(가) 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1662
#, python-format
msgid ""
"_create_copy: cannot get source vdisk %(src)s capacity from vdisk "
"attributes %(attr)s"
msgstr "_create_copy: vdisk 속성 %(attr)s에서 소스 vdisk %(src)s 용량을(를) 가져올 수 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1681
#, python-format
msgid "leave: _create_copy: snapshot vdisk %(tgt_vdisk)s from vdisk %(src_vdisk)s"
msgstr "나가기: _create_copy: vdisk %(src_vdisk)s(으)로부터 스냅샷 vdisk %(tgt_vdisk)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1688
#, python-format
msgid "enter: _get_flashcopy_mapping_attributes: mapping %s"
msgstr "입력: _get_flashcopy_mapping_attributes: 맵핑 %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1711
#, python-format
msgid ""
"leave: _get_flashcopy_mapping_attributes: mapping %(fc_map_id)s, "
"attributes %(attributes)s"
msgstr ""
"나가기: _get_flashcopy_mapping_attributes: 맵핑 %(fc_map_id)s, 속성 "
"%(attributes)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1719
#, python-format
msgid "enter: _is_vdisk_defined: vdisk %s "
msgstr "입력: _is_vdisk_defined: vdisk %s "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1721
#, python-format
msgid "leave: _is_vdisk_defined: vdisk %(vdisk)s with %(str)s "
msgstr "나가기: _is_vdisk_defined: vdisk %(vdisk)s(%(str)s 포함) "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1764
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1228
#, python-format
msgid "%(map_id)s [vdisk %(src)s to vdisk %(tgt)s]"
msgstr "%(map_id)s [vdisk %(src)s에서 vdisk %(tgt)s(으)로]"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1777
#, python-format
msgid ""
"To delete vdisk %(vdisk_id)s, increasing copyrate of flashcopy mapping "
"%(map)s from 0 to %(copyrate)s and waiting for completion."
msgstr ""
"NV-0B06E40 vdisk %(vdisk_id)s을(를) 삭제하기 위해 flashcopy 맵핑 %(map)s의 복사율을 0에서 "
"%(copyrate)s(으)로 늘리고 완료를 기다립니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1791
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1261
#, python-format
msgid "Vdisk %(id)s not involved in mapping %(src)s -> %(tgt)s"
msgstr "맵핑 %(src)s -> %(tgt)s에 포함되지 않은 Vdisk %(id)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1798
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1268
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, flashcopy mapping %(map)s with "
"status '%(status)s' was removed."
msgstr ""
"NV-4CA8ED6 vdisk %(vdisk_id)s 삭제를 허용하기 위해 flashcopy 맵핑 %(map)s(상태: "
"'%(status)s')이(가) 제거되었습니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1806
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1276
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, waiting for flashcopy mapping "
"%(map)s with status '%(status)s' to complete."
msgstr ""
"NV-E66FA4E vdisk %(vdisk_id)s 삭제를 허용하기 위해 flashcopy 맵핑 %(map)s(상태: "
"'%(status)s')이(가) 완료되길 기다립니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1816
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1286
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, forcing removal of flashcopy "
"mapping %(map)s with status '%(status)s'"
msgstr ""
"NV-824284E vdisk %(vdisk_id)s 삭제를 허용하기 위해 flashcopy 맵핑 %(map)s(상태: "
"'%(status)s')을(를) 강제로 제거합니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1827
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1300
#, python-format
msgid ""
"To allow deletion of vdisk %(vdisk_id)s, prepared flashcopy mapping "
"%(map)s was removed."
msgstr ""
"NV-211FA49 vdisk %(vdisk_id)s 삭제를 허용하기 위해 준비된 flashcopy 맵핑 %(map)s이(가) "
"제거되었습니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1835
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1310
#, python-format
msgid ""
"To delete vdisk %(vdisk_id)s, flashcopy mapping %(map)s with status "
"'idle_or_copied' was removed."
msgstr ""
"NV-DA08F03 vdisk %(vdisk_id)s을(를) 삭제하기 위해 flashcopy 맵핑 %(map)s(상태: "
"'idle_or_copied')이(가) 제거되었습니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1841
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1318
#, python-format
msgid ""
"To delete vdisk %(vdisk_id)s, waiting for completion of flashcopy mapping"
" %(map)s, which is currently %(progress)s%% complete and has status "
"'%(status)s'."
msgstr ""
"NV-CE3069A vdisk %(vdisk_id)s을(를) 삭제하기 위해 flashcopy 맵핑 %(map)s(현재 완료율: "
"%(progress)s%%, 상태: '%(status)s')이(가) 완료되길 기다립니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1881
msgid ""
"Flashcopy mapping copy rate is 0. Copy is not in progress. Return to "
"caller."
msgstr "NV-45B5480 Flashcopy 맵핑 복사율이 0입니다. 복사가 진행되지 않습니다. 호출자로 돌아가십시오."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1944
#, python-format
msgid "enter: _delete_vdisk: vdisk %s"
msgstr "입력: _delete_vdisk: vdisk %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1949
#, python-format
msgid "warning: Tried to delete vdisk %s but it does not exist."
msgstr "NV-E47B663 경고: vdisk %s을(를) 삭제하려고 했지만 이 vdisk가 없습니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1955
#, python-format
msgid "Removing vdisk %(vdisk_id)s"
msgstr "NV-E18AA05 vdisk %(vdisk_id)s 제거 중"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1968
#, python-format
msgid ""
"Hosts mapped to vdisk %(vdisk)s:\n"
"%(out)s"
msgstr ""
"NV-4159ED7 vdisk %(vdisk)s에 맵핑된 호스트:\n"
"%(out)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1974
#, python-format
msgid ""
"Existing FlashCopy mappings:\n"
"%(out)s"
msgstr ""
"NV-A345C87 기존 FlashCopy 맵핑:\n"
"%(out)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1982
#, python-format
msgid "leave: _delete_vdisk: vdisk %s"
msgstr "나가기: _delete_vdisk: vdisk %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:1992
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2086
#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2135
#, python-format
msgid "adding volume_type_id to volume=%s"
msgstr "NV-86F0410 volume_type_id를 볼륨=%s에 추가"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2014
#, python-format
msgid ""
"Starting deletion of volume %(volume_id)s.  There is no associated vdisk,"
" so no operation will be performed on the storage controller."
msgstr ""
"NV-04391FA 볼륨 %(volume_id)s의 삭제를 시작합니다. 연관된 vdisk가 없으므로 스토리지 제어기에서 조작이 "
"수행되지 않습니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2020
#, python-format
msgid "Starting deletion of volume %(volume_id)s, backed by vdisk %(vdisk_id)s"
msgstr "NV-0C0C004 vdisk %(vdisk_id)s에서 지원하는 볼륨 %(volume_id)s의 삭제를 시작하는 중 "

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2032
#, python-format
msgid ""
"delete_volume: vdisk mismatch: %(err)s. Performing no operation on the "
"storage controller"
msgstr "NV-D258084 delete_volume: vdisk 불일치: %(err)s. 스토리지 제어기에서 조작이 수행되지 않음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2038
#, python-format
msgid ""
"delete_volume: vdisk deleted: %(err)s. Performing no operation on the "
"storage controller"
msgstr "NV-FC2A0B0 delete_volume: vdisk 삭제됨: %(err)s. 스토리지 제어기에서 조작이 수행되지 않음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2075
msgid "create_volume_from_snapshot: Source and destination size differ."
msgstr "NV-5A82296 create_volume_from_snapshot: 소스 및 대상 크기가 다릅니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2096
#, python-format
msgid "create_volume_from_snapshot:  Source vdisk %s does not exist"
msgstr "NV-4729BC4 create_volume_from_snapshot: 소스 vdisk %s이(가) 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2123
msgid "create_cloned_volume: Source and destination size differ."
msgstr "NV-4DD8AF7 create_cloned_volume: 소스 및 대상 크기가 다릅니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2164
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1025
#, python-format
msgid "enter: extend_volume: volume %s"
msgstr "NV-826757D 입력: extend_volume: 볼륨 %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2174
msgid "extend_volume: Extending a volume with snapshots is not supported."
msgstr "NV-E7C02C3 extend_volume: 스냅샷을 포함하는 볼륨 확장은 지원되지 않습니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2186
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1051
#, python-format
msgid "leave: extend_volume: volume %s"
msgstr "NV-0CDE488 나가기: extend_volume: 볼륨 %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2202
#, python-format
msgid "enter: migrate_volume: id=%(id)s, host=%(host)s"
msgstr "입력: migrate_volume: id=%(id)s, 호스트=%(host)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2234
msgid "migrate_volume started with more than one vdisk copy"
msgstr "둘 이상의 vdisk 사본을 포함하는 migrate_volume 시작됨"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2252
#, python-format
msgid ""
"migrate_volume %(name)s - did not find success message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"migrate_volume %(name)s - CLI 출력에서 성공 메시지를 찾을 수 없습니다.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2264
msgid "migrate_volume: Could not get vdisk copy data"
msgstr "NV-E8B0820 migrate_volume: vdisk 사본 데이터를 가져올 수 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2279
#, python-format
msgid "leave: migrate_volume: id=%(id)s, host=%(host)s"
msgstr "나가기: migrate_volume: id=%(id)s, 호스트=%(host)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2301
msgid "Updating volume stats"
msgstr "볼륨 stats 업데이트"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2324
msgid "Could not get pool data from the storage"
msgstr "NV-675559D 스토리지에서 풀 데이터를 가져올 수 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2325
msgid "_update_volume_stats: Could not get storage pool data"
msgstr "NV-F6BB258 _update_volume_stats: 스토리지 풀 데이터를 가져올 수 없음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2412
msgid ""
"Illegal value specified for storwize_svc_vol_rsize: set to either a "
"percentage (0-100) or -1"
msgstr "NV-8977C50 storwize_svc_vol_rsize에 지정된 잘못된 값: 백분율(0-100) 또는 -1로 설정"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2418
msgid ""
"Illegal value specified for storwize_svc_vol_warning: set to a percentage"
" (0-100)"
msgstr "NV-80C1898 storwize_svc_vol_warning에 지정된 잘못된 값: 백분율(0-100)로 설정"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2425
msgid ""
"Illegal value specified for storwize_svc_vol_grainsize: set to either 32,"
" 64, 128, or 256"
msgstr "NV-8A90F92 storwize_svc_vol_grainsize에 지정된 잘못된 값: 32, 64, 128 또는 256으로 설정"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2432
msgid "System does not support compression"
msgstr "NV-90F35C9 시스템이 압축을 지원하지 않음"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2437
msgid "If compression is set to True, rsize must also be set (not equal to -1)"
msgstr "NV-102C98D 압축이 True로 설정되면 rsize도 설정되어야 함(-1이 아님)"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2443
#, python-format
msgid ""
"Illegal value %(prot)s specified for storwize_svc_connection_protocol: "
"valid values are %(enabled)s"
msgstr ""
"NV-5EBEB51 storwize_svc_connection_protocol에 올바르지 않은 값 %(prot)s이(가) "
"지정되었습니다. 올바른 값은 %(enabled)s입니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2451
#, python-format
msgid "I/O group %(iogrp)d is not valid; available I/O groups are %(avail)s"
msgstr "NV-9E31DDB I/O 그룹 %(iogrp)d이(가) 올바르지 않음, 사용 가능한 I/O 그룹은 %(avail)s임"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2465
#, python-format
msgid "enter: _execute_command_and_parse_attributes:  command %s"
msgstr "입력: _execute_command_and_parse_attributes: 명령 %s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2477
#, python-format
msgid ""
"CLI Exception output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"NV-A3B1CA4 CLI 예외 출력:\n"
" 명령: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2494
#, python-format
msgid ""
"leave: _execute_command_and_parse_attributes:\n"
"command: %(cmd)s\n"
"attributes: %(attr)s"
msgstr ""
"나가기: _execute_command_and_parse_attributes:\n"
"명령: %(cmd)s\n"
"속성: %(attr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2513
#, python-format
msgid ""
"_get_hdr_dic: attribute headers and values do not match.\n"
" Headers: %(header)s\n"
" Values: %(row)s"
msgstr ""
"_get_hdr_dic: 속성 헤더 및 값이 일치하지 않습니다.\n"
" 헤더: %(header)s\n"
" 값: %(row)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2521
#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
"stdout: %(out)s\n"
"stderr: %(err)s\n"
msgstr ""
"NV-39015B6 %(fun)s: 예상치 못한 CLI 출력과 함께 실패했습니다.\n"
" 명령: %(cmd)s\n"
"stdout: %(out)s\n"
"stderr: %(err)s\n"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2535
#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"%(fun)s: 예상치 못한 CLI 출력과 함께 실패했습니다.\n"
" 명령: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_driver_id.py:2543
#, python-format
msgid "Did not find expected column in %(fun)s: %(hdr)s"
msgstr "NV-BEC3CF8 %(fun)s에서 예상한 열을 찾지 못함: %(hdr)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:103
#, python-format
msgid ""
"StorwizeSVCProductDriver: start flashcopy mapping polling timer, polling "
"interval: %(intval)s seconds"
msgstr ""
"NV-796256C StorwizeSVCProductDriver: flashcopy 맵핑 폴링 타이머 시작, 폴링 간격: "
"%(intval)s초"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:328
#, python-format
msgid ""
"The volume %(name)s is in the error state and not a candidate for "
"management.  vdisk status: %(status)s  vdisk id: %(vdisk_id)s  vdisk uid:"
" %(vdisk_uid)s  "
msgstr ""
"볼륨 %(name)s이(가) 오류 상태이며 관리 후보가 아닙니다. vdisk 상태: %(status)s  vdisk id: "
"%(vdisk_id)s  vdisk uid: %(vdisk_uid)s  "

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:592
#, python-format
msgid ""
"The connector %(connector)s does not contain the required keys, which are"
" %(expected_fc_keys)s.or %(expected_iscsi_keys)s"
msgstr ""
"커넥터 %(connector)s에 필수 키가 없음, 필수 키: %(expected_fc_keys)s. 또는 "
"%(expected_iscsi_keys)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:647
#, python-format
msgid "Incorporating WWPNS for Node %(node_id)s: %(wwpns)s"
msgstr "NV-365ED6F 노드 %(node_id)s에 대한 WWPNS 통합: %(wwpns)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:659
#, python-format
msgid ""
"Attachment for host '%(host)s' to %(storage)s for volume %(volume)s "
"expects zoning between initiator WWPNs %(initiators)s and target WWPNs "
"%(targets)s"
msgstr ""
"NV-0F22247 볼륨 %(volume)s에서 %(storage)s에 대한 호스트 '%(host)s'의 첨부 시 이니시에이터 "
"WWPN %(initiators)s 및 대상 WWPN %(targets)s 사이의 구역화가 예상됨"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:721
#, python-format
msgid "Mapping initiator %(phy)s to node %(node)s"
msgstr "NV-5DC7B55 이니시에이터 %(phy)s을(를) 노드 %(node)s에 맵핑"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:766
#, python-format
msgid ""
"Fabric %(fabric)s does not have visibility to any WWPNs in node %(node)s,"
" part of iogrp %(iogrp)s of storage controller %(name)s. WWPNs visible on"
" the fabric are %(visible)s. WWPNs on the controller are %(available)s."
msgstr ""
"패브릭 %(fabric)s이(가) 스토리지 제어기 %(name)s의 iogrp %(iogrp)s 중 일부인 노드 %(node)s에서"
" WWPN에 대해 표시되지 않습니다. 패브릭에 표시되는 WWPN은 %(visible)s입니다. 제어기에서 WWPN은 "
"%(available)s입니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:811
msgid "Zoning for single fabric, one initiator."
msgstr "NV-6E5D37F 단일 패브릭에 대한 구역화, 1개 이니시에이터."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:821
msgid "Zoning for single fabric, two initiators."
msgstr "NV-2E0EF21 단일 패브릭에 대한 구역화, 2개 이니시에이터."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:835
#, python-format
msgid ""
"Zoning for single fabric, general case due to %(count)s initiators on "
"fabric."
msgstr "NV-D9A5CD2 단일 패브릭에 대한 구역화, 패브릭의 %(count)s개 이니시에이터로 인한 일반적인 경우."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:845
msgid "Zoning for dual fabric, one initiator per fabric."
msgstr "NV-EE35C79 듀얼 패브릭에 대한 구역화, 패브릭당 1개 이니시에이터."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:864
msgid "Zoning for dual fabric, two initiators per fabric."
msgstr "NV-C638EFA 듀얼 패브릭에 대한 구역화, 패브릭당 2개 이니시에이터."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:884
#, python-format
msgid ""
"Zoning for dual fabric, general case due to %(count1)s initiators on "
"first fabric and %(count2)s initiators on second fabric."
msgstr ""
"NV-4351BA7 듀얼 패브릭에 대한 구역화, 첫 번째 패브릭의 %(count1)s개 이니시에이터 및 두 번째 패브릭의 "
"%(count2)s개 이니시에이터로 인한 일반적인 경우."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:894
#, python-format
msgid "Zoning for general case due to %(count)s fabrics."
msgstr "NV-0733A1E %(count)s 패브릭으로 일반 경우의 구역화."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:911
#, python-format
msgid "Creating zones: %r"
msgstr "NV-70BDC4D 구역 작성: %r"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:923
#, python-format
msgid "Requested mapping for initiators  %(initiators)s and targets %(targets)s"
msgstr "NV-35F3CC8 이니시에이터 %(initiators)s 및 대상 %(targets)s에 대해 요청된 맵핑"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:941
#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:950
#, python-format
msgid "Returned mapping is %(mapping)s"
msgstr "NV-10E28B0 리턴된 맵핑: %(mapping)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:976
#, python-format
msgid "Terminating connection with parameters %(connector)sconnector"
msgstr "NV-4EFE246 매개변수 %(connector)s 커넥터를 사용한 연결 종료 중"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:986
#, python-format
msgid "Removing zones for initiators: %(initiator_list)s"
msgstr "NV-CC588B5 이니시에이터에 대한 구역 제거: %(initiator_list)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:996
#, python-format
msgid ""
"There was a failure when the zone manager attempted to remove zones "
"created for WWPNs %(wwpns)s during detach of volume %(vol)s."
msgstr ""
"NV-AA064A4 볼륨 %(vol)s의 분리 중에 구역 관리자가 WWPN %(wwpns)s에 대해 작성된 구역을 제거하려고 할 때"
" 실패가 발생했습니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1083
#, python-format
msgid "SSH Pool: %d free, %d waiting, in-flight commands:"
msgstr "NV-F9DD698 SSH 풀: %d 사용 가능, %d 대기 중, in-flight 명령:"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1087
#, python-format
msgid " %(duration).2f %(commands)s"
msgstr "NV-98D8DC3  %(duration).2f %(commands)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1141
#, python-format
msgid ""
"vdisk %(vdsk)s has been added to the flashcopy mapping delete queue with "
"priority %(pri)s."
msgstr "NV-38E83B6 vdisk %(vdsk)s이(가) 우선순위가 %(pri)s인 flashcopy 맵핑 삭제 큐에 추가됩니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1149
#, python-format
msgid ""
"Successfully returned from flashcopy mapping waiter for vdisk %(vdsk)s, "
"returned value: %(ret)s, total wait time: %(wt)s seconds."
msgstr ""
"NV-62F28E6 vdisk %(vdsk)s에 대한 flashcopy 맵핑 대기자에서 리턴되었습니다. 리턴된 값: %(ret)s,"
" 총 대기 시간: %(wt)s초."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1166
#, python-format
msgid ""
"Exception happened when waiting for flashcopy mapping handling for vdisk "
"%(vdsk)s, total wait time: %(wt)s seconds."
msgstr ""
"NV-71EC636 vdisk %(vdsk)s에 대한 flashcopy 맵핑 처리를 위해 기다리는 중 예외가 발생했습니다. 총 대기"
" 시간: %(wt)s초."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1172
#, python-format
msgid ""
"Removed flashcopy mappings waiter from waiting queue for vdisk %(vdsk)s "
"deletion."
msgstr "NV-46703B0 vdisk %(vdsk)s 삭제를 위해 대기 중인 큐에서 flashcopy 맵핑 대기자가 제거되었습니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1183
#, python-format
msgid "Flashcopy mapping delete queue: %(vdsks)s"
msgstr "NV-CA4A211 Flashcopy 맵핑 삭제 큐: %(vdsks)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1193
#, python-format
msgid ""
"Flashcopy mapping delete queue: %(cnt)s vdisks pending delete, average "
"wait time: %(avg)s seconds"
msgstr "NV-91BB641 Flashcopy 맵핑 삭제 큐: %(cnt)s vdisk 삭제 보류 중, 평균 대기 시간: %(avg)s초"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1242
#, python-format
msgid "fcmapping_handler: %(err)s"
msgstr "fcmapping_handler: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1245
#, python-format
msgid ""
"fcmapping_handler: to delete vdisk %(vdisk_id)s, increasing copyrate of "
"flashcopy mapping %(map)s from 0 to %(copyrate)s and waiting for "
"completion."
msgstr ""
"NV-EE5BEB1 fcmapping_handler: vdisk %(vdisk_id)s을(를) 삭제하기 위해 flashcopy 맵핑"
" %(map)s의 복사율을 0에서 %(copyrate)s(으)로 늘리고 완료를 기다립니다."

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1357
#, python-format
msgid ""
"Exception happened during processing flashcopy mapping per vdisk %(vdsk)s"
" deletion: %(err)s"
msgstr "NV-71C30D1 vdisk %(vdsk)s 삭제당 flashcopy 맵핑을 처리하는 중 예외 발생: %(err)s"

#: paxes_cinder/volume/drivers/svc/storwize_svc_product.py:1387
#, python-format
msgid ""
"Duration of fcmapping_handler timer: %(runtime)s seconds, %(pct)s%% of "
"fixed polling interval."
msgstr "NV-80870AC fcmapping_handler 타이머 기간: %(runtime)s초, 고정된 폴링 간격의 %(pct)s%%."

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:93
#, python-format
msgid "Fabric names are not unique: %(fabric_names)s"
msgstr "NV-2ED2D0B 패브릭 이름이 고유하지 않음: %(fabric_names)s"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:261
#, python-format
msgid "Connection established to fabric %(f_name)s"
msgstr "NV-41B567C 패브릭 %(f_name)s에 대한 연결 설정됨"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:376
#, python-format
msgid "Zones to be created for %(fabric)s are %(zones)r"
msgstr "NV-2E6EE4A %(fabric)s에 대해 작성할 구역: %(zones)r"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:410
#, python-format
msgid "%(fabric_descriptor)s: deleting zones %(zone_list)s"
msgstr "NV-C3FDFEA %(fabric_descriptor)s: 구역 %(zone_list)s 삭제"

#: paxes_cinder/zonemanager/paxes_fc_zone_manager.py:449
#, python-format
msgid "Returned data from get_nameserver_info() is %(info)r"
msgstr "NV-7863F08 get_nameserver_info()에서 리턴된 데이터: %(info)r"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:122
msgid "Could not connect"
msgstr "NV-07C9AAF 연결할 수 없음"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:124
#, python-format
msgid "SSH Client created for %s"
msgstr "NV-08C2923 %s에 대해 작성된 SSH 클라이언트"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:187
#, python-format
msgid "Failed getting active zone set from %s"
msgstr "NV-373682A %s에서 활성 구역 세트를 가져오는 데 실패함"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:218
msgid "Malformed zone configuration"
msgstr "NV-9BF2FBF 잘못 구성된 구역 구성"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:220
#, python-format
msgid "Failed getting active zone set from fabric %s"
msgstr "NV-A5B77A2 패브릭 %s에서 활성 구역 세트를 가져오는 데 실패함"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:259
#, python-format
msgid "Add Zones - Zones passed: %s"
msgstr "NV-8A18A84 구역 추가 - 전달된 구역: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:267
#, python-format
msgid "Adding zone failed. Error in getting active zone set from fabric %s"
msgstr "NV-C692314 구역 추가 실패, 패브릭 %s에서 활성 구역 세트를 가져오는 데 실패함"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:276
#, python-format
msgid "Zone %(zoneName)s already contains required members"
msgstr "NV-EADDEDC 구역 %(zoneName)s에 이미 필수 멤버가 있음"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:282
#, python-format
msgid "Deleted Zone before insert : %s"
msgstr "NV-4C9797D 삽입 전 구역이 삭제됨: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:286
#, python-format
msgid "Deleting zone failed %s"
msgstr "NV-C1A773E 구역 삭제 실패 %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:294
#, python-format
msgid "Adding zone, cmd to run %s"
msgstr "NV-D2B3DDC 구역 추가, 실행할 명령 %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:301
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:304
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:338
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:341
#, python-format
msgid "Adding zone failed, cmd %s"
msgstr "NV-3F8FCCF 구역 추가 실패, 명령 %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:312
msgid "No new zones created"
msgstr "NV-145C307 새 구역이 작성되지 않음"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:322
#, python-format
msgid "Zoneset create operation failed with output %s"
msgstr "NV-0645570 구역 세트 작성 조작 실패, 출력: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:330
#, python-format
msgid "cfgAdd operation failed : %s"
msgstr "NV-C8F3EB6 cfgAdd 조작 실패: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:343
msgid "Zoning completed"
msgstr "NV-BC5301E 구역화 완료"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:373
#, python-format
msgid "Failed getting active zones from fabric %s"
msgstr "NV-21CE132 패브릭 %s에서 활성 구역을 가져오는 데 실패함"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:395
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:398
#, python-format
msgid "Deleting zones failed, cmd %s"
msgstr "NV-AFACFBC 구역 삭제 실패, 명령 %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:414
#, python-format
msgid "Failed collecting nsshow info for fabric %s"
msgstr "NV-6039569 패브릭 %s에 대한 nsshow 정보 수집 실패"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:421
#, python-format
msgid "Failed collecting nscamshow info for fabric %s"
msgstr "NV-A1992B9 패브릭 %s에 대한 nscamshow 정보 수집 실패"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:453
#, python-format
msgid "Problem: %(problem)s"
msgstr "NV-D20CB78 문제점: %(problem)s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:471
#, python-format
msgid "Will retry after %(seconds)s seconds..."
msgstr "NV-A7C85C7 %(seconds)s초 후 재시도..."

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:490
#, python-format
msgid "Failed closing SSH connection %s"
msgstr "NV-3EA57B2 SSH 연결 %s을(를) 닫는 중 실패"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:512
#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:561
#, python-format
msgid "running: '%s'"
msgstr "NV-081F69F 실행: '%s'"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:521
#, python-format
msgid "Returned data was %r"
msgstr "NV-93F16B7 리턴된 데이터: %r"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:535
#, python-format
msgid "Error running command via ssh: %s"
msgstr "NV-20D0255 ssh를 통해 명령 실행 중 오류 발생: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:587
#, python-format
msgid "Error while checking zoning txn status: %s"
msgstr "NV-2D4C6DF 구역화 txn 상태 확인 중 오류 발생: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:599
#, python-format
msgid "Executing: %s"
msgstr "NV-4EBB354 실행: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:609
#, python-format
msgid "CLI execution returned: %s"
msgstr "NV-538FB7E CLI 실행에서 리턴: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:633
#, python-format
msgid "Error executing command %(cmd)s: %s"
msgstr "명령 %(cmd)s 실행 중 오류 발생: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:648
#, python-format
msgid "Failed when executing command '%(cmd)s': %(err)s"
msgstr "NV-B5BA5A5 명령 '%(cmd)s' 실행 중 실패: %(err)s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:670
#, python-format
msgid "Malformed nameserver output is: %s"
msgstr "NV-07E23F0 잘못 구성된 이름 서버 출력: %s"

#: paxes_cinder/zonemanager/drivers/brocade/brcd_fc_zone_client_cli.py:672
msgid "Malformed nameserver info"
msgstr "NV-4331BBF 잘못 구성된 이름 서버 정보"

